omni-network/omni

e2e/app/admin/bridgespec.go
e2e/app/admin/common.go
e2e/app/admin/pausebridge.go
e2e/app/admin/pauseportal.go
e2e/app/admin/pausexcall.go
e2e/app/admin/pausexsubmit.go
e2e/app/admin/portalspec.go
e2e/app/admin/test.go
e2e/app/admin/upgrade.go
e2e/app/definition.go
e2e/app/erc20faucet.go
e2e/app/fund.go
e2e/app/gaspump.go
e2e/app/monitor.go
e2e/app/run.go
e2e/app/tokenbridge.go
e2e/app/valupdates.go
e2e/types/testnet.go

Replaces most usage of `netconf.Network` in e2e since we don't actually have `DeployHeight` in most cases. It can only be used after `netman.DeployPortals` in `Deploy` or `TestE2E` command.
Replace it with `types.Testnet` and `types.EVMChain`.
issue: none

refactor(e2e): remove most netconf usage

---

.github/dependabot.yml

Relax npm dependabot interval to weekly.
Too much noise.
issue: none

chore(ci): relax npm dependabot interval

---

monitor/xmonitor/metrics.go
monitor/xmonitor/monitor.go

Only monitor each attestation once. This prevent errors on quiet streams.
issue: none

chore(monitor): improve attest metrics

---

.github/dependabot.yml

Ignore contract dependencies installed via gh url in dependabot config.
issue: none

chore(ci): ignore contract gh dependencies in dependabot

---

e2e/cmd/cmd.go
e2e/cmd/keys.go
e2e/manifests/mainnet.toml

Adds mainnet manifest including keys created by `e2e key-create-all`
issue: #2079

ci(e2e): add mainnet manifest

---

e2e/app/gaspump.go
e2e/app/run.go
lib/contracts/fund.go

Do not deploy: gas pump on mainnet.
issue: none

chore(e2e): do not deploy gas pump on mainnet

---

.github/workflows/ci-join.yml

Adds a nightly github action that joins omega and fails if it takes longer than 6 hours.
issue: #2175

ci(github): add join nightly

---

relayer/app/app.go
relayer/app/buffer.go
relayer/app/buffer_internal_test.go
relayer/app/cursors_internal_test.go
relayer/app/sender.go
relayer/app/sender_internal_test.go
relayer/app/types.go
relayer/app/worker.go
relayer/app/worker_internal_test.go

Fixes race condition in relayer that resulted in unordered submissions sometimes. 
This refactors the `Sender` to reserve nonces synchronously, but do the actual sending asynchronously. Active buffer refactored to reserves nonces synchronously ensuring strictly ordered submissions.
issue: https://github.com/omni-network/ops/issues/533

fix(relayer): ensure submission order

---

halo/cmd/ready.go

Fixes the `ready` command that is using the wrong URL for readiness check.
issue: none

fix(halo/app): fix ready command

---

halo/app/start.go
halo/app/start_test.go

Revert to only using cometBFT cprovider since gRPC based cprovider is causing data races in CI.
issue: #2002

refactor(halo): revert to using comet cprovider

---

e2e/app/tokenbridge.go

Do not setup bridge on initial mainnet deployment.
Allows us to deploy mainnet first, and setup bridge once stable.
issue: none

chore(e2e): setup bridge post network deploy

---

e2e/app/fund.go

Skip mainnet omni on funding since it doesn't exist yet.
issue: none

ci(e2e): skip funding omni on mainnet

---

e2e/app/run.go

Skip redeploying mainnet chain vms as this is done, only do contracts.
issue: none

ci(e2e): skip mainnet vm deploys

---

contracts/allocs/allocs.go
lib/netconf/mainnet/consensus-genesis.json
lib/netconf/static.go

Add mainnet netconf static.
issue: none

chore(lib/netconf): add mainnet static

---

monitor/xfeemngr/xfeemngr.go

Increases buffer for gas price threshold to 20% that should cause less updates to the chain which are expensive.
Example of 10% vs 20% updates required:
issue: none

fix(monitor): increase gas price threshold

---

monitor/routerecon/metrics.go
monitor/routerecon/recon.go
monitor/routerecon/routescan_internal_test.go

Fix routescan recon lag metric. Previously, we compared the live submit_offset to a stale (up 30min old) routescan_offset which resulted in incorrect insight.
issue: none

fix(monitor/routerecon): fix lag metric

---

e2e/app/definition.go
e2e/app/run.go
e2e/app/setup.go
e2e/docker/docker.go
e2e/netman/manager.go
e2e/types/manifest.go
e2e/types/testnet.go

Removes some old used to deploy the monitor without a live network. Now that mainnet is live we can remove it.
issue: none

chore(e2e): cleanup monitorOnly in e2e

---

scripts/join/join_test.go

Fail `join-nightly` test if too fast.
issue: none

ci(scripts/join): fail if too fast

---

.github/workflows/ci-join.yml

By default, a Go test times out after 10m. But the syncing is expected to take much longer, so we disable the time out because the test has a built in timeout of 6h.
issue: none

fix(ci): increase the nightly-join test timeout

---

halo/app/monitor.go

We're currently setting the http status code twice when the server is unhealthy.
issue: none

fix(halo/app): do not override the http status header

---

scripts/join/join_test.go

SyncProgress returns nil when synced.
issue: #2294

ci(scripts/join): fix join nightly nil pointer

---

.github/CODEOWNERS

chore(ci): add zodomo to codeowners

---

halo/app/monitor.go
lib/ethclient/enginemock.go
lib/ethclient/ethbackend/backend.go
lib/ethclient/ethclient.go
lib/ethclient/ethclient_gen.go
lib/ethclient/genwrap/genwrap.go
lib/ethclient/mock/mock_interfaces.go
lib/txmgr/txmgr.go
lib/txmgr/txmgr_internal_test.go
monitor/app/public_rpc.go
scripts/join/join_test.go

Replace `ethclient.SyncProgress` which is prone to panics with a safe version `ethclient.ProgressIfSyncing` which returns `pointer, bool, error`.
issue: none

refactor(lib/ethclient): make syncprogress safe

---

cli/cmd/initnodes.go
cli/cmd/staking.go
e2e/app/monitor.go
e2e/test/attestations_test.go
e2e/test/cli_test.go
halo/app/pruning_test.go
halo/app/start.go
halo/app/start_test.go
lib/cchain/provider/abci.go
lib/cchain/provider/metrics.go
lib/cchain/provider/provider.go
lib/stream/cache.go
lib/stream/cache_internal_test.go
lib/stream/cache_test.go
lib/stream/stream.go
lib/xchain/connect/connect.go
lib/xchain/provider/provider.go
monitor/app/app.go
relayer/app/app.go

Add support for cache in `stream` package. Implement a map based cache and wire it as part of cprovider.
issue: #2321

feat(cchain/provider): add attest stream cache

---

.github/workflows/ci-join.yml
scripts/join/join_test.go

- Disable omega nightly join until the sync timeout is understood
- Enable mainnet nightly sync (syncs in 10m on a Macbook)
- Allow to run the action manually both for test and mainnet
issue: #2314

ci(github): add mainnet join nightly

---

lib/p2putil/pex_test.go

Print remote address in pex utility.
issue: none

fix(p2putil): print remote address

---

scripts/join/join_test.go

Instead of erroring when ready but halo not sycned, just wait for all conditions before exiting, This way we can see what is going on.
issue: #2314

ci(scripts/join): wait instead of error

---

scripts/join/join_test.go

Reduce the internal timer to 10m (otherwise it fails locally on joining mainnet).
issue: none

fix(ci): fix timer for local join of mainnet

---

.github/workflows/ci-join.yml

Run the test with sudo do avoid dealing with file permissions of the geth state. (See [GitHub docs](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#administrative-privileges))
issue: none

fix(ci): run with sudo

---

.github/workflows/ci-join.yaml

Minor fix of log file and specifying a large instance to run the network join test.
issue: none

fix(ci): fix the log file label and run on bigger runner

---

lib/cchain/provider/abci.go
lib/cchain/provider/metrics.go
lib/cchain/provider/provider.go
lib/cchain/provider/provider_test.go

Cache the height found during attestation offset lookback search so it can be reused on the next offset search.
issue: #1860

feat(realyer): cache height for offset search

---

e2e/app/admin/test.go

Disable the test for OmniBridgeNative as it was failing because the bridge has not yet been upgraded. Post-upgrade the test can be reenabled.
issue: none

test(e2e/app): disable testUpgradeBridgeNative

---

e2e/cmd/cmd.go

Remove ephemeral network check from bridge-deploy command, which prevented deployment to staging.
issue: #2390

chore(e2e/cmd): remove ephemeral network check on bridge deploy

---

.github/workflows/ci-join.yaml
scripts/join/join_test.go

Add the `halo_tag` flag to `TestJoin`.
Default to using `main` docker images for `TestJoin`. This drops building docker images as a requirement, making it easier to run. Also just use `main` in CI.
issue: none

chore(scripts/join): avoid building images

---

solver/app/bindings.go
solver/app/processor.go
solver/app/processor_internal_test.go

Basic solver architecture based on a well-abstracted event processor.
issue: #2384

feat(solver/app): basic event processor

---

lib/netconf/netconf.go

Modify IsEthereumChain to check against "holesky" for Staging, which was previously exempt and would always return false for all chains.
issue: #2390

chore(lib/netconf): add staging to ethereum chain config return

---

monitor/app/config_test.go
monitor/app/testdata/default_monitor.toml
monitor/cmd/flags.go

Fixes incorrect coingecko flag name that didn't route viper to cobra.
issue: #1839

fix(monitor/cmd): rename coingecko flag

---

lib/cchain/provider/provider.go
lib/cchain/provider/provider_test.go

Disables historical caching to see if bootstrapping reverts to previous behavior
issue: none

feat(cchain/provider): disable historical caching

---

e2e/app/admin/pausebridge.go

Fix logs in bridge pause actions. 
issue: none

chore(e2e): fix admin logs

---

lib/contracts/gaspump/deploy.go

0.02 ETH was far too much, reduced it to 0.001 ETH. Gas Pump is not a DEX.
issue: #2206

chore(lib/contracts): reduced gas pump max swap init

---

halo/attest/voter/voter.go
halo/attest/voter/voter_test.go

Currently, if a validator prosed a vote(s) but they are not included in the next rounds proposed block, they will only be reset to available if that (or once subsequent) proposed blocks contain another vote from the same validator. This creates an inefficiency, where votes are only rebroadcasted once subsequent votes are included. This could delay voting by up to `AttestInterval` (1 hour).
It is better to rebroadcast if even no votes from the validator is included in the next proposal.
issue: none

fix(attest/voter): reset to available if not included

---

halo/attest/voter/voter_test.go
lib/xchain/provider.go
lib/xchain/provider/fetch.go
lib/xchain/provider/mock.go
monitor/routerecon/recon.go
monitor/routerecon/recon_internal_test.go
monitor/routerecon/routescan_internal_test.go
monitor/xmonitor/monitor.go
relayer/app/cursors.go
relayer/app/cursors_internal_test.go
relayer/app/worker_internal_test.go

Use ref with submitted cursors so we can get finalized cursors. 
issue: none

refactor(xchain/provider): use ref with get submitted cursor

---

halo/app/lazyvoter.go
halo/attest/keeper/keeper.go
halo/attest/keeper/msg_server.go
halo/attest/keeper/proposal_server.go
halo/attest/testutil/mock_interfaces.go
halo/attest/types/helper.go
halo/attest/types/interface.go
halo/attest/voter/voter.go
halo/attest/voter/voter_test.go

Add temporary logs to voter to debug duplicate vote issue.
issue: #2286

chore(halo/voter): improve errors and logs

---

lib/k1util/k1util.go
lib/k1util/k1util_test.go

Verify pubkey are valid when converting types. This prevent invalid pubkeys being registered in evmstaking. Which will halt the chain.
issue: #2430

fix(lib/k1util): always verify pubkeys

---

lib/k1util/k1util.go
lib/k1util/k1util_test.go

Align consensus chain vote verification with portal OpenZepellin verification that does additional ECDSA malleability checks. This mitigates an attack where consensus chain signatures pass but fail in portal.
issue: #2432

fix(lib/k1util): prevent ECDSA malleability

---

e2e/types/infra.go
e2e/types/infra_test.go
e2e/vmcompose/provider.go

Make canary upgrades simple and consistent by specifying a special "service regex"
- `canary` will upgrade canary services.
- `non-canary` will upgrade all other services.
issue: none

ci(e2e): support canary upgrade regex

---

e2e/app/admin/common.go
e2e/fbproxy/app/app.go

Increase admin action timeouts.
issue: none

chore(e2e): increase admin fb signing timeout

---

halo/app/prouter.go
lib/ethclient/client_test.go
lib/ethclient/engineclient.go
octane/evmengine/keeper/abci.go
octane/evmengine/keeper/abci_internal_test.go
octane/evmengine/keeper/msg_server.go
octane/evmengine/keeper/proposal_server.go

Improve EngineAPI error handling:
- Geth returns `status:INVALID` AND errors, so swallow errors if known status is returned.
- Remaining errors (with unknown status) should only be temporary networking (or some unexpected geth error).
- Timeout PrepareProposal after 10s, proposing an empty consensus block rather (other validators probably already moved on in any case.)
- Timeout ProcessProposal after 1min, prevent blocking forever
issue: #2461

fix(octane/evmengine): handle engine errors

---

contracts/Makefile
contracts/bindings/mocktoken.go
contracts/bindings/mockvault.go
e2e/solve/deploy.go
e2e/solve/devapp/deploy.go
e2e/solve/devapp/devapp.go
e2e/solve/devapp/target.go
lib/contracts/address.go
solver/app/target.go

Add devnet solver target and initial target interface.
issue: #2355

feat(e2e/solve): devnet target

---

e2e/app/gaspump.go

Separate funding gas station action from deployment on mainnet only.
issue: #2206

chore(e2e/app): disable fundGasStation on mainnet

---

contracts/Makefile
contracts/bindings/feeoraclev2.go
e2e/app/feeoraclev2.go
e2e/cmd/cmd.go
lib/contracts/address.go
lib/contracts/feeoraclev2/deploy.go
lib/contracts/feeoraclev2/feeparams.go

Created a FeeOracleV2 deployment routine that uses Create3. We cannot upgrade FeeOracleV1 as V2 has a different storage layout. This routine does not currently include upgrade logic.
issue: #1951

feat(e2e): create FeeOracleV2 deployer

---

halo/attest/keeper/cpayload.go
halo/attest/keeper/cpayload_internal_test.go
halo/attest/keeper/keeper.go
halo/attest/keeper/valaddr.go
octane/evmengine/keeper/abci.go
octane/evmengine/keeper/abci_internal_test.go
octane/evmengine/types/cpayload.go

Verify (and discard) invalid votes before proposing. This is required since VerifyVoteExtension isn't always called, so LastLocalCommit may contain invalid votes.
issue: #2460

fix(halo/attest): verify votes before proposing

---

lib/contracts/address.go
lib/contracts/address_test.go
lib/contracts/testdata/TestContractAddressReference.golden

FeeOracleV2 Create3 salt was missing.
issue: #1951

fix(lib/contracts): add feeoraclev2 salt generation

---

lib/contracts/fund.go

Unlock funding gas station on mainnet by removing automatic return if network is mainnet.
NOTE: This PR should not be merged until the gas station is deployed.
issue: #2206

chore(lib/contracts): unlock funding gas station

---

lib/contracts/feeoraclev2/deploy.go
lib/contracts/feeoraclev2/feeparams.go

Generation of FeeParams for L2 Sepolia testnets was failing as Sepolia isn't in the manifests for staging or omega. Default gas prices to 1 gwei for non-mainnet manifests.
issue: #1951

fix(lib/contracts): correct deployment of feeoraclev2

---

monitor/xfeemngr/gasprice/tiers.go

Update lower gas price tiers to match arb / op real values.
issue: none

chore(monitor/xfeemngr): tweak low gas price tiers to reflect real chains

---

lib/contracts/feeoraclev1/feeparams.go
lib/contracts/feeoraclev2/feeparams.go

Occasionally the CoinGecko API fails during our CI tests, triggering the default toNativeRate assignment. 1 was improper for certain routes, causing gas pump errors to occur. I've assigned correct placeholder values taking all native token conversions (ETH->ETH, ETH->OMNI, OMNI->ETH) into account.
issue: none

fix(lib/contracts): proper default toNativeRate values

---

lib/chaos/chaos.go
lib/chaos/chaos_test.go
lib/errors/errors.go
lib/errors/errors_test.go
relayer/app/buffer.go
relayer/app/worker.go

Adds chaos testing to relayer workers such that they regularly reset. This helps to ensure that the cursor store are working as expected as it is only read when workers bootstrap.
issue: none

feat(lib/chaos): add chaos errors to relayer workers

---

octane/evmengine/keeper/abci.go

Don't error (stall node) in `PostFinalize` if `CometBFT.Validators` returns an error, rather handle it graacefully and skip optimisic build. `CometBFT.Validators` is non-deterministic and may return unexpected errors in edge cases.
issue: #2480

fix(octane/evmengine): graceful post finalize errors

---

lib/chaos/chaos.go

Fix missing chaos probability in staging, set equaled to devnet chaos.
issue: none

ci(lib/chaos): enable chaos errors in staging

---

e2e/app/setup.go
e2e/types/manifest.go
halo/app/start.go
halo/cmd/flags.go
halo/cmd/testdata/TestCLIReference_rollback.golden
halo/cmd/testdata/TestCLIReference_run.golden
halo/cmd/testdata/TestRunCmd_defaults.golden
halo/cmd/testdata/TestRunCmd_flags.golden
halo/cmd/testdata/TestRunCmd_json_files.golden
halo/cmd/testdata/TestRunCmd_toml_files.golden
halo/cmd/testinput/input1/config/halo.toml
halo/config/config.go
halo/config/config.toml.tmpl
halo/config/config_test.go
halo/config/testdata/test_halo.toml
halo/evmstaking/evmstaking.go
lib/feature/feature.go
lib/feature/feature_test.go
lib/feature/flags.go

Add support for feature flags via a new `feature` package. Also add support to enable feature flags in manifests with the aim of having dedicated manifests with WIP features so that CI tests them.
issue: none

feat(lib/feature): add support for feature flags

---

halo/app/lazyvoter.go
halo/app/start.go
halo/comet/comet.go
octane/evmengine/keeper/abci.go
octane/evmengine/keeper/abci_internal_test.go
octane/evmengine/keeper/keeper.go
octane/evmengine/keeper/keeper_internal_test.go

Fixes next proposer selection algo:
- Leverage comet light client that does heavy lifting of fetching the current validator set.
- Use `CopyIncrementProposerPriority` which is built-in function to automatically select next proposer.
- Add debug logs
- Fix missing local address in lazy voter
issue: #2463

fix(octane/evmengine): fix next proposer algo

---

halo/attest/keeper/keeper.go
halo/attest/keeper/keeper_test.go

- Issue: Attestations were created even if double signing was detected, allowing malicious validators to spam the database with invalid data.
- Cause: Attestation creation was not rolled back if no valid signature was stored due to double sign detection.
- Solution: Added logic to delete the attestation if it was created but no signatures were added, preventing the spam of invalid data in the DB as suggested by @corverroos in https://github.com/omni-network/omni/issues/2488#:~:text=Proposed%20Solution-,In%20addOne%2C%20delete%20the%20attestation%20if%20it%20was%20created%20but%20signatures%20were%20inserted.,-corverroos%20added%20the
issue: fixes #2488

fix(halo/attest): delete empty attestations on double-sign detection

---

octane/evmengine/keeper/keeper.go

Reject execution payloads with deposits since they are not supported.
issue: #2481

fix(octane/evmengine): reject payloads with deposits

---

.pre-commit-config.yaml
e2e/app/geth/config.go
e2e/app/geth/types.go
e2e/app/geth/types_test.go
e2e/app/perturb.go
e2e/app/setup.go
e2e/docker/compose.yaml.tmpl
e2e/docker/docker.go
e2e/docker/docker_test.go
e2e/docker/testdata/TestComposeTemplate_commit.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network_upgrade.golden
e2e/manifests/backwards.toml
e2e/types/manifest.go
e2e/vmcompose/testdata/TestSetup_127-0-0-1-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-2-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-4-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-5-compose.yaml.golden
halo/genutil/evm/evm.go
halo/genutil/evm/evm_test.go

Add explicit supported geth versions. Ensure backwards compatibility in backwards.toml.
issue: none

ci(e2e): explicit supported geth versions

---

lib/contracts/feeoraclev1/deploy.go

Staging deployment is failing because FeeOracleV1 is failing to deploy. It is working in devnet deployments and in CI tests, so I am confirming it isn't an address collision first.
issue: none

chore(lib/contracts): output FeeOracleV1 impl and proxy addrs in logs

---

halo/genutil/evm/evm_test.go
lib/txmgr/txmgr.go

Backwards tests restarts all geths. This causes txmgr to fail submitting portalregistrations since it doesn't return a network error but EOF, catch and handle this.
EVM genesis test golden wasn't updated in recent PR, also make it smaller.
issue: none

test(e2e): fix tests

---

lib/ethclient/ethbackend/backend.go

The 12 second wait applied to Holesky contract deployments did not solve the issues we're seeing in Staging deployments.
issue: none

chore(lib/ethclient): remove holesky wait delay

---

e2e/app/evidence.go
e2e/app/gaspump.go
e2e/app/portalregistry.go
e2e/app/run.go
e2e/cmd/cmd.go
e2e/manifests/ci.toml

Add support for `manifest.evidence` that submits a double signing evidence and asserts the validator is slashed.
Also speed up e2e by doing stuff in parralel.
issue: #2490

ci(e2e): add slashing testcase

---

halo/evmstaking2/keeper/helpers.go
halo/evmstaking2/keeper/keeper.go
halo/evmstaking2/keeper/keeper_internal_test.go
halo/evmstaking2/module/module.go

Copies `Prepare` from `evmstaking` package and adds all the boilerplate around it.
issue: #2525

feat(halo/evmstaking2): implement Prepare

---

halo/app/ready.go

Avoid re-entrant `sync.RWMutex` read locking.
issue: none

fix(halo/app): fix readiness deadlock

---

halo/evmstaking2/keeper/helpers.go
halo/evmstaking2/keeper/keeper.go
halo/evmstaking2/keeper/keeper_internal_test.go
halo/evmstaking2/module/module.go

- Introduces a new method `processBufferedEvent` that clones the state and tries to deliver the passed EVM event
- Integrates the implementation of `deliverDelegate` function from `evmstaking` package
issue: #2525

feat(halo/evmstaking2): integrate delegation delivery code

---

e2e/app/definition.go
e2e/app/setup.go
lib/ethclient/ethbackend/backends.go
solver/app/app.go
solver/app/bindings.go
solver/app/cursor.go
solver/app/definition.go
solver/app/deps.go
solver/app/helpers.go
solver/app/targets.go

Wire solver event streamers.
issue: none

chore(solver/app): wire event streamers

---

e2e/app/setup.go

Only use proper solver keys in devnet (other networks don't have it configured).
issue: none

ci(e2e): fix solver deploy key

---

e2e/app/rpc.go
e2e/app/test.go
halo/attest/keeper/keeper.go
halo/evmstaking2/keeper/keeper.go
lib/contracts/feeoraclev1/feeparams.go
lib/contracts/feeoraclev2/feeparams.go
lib/log/log.go
lib/log/log_test.go
lib/log/testdata/TestSimpleLogs_cli.golden
lib/log/testdata/TestSimpleLogs_console.golden
lib/log/testdata/TestSimpleLogs_json.golden
lib/log/testdata/TestSimpleLogs_logfmt.golden
lib/netconf/provider.go
lib/p2putil/disc_test.go
lib/txmgr/config.go
lib/txmgr/ether.go
lib/txmgr/txmgr.go
monitor/app/public_rpc.go
monitor/routerecon/recon_internal_test.go
relayer/app/worker.go
scripts/golint/logattrs.go
scripts/golint/logattrs_internal_test.go
scripts/join/join_test.go

Adds:
- `log.InfoErr(ctx, "message", err)` to log errors at Info level. Same for `log.DebugErr`.
- Improve linter to check for invalid logging usage.
- Fix invalid usages. 
issue: none

chore(lib/log): add InfoErr and DebugErr

---

lib/contracts/contracts.go

Reduced gas station balance thresholds, as alerts were firing when the balance was fine.
issue: none

chore(lib/contracts): reduce gas station balance thresholds

---

e2e/app/geth/config.go
e2e/app/geth/testdata/TestWriteConfigTOML_archive.golden
e2e/app/geth/testdata/TestWriteConfigTOML_full.golden
e2e/app/geth/testdata/default_config.toml

Increase geth rpc fee cap.
issue: none

fix(e2e): increase rpc fee cap

---

e2e/types/testnet.go

Switches relayer to use archive1 to relieve cpu utilization on archive2
issue: none

chore(e2e): use first archive node

---

halo/evmstaking2/keeper/keeper.go
halo/evmstaking2/keeper/keeper_internal_test.go
halo/evmstaking2/module/module.go
halo/evmstaking2/types/interfaces.go

Implements the unit test for the delegate event delivery. At the end of the test, we assert that the staking message server actually received the message of the expected type.
issue: #2525

feat(halo/evmstaking2): unit test for delegate event delivery

---

relayer/app/worker.go

Wait for fuzzy submissions to finalize before confirming confFinalized streamers.
This fixes the following issue
- Fuzzy streamer is busy submitting some fuzzy messages (so msgCursorFilter has been updated).
- Finalized streamer skips over them (filters them out)
- Finalized streamer updates cursor store WITHOUT these fuzzy streams (BUG).
- But fuzzy streamer doesn't actually submit messages (due to whatever reason).
- When worker resets
- Finalized streamer is ahead of fuzzy streamer and gets stuck and logs "Gap in fuzzy msg offsets".
Solution
- Include all applicable messages in cursor, not just submitted.
- Finalized cursor will in that case not confirm, which is correct.
issue: none

fix(relayer): include all applicable msgs in cursor store

---

relayer/app/cursor/cursors_internal_test.go
relayer/app/cursor/store.go
relayer/app/worker.go

Don't overwrite existing cursors. Just check if offsets are identical.
This fixes the following problem:
- Cursor X is inserted into the DB
- Cursor X is confirmed (so it is the only cursor for this streamer).
- Worker resets, starts streaming from X (inclusive)
- Cursor X is overwritten (resetting it to unconfirmed).
- Worker resets (before cursor can be confirmed). In this case, there are no confirmed cursors.
- So worker starts streaming from MUCH lower height (overloading archive node).
- MUCH lower cursors become new confirmed height.
We could also start streaming from X+1 instead, since confirmed cursors are fully finalized, so no need to reprocess to handle partial submissions.
issue: none

fix(relayer/cursor): dont overwrite existing

---

cli/cmd/cmd.go
cli/cmd/register.go
cli/cmd/register_test.go
lib/contracts/avs/register.go

Added a CLI command to deregister an operator from the AVS contracts.
issue: https://github.com/omni-network/ops/issues/601

feat(cli): add AVS operator deregistration cmd

---

e2e/app/geth/config.go
e2e/app/geth/testdata/TestWriteConfigTOML_archive.golden
e2e/app/geth/testdata/TestWriteConfigTOML_full.golden
e2e/app/geth/testdata/default_config.toml

Limit `SuggestGasTipCap` (max 1 gwei) of omni's own nodes, since relayer is currently driving the price up bidding against itself since there are very few other txs. Blocks are also pretty much empty. So tips are not required.
issue: #2200

ci(e2e/geth): limit omni evm gas tips

---

e2e/types/infra.go

Adds an easy way to deploy all halo nodes by just specifying `halo` as e2e services regex.
issue: none

chore(e2e): support easy halo deploys

---

e2e/app/admin/allowoperator.go

Fix allow network logic
issue: none

chore(admin): fix allow network logic

---

docs/content/solvernet/how.md
docs/content/solvernet/problem.md
docs/website/sidebars.ts

Adds more context about the problem we're solving to the SolverNet section, so users coming to that section have full context and don't need to read through the `Learn` section as well. Don't change the learn section though, it's good to have it there too.
issue: none

chore(docs): more SolverNet

---

contracts/misc/package.json
contracts/misc/pnpm-lock.yaml
contracts/misc/script/pledge/Pledge.s.sol

Added foundry deploy script for Pledge contract
issue: none

feat(contracts/misc): add pledge deploy script

---

e2e/app/definition.go
e2e/docker/docker.go
e2e/docker/docker_test.go
e2e/docker/testdata/TestComposeTemplate_commit.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network_upgrade.golden
e2e/types/manifest.go
e2e/vmcompose/provider.go

Remove unused manifest `Pinned*` fields.
issue: none

chore(e2e/types): remove unused pinned manifest tags

---

e2e/app/run.go

Stop portal submissions early since perturbations cause it to flap.
issue: none

ci(e2e): fix flapper

---

contracts/solve/script/MintMockToken.s.sol
e2e/solve/deploy.go
e2e/solve/devapp/deploy.go
e2e/solve/symbiotic/app.go
e2e/solve/symbiotic/default-collateral-abi.json
e2e/solve/symbiotic/fund.go
e2e/solve/symbiotic/target.go
lib/anvil/utils.go
solver/app/targets.go

Add symbiotic devnet and staging targets.
issue: none

feat(e2e/solve): add symbiotic target

---

e2e/app/definition.go
e2e/docker/docker.go
e2e/docker/docker_test.go
e2e/docker/testdata/TestComposeTemplate_commit.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network_upgrade.golden
e2e/manifests/mainnet.toml
e2e/manifests/omega.toml
e2e/types/manifest.go
e2e/vmcompose/provider.go

Revert to using pinned docker image tags for protected network. This allows explicit versions, removes remembering what is/can/should be deployed. Makes upgrading explicit and documented.
issue: none

ci(e2e): revert to using pinned tags

---

e2e/app/cleanup.go
lib/chaos/chaos.go
lib/expbackoff/expbackoff.go
lib/expbackoff/retry.go
lib/expbackoff/retry_test.go
relayer/app/app.go
relayer/app/cursor/store.go

Few fixes and improvements:
- add a `expbackoff.Retry` util function. (will refactor existing retries to this in next PR)
- add debug logs to relayer cursors
- Enable chaos errors in relayer.
issue: none

chore(*): few tiny fixes

---

e2e/solve/symbiotic/app.go

Fix manager addr in allow calls.
issue: none

fix(e2e): fix manager addr

---

e2e/vmcompose/provider.go
lib/expbackoff/expbackoff.go
lib/expbackoff/retry.go
lib/expbackoff/retry_test.go

Attempt to mitigate sporadic Permission denied SCP errors by retrying a few times when upgrading services in E2E.
issue: none

ci(e2e): retry scp on permission denied

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bump protected network relayer (and monitor for simplicity) to remove BUG log on cursor migration.
issue: none

ci(e2e): bump protected web2 services

---

e2e/cmd/cmd.go

Use `reset` as an alias for `deploy` in e2e. This allows humans and github actions to refer to "resetting staging", and the use the term "deploy" for a more general process of running different docker containers.
issue: none

ci(e2e): alias deploy as reset

---

halo/app/app_config.go
halo/evmstaking2/keeper/keeper.go

- changes the delivered events metric to only go up if at least one event was delivered
- adds a new interval for staging for easier testing
issue: #2525

fix(halo/evmstaking2): improve delivered events metric

---

monitor/routerecon/recon.go
monitor/routerecon/recon_internal_test.go
monitor/routerecon/routescan.go
monitor/routerecon/routescan_internal_test.go

Enable routerecon for mainnet.
issue: https://github.com/omni-network/ops/issues/654

chore(monitor/routerecon): support mainnet

---

halo/app/app.go
halo/app/app_config.go

The current event processor seems to steal the EVM. We need to remove the injection of the processor if the valsync buffering is on.
issue: #2525

fix(halo/evmstaking2): fix EVM event hijacking

---

solver/app/metrics.go
solver/app/processor.go

Add event processed counter to solver. The aim is to simply track the number of events processed by status.
issue: none

chore(solver/app): event counter metric

---

octane/evmengine/keeper/keeper.go

Validate EVM event processors and error on duplicate names or addresses.
issue: #2525

fix(octane/evmengine): error on duplicate event processors

---

scripts/stagingaddrs/main.go

Updated the `stagingaddrs` script to return all contracts we're deploying with Create3.
issue: none

chore(scripts): return all create3 contracts

---

monitor/xfeemngr/gasprice/tiers.go

In order to help resolve the noisy gas price alerts, I added more gas price tiers to the monitor. I also decreased the alert trigger threshold from 0.3 to 0.2, as we now use a model where oracle gas prices will usually be a little higher than onchain.
issue: #2678

feat(monitor/xfeemngr): added gas tiers above 200 gwei

---

e2e/solve/devapp/target.go

Fix hardcoded devnet addresses
issue: none

chore(solver): fix staging solver addresses

---

cli/cmd/flags.go
cli/cmd/staking.go
solver/app/targets.go

Fixes typo in solver.
Also makes cli `delegate` command public so it can be used in scripts.
issue: none

chore(solver): fix solver typo

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bump relayer and monitor in protected network to latest main.
Aim is to deploy RouteScan recon on mainnet monitor.
issue: none

e2e(manifest): bump monitor in protected networks

---

cli/cmd/flags.go

This PR updates the flags for the operator init-nodes cmd so that the cmd can be run directly from source without having to install the omni CLI. This PR adds a new flag **--halo-tag**, which is the halo tag to use for the new node. This is required because the current `buildinfo.GitCommit() ` func will return an err if the cmd is not run from an binary. This PR also binds the current **--feature-flags** to the init-nodes command. Now we can run the command in CI and locally as follows 
```
cd cli/cmd/omni
go run main.go operator init-nodes --network=staging \
--moniker=foo \
--home=/tmp \
--halo-tag=main \
--feature-flags=evmstaking
```
issue: none

fix(cli/cmd): update operator init-nodes cmd

---

contracts/solve/src/ERC7683/SolverNetInbox.sol
contracts/solve/src/ERC7683/SolverNetOutbox.sol
contracts/solve/src/ERC7683/interfaces/IDestinationSettler.sol
contracts/solve/src/ERC7683/interfaces/IERC7683.sol
contracts/solve/src/ERC7683/interfaces/IOriginSettler.sol
contracts/solve/src/ERC7683/interfaces/ISolverNet.sol
contracts/solve/src/ERC7683/interfaces/ISolverNetInbox.sol
contracts/solve/src/ERC7683/interfaces/ISolverNetOutbox.sol

Implemented an ERC7683 compliant version of the Solve contracts. No tests have been implemented yet at the time of this PR.
issue: #2691

feat(contracts/solve): implemented ERC7683 version of solve

---

docs/content/core/mainnet.md

Add a simple link to the bridge in our docs. Could probably use a rethink though, since this is buried in the Core section.
issue: none

chore(docs): add bridge to docs

---

contracts/solve/src/ERC7683/SolverNetInbox.sol
contracts/solve/src/ERC7683/interfaces/ISolverNetInbox.sol

Refactor order state types / logic.
- rename "params" -> "state", more reflective of purpose
- removed `SolverNet` prefix to typenames
- return tuple from `getOrder`, instead of forcing name on wrapped struct
- shorten names when reasonable
- introduce upsert (update / insert) pattern
issue: none

chore(contracts/solve): refactor order state

---

cli/cmd/avs_register.go
cli/cmd/avs_register_test.go
cli/cmd/cmd.go
docs/content/operate/faq.md

Prefix `omni operator register / deregister` with `avs-`, as these commands only concern avs registration.
issue: none

chore(cli): add prefix to avs commands

---

halo/evmslashing/depinject.go
halo/evmslashing/evmslashing.go
halo/evmstaking/depinject.go
halo/evmstaking/evmstaking.go
halo/evmstaking2/keeper/keeper.go
halo/evmstaking2/keeper/keeper_internal_test.go
halo/evmstaking2/module/module.go
halo/evmupgrade/evmupgrade.go
halo/registry/keeper/keeper.go
halo/registry/keeper/logeventproc.go
halo/registry/keeper/logeventproc_internal_test.go
halo/registry/module/module.go
octane/evmengine/keeper/abci_internal_test.go
octane/evmengine/keeper/events.go
octane/evmengine/keeper/keeper.go
octane/evmengine/keeper/msg_server.go
octane/evmengine/keeper/msg_server_internal_test.go
octane/evmengine/types/cpayload.go

Simplify the `evmengine.EvmEventProcessor` interface to return filter query params, instead of doing fetch logic. This reduces lots of duplication and removes EthCl dependency from event procs
issue: #2106

refactor(octane/evmengine): simplify event proc interface

---

e2e/manifests/devnet2.toml
e2e/manifests/staging.toml
halo/app/start_test.go
halo/evmstaking2/keeper/keeper_internal_test.go
lib/ethclient/enginemock.go
lib/feature/feature.go
octane/evmengine/keeper/abci.go
octane/evmengine/keeper/abci_internal_test.go
octane/evmengine/keeper/events.go
octane/evmengine/keeper/events_test.go
octane/evmengine/keeper/msg_server.go
octane/evmengine/keeper/msg_server_internal_test.go
octane/evmengine/keeper/proposal_server.go
octane/evmengine/keeper/proposal_server_internal_test.go
octane/evmengine/types/tx.proto

Simplify the evm event processing in octane. Note this is behind the new `simple-evm-events` feature flag since it is consensus breaking. Also, this skips evm events from the block before the network upgrade.
issue: #2106

refactor(octane/evmengine): simplify event processing

---

cli/cmd/staking.go
contracts/avs/test/common/Utils.sol
contracts/bindings/slashing.go
contracts/core/src/octane/Staking.sol
contracts/core/src/octane/Upgrade.sol
contracts/core/src/token/OmniBridgeNative.sol
docs/content/operate/validator.md
e2e/app/key/key.go

This PR addresses multiple grammatical errors in comments and documentation across various files in the repository. These changes improve readability and adhere to proper English grammar standards.
1. **`staking.go`**  
- Corrected "a unjail transaction" to "an unjail transaction."
2. **`Utils.sol`**  
- Corrected "a operator" to "an operator."
3. **`slashing.go`**  
- Corrected similar grammar inconsistencies in generated files.
4. **`Staking.sol`**  
- Corrected "an new implementation" to "a new implementation."
5. **`Upgrade.sol`**  
- Corrected "an new implementation" to "a new implementation."
6. **`OmniBridgeNative.sol`**  
- Corrected "an new implementation" to "a new implementation."
7. **`validator.md`**  
- Corrected "a operator private key" to "an operator private key."
8. …

fix(docs): correct grammatical errors

---

halo/genutil/evm/predeploys/predeploys.go

In OZ v5, proxy contracts deploy their own proxy admin.
They do so in genesis creation script.
This is no longer accurate, or needed.
issue: none

chore(halo/genuitl): remove unused and innacurate proxy admin addr

---

docs/content/operate/roadmap.md

Update operators roadmap
issue: none

chore(docs): update operators roadmap

---

lib/contracts/address.go
lib/contracts/testdata/TestContractAddressReference.golden
lib/netconf/static.go

Static staging token address.
We do not need to redeploy the token each time, as it's code will not change.
issue: none

chore(lib/contracts): static staging token addr

---

.github/workflows/ci-join-manual.yaml
.github/workflows/ci-join.yaml
cli/cmd/flags.go
cli/cmd/initnodes.go
scripts/join/join_test.go

- Support testing the scenario of a node synced from a backup snapshot to join a network utilizing the new `--from-latest-snapshot` option of the `init-nodes` command.
issue:  #2803

ci(scripts/join): add join test for node snapshots

---

halo/app/lazyvoter.go
halo/attest/types/interface.go

Fix edge-case where lazy voter attest header caches contain multiple rounds of attest headers which may be duplicated. Fix is to dedup cached values to prevent BUG log.
issue: none

fix(halo/app): dedup lazy voter header caches

---

lib/cast/cast.go
lib/ethclient/ethbackend/backends.go
lib/netconf/netconf.go
solver/app/v2/app.go
solver/app/v2/metrics.go
solver/app/v2/procdeps.go
solver/app/v2/processor.go
solver/app/v2/processor_internal_test.go
solver/app/v2/reject.go
solver/app/v2/reject_internal_test.go
solver/app/v2/rejectreason_string.go
solver/app/v2/tokens.go
solver/app/v2/types.go

Solve v2 ERC6783 orders by managing on-chain liquidity.
Liquidity only checked on ShouldReject, existing commitments not accounted for.
Restricted to hardcoded list of supported tokens.
issue: none

feat(app/solver): v2 solve by liquidity

---

e2e/solve/deploy.go
lib/contracts/address.go
lib/contracts/address_test.go
lib/contracts/solvernet/inbox/deploy.go
lib/contracts/solvernet/outbox/deploy.go
lib/contracts/testdata/TestContractAddressReference.golden

Deploy v2 SolverNet Inbox / Outbox contracts in e2e.
Deploy files are copy of existing `lib/contracts/solve(inbox|outboux)/deploy.so`, just changed the bindings used. 
issue: none

chore(e2e/solve): deploy v2 solvernet boxes

---

monitor/app/app.go

Logs an error instead of crashing.
issue: none

fix(monitor): dont crash monitor app

---

.github/actions/setup-foundry/action.yaml
.github/workflows/gotest.yaml

Pull correct foundry docker image tag in test setup.
We were pulling latest, but tests were using the global foundry version sha in `scripts/foundry_version.txt`. 
So tests needed to pull, which caused timemouts.
issue: none

chore(ci): install locked foundry version in go test

---

e2e/app/erc20faucet.go
e2e/app/tokenbridge.go
lib/contracts/omnitoken/deploy.go
lib/contracts/omnitoken/mint.go

Make OMNI mintable on devnet and staging. 
issue: none

feat(e2e): make omni token mintable on ephemeral networks

---

cli/cmd/initnodes.go

wrong snapshot download path - relative instead of absolute
issue: #2814

fix(cli/cmd): fix rel to abs snapshot download path

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Pin monitor and relayer tag to [cef2aa0](https://github.com/omni-network/omni/commit/cef2aa06359f6743c5e4a63b4cee236339f9c747).
issue: #2275

chore(e2e): pin monitor tag cef2aa0

---

cli/cmd/flags.go
cli/cmd/initnodes.go
scripts/join/join_test.go

Improve omni cli `--init-nodes` flags:
- Remove `--feature-flags` since it wasn't actually used
- Default `--halo-tag` to version of git commit
issue: none

chore(cli): improve init-nodes flags

---

README.md

Update the repo map in readme:
- adds sdk and solver
- removes subdirectories from this level map, leave that to the directories themselves. less is more
issue: none

chore(readme): update repo map

---

e2e/manifests/devnet2.toml
lib/feature/feature.go
octane/evmengine/keeper/abci.go
octane/evmengine/keeper/evmengine.proto
octane/evmengine/keeper/keeper.go
octane/evmengine/types/convert.go
octane/evmengine/types/customproto.go
octane/evmengine/types/tx.pb.go
octane/evmengine/types/tx.proto

Swap octane evmengine ExecutionPayload encoding from json to protobuf which is strictly decoded by cosmos.
This mitigates arbitrary data injection by proposers. 
It also decreases consensus block size since protobufs serialize smaller than json.
Note this feature is behind the `proto-evm-payload` feature flag and will only be enabled in next network upgrade.
issue: #2533

feat(octane/evmengine): proto encode execution payload

---

.github/workflows/ci-join.yaml

- Temporarily remove node snapshot job due to them failing because of disk space issues.
- Those flows will be migrated out of this repo, but for now we just want to avoid having nightly failures for `Join Network Tests Nightly`.
issue: none

fix(github): temp remove node snapshot flow

---

cli/cmd/initnodes.go

Skip Geth Initialization when running in --node-snapshot mode.
issue: #2842

fix(cli/cmd): run geth DB init only on full sync

---

e2e/app/setup.go
e2e/docker/compose.yaml.tmpl
e2e/docker/docker.go
e2e/docker/docker_test.go
e2e/docker/testdata/TestComposeTemplate_commit.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network_upgrade.golden
e2e/vmcompose/provider.go
e2e/vmcompose/provider_test.go
e2e/vmcompose/testdata/TestSetup_127-0-0-1-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-2-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-4-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-5-compose.yaml.golden
halo/app/start.go
lib/cchain/provider/abci.go
relayer/app/app.go
relayer/app/config.go
relayer/app/config.toml.tmpl
relayer/app/config_test.go
relayer/app/testdata/default_relayer.toml
relayer/cmd/flags.go

Switch relayer to use halo gRPC CProvider for improved performance.
issue: #2252

chore(relayer): use halo gRPC cprovider

---

docs/content/operate/faq.md

Added a FAQ question providing info about how to deregister from the AVS.
issue: #601

feat(docs): added FAQ question for AVS deregistration

---

relayer/app/gas.go
relayer/app/gas_internal_test.go

Skip manual gas estimation for arb mainnet, like we do for arb sepolia. 
issue: none

fix(relayer): skip manual gas estimation for arb mainnet

---

e2e/manifests/omega.toml

Updating relayer / monitor omega pin.
To get fix 6389aca into omega, then mainnet.
issue: none

chore(e2e/manifests): update omega relayer monitor pin

---

lib/contracts/solvernet/bindings.go
lib/contracts/solvernet/bindings_test.go
lib/contracts/solvernet/errors.go
lib/contracts/solvernet/order.go
solver/app/v2/bindings.go
solver/app/v2/procdeps.go
solver/app/v2/types.go

Move solvernet utils to lib. Add open order util.
issue: none

feat(lib/contracts): move solvernet utils to lib

---

docs/content/core/intro.md
docs/content/learn/what.md

In `docs/content/core/intro.md`:
- Old: "A execution layer"
- New: "An execution layer" 
Reason: Fixed article usage - "an" is used before words beginning with vowel sounds.
In `docs/content/learn/what.md`:
- Old: "proff"
- New: "proof"
Reason: Fixed spelling error in the word "proof".
These changes improve documentation accuracy and readability by fixing typos and grammatical errors.
issue: none

docs(content): fix typos 

---

.github/workflows/ci-join-manual.yaml
.github/workflows/ci-join.yaml

temp disable omega full sync join tests due to insufficient github runner resources
issue: none

fix(github): temp remove omega full sync flow

---

.github/workflows/ci-pr-docs.yaml

Don't preview docs on PRs from external contributors. Why?
- ci currently fails on PRs from external contributors that modify docs. [example](https://github.com/omni-network/omni/pull/2871)
- this is because the preview deploy action requires a vercel token, which is a github secret
- we don't want github secrets to be public to external PRs
- to do this, just check if it's from a fork of the repo, since contributors without write access need to fork instead of creating a branch
issue: none

chore(ci): dont preview docs on external prs

---

e2e/app/setup.go
e2e/manifests/fuzzyhead.toml
halo/app/start.go
lib/ethclient/engineclient.go
lib/feature/feature.go
octane/evmengine/keeper/abci.go

Previous attempts at engine API error handling didn't actually work in the case that geth returns INVALID AND ERRORS. This is because the geth client, only returns responses OR errors. 
Detect application errors in NewPayloadV3 by checking for RPC error types, convert all these to INVALID status.
Also add support for fuzz testing octane evm payload proposing. This ensures that invalid payloads dont stall (slow down) the chain.
issue: #2461

test(octane/evmengine): fuzz test proposed payload

---

e2e/app/agent/prometheus.yaml.tmpl
e2e/app/agent/testdata/TestPromGen_manifest1_gen.golden
e2e/app/agent/testdata/TestPromGen_manifest1_update.golden
e2e/app/agent/testdata/TestPromGen_manifest2_gen.golden
e2e/app/agent/testdata/TestPromGen_manifest2_update.golden
e2e/app/agent/testdata/TestPromGen_manifest3_gen.golden
e2e/app/agent/testdata/TestPromGen_manifest3_update.golden
e2e/app/agent/testdata/TestPromGen_manifest4_gen.golden
e2e/app/agent/testdata/TestPromGen_manifest4_update.golden

Decrease prometheus scrape interval from 30s to 1m.This should reduce Grafana cloud costs by 50%.
issue: https://github.com/omni-network/ops/issues/715

chore(e2e/agent): decrease prometheus scrape interval

---

lib/cchain/provider.go
lib/cchain/provider/abci.go
lib/cchain/provider/provider.go
lib/cchain/types.go

Expose underlying cosmos gRPC query clients in cprovider.
CProvider interface is getting very big. We don't need to wrap and customize each module function. So rather just expose all clients. If we see we want to wrap a specific method, then we can do that later once the need is clear.
issue: none

chore(cchain/provider): expose cosmos module query clients

---

e2e/manifests/staging.toml

convert validator01 on staging's manifest to be an archive node intended for node snapshot usage
issue: #2900

ci(e2e): convert validator01 to archive node

---

monitor/account/monitor.go

Typo in the function name. Fixed it to `monitorAccountForever` to align with the intended functionality and naming conventions.
issue: none

fix: fix function name in monitor.go

---

halo/attest/keeper/keeper.go

Fix typo that results in accepting of invalid VEs. 
Impact of bug: 
- Malicious validator can submit invalid votes which are then accepted and included in comet block.
- But, these invalid votes will be ignored in `PrepareVotes` by honest validators.
- Malicious validators that do include these in block proposals will be rejected.
- So this impact is Low as the only impact is invalid votes in consensus blocks. It cannot stall the chain or prevent block building or further vote attestations.
issue: none

fix(halo/attest): fix vote extension validation issue

---

e2e/solve/deploy.go
e2e/solve/mocktokens.go
solver/app/v2/testdata/TestTokens.golden
solver/app/v2/tokens.go
solver/app/v2/tokens_internal_test.go

Add mock solvernet token deployments, to test solver in devnet / staging.
Relies on #2906
issue: none

chore(e2e/solve): add mock token deployments

---

solver/app/v2/quote.go
solver/app/v2/reject.go
solver/app/v2/reject_internal_test.go
solver/app/v2/rejectreason_string.go
solver/app/v2/testdata/TestTokens.golden
solver/app/v2/tokens.go

Require deposits match expenses 1:1.
- introduce concept of a quote. will be useful in api (e.g GET /quote)
- only support single expense / deposit, require tokens match (by symbol)
Additionally, refector reject.go to use `RejectOrErr`. Makes it easier to split `shouldReject` into utils.
issue: #2920

feat(solver/app): require deposits match quote for expenses

---

solver/app/v2/testdata/TestTokens.golden
solver/app/v2/tokens.go

Copy holesky tokens to mock L1. So we can use them in e2e fork mode.
issue: none

chore(solver): copy holesky tokens to mock l1

---

Makefile
e2e/manifests/devnetsolve.toml

Enable v2 in devnetsolve manifest and extend manifest param to `devnet-clean`
issue: none

chore(e2e): enable v2 in devnetsolve manifest

---

halo/config/config.go

Enable unsafe CORS on ephemeral network by default. 
issue: none

chore(halo): enable unsafe CORS on ephemeral networks

---

e2e/solve/deploy.go
e2e/solve/fund.go

Fund solver with holeksy wstETH on devnet.
We'll do this for all devnets with MockL1. It's fine.
If we have a bunch of public tokens we want to use in fork mode, we can change it
to only fund solver if we are indeed forking that chain
issue: none

chore(e2e/solve): fund solver holesky wstETH on devnet

---

e2e/manifests/devnet2.toml
e2e/test/cli_test.go
halo/evmstaking2/keeper/keeper.go
halo/evmstaking2/keeper/keeper_internal_test.go
lib/feature/feature.go

Merges `evm-staking-module` and `delegations` feature flags because both features will be released in the same release.
issue: none

chore(lib/feature): merge feature flags

---

contracts/solve/src/_optimized/SolverNetExecutor.sol
contracts/solve/src/_optimized/SolverNetInbox.sol
contracts/solve/src/_optimized/SolverNetOutbox.sol
contracts/solve/src/_optimized/interfaces/ISolverNet.sol
contracts/solve/src/_optimized/interfaces/ISolverNetExecutor.sol
contracts/solve/src/_optimized/interfaces/ISolverNetInbox.sol
contracts/solve/src/_optimized/interfaces/ISolverNetOutbox.sol
contracts/solve/src/_optimized/lib/SolverNet.sol

By completely refactoring the `OrderData` type and storing it instead of a `ResolvedCrossChainOrder` type, I managed to reduce costs by ~70%. The new type requires 6 slots minimally, with 2 additional slots per token approval required. This is substantially optimized from the 25+ slots required to store the entire ERC7683 resolved order.
The user and solver-facing interface remains completely unchanged. The only breaking change in this implementation is that the `OrderData` is much different. However, it is also flatter, which should make it easier for the solver to populate.
issue: #2917

feat(contracts/solve): drastically optimized SolverNet orderData

---

e2e/app/setup.go
halo/app/app_config.go
halo/app/start.go
halo/app/start_test.go
halo/cmd/init.go
halo/genutil/genutil.go
halo/genutil/genutil_internal_test.go
halo/genutil/genutil_test.go
lib/cchain/provider/abci.go
monitor/app/app.go
relayer/app/app.go

Provide a `halo_app.ClientEncodingConfig` function, similar to cosmos `MakeTestEncodingConfig` that uses depinject to load the codecs. Use this in the gRPC client so custom types can be decoded.
issue: #2963

chore(halo/app): use depinject for encoding config

---

contracts/core/script/manual/GenesisStake.s.sol

This PR simply stores the foundry script I used to manually test the GenesisStake migration via SolverNet on Staging. This [TX](https://holesky.etherscan.io/tx/0xd9727a00a91fc241657e0c9b45f5d415647a368e34373ecbc4bdb301078bc5c9) successfully led to a 100 OMNI transfer received on Omni Staging.
issue: none

feat(contracts/core): test genesis stake migration on staging

---

halo/app/start_test.go
halo/app/upgrades/uluwatu/upgrade.go

Account for 5% validator rewards so that users get roughly 11% per year.
issue: #2891

feat(halo/app): account for validator rewards

---

scripts/join/join_test.go

enable logging when calling init-nodes in join_test.go
issue: none

fix(scripts): enable logging on init-nodes

---

octane/evmengine/keeper/abci.go
octane/evmengine/keeper/msg_server.go
octane/evmengine/keeper/msg_server_internal_test.go
octane/evmengine/keeper/proposal_server.go

Fixes issue where malicious proposers can trigger `retryForever` by proposing invalid `BlobCommitments`.
issue: none

fix(octane/evmengine): fix proposing invalid blobs

---

e2e/cmd/cmd.go

Added a new `newDeployXBridgeCmd` e2e command that deploys the xBridge contracts using `xbridge.Deploy`.
issue: #3018

feat(e2e/cmd): add deploy xbridge e2e cmd

---

e2e/cmd/cmd.go
e2e/solve/deploy.go

Added a new `newDeploySolverNetCmd` e2e command that deploys the SolverNet contracts using `solve.Deploy`.
issue: #3007

feat(e2e/cmd): add deploy solvernet e2e cmd

---

solver/app/reject.go

Approve outbox spend before checking reverts
issue: none

fix(solver): approve outbox spend before checking revert

---

.github/workflows/release-official.yaml
.github/workflows/release-snapshot.yaml

When building `halovisor` images, use main/local commit at `magellan` not `uluwatu`.
issue: none

ci(github): switch main binary to magellan

---

sdk/src/constants/contracts.ts
sdk/src/index.ts
sdk/src/types/order.ts
sdk/src/utils/withExecAndTransfer.ts

Introduce `ExecutionCall` to enable support for execution via middleman contract, without leaking implementation to users (mostly motivated by the fact the rp gist is incorrect right now without this). Ideally, we'd infer this rather than bloating the interface, but onBehalfOf functionality is different across protocols. 
issue: none

feat(sdk): withExecAndTransfer call constructor

---

solver/app/app.go

Disable solver on mainnet.
issue: none

chore(solver): disable on mainnet

---

.github/workflows/soltest.yaml
e2e/app/definition.go
e2e/app/monitor.go
e2e/app/run.go
e2e/cmd/cmd.go
e2e/cmd/util.go

NetworkFromDef relies on portals deployed in e2e.
Other e2e commands outside of deploy should not use it.
issue: none

fix(e2e): remove NetworkFromDef use outside e2e deploy

---

e2e/xbridge/bridge.go
e2e/xbridge/lockbox.go
e2e/xbridge/reference_test.go
e2e/xbridge/rlusd/deploy_token.go
e2e/xbridge/rlusd/xtoken.go
e2e/xbridge/testdata/TestReference.golden
lib/contracts/address.go

Separate xbridge and solvernet salts from core.
Let's use progress them independently.
issue: none

chore(lib/contracts): separate solvernet and xbridge salts from core

---

lib/tokens/tokens.go
monitor/flowgen/flowgen.go
monitor/flowgen/job.go
monitor/flowgen/symbiotic.go
monitor/flowgen/util.go
monitor/flowgen/util_internal_test.go

Add flowgen skeleton.
issue: #3006

chore(monitor): flowgen skeleton

---

e2e/manifests/omega.toml

Upgrade omega solver pin.
Includes #3075 , avoids loop on bad unsupported test chain.
issue: none

chore(e2e/manifests): upgrade omega solver pin

---

lib/cchain/queryutil/upgrade.go
scripts/join/join_test.go

Fix join test local images on macOS arm64. 
Also fix `queryutil.CurrentUpgrade`
issue: none

chore(scripts/join): fix local docker images

---

e2e/manifests/omega.toml

update monitor omega git tag to include the integrated RouteScan API key for increased rate limits
issue: none

chore(e2e): update monitor omega git tag

---

e2e/test/module_test.go
halo/app/start_test.go
halo/app/upgrades/magellan/upgrade.go
halo/app/upgrades/magellan/upgrade_internal_test.go
halo/app/upgrades/upgrades.go

Update slashing params for magellan upgrade:
- Reduce `DowntimeJailDuration` to minimum 1min to allow fast unjailing.
- Update `MinSignedPerWindow` to 5% which is Cosmos default.
issue: none

feat(upgrade/magellan): slashing params

---

e2e/app/admin/upgrade.go

The Staking upgrade was upgraded before its last round of changes. As reinitialization is not needed for this upgrade, the initializer call needs to be removed.
issue: #3031

chore(e2e): remove initializer from staking upgrade script

---

contracts/allocs/scripts/genallocs_internal_test.go
e2e/manifests/mainnet.toml

Adds two mainnet validators  to manifest(with keys).
issue: none

ci(e2e/manifest): add 2 mainnet validators

---

lib/contracts/address.go
lib/contracts/testdata/TestContractAddressReference.golden

The last SolverNet deployment wasn't verified, and we applied some contract changes since then, so we can no longer verify without pulling older commits. Just going to redeploy the current contracts, which should experience no further changes until the audit is finalized.
issue: none

chore(lib/contracts): bump solvernet omega version

---

e2e/solve/test.go
e2e/solve/testutil.go
lib/contracts/solvernet/types.go
lib/contracts/solvernet/types_test.go
solver/app/check.go
solver/app/internal_testutils.go
solver/types/api.go

Use call data in api, hex encoded.
issue: none

feat(solver): use full call data in api call type

---

sdk/src/constants/tokens.ts

Add token addresses to constants.
Will be useful for sharing mock token addrs.
issue: none

chore(sdk): add token addr constants

---

e2e/solve/mocktokens.go
solver/app/testdata/TestTokens.golden

stETH will not exist on L2s (only wstETH).
So it's not useful to have mock L2 steth tokens.
issue: none

chore(solver): remove mock l2 steth

---

sdk/src/hooks/useDidFill.ts
sdk/src/hooks/useOrder.ts

- we need to respect fetch status as txReceipt status === pending when txHash is not defined
issue: none

chore(sdk): respect fetch status of waitTx hook

---

e2e/app/testdata/TestManifestServiceReference.golden
e2e/manifests/staging.toml

Holesky has stalled, it is unclear when it will restart. Use mock_l1 on staging in the mean time. 
issue: none

ci(e2e/manifest): replace staging holesky with mock-l1

---

cli/cmd/flags.go
cli/cmd/staking.go
e2e/app/admin/allowoperator.go

Adds val3 and val4 to mainnet allow list.
issue: none

ci(e2e): allow val3 and val4 on mainnet

---

lib/fireblocks/client.go
lib/fireblocks/client_test.go

Switch to using `sepolia` assets for fileblocks raw signing on staging and omega. Since holesky has paused and fireblocks are returning errors when requested to sign using that asset. Note that the asset isn't actually used, it is only required by fireblocks API for validation.
```
chain=mock_l1 nonce=0 err="sign tx: external sign: create raw sign tx: non-JSON error response" status_code=400 body="{\"message\":\"Network hard-fork issues: [https://www.tokenpost.com/news/technology/14157\](https://www.tokenpost.com/news/technology/14157/)",\"code\":1450}"
```
issue: none

chore(lib/fireblocks): use sepolia assert instead of holesky

---

halo/app/start_test.go
halo/app/upgrades/magellan/upgrade.go
halo/app/upgrades/magellan/upgrade_internal_test.go

Update `magellan` distribution params.
- Flat 11% rewards for delegators since validators don't charge commision.
- Block period decreased a steady 1.5s
issue: none

feat(upgrade/magellan): update distribution params

---

halo/attest/keeper/keeper.go
halo/attest/keeper/metrics.go

Adds a `halo_attest_pending_blocks` metric that tracks the number of consensus blocks between the first vote and reaching quorum. This will alert if we loose xchain vote quorum. It will also allow tracking fast vs slow validators (to a limited extent).
issue: none

chore(halo/attest): add pending blocks metric

---

sdk/package.json
sdk/src/context/omni.tsx
sdk/src/hooks/useOrder.ts
sdk/src/hooks/useQuote.ts
sdk/src/index.ts
sdk/src/internal/api.ts
sdk/src/types/quote.ts

The `orderId` is needed to track the order on the outbox in the SolverNet app, and the `Quote` type is used internally by the app so it's convenient to have it exported by the SDK.
I also had to make some changes to the type checks so that Biome wouldn't complain about the use of `any`.
issue: none

feat(sdk): export Quote type and expose orderId

---

e2e/app/testdata/TestManifestServiceReference.golden
e2e/manifests/staging.toml

`mock_l1` chain is giving lots of RPC and funding errors because it does not have an externally reachable RPC. Removing it from manifest to redeploy staging without it.
issue: none

chore(e2e): remove mock L1 from staging manifest

---

docs/content/operate/magellan.md
docs/content/operate/uluwatu.md
docs/website/sidebars.ts

Adds the `Network Upgrade: Magellan` doc to website.
issue: none

docs(operate): add magellan network upgrade to public docs

---

e2e/manifests/omega.toml

Bumps omega halo nodes to v0.13.0. Also bumps relayer and monitor to a recent release.
issue: none

ci(e2e): deploy v0-13-0 to omega

---

docs/content/operate/magellan.md
docs/content/operate/run-full-node.md

Updates the "run a fullnode" docs wrt the `2_magellan` upgrade.
issue: none

docs(operator): improve run-a-fullnode docs

---

e2e/manifests/staging.toml
e2e/types/chain.go
lib/netconf/netconf.go
lib/xchain/connect/connect.go
monitor/xfeemngr/xfeemngr.go
solver/app/testdata/TestTokens.golden
solver/app/tokens.go

Replaced holesky with sepolia in the staging manifest, and went through various regions of the codebase that needed new Sepolia references.
issue: none

chore(e2e): holesky to sepolia in staging manifest

---

sdk/src/hooks/useOrder.ts
sdk/src/hooks/useValidateOrder.ts

Encoding defaults.
Also rename `props.validate` to `props.validateEnabled`
issue: none

chore(sdk): encoding defaults

---

e2e/app/admin/pausesolvernet.go
e2e/app/admin/solvernetspec.go
e2e/app/admin/solvernetspec_internal_test.go
e2e/app/admin/testdata/TestNetworkSolverNetSpec.golden
e2e/cmd/admin.go

Created `solvernetspec.go` following similar patterns found in `bridgespec.go` and `portalspec.go` to pause the `open` and `close` functions, or both. This will be used via the Contract Admin GitHub action.
issue: #3122

feat(e2e): add solvernetspec

---

solver/app/testdata/TestTokens.golden
solver/app/tokens.go

Added support for manually deployed mock OMNI tokens so we can test L2 -> Omni EVM like-asset transfers via solver.
issue: #3121

feat(solver): add mock OMNI ERC20 tokens

---

e2e/app/admin/planupgrade.go

Add omega `2_magellan` upgrade height to `87200000` roughly at Mon 27 Feb 1pm UTC.
issue: none

ci(e2e): set omega magellan upgrade height

---

sdk/.gitignore
sdk/biome.json
sdk/package.json
sdk/pnpm-lock.yaml
sdk/src/index.test.ts
sdk/vitest.config.ts

Basic setup of [Vitest](https://vitest.dev/) to run tests. I tried also bundling with Vite but it seems only meant for browser use, bundling all the dependencies rather than using package imports, so it's probably not ideal for most apps that bundle their code anyway and would benefit from tree-shaking.
issue: https://github.com/omni-network/ops/issues/951

chore(sdk): setup Vitest

---

e2e/solve/test.go
e2e/solve/testutil.go

Covers following test cases:
- DestCallReverts reject reason.
- Valid order with valid ETH spend.
- Add RejectDescription to fail message to give more info on cause of test failure.
issue: #3177

test(e2e/solve): add valid and invalid test order

---

solver/app/app.go
solver/app/check.go
solver/app/check_internal_test.go
solver/app/handler.go
solver/app/quote.go
solver/app/quote_internal_test.go
solver/app/server.go
solver/types/api.go

Refactor solver API handlers:
- single `handlerAdapator` that does all JSON (un)marshalling for all endpoints.
- Decouple JSON errors from handler response types. Logic now returns struct and errors (standard go).
issue: none

refactor(solver/app): refactor http handlers and types

---

e2e/app/admin/planupgrade.go
e2e/manifests/mainnet.toml

Set mainnet magellan upgrade height. 
Also bump mainnet pins.
issue: none

ci(e2e): mainnet magellan upgrade height

---

solver/app/app.go
solver/app/check_internal_test.go
solver/app/handler.go
solver/app/processor.go
solver/app/quote_internal_test.go
solver/app/server.go
solver/app/types.go

Improve solver logs and metrics:
- Best effort target names `ERC20:<Symbol>` and `Native:<Symbol>`
- Skip instrumenting `/api/v1/contracts` since it returns static data
- Reduce call debug logs to single line (noisy)
- Add tracing of API requests.
Also:
- Remove remaining type aliases (more canonical go)
issue: #3199

chore(solver): improve logs and tracing

---

sdk/package.json
sdk/pnpm-lock.yaml
sdk/test/index.ts
sdk/test/react.ts
sdk/test/shared.ts
sdk/vitest.config.ts

- add shared `createWrapper` and `renderHook` setups 
- benefits of this is to reduce code duplication and standardise configs across test setups
- enabled `happy-dom` for unit tests
issue: none

feat(sdk): setup shared test items

---

Makefile
e2e/manifests/backwards.toml

Enables the `backwards.toml` now that `v0.13.0` has been released, this ensures that `main` stays backwards compatible with `v0.13.0`, the first version that supports `magellan` upgrade.
issue: none

ci(e2e): enable backwards ci

---

e2e/app/setup.go
e2e/solve/order_tracker.go
e2e/solve/test.go
lib/contracts/solvernet/bindings.go
solver/app/app.go
solver/app/config.go
solver/app/config.toml.tmpl
solver/app/config_test.go
solver/app/testdata/default_solver.toml
solver/cmd/flags.go

Configure and enable tracing on `solver`.
Also improve logging and testing a bit. Align naming to `order_id`. Ensure orders are not added to tracker after checking for done starts.
issue: #3199

ci(solver): enable tracing on solver

---

lib/netconf/provider.go

Omega relayer/monitor is crashlooping with the error after disabling holesky.
```
Execution registry doesn't contain all eactual=map[164:omni_evm 84532:base_sepolia 421614:arb_sepolia 1000164:omni_consensus 11155420:op_sepolia] expected=[holesky omni_consensus omni_evm op_sepolia arb_sepolia base_sepolia] 
```
This disables that logic for all non-devnet networks.
issue: none

chore(lib/netconf): fix omega relayer/monitor

---

e2e/manifests/omega.toml

Bump omega images to include fix required after disabling holesky.
issue: none

ci(e2e): bump omega to fix holesky disable

---

e2e/solve/test.go
e2e/solve/testutil.go
lib/contracts/solvernet/types.go
lib/contracts/solvernet/types_test.go
monitor/flowgen/bridging/bridging.go
solver/app/check.go
solver/types/api.go

Remove the use of slice types `solvernet.Calls` and `solvernet.Expenses`.
Reasoning:
- Slice types isn't canonical go
- It results in OOP style code and logic
- Since we have multiple layers of types: `solver/types.Call` embeds `solvernet.Call` aliases `bindings.SolverNetCall`
- It is much simpler to work since slice of those types, instead of having to create the same structure for the slice types as well.
- less types is simpler to reason about and work with (but slightly more verbose).
issue: none

refactor(contracts/solvernet): remove slice types

---

e2e/app/test.go

increase e2e go test command timeout to 2 min due to almost reaching the previous limit of 1 min
issue: none

chore(e2e/app): increase go test timeout to 2m

---

e2e/app/fund.go

Skip disabled chains when funding accounts.
issue: none

fix(e2e/fund): dont fund disabled chains

---

solver/app/testdata/TestTokens.golden
solver/app/tokens.go

The old mock OMNI tokens I deployed can no longer be verified due to updated foundry configs. Replacing them with new mocks I have verified.
issue: none

chore(solver): replace mock OMNI tokens

---

e2e/manifests/omega.toml

Updating omega solver pinned version to get updated mock token addresses in.
issue: none

chore(e2e): update omega solver pin

---

e2e/solve/test.go
e2e/solve/testutil.go

Test orders for missing branches:
- Reject with `InvalidExpense` due to multiple native expenses.
- Reject with `InvalidExpense` due to multiple ERC20 expenses.
issue: #3177

test(e2e/solve): tests covering missing branches

---

sdk/src/hooks/useDidFill.test-d.ts
sdk/src/hooks/useGetOrder.test-d.ts
sdk/src/hooks/useGetOrder.test.ts
sdk/src/hooks/useParseOpenEvent.test-d.ts
sdk/src/hooks/useParseOpenEvent.test.ts
sdk/vitest.config.ts

- useGetOrder units
- tweaks to type tests
- enable type tests in vitest unit workspace
issue: #3170

chore(sdk): more unit tests and enable type tests

---

e2e/solve/test.go

Add a 90s context timeout to order tracker to improve troubleshooting when order tracker fails to complete because of some hanging issue.
issue: #3177

chore(e2e/solve): add a 90s context timeout to order tracker

---

lib/contracts/feeoraclev1/feeparams.go
lib/contracts/feeoraclev2/feeparams.go
lib/tokens/coingecko/coingecko.go
lib/tokens/coingecko/coingecko_test.go
lib/tokens/mock.go
lib/tokens/pricer.go
lib/tokens/pricer_test.go
monitor/xfeemngr/tokenprice/buffer.go
monitor/xfeemngr/tokenprice/buffer_test.go
relayer/app/pnl.go
solver/app/app.go
solver/app/pnl.go
solver/app/procdeps.go

Adds PnL in USD to solver.
issue: #3199

chore(solver/app): add usd pnl

---

lib/cchain/provider.go
lib/cchain/provider/provider.go
lib/cchain/queryutil/rewards.go
monitor/app/rewards.go

Use wall time for the estimation of effective inflation.
issue: #3279

fix(monitor): use wall time for rewards estimation

---

cli/cmd/compose.yaml.tpl
cli/cmd/initnodes.go
e2e/app/geth/config.go
e2e/app/geth/config_internal_test.go
e2e/app/geth/testdata/TestWriteConfigTOML_archive.golden
e2e/app/geth/testdata/TestWriteConfigTOML_full.golden
e2e/app/geth/testdata/default_config.toml
e2e/app/geth/types.go
e2e/app/geth/types_test.go
e2e/docker/compose.yaml.tmpl
e2e/docker/docker.go
e2e/docker/testdata/TestComposeTemplate_commit.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network_upgrade.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-1-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-2-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-4-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-5-compose.yaml.golden
solver/app/handlers_internal_test.go

Downgrade geth server to previous v1.14.13 since v1.15.5 isn't compatible with existing omega and mainnet genesis stored in chain DB.
issue: none

chore(geth): downgrade geth server to v1-14-13

---

halo/attest/keeper/msg_server.go
halo/attest/keeper/proposal_server.go
octane/evmengine/keeper/keeper.go

Assert msg authority fields.
issue: #3328

fix(halo): assert msg authority fields

---

lib/xchain/conflevel_string.go
lib/xchain/provider/fetch.go
lib/xchain/types.go
solver/app/app.go

Add support for `xchain.ConfMin1` which lags behind head by 1 block.
issue: none

chore(lib/xchain): add support for head-min-1 conf level

---

sdk/README.md
sdk/src/context/omni.tsx
sdk/src/errors/base.ts
sdk/src/hooks/useDidFill.ts
sdk/src/hooks/useGetOrder.ts
sdk/src/hooks/useOmniContracts.ts
sdk/src/hooks/useOrder.ts
sdk/src/index.test.ts
sdk/src/index.ts
sdk/src/types/config.ts
sdk/src/types/contracts.ts
sdk/src/types/order.ts
sdk/src/utils/getContracts.ts
sdk/src/utils/withExecAndTransfer.ts

Extracts the contract addresses from the Omni context to ensure they are always loaded from the API.
This affects other hooks and APIs that need to handle loading the contracts addresses.
issue: https://github.com/omni-network/omni/issues/3332

chore(sdk): add useOmniContracts hook

---

monitor/xmonitor/indexer/indexer.go
monitor/xmonitor/indexer/indexer_internal_test.go

Adds `solver` xdapp (outbox address) to monitor indexer. This ensures we can monitor/instrument/alerts on fill reverts and all other xmsg related metrics.
issue: #3199

chore(monitor): add solver xdapp metrics

---

lib/evmchain/evmchain.go
lib/xchain/types.go
solver/app/app.go
solver/app/cursor.go
solver/app/processor.go

Add a second solver event processor to all devnet chains. 
This ensures two things:
1. Processor is indeed idempotent (since each block processed twice explicitly).
2. That we are ready to enable this in public chains if required. 
issue: none

refactor(solver): multiple devnet streamers

---

e2e/anvilproxy/Dockerfile

When building `anvilproxy`, don't hardcode upstream forge docker image platform. Rather infer from environment. 
On latest docker and MacOS, this resulted in the forge binary being amd64, while the anvil proxy image was arm64, so it crashed.
issue: none

ci(e2e/anvil): infer upstream image platform

---

e2e/manifests/omega.toml

Bump omega monitor (only), enabling holesky, to see how finalization and chain heads look like.
issue: none

ci(e2e): enable holesky on omega monitor

---

lib/contracts/solvernet/bindings.go
solver/app/app.go
solver/app/check.go
solver/app/check_internal_test.go
solver/app/internal_testutils.go
solver/app/reject.go
solver/app/reject_internal_test.go
solver/app/targets.go
solver/app/targets_internal_test.go
solver/targets/targets.go
solver/types/reject.go
solver/types/rejectreason_string.go

Restrict call targets
Allow
- symbiotic wsteth vaults on sepolia
- staking contract on omni evm
- flowgen bridging
- calls through middleman to allowed targets
Middleman is part of the "product" for devs, so we need to support it. 
issue: #3349

feat(solver): restrict call targets

---

sdk/.gitignore
sdk/src/hooks/useDidFill.test.ts
sdk/src/hooks/useGetOrder.test.ts
sdk/src/hooks/useInboxStatus.test-d.ts
sdk/src/hooks/useInboxStatus.test.ts
sdk/src/hooks/useInboxStatus.ts
sdk/src/hooks/useParseOpenEvent.test-d.ts
sdk/src/hooks/useQuote.test-d.ts
sdk/src/hooks/useQuote.test.ts
sdk/src/hooks/useQuote.ts
sdk/src/hooks/useValidateOrder.test-d.ts
sdk/src/hooks/useValidateOrder.test.ts
sdk/test/mocks.ts
sdk/test/shared.ts

- useInboxStatus units
- require generic on `createMockReadContractResult` to restrict input type of data to match expected
issue: #3170

chore(sdk): units and require generic on mock

---

e2e/app/run.go

We are seeing `ci main` fail due to timeouts on xdapp tests. I'm disabling xbridge deployment and tests for now, as it is currently deprioritized.
issue: none

chore(e2e): disable xbridge deployment and tests

---

e2e/manifests/omega.toml

Bumps omega halo and relayer pinned images to enable hoelshy xchain attestations and relaying. 
issue: none

ci(e2e): enable omega holesky xchain

---

lib/contracts/solvernet/types.go
lib/xchain/connect/connect.go
lib/xchain/provider/streamlogs.go
monitor/flowgen/bridging/bridging.go
monitor/flowgen/flowgen.go
solver/app/app.go
solver/app/internal_testutils.go
solver/app/metrics.go
solver/app/pnl.go
solver/app/procdeps.go
solver/app/processor.go
solver/app/processor_internal_test.go
solver/app/reject.go
solver/app/reject_internal_test.go
solver/app/types.go

Split `solver/app.Order`into multiple types, since not all fields are always available. `PendingData` is only available in `pending` state, similarly for `FilledData`.
Had to refactor monitoring since the data isn't always available.
issue: #3199

refactor(solver/app): explicit pending data

---

e2e/test/sdk_test.go
sdk/integration-tests/flows.test.tsx

Skip tests if SolverNet is not available
issue: none

chore(ci): skip SDK tests in environments without solver

---

e2e/app/eoa/sponsors.go
e2e/app/fund.go
monitor/account/monitor.go

Monitoring and funding for temp genesis stake sponsor accounts.
Goal:
- easy way to fund sponsors by with existing fund action
- monitor accounts so we know when low
Sponsors were not added to "roles" because they are chain specific, and 
we are not setup for chain specific roles. These are temporary so added them 
separately. 
issue: none

chore(e2e): fund and monitor temp sponsor accounts

---

e2e/manifests/omega.toml

Update monitor pin on omega to pick up staking metric fixes.
issue: none

chore(e2e): update monitor pin on omega

---

solver/app/app.go
solver/app/metrics.go
solver/app/pnl.go
solver/app/procdeps.go
solver/app/targets.go
solver/targets/targets.go

Refactor solver PNL to include `target` as subcategory. 
This required moving `Income` to filled (from claimed), since target only available in pending data.
Also refactor target package to provide names.
issue: #3199

refactor(solver/app): refactor pnl

---

solver/app/age.go
solver/app/app.go
solver/app/metrics.go
solver/app/procdeps.go
solver/app/processor.go
solver/app/processor_internal_test.go

Refactor age cache:
- Use a central cache (since orderID unique across chains, and multiple processors may process the same order)
- Avoid adding `ago=0s` to most orders, only add is actually found.
- Use `dest_filled` block timestamp for accurate age
issue: #3199

refactor(solver/app): refactor age cache

---

solver/app/internal_testutils.go
solver/app/reject.go
solver/app/reject_internal_test.go

Do not reject native omni orders on insufficient inventory.
issue: none

feat(solver): do not reject OMNI insufficient inventory

---

solver/app/testdata/TestTokens.golden
solver/app/tokens.go
solver/app/tokens_internal_test.go

Allow different spend bounds by chain class.
Increase spend bounds for mainnet.
issue: none

feat(solver): allow different spend bounds by chain class

---

solver/app/rebalance.go

Rebalance native OMNI more quickly on omega
issue: none

chore(solver): rebalance omega more frequently

---

docs/website/package.json
docs/website/pnpm-lock.yaml

- override regex dep as it's not patched in latest docsauras 
issue: none

chore(docs): override regex dep

---

lib/bi/big.go
solver/app/quote.go
solver/app/quote_internal_test.go

When quoting deposits, round up (instead of down). This ensures that:
```
deposit := y
fee := z
expense = quoteExpense(deposit, fee)
deposit2 := quoteDeposit(expense, fee)
deposit2 == deposit
```
issue: none

fix(solver/app): round up when quoting deposit

---

solver/app/handler.go
solver/app/handlers_internal_test.go

When the request context is cancelled, return a 408 instead of 500, since it isn't "internal server error", but rather "request cancelled (or timeout)" for user side. So 4XX instead of 5XX.
issue: none

chore(solver): return 408 on request cancel

---

e2e/solve/test.go
lib/xchain/provider.go
lib/xchain/provider/metrics.go
lib/xchain/provider/streamlogs.go
solver/app/app.go
solver/app/metrics.go
solver/app/processor.go
solver/app/processor_internal_test.go

Add explicit processor lag metric. Since `ConfMin2` "head" isn't tracked, so we can't implicitly calculate lag by comparing processor height to head height.
Refactor EventStreamer to pass in `header` instead of just `height`.
issue: none

chore(solver/app): explicit proc lag metric

---

sdk/integration-tests/flows.test.tsx
sdk/integration-tests/hooks.test.tsx
sdk/integration-tests/test-utils.tsx
sdk/src/hooks/useGetOrderStatus.ts

Adds coverage for `useOrder` hook
issue: https://github.com/omni-network/ops/issues/826

chore(sdk): integration tests for hooks

---

lib/pnl/log.go
lib/xchain/provider/metrics.go
solver/app/app.go
solver/app/pnl.go
solver/app/procdeps.go

Improve PnL:
- Add `delta_gwei` field to all PnL logs, so profile can be calculated by simply summing all delta values.
- Rename gas+status PNL `filled` subcatefory to `Inbox:Claim`, and similarly `pending` to `Inbox:Reject`.
- Add more buckets to processor duration (2s is not enough).
issue: none

chore(solver/app): improve PnL

---

e2e/app/eoa/solver.go
e2e/app/eoa/solver_test.go
e2e/solve/mocktokens.go
monitor/account/monitor.go
solver/app/claimants.go
solver/tokens/tokens.go

Adds more cases to `monitor_account_token_balance_ether`:
- Also track all `claimant` balances on all chains for all `solver/tokens`
- Also track `solver` and `flowgen` balances for all chains and all `solver/tokens`. Not only those with `MinThresholds`. 
issue: none

chore(monitor): track more token balances

---

solver/tokens/testdata/TestTokens.golden
solver/tokens/tokens.go

Remove `stETH` mock token from devnet since it isn't used or deployed.
issue: none

chore(e2e): remove stETH mock token from devnet

---

e2e/manifests/omega.toml

Update omega solver pin.
Unlocks eigen testnet integration.
issue: none

chore(e2e): update solver pin

---

monitor/flowgen/bridging/bridging.go

When computing the order size, account for commissions and fees.
issue: none

fix(monitor/flowgen): account for fees and commissions

---

lib/ethclient/engineclient.go
lib/ethclient/ethclient.go
lib/ethclient/ethclient_gen.go
lib/ethclient/genwrap/genwrap.go
lib/ethclient/headercache.go
lib/ethclient/headercahce_internal_test.go
lib/ethclient/mock/mock_interfaces.go
lib/xchain/provider/fetch.go
lib/xchain/provider/provider.go
lib/xchain/types.go
lib/xchain/types_internal_test.go

When fetching `xchain.ConfMinX` headers, don't use `latest block heigh - X` since this can return old forks, especially from RPC providers which load balance requests over multiple nodes. 
Instead, walk back up the chain from latest using parentHash.
Add a headerCache to ethclient to mitigate increased queries.
issue: none

fix(lib/xchain): conf minX using explicit parents

---

e2e/manifests/mainnet.toml

Pin halo and mainnet services to the version running on omega.
issue: none

chore(e2): pin halo and monitor on mainnet

---

sdk/packages/test-utils/package.json
sdk/pnpm-lock.yaml

Added TS to dev dependencies for the `test-utils` package
issue: none

fix(sdk): add missing typescript dependency

---

lib/expbackoff/expbackoff.go
lib/expbackoff/expbackoff_test.go

Adds support for interrupting exponential backoffs. This aims to support websockets which interrupt "fetch backoff" when a new header is received. When combined with header cache, this will result in immediate processing of logs/blocks as soon as new head is seen. 
Currently, exponential backoff cause blocks to be processed 2s, 4s, sometimes 8s after new block is mined. Especially for L1 which is slow, exp backoff causes slow reaction times.
issue: none

chore(lib/expbackoff): add support for interrupting backoff

---

lib/ethclient/headercache.go
lib/ethclient/metrics.go

When streaming headers via websockets, also add them to the headercache.
Add metric that tracks age/latency of headers received via websockets.
issue: none

chore(lib/ethclient): add websockets to header cache

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Pin solver on omega and mainnet to version running on staging.
issue: none

chore(e2e): pin solver on omega and mainnet

---

lib/ethclient/engineclient.go
lib/ethclient/ethclient.go

Disable headercache since it introduces risk of caching (and then using/attesting/solving) reorged blocks if reorg detection fails (or is late) for any reason. This occured on staging relayer since it doesn't query/stream all xblocks, so it doesn't detect reorgs consistently. 
issue: none

chore(lib/ethclient): disable header cache

---

lib/xchain/provider/metrics.go
lib/xchain/provider/provider.go
lib/xchain/provider/streamlogs.go

Adds stream lag metric to track how fast we can react to on-chain events. 
issue: none

chore(lib/xchain): add stream lag metric

---

lib/bi/unit.go
lib/bi/unit_test.go
lib/tokens/tokens.go
lib/tokens/tokens_test.go
solver/app/internal_testutils.go
solver/app/pnl.go
solver/app/pnl_internal_test.go
solver/tokens/testdata/TestTokens.golden
solver/tokens/tokens.go

Supporting usdc in solver.
Notes:
- usdc has 6 dec, this should only matter in spend bounds & pnl logs (i've addressed)
- holesky does not have a canonical usdc
issue: none

feat(solver): support usdc

---

sdk/packages/react/src/hooks/useValidateOrder.test.ts
sdk/packages/react/src/hooks/useValidateOrder.ts

Wraps the order encoding so we can check and carry the error as needed.
issue: https://github.com/omni-network/omni/issues/3534

fix(sdk): return an error when encoding order

---

lib/ethclient/engineclient.go
lib/ethclient/ethclient.go
lib/ethclient/headercache.go
lib/ethclient/headercahce_internal_test.go

Re-enable headercache, but only for `HeaderByHash` since this has zero risk to return unexpected blocks. 
This also re-enables reorg detection metrics and alerts which is useful.
issue: none

chore(lib/ethclient): enable header by hash cache

---

halo/app/prouter.go
halo/app/prouter_internal_test.go
solver/app/metrics.go

Ensure that tx signing info is empty. This prevents malicious proposers from adding arbitrary data to the chain, which negatively affects chain operation.
This issue was reported on Immunify
issue: none

fix(halo/app): verify tx signing info empty

---

e2e/app/definition.go
e2e/app/definition_test.go
e2e/docker/data.go
e2e/solve/test.go
e2e/test/bridge_test.go
e2e/test/cli_test.go
e2e/test/e2e_test.go
e2e/test/gaspump_test.go
e2e/test/module_test.go
e2e/test/portal_registry_test.go
e2e/test/sdk_test.go
e2e/test/solve_test.go
e2e/test/upgrade_test.go
e2e/types/testnet.go
e2e/vmcompose/data.go

Adds `SolverAddr` to `Testnet` and use it in e2e/tests.
Populate this from `InfraData`, which is populated in docker and vmcompose respectively.
issue: none

ci(e2e): add solver address to testnet

---

solver/app/handler.go
solver/app/testdata/TestCheck/insufficient_deposit/resp_body.json
solver/app/testdata/TestCheck/insufficient_native_balance/resp_body.json
solver/app/testdata/TestCheck/sufficient_ERC20_balance/resp_body.json
solver/app/testdata/TestCheck/sufficient_native_balance/resp_body.json
solver/types/api.go
solver/types/reject.go

Add a `rejectCode` field to `/check` response which allows better programatic comparison of reject reasons (as compared with english string `rejectReason`). Also easier to lookup and reference.
issue: none

chore(solver/app): add rejectCode to check response

---

cli/cmd/devnet.go
cli/cmd/staking.go
e2e/anvilproxy/app/anvil.go
e2e/anvilproxy/app/xmsg.go
e2e/app/admin/bridgespec.go
e2e/app/admin/portalspec.go
e2e/app/admin/solvernetspec.go
e2e/app/admin/upgrade.go
e2e/app/definition.go
e2e/app/valupdates.go
e2e/cmd/util.go
e2e/solve/test.go
e2e/xbridge/test.go
halo/app/lazyvoter.go
halo/app/monitor.go
lib/anvil/anvil.go
lib/contracts/address.go
lib/ethclient/ethbackend/backends.go
lib/ethclient/ethclient.go
lib/ethclient/ethclient_gen.go
lib/ethclient/genwrap/genwrap.go
lib/ethclient/mock/mock_interfaces.go
lib/xchain/connect/connect.go
monitor/app/app.go
monitor/app/public_rpc.go
monitor/flowgen/flowgen.go
monitor/loadgen/loadgen.go
monitor/xfeemngr/xfeemngr.go
relayer/app/app.go
solver/app/app.go

Add `CloseIdleConnectionsForever` to ethclient. Call it in production use-cases.
This aims to mitigate the problem of TCP-keep-alive maintaining long-lived connections to stalled (but alive) RCP servers. This sometimes occurs with QuickNode, when one of the load-balanced upstream servers/nodes stalled, but we remain connected to it, requiring a restart of the affected service to reconnect to a healthy upstream. 
By periodically closing idle connections, we get best of both worlds, TCP-keep-alive improves performance of most queries since TCP connection doesn't need to be reestablished for each query. But we still reconnect every 5min ensuring good load balancing over time.
This also required some cleanup:
- Pass in context in production uses of `ethclient.DialContext`.
- Remove …

chore(lib/ethclient): close idle connections periodically

---

.github/workflows/e2etest.yaml
.github/workflows/pr-e2etest.yaml
e2e/test/sdk_test.go
sdk/integration-tests/assets/SolverNetInbox.json
sdk/integration-tests/assets/SolverNetMiddleman.json
sdk/integration-tests/assets/SolverNetOutbox.json
sdk/integration-tests/suites/contracts.ts
sdk/packages/react/src/constants/abis.ts
sdk/packages/react/src/hooks/useGetOrder.test.ts
sdk/packages/react/src/hooks/useInboxStatus.test.ts

The integration tests import the ABIs used in the source of the SDK and ensure they match the JSON files generated by forge.
In CI, these JSON files are always generated before running the tests, so any change should be captured even if the reference files in the integration tests assets folder haven't been updated.
issue: https://github.com/omni-network/omni/issues/3559

chore(sdk): add integration tests for contracts

---

sdk/integration-tests/test-utils.tsx
sdk/integration-tests/vitest.config.ts
sdk/packages/react/src/hooks/useParseOpenEvent.ts
sdk/packages/test-utils/src/constants.ts

Fix open event logs parsing.
In recent contract change, we added a new event to event log at the end of Inbox.open. Which means we can no longer use the last order as open event.
issue: none

fix(sdk): fix open log parsing

---

lib/ethclient/headerdb/headerdb.go
lib/ethclient/headerdb/headerdb_internal_test.go
lib/ethclient/headerdb/headerdb_test.go
monitor/xmonitor/monitor.go

Fixes deadlock in `headercachedb` since `cosmos-db.MemDB` deosn't support iterating and writing. It can deadlock when iteration is large.
issue: none

fix(ethclient/headerdb): prevent deadlock

---

lib/contracts/solvernet/types.go
monitor/flowgen/bridging/bridging.go
monitor/flowgen/bridging/bridging_internal_test.go
monitor/flowgen/bridging/config.go
monitor/flowgen/flowgen.go
monitor/flowgen/symbiotic/symbiotic.go
monitor/flowgen/types/types.go
solver/types/api.go

Split flowgen bridge orders into 64 smaller order to also do some load testing.
issue: #3540

refactor(monitor/flowgen): split bridge orders

---

monitor/flowgen/bridging/bridging.go
monitor/flowgen/flowgen.go
monitor/flowgen/symbiotic/config.go
monitor/flowgen/symbiotic/symbiotic.go

Refactor flowgen to use solver client for quotes. This decouples flowgen from internal solver logic, which is going to become much more complex with addition of swaps.
issue: none

chore(monitor/flowgen): use solver quote endpoint

---

sdk/packages/react/src/hooks/useDidFillOutbox.test.ts
sdk/packages/react/src/hooks/useGetOrder.test.ts
sdk/packages/react/src/hooks/useOrder.test.ts
sdk/packages/react/src/hooks/useOrder.ts
sdk/packages/react/test/mocks.ts

- continued useOrder test cases
- move wagmi mocks into shared mocks module
issue: #3170

test(sdk): continued useOrder test cases

---

.github/actions/setup-foundry/action.yaml
e2e/anvilproxy/Dockerfile
lib/anvil/compose.yaml.tmpl

Replaces the foundry docker image with a `stable` build hosted by my account. We should roll this back as soon as the official one gets fixed.
issue: none

fix(e2e): temporal fix of foundry docker image

---

lib/uniswap/addrs.go
lib/uniswap/genbindings.go
lib/uniswap/pools.go
lib/uniswap/swap.go
lib/uniswap/uniquoterv2.json
lib/uniswap/uniquoterv2_bindings.go
lib/uniswap/uniswaprouter02.json
lib/uniswap/uniswaprouter02_bindings.go

Init SwapToUsdc skeleton
- define pool fees and swap routes statically, based on mainnet [pools](https://app.uniswap.org/explore/pools). dynamic pool / route discovery not worth it atm
- add Quoter and SwapRouter02 bindings
- add skeleton SwapToUSDC entrypoint
issue: none

chore(lib/uniswap): init swap to usdc

---

lib/ethclient/ethbackend/backend.go

Adds mempool limit semaphore call to `SendTransaction`.
issue: none

chore(lib/ethbackend): fix missing semaphore

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Roll out latest monitor and solver changes to mainnet and omega.
issue: none

ci(e2e): bump omega mainnet web2

---

e2e/test/cli_test.go

Increases timeouts in cli e2e tests.
issue: none

test(e2e): increase the timeout

---

e2e/cmd/admin.go

Bridge isn't always deployed anymore, so deploy it explicitly in e2e-admin test.
issue: none

ci(e2e): fix admin test

---

lib/txmgr/txmgr.go

Handle `nonce too high` errors by simply retrying a few times (with backoff).
This mitigates races when multiple concurrent submissions reserve nonces and reach upstream geth nodes out of order.
issue: none

chore(lib/txmgr): handle nonce too high

---

lib/contracts/solvernet/bindings.go
lib/ethclient/ethbackend/backend.go
relayer/app/sender.go
solver/app/app.go
solver/app/helpers.go
solver/app/procdeps.go
solver/app/processor.go
solver/app/processor_internal_test.go
solver/app/worker.go

Best effort debugging of reverted txs by doing `Call` and custom error conversions.
Also improve `Failed job` logs (adding `order_id`). 
Also improve ID parsing.
issue: none

chore(solver/app): debug reverted txs

---

lib/ethclient/ethclient.go

Add 30s timeout to all ethclient http requests. This should fix production issue where clients are stuck waiting for response from server.
issue: none

chore(lib/ethclient): add http timeout

---

octane/evmengine/keeper/abci_internal_test.go
octane/evmengine/keeper/keeper.go
octane/evmengine/keeper/msg_server_internal_test.go
octane/evmengine/keeper/proposal_server_internal_test.go

Introduces the `strictMode` flag to the block payload validation which defines whether the payload should be rejected if it contains no withdrawals, even though we have some eligible ones. This is required, because after we upgrade the network to a new binary, the first block it executes is built by the previous binary, which cannot include the withdrawals.
This change should be deleted after drake is rolled out.
issue: none

fix(halo): relax block validation around upgrades

---

monitor/flowgen/bridging/bridging.go
monitor/flowgen/bridging/bridging_internal_test.go
solver/app/app.go
solver/app/handler.go
solver/app/pricer.go
solver/app/server.go
solver/app/tokens.go
solver/client/client.go
solver/types/api.go

Add `api/v1/price` endpoint to solver. This allows flowgen to calculate what size deposits are allows, since `SpendBounds` are defined on expenses, not deposits.
issue: none

chore(solver): add price endpoint

---

sdk/integration-tests/suites/flows.tsx
sdk/integration-tests/suites/hooks.tsx
sdk/integration-tests/test-utils.tsx
sdk/packages/test-utils/src/account.ts
sdk/packages/test-utils/src/constants.ts

- move to camel case naming
- add balance checks to filled lifecycle test
- add more assertions to existing tests
- replace some if(condition) checks in tests with throwing condition, otherwise the tests may be false positive
- tests for `useParseOpenEvent`, `useGetOrder`, `useOmniContracts` - remaining hooks are tested implicitly already (as are these, but wanted to add explicit testing of return types)
- assert data shape of returned value from various hooks to bolster defence against contract changes
issue: #3618

test(sdk): increase integration test coverage

---

solver/app/internal_testutils.go
solver/app/reject.go
solver/app/tokens.go

Reject orders that will bring solver balance below a safe minimum.
issue: none

chore(solver): maintain min safe eth balance

---

lib/cctp/audit.go
lib/cctp/audit_internal_test.go
lib/cctp/mint.go
lib/cctp/types/types.go
lib/cctp/types/types_test.go

Audite db with finalized messages
- rename StoreMessageForever to AuditForever (more appropriate)
- revert `minted` to `submitted` if mint not confirmed (will be retried by MintForever)
- refactor a bit
- correct any content mismatch. should only happen on reorg
change in block height / message bytes / message hash
- log diff if corrections are required
- log [BUG] logs if unexpected fields changes
issue: none

feat(lib/cctp): audit db with finalized messages

---

README.md

Docs dir was restructured. Switch to link to live docs.
issue: none

chore(README): fix logo link

---

e2e/manifests/ci.toml
e2e/solve/test.go
lib/bi/big.go
lib/bi/unit.go
lib/tokenpricer/coingecko/coingecko.go
lib/tokenpricer/coingecko/coingecko_internal_test.go
lib/tokenpricer/coingecko/coingecko_test.go
lib/tokenpricer/mock.go
lib/tokenpricer/mock_internal_test.go
lib/tokenpricer/tokenpricer.go
lib/tokens/asset.go
monitor/flowgen/bridging/bridging.go
sdk/integration-tests/suites/hooks.tsx
solver/app/check.go
solver/app/handler.go
solver/app/pricer.go
solver/app/pricer_internal_test.go
solver/app/quote.go
solver/app/quote_internal_test.go
solver/app/reject.go
solver/app/testdata/TestQuote/invalid_deposit_(chain_mismatch)/resp_body.json
solver/app/testutils_internal_test.go
solver/app/tokens.go
solver/client/client.go
solver/types/api.go
solver/types/price.go
solver/types/price_test.go

Remove all uses of float64 prices, instead use `*big.Rat` in token.Pricer.
For amount conversions (ensuring correct decimals), introduce a `solver/types.Price`.
Refactor fees to be added price price.
Fix flowgen amount calculations by using new prices.
issue: none

refactor(solver): no more float64 prices

---

e2e/manifests/ci.toml

Disable `all_e2e_tests` in `ci.toml` since undelegations tests are failing
issue: #3729

ci(e2e): disable all-e2e-tests in ci toml

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bumps off-chain services to latest main (omega and mainnet). This enables swaps on omega and releases all other latest changes to "prod".
issue: none

ci(e2e/manifest): bump protected network off-chain services

---

e2e/manifests/mainnet.toml

Bumps mainnet off-chain services. This disables flowgen swaps on mainnet. Align all off-chain service tags for simplicity. 
issue: none

ci(e2e/manifest): dump mainnet off-chain services

---

e2e/app/eoa/fund.go
e2e/app/eoa/testdata/threshold_reference.json
lib/contracts/solvernet/helpers.go
lib/contracts/solvernet/helpers_internal_test.go
lib/xchain/connect/connect.go
monitor/flowgen/bridging/bridging.go
solver/app/processor.go
solver/app/processor_internal_test.go
solver/app/util_internal_test.go

Detect "invalid transitions" and retry, assuming that this is due to RPC providers providing stale data, so retries should fix it.
Also write a `TestManualClaim` utility to manually claim orders.
Also improve flowgen logging and decrease flowgen role min balance. 
issue: none

fix(solver/app): retry on invalid transitions

---

e2e/test/e2e_test.go
lib/log/log_test.go
lib/log/logger.go
lib/log/t.go

Adds a `log.WihtTestLogger` function that tests can use to group test logs.
issue: none

chore(lib/log): add test logger for e2e tests

---

e2e/app/definition.go
lib/netconf/netconf.go
lib/netconf/provider.go
lib/netconf/static.go
lib/xchain/provider/fetch.go
relayer/app/worker_internal_test.go

Extend `netconf.Network` with support for non-portal (non-core) chains. This will be required in `solver` when adding non-core chain support.
The idea is:
- load network from portal registry like we do now
- then add a set of hardcoded external chains (for that network).
No additional changes should be required.
issue: none

chore(lib/netconf): support non-portal chains

---

sdk/packages/core/src/utils/toJSON.test.ts
sdk/packages/core/src/utils/toJSON.ts
sdk/packages/react/package.json
sdk/packages/react/src/hooks/util.test.ts
sdk/packages/react/src/hooks/util.ts

- encode bigints prior to JSON.stringify
- this fix is needed since we found browser extensions (e.g. initia wallet) may introduce a toJSON method to BigInt
- by doing so, the replacer passed to JSON.stringify to convert big ints to hex strings is bypassed
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#:~:text=Attempting%20to%20serialize,by%20the%20user.
issue: none

chore(sdk): encode bigint prior to stringify

---

lib/txmgr/txmgr.go
lib/txmgr/txmgr_internal_test.go
monitor/xmonitor/indexer/indexer.go
solver/app/helpers.go

Increase gas limit by 100% in txmgr. This mitigates txs failing due to dynamic gas usage.
issue: none

chore(lib/txmgr): over estimate gas limit

---

lib/ethclient/ethbackend/backend.go
solver/app/procdeps.go
solver/app/processor.go

Handle RPC issues (timeouts) better in solver:
- Retry `alreadyFilled` on any RPC error
- Continue retrying `WaitConfirm` on any RPC error
- Don't log `[BUG]` if re-checking DidFull hits a lagging node (just error and retry).
issue: none

chore(solver/app): handle rpc timeouts better

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bump protected off-chain services to latest main `2abbc90`. 
This mainly includes a few solver fixes.
issue: none

ci(e2e/manifest): bump protected off-chain services to 2abbc90

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bumps protected off-chain services to 531924c, this includes a fix for gas-limit-bumping.
issue: none

ci(e2e/manifest): bump off-chain services to 531924c

---

lib/cctp/client.go

Only parse attestation when it is complete. Else it is not a hex string.
issue: none

fix(lib/cctp): only parse attestation when complete

---

lib/cctp/audit_internal_test.go
lib/cctp/domains.go
lib/cctp/integration_test.go
lib/cctp/send.go
monitor/cctpgen/cctpgen.go

Ensure dest chain ids is in-network.
CCTP uses same domains for testnet / mainnet. So it was possible to send a message to an in-network domain, but not in-network chain id. 
issue: none

chore(lib/cctp): require dest chain id is in-network

---

monitor/flowgen/bridging/bridging.go

Delay flowgen swaps on staging by up to 2mins. Since we are not seeing any rejections yet.
issue: none

chore(monitor/flowgen): delay flowgen swaps more

---

sdk/packages/react-next/package.json
sdk/packages/react-next/src/hooks/useOrder.test-d.ts
sdk/packages/react-next/src/hooks/useOrder.test.ts
sdk/packages/react-next/src/hooks/useOrder.ts
sdk/packages/react-next/test/mocks.ts

- use order units in react next pckg
- moved from `mutateAsync` to `mutate` for open method - happy to discuss this, but `mutateAsync` will reject the promise awaited by the consumer if there's an error, rather than relying on react query propagating state and preventing a throw
- there's benefits to both, but existing behaviour is to not allow the promise to reject when called
- that said, return type of `open` is not longer the `txHash`, and doesn't return a promise, consumers will need to get hash from the `txHash` return value
issue: none

test(sdk): useOrder units react next pckg

---

e2e/solve/deploy.go
lib/contracts/solvernet/chains.go
lib/contracts/solvernet/chains_test.go
solver/app/app.go

Adds support for defining hyperlane-secured solvernet chains in `lib/contracts/solvernet`. 
issue: none

chore(contracts/solvernet): support hyperlane chains

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

bump protected solver to 39f21d4. This includes price monitoring.
issue: none

ci(e2e/manifest): bump protected solver to 39f21d4

---

lib/cctp/audit.go
lib/cctp/cctp.go
lib/cctp/integration_test.go
lib/cctp/mint.go
lib/cctp/monitor.go
lib/cctp/options.go
monitor/cctpgen/cctpgen.go
solver/rebalance/start.go

Reduce public interface of lib/cctp
Mint, audit, and monitor should always be called together.
issue: none

chore(lib/cctp): reduce public interface

---

monitor/cctpgen/cctpgen.go

Trim network to cctp supported chains.
issue: none

fix(monitor/cctpgen): trim network to supported cctp chains

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bump solver pin. This includes reducing OMNI max spend to 450k.
issue: none

chore(e2e/manifests): bump solver pins

---

e2e/solve/deploy.go
lib/contracts/solvernet/chains.go
lib/contracts/solvernet/chains_test.go
solver/app/app.go

Support filtering HL chains by backends (for e2e deploy) and inbox contracts (for solver app).
issue: none

chore(contracts/solvernet): filter HL chains

---

e2e/manifests/mainnet.toml

bump mainnet monitor to 33faf3b, this enables mainnet flowgen swaps.
issue: none

ci(e2e/manifest): bump mainnet monitor to 33faf3b

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bump monitor pin. This includes cctpgen fixes and enabling it on mainnet.
issue: none

chore(e2e/manifests): bump monitor pin

---

solver/rebalance/integration_test.go
solver/rebalance/thresholds.go

Add default threshold that makes sure token is never 
considered in deficit / surplus. So that is not used for swaps / sends.
issue: none

chore(solver/rebalance): default threshold

---

solver/rebalance/thresholds.go

Tweak solver thresholds
- bump l1 usdc surplus (so that current balance isn't in surplus)
- reduce target base usdc (so that current balance isn't in deficit)
First is to reduce size of swaps when we first turn this one.
Second is general house cleaning to give us room between surplus and decific. Can increase target later if we have demand.
issue: none

chore(solver/rebalance): tweak thresholds

---

e2e/manifests/staging.toml

Removed Sepolia from staging manifest as we will treat it like a Hyperlane chain.
issue: none

chore(e2e): remove sepolia from staging manifest

---

sdk/integration-tests/suites/flows.tsx

Makes the middleman-related tests run sequentially and loosen the balance checks
issue: none

chore(ci): loosen integration tests with middleman contract

---

lib/cctp/cctp.go
lib/cctp/monitor.go

Reset inflight metrics before setting them.
Else minted values stay "in-flight"
issue: none

chore(lib/cctp): reset in flight metrics

---

sdk/integration-tests/README.md
sdk/integration-tests/package.json
sdk/package.json
sdk/packages/core/package.json
sdk/packages/react/package.json
sdk/packages/test-utils/package.json
sdk/pnpm-lock.yaml
sdk/pnpm-workspace.yaml

- needed to bump viem and wagmi version to resolve issues with `Client` type and using a catalog is a lot easier to unify deps across the workspace - open to feedback here though!
- fixed viem and wagmi versions so we can manually bump
- also scoped build command to only run for /packages
issue: none

chore(sdk): pnpm catalog to unify deps

---

e2e/app/chains.go
e2e/app/fund.go

Can't use `app.networkFromDef` in `fund.go` due to `Portals` context not being present here. Decided to supplement the portal values in `hlNetworkFromDef`.
issue: none

feat(e2e): use hlNetworkFromDef in fund action

---

.pre-commit/run_sdk_checks.sh
sdk/integration-tests/test-utils.tsx
sdk/packages/react/src/hooks/useOrder.test.ts
sdk/packages/react/src/hooks/useOrder.ts

- useClient returns a public client but for mutations we need the wallet client
- `getConnectorClient` will give us the necessary wallet client to allow us to access mutations that require an account
issue: none

chore(sdk): get wallet client for mutation

---

solver/app/app.go

Currently, we use the contract address as target when unknown, this polutes the dashboards with random addresses that don't mean anything. Rather group them under "unknown". This results in less noise.
issue: none

chore(solver/app): group unknown targets

---

sdk/package.json
sdk/packages/core/package.json
sdk/packages/react/package.json
sdk/packages/test-utils/package.json

- need to bump to 9.12.1 as it introduced a fix to allow scoped packages to be used in workspace catalog
issue: none

chore(sdk): bump pnpm version

---

e2e/app/chains.go
e2e/app/fund.go
e2e/solve/routing.go
e2e/solve/routing_internal_test.go
lib/contracts/solvernet/chains.go
lib/contracts/solvernet/config.go
lib/contracts/solvernet/outbox/deploy.go

Refactor solvernet routing to use a single Provider(src, dest) util,
that returns the preferred interpo provider between a src and dest chain.
Use things in e2e/solve/routing and lib/contracts/solvernet/deploy. Fix routing tests.
issue: none

chore(e2e): fix and refactor solvernet routing

---

e2e/app/admin/common.go

The Omni consensus chain needs to be skipped within the expanded network when using the HL-specific upgrade functions.
issue: #3925

fix(e2e): skip omni consensus chain

---

solver/rebalance/deficit.go
solver/rebalance/integration_test.go
solver/rebalance/rebalance.go
solver/rebalance/snapshot_test.go
solver/rebalance/thresholds.go
solver/rebalance/tokens.go

Enable new tokens and thresholds.
Most of changes here are updating tests
- updating snapshot tests to show total chain deficits (in USD)
- and most importantly, updating integration tests to rebalance more tokens
Integration tests now work as follows
- put some tokens in deficit
- put others in surplus
- wait for deficit to decrease to acceptable amount
issue: none

chore(solver/rebalance): add new tokens and thresholds

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bump solver pins to 08b2b8d.
- fixes pricer cache
- rebalances all tokens
issue: none

chore(e2e): bump solver pins to 08b2b8d

---

solver/rebalance/rebalance.go

Do not send less than minSend.
This prevents repetitive low value sends to chains it low deficit, 
that isn't filled due to minSwap caps.
issue: none

fix(solver/rebalance): do not send usdc lt minSend

---

sdk/packages/core/README.md
sdk/packages/core/package.json
sdk/packages/core/src/version.ts
sdk/packages/react/package.json
sdk/packages/react/src/version.ts

- bump versions since publish didn't strip `catalog:` from package.json
-  remove alpha comments 
- update scripts
issue: none

chore(sdk): bump versions

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bump solver pin to aad2488.
This includes a minSend check fix.
issue: none

chore(e2e): bump solver pin to aad2488

---

lib/contracts/solvernet/chains.go

Trying to debug why the staging solver doesn't see the Sepolia contracts.
issue: none

chore(lib): add debug logs to FilterByContracts

---

solver/app/app.go
solver/app/chains.go
solver/app/config.go
solver/cmd/flags.go

Solver app itself was not retrieving the RPC overrides, so the Hyperlane network did not include any Hyperlane chains due to missing endpoints. I've attempted to bind these RPC overrides to the solver config. This PR doesn't functionally change the solver as the hyperlane extended network is not used after creating it, as I want to see if this works first.
issue: none

feat(solver): enable RPC overrides in solver

---

lib/tokens/tokens.json
lib/tokens/tokens_test.go
solver/app/testdata/TestClaimants.golden
solver/app/testdata/TestTokens.golden

Hyperlane backends appear to be functioning, however my orders got rejected due to Sepolia ETH not being in the solver's token list. Added Sepolia ETH.
issue: none

feat(lib): support Sepolia ETH in solver

---

.github/workflows/rebalance-test.yaml

Skip rebaance tests on runs without access to secrets.
issue: none

chore(ci): skip rebalance tests without secrets

---

e2e/solve/routing.go
e2e/solve/routing_internal_test.go

All valid routes are currently being written when routes are set. This change filters out routes that are already applied, saving gas.
issue: none

feat(e2e/solve): filter out applied routes

---

e2e/solve/routing_internal_test.go
lib/contracts/solvernet/chains.go

Temporarily disabling sepolia as a hyperlane chain so I can test the route filtering logic.
issue: none

chore(lib): disable sepolia hyperlane chain

---

solver/rebalance/start.go

Wrap steth asynchronously, so we don't block rest of start up process.
issue: none

chore(solver/rebalance): wrap steth asynchronously

---

e2e/app/admin/upgrade.go

Post-upgrade tests for the Executor included the Omni EVM chain ID in all runs, when not all routes support it. This change validates routes prior to testing, so we don't trigger reverts from invalid routes.

fix(e2e): fix post upgrade executor test

---

lib/cctp/db/db.go
lib/cctp/integration_test.go
lib/cctp/mint.go

Improve mint purge loops:
In purge:
Purge messages with tx hashes that do not exist. this can happen if a tx is "dropped and replaced". as what happened with [this tx ](https://etherscan.io/tx/0xd6b20ddc1feaf49eb5e0ce8b4d3e41ebead89413aa8156d6c4fdc8e3c59b196e) on mainnet flowgen 
In mint:
Small change - do not error after first failed mint. Try to mint all messages in db, warn for each error.  
issue: none

chore(lib/cctp): improve mint purge loops

---

.github/workflows/changeset.yaml

- drop bad cmd causing ci to bomb
issue: none

chore(sdk): drop bad workflow cmd and use absolute path

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bump solver and monitor to e704542.
Includes solver min threshold updates.
And cctp mint / purge improvements.
issue: none

chore(e2e): bump solver monitor pins to e704542

---

e2e/solve/routing.go
e2e/solve/routing_internal_test.go

The `Route` struct field names were confusing, and the script would execute transactions even if no routes needed to be applied. Fixed both.

feat(e2e): improve routing vars and function

---

e2e/solve/routing.go

Routing log message was in the wrong place.

chore(e2e): move routing log

---

sdk/integration-tests/package.json
sdk/package.json
sdk/packages/core/package.json
sdk/packages/react/package.json

- integrations need to be set as private
- prepublish and publish scripts in packages were causing issues with running `changeset:publish` and we should only be publishing via changeset now anyway
issue: none

chore(sdk): resolve conflicts when publishing

---

e2e/app/admin/common.go
e2e/app/admin/pausebridge.go
e2e/app/admin/pauseportal.go
e2e/app/admin/pausesolvernet.go
e2e/app/admin/pausexcall.go
e2e/app/admin/pausexsubmit.go
e2e/app/admin/upgrade.go

`runForge` and `runForgeOnce` were hardcoded to operate out of the `core` contracts directory on the `Admin.s.sol` script there. These changes allow us to run it from other directories on other scripts.

feat(e2e): more flexible runForge

---

e2e/solve/routing_internal_test.go
lib/contracts/solvernet/chains.go

Enable Sepolia in the Omega Hyperlane network, and validate all routes are correct.
ref https://linear.app/omni-network/issue/OMNI-244

feat(e2e): enable sepolia on omega

---

e2e/manifests/omega.toml

Updating solver/monitor pin to support Sepolia on Omega.

feat(e2e): update solver and monitor pin

---

monitor/account/monitor.go

No need to monitor non-HL roles on HL-only chains.
issue: none

chore(monitor): do not monitor non-hl roles on hl-only chains

---

lib/contracts/solvernet/inbox/deploy.go
lib/contracts/solvernet/outbox/deploy.go

Portal address needs to be the zero address on hyperlane-only chains when deployed.
ref https://linear.app/omni-network/issue/OMNI-244

fix(lib): fix portal assignment in deploy

---

e2e/app/admin/upgrade.go

Mainnet still needs the V2 initializers, they were removed for additional upgrades on staging and omega.
Do not merge until we are ready for mainnet upgrade.

chore(e2e): readd initializers for mainnet upgrade

---

e2e/app/admin/common.go

Allow --chain arg to work for commands with runHL.
issue: none

fix(e2e): allow runHL on specific chains

---

e2e/app/admin/common.go

Foundry block gas limit needs to be disabled for `upgrade-solvernet-all`.

chore(e2e): disable foundry block gas limit

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Updating pins for solver and monitor on omega and mainnet.

chore(e2e): new solver and monitor pins

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Need to update monitor/solver to include mantle in the HL network.

chore(e2e): pins for mantle inclusion

---

sdk/packages/react/src/hooks/useGetOrderStatus.test.ts
sdk/packages/react/src/hooks/useGetOrderStatus.ts

Uses different parameters for the hooks used internally
issue: none

feat(sdk): add queryOpts support to useGetOrderStatus

---

sdk/.changeset/slick-mirrors-add.md
sdk/examples/core/src/run.ts
sdk/examples/react/src/App.tsx
sdk/integration-tests/suites/flows.tsx
sdk/integration-tests/suites/react-hooks.tsx
sdk/packages/core/src/api/getQuote.test.ts
sdk/packages/core/src/api/getQuote.ts
sdk/packages/core/src/contracts/sendOrder.test.ts
sdk/packages/core/src/types/quote.ts
sdk/packages/core/src/types/utils.ts
sdk/packages/react/src/hooks/useQuote.test-d.ts
sdk/packages/react/src/hooks/useQuote.test.ts
sdk/packages/react/src/hooks/useQuote.ts

- remove isNative flag from quote
- it creates an awkward experience as a consumer due to the never type, instead we can just make token optional, and infer native when that's the case
issue: none

chore(sdk): remove is native flag

---

docs/docs/pages/sdk/utils/withExecAndTransfer.mdx

Publish updated docs for using executor instead of middleman
issue: none

chore(docs): replace middleman by executor

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bump protected network halo to v0.15.0, in preparation for `3_drake` upgrade`.
issue: none

chore(e2e/manifest): bump protected to v0-15-0

---

docs/docs/pages/guides/contracts-without-onbehalfof.mdx
docs/docs/pages/sdk/faq.mdx
docs/docs/pages/sdk/utils/withExecAndTransfer.mdx

Small docs fixes
- remove middleman references from faq
- remove caveat that withExecAndTransfer only works for native deposits (it supports erc20 deposits now)
issue: none

chore(docs): remove middleman update withExecAndTransfer

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bump solver manifests pins.
This includes adding Mantle USDC support &  rebalancing. 
issue: none

chore(e2e): bump solver monitor pins to 0502c1f

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bump solver pints 19d83ba
Includes mantle fund threshold updates.
issue: none

chore(e2e): bump solver monitor pins to 19d83ba

---

e2e/app/admin/planupgrade.go

Fix `3_drake` mainnet upgrade height/date. Note this hasn't been planned yet, so no need to cancel.
issue: none

chore(e2e/admin): drake mainnet upgrade height

---

docs/docs/pages/sdk/assets/mainnet.mdx
docs/docs/pages/sdk/assets/testnet.mdx
solver/app/tokens_internal_test.go

Remove network name from asset table.
We have headers for "Testnet" and "Mainnet" in docs
The network name in each table row was the same.
issue: none

chore(docs): remove network name from assets table

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bumping solver and monitor pins for HyperEVM mainnet support.
ref https://linear.app/omni-network/issue/OMNI-320

chore(e2e): bump solver and monitor pins

---

sdk/examples/react/src/App.tsx
sdk/packages/core/package.json
sdk/packages/core/src/api/getQuote.ts
sdk/packages/core/src/api/validateOrder.ts
sdk/packages/core/src/internal/api.ts
sdk/packages/core/src/schema/types.ts
sdk/packages/react/src/hooks/useValidateOrder.ts
sdk/pnpm-lock.yaml

This pull request introduces schema validation using `zod` for API responses and updates the dependency versions accordingly. The key changes include replacing manual type checks with `zod` schemas, adding reusable schema definitions for `Hex` and `Address`, and updating the `zod` dependency to version `3.25.7`.
* Introduced `zod` schemas for API response validation, replacing manual type checks:
- Added `quoteResponseSchema` in `getQuote.ts` for validating `/quote` endpoint responses. [[1]](diffhunk://#diff-101f182783d724265f180469bd06c3b45c5e6b3859a72b370542240fc823a94dL1-R20) [[2]](diffhunk://#diff-101f182783d724265f180469bd06c3b45c5e6b3859a72b370542240fc823a94dL29-R42) [[3]](diffhunk://#diff-101f182783d724265f180469bd06c3b45c5e6b3859a72b370542240fc823a94dL80-R90)
- Added …

refactor(core): apply zod validation

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bump solver monitor pins to cdbfa4b.
Includes cctp sanity check log removal.
issue: none

chore(e2e): bump solver monitor pins to cdbfa4b

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Update solver monitor pins to f770313.
This includes
- addtional mantle tokens support
- better rejects for unsupported routes
issue: none

chore(e2e): update solver monitor pins to f770313

---

halo/app/prouter.go
halo/app/prouter_internal_test.go

Convert tx interface to actual proto and enfore most fields are empty. This mitigates against malicious proposer "block bloat" attacks.
Thanks to https://github.com/piplabs/story/pull/529 for raising this.
issue: none

chore(halo/app): improve tx verification

---

solver/rebalance/hyperevm.go

Init hyperevm rebalanace loops, leave unused for now.
- Refilled HyperEVM USDT0 from Ethereum USDT
- Swap to USDT from USDC if necessary
TODO:
- add usdt0 db, run monitor loop
- (maybe) add mutex per chain, so only on rebalance loop runs per chain per time
issue: none

chore(solver/rebalance): init hyperevm rebalance loops

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Update solver pin to 7112442.
This includes:
- same check /check fixes
- hyper evm rebalancing
issue: none

chore(e2e/manifests): update solver pin to 7112442

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bump solver monitor pin to 99562dc.
Includes:
- rebalance mutex fix
- solvernet contract binding updates (backwards compatible)
issue: none

chore(e2e): bump solver monitor pin to 99562dc

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bump solver monitor pins to 1fb2571.
This includes enabling HYPE and USDT0.
issue: none

chore(solver): bump solver monitor pins to 1fb2571

---

e2e/app/admin/common.go
e2e/app/admin/upgrade.go

Upgrading `SolverNetOutbox` and need to remove initializers that are no longer necessary.
ref none

chore(e2e): remove unneeded initializers

---

anchor/package.json
anchor/yarn.lock

Bump `serialize-javascript` dependency version as per [security advisory](https://github.com/omni-network/omni/security/dependabot/197).
issue: none

chore(anchor/yarn): bump serialize-javascript version

---

solver/app/svmproc.go
solver/app/svmtypes.go

Make SVM `Markfilled` logic more robust:
- Idempotent, so can always retry
- Ensure markfilled in DidFill as well as Fill
issue: none

chore(solver/svm): robust svm markfilled

---

e2e/app/admin/common.go

Adding a 5 second sleep timer to forge retries to allow for RPC issues to resolve, as we are seeing on Mantle when upgrading contracts.
ref none

feat(e2e): add sleep to forge retry loop

---

anchor/.gitignore
lib/svmutil/compose.go
lib/svmutil/compose_test.go
lib/svmutil/helpers.go
lib/svmutil/helpers_test.go

Support rebuilding program in order to deploy them with runtime keys.
issue: none

chore(lib/svmutil): support rebuilding anchor programs

---

e2e/vmcompose/provider.go
e2e/vmcompose/testdata/TestSetup_127-0-0-1-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-2-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-4-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-5-compose.yaml.golden

Increase geth logs to debug so we can see which rpc are called.
issue: none

chore(e2e/vmcompose): enable geth debug logs

---

monitor/flowgen/bridging/bridging.go
solver/app/pricer.go
solver/app/pricer_internal_test.go
solver/app/testdata/TestPrice/0-OMNI-OMNI/req_body.json
solver/app/testdata/TestPrice/0-OMNI-OMNI/resp_body.json
solver/app/testdata/TestPrice/1-ETH-OMNI/req_body.json
solver/app/testdata/TestPrice/1-ETH-OMNI/resp_body.json
solver/app/testdata/TestPrice/2-wstETH-wstETH/req_body.json
solver/app/testdata/TestPrice/2-wstETH-wstETH/resp_body.json
solver/app/testdata/TestPrice/3-wstETH-ETH/req_body.json
solver/app/testdata/TestPrice/3-wstETH-ETH/resp_body.json
solver/app/testdata/TestPrice/4-USDC-ETH/req_body.json
solver/app/testdata/TestPrice/4-USDC-ETH/resp_body.json
solver/app/testutils_internal_test.go
solver/types/api.go

Add `includeFees` field to `/price` endpoint and make it optional and default to `false`. 
issue: none

chore(solver/client): optional fees in price endpoint

---

lib/log/config.go

Adds an optional log io.Writer to Config.
issue: none

chore(lib/log): add optional log writer

---

e2e/vmcompose/provider.go

Wire missing vmcompose ephemeral genesis.
issue: none

chore(e2e/vmcompose): wire ephemeral genesis

---

halo/app/sdklog.go
halo/comet/cmtlog.go

Prevent array-out-of-bounds in `splitOutError`.
issue: none

fix(halo): prevent array out of bounds

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bump solver pins to 6cedc51.
Includes hyper evm cursor bootstrap.
issue: none

chore(e2e): bump solver pins to 6cedc51

---

halo/app/app_config.go

Disable 12h staking event buffer in protected networks. This means that staking events will be processed immediately, resulting in more validator set update messages being emitted from consensus chain, but improves UX.
This will be included in `4_earhart` upgrade.
issue: none

feat(halo/app): disable staking buffer in prod

---

halo/evmredenom/README.md

Add a README for `evmredenom` module.
issue: none

chore(halo/evmredenom): add readme

---

solver/app/check.go
solver/app/check_internal_test.go
solver/app/reject.go
solver/app/reject_internal_test.go
solver/app/testdata/TestCheck/sufficient_ERC20_balance/resp_body.json
solver/app/testdata/TestCheck/sufficient_native_balance/resp_body.json

Implemented simple rejections for all orders to and from Omni EVM. These changes should be removed after the EVM upgrade is successful.
issue: none

feat(solver): temp reject omni orders

---

e2e/app/admin/planupgrade.go

Prep for omega `4_earhart` upgrade at `Height: 20_128_000, // Tue 26 Aug 13pm UTC`
issue: none

ci(e2e/admin): prep omega upgrade action

---

e2e/manifests/omega.toml

Solver pin bump reenables solver on Omega.
issue: none

chore(e2e): bump omega solver pin

---

contracts/solve/script/fixtures/SolverNetStagingFixtures.sol
contracts/solve/script/staging/Nomina_transfer.s.sol
e2e/manifests/omega.toml

Adjusted solver script to test ERC20 NOM to Native NOM orders on staging. As they were successful, I've bumped the relayer, solver, and monitor versions in the omega manifest.
issue: none

feat(e2e): update manifest and solver script

---

e2e/manifests/mainnet.toml

Updating mainnet pins for relayer, solver, and monitor to handle NOM now having replaced OMNI.
issue: none

chore(e2e): update mainnet pins

---

e2e/manifests/mainnet.toml

Updating mainnet solver pin to fully reenable solver.
issue: none

chore(e2e): update mainnet solver pin

---

docs/docs/public/tokenlist.json

- remove native omni token details from json (used by metamask)
issue: none

chore(docs): rm native omni token info
