omni-network/omni

monitor/avs/avs.go
monitor/routerecon/recon.go

Update some missing mainnet values.
issue: none

fix(*): add mainnet network checks

---

scripts/join/join_test.go

Add `eta` and `bps` metrics to logs.
issue: #2294

ci(scripts/join): improve join nightly metrics

---

e2e/app/admin/allowoperator.go

Whitelist operator Finoa
issue: none

chore(admin): whitelist operator Finoa

---

docs/content/operate/1-run-full-node.md

chore(docs): fix release link

---

scripts/join/join_test.go

Fix zero eta issue.
issue: #2294

ci(scripts/join): fix join nightly eta

---

e2e/app/definition.go
e2e/app/setup.go
e2e/cmd/flags.go
lib/tokens/coingecko/coingecko.go
lib/tokens/coingecko/coingecko_internal_test.go
lib/tokens/coingecko/coingecko_test.go
lib/tokens/coingecko/options.go
monitor/app/config.toml.tpl
monitor/app/testdata/default_monitor.toml
monitor/cmd/flags.go
monitor/xfeemngr/xfeemngr.go

Support apikey in coingecko client. Wire the monitor config.
issue: #1839

feat(monitor/xfeemngr): support coingecko pro

---

docs/content/operate/4-roadmap.md

Update operators roadmap
issue: none

chore(docs): update operators roadmap

---

e2e/app/definition.go
e2e/test/e2e_test.go
e2e/vmcompose/data.go

Skip VMs in infrafile without services.
issue: none

ci(e2e): skip infra vms without services

---

e2e/app/run.go

Upgrading staging doesn't work, so rather error properly.
issue: none

ci(e2e): dont upgrade staging

---

lib/stream/stream.go

Don't count empty fetches as cache misses, since the cache couldn't contain the data.
issue: none

chore(lib/stream): dont count empty fetches as misses

---

e2e/vmcompose/data.go

Replace info log with debug log when skipping infra vms. 
issue: none

fix(e2e): use debug log

---

monitor/xfeemngr/xfeemngr.go

Increase xfeemngr onchain sync interval.
issue: none

chore(monitor/xfeemngr): increase sync interval

---

docs/content/build/4-faq.md
docs/content/build/5-mainnet.md
docs/content/operate/1-run-full-node.md
docs/content/operate/2-validator.md
docs/content/operate/5-faq.md
docs/content/operate/6-config.md
docs/website/sidebars.ts

chore(docs): add mainnet

---

cli/cmd/initnodes.go

convert home to absolute path if it's relative
issue: fixes #1841

fix(cli): use relative paths

---

monitor/xfeemngr/oracle.go
monitor/xfeemngr/xfeemngr.go
monitor/xfeemngr/xfeemngr_internal_test.go

Increase sync interval for eth mainnet and omega.
issue: none

feat(monitor/xfeemngr): slow sync on ethereum

---

.github/workflows/ci-join.yaml

Reverts the runner to the default one.
issue: none

fix(ci): revert runner change

---

.github/workflows/release-snapshot.yaml

Push solver docker image snapshots in CI.
issue: https://github.com/omni-network/omni/issues/2364

ci(github): solver snapshot image

---

e2e/vmcompose/data.go

Remove nil from log
issue: none

fix(e2e/vmcompose): remove nil from log

---

e2e/app/run.go
e2e/app/tokenbridge.go
e2e/cmd/cmd.go
lib/netconf/static.go

Add setup-bridge command. 
issue: none

feat(e2e/cmd): add deploy bridge command

---

lib/cchain/provider/abci.go
lib/cchain/provider/provider.go

Wrong block height was used for cursor, xblock height instead of consensus block height.
issue: none

fix(relayer): wrong block height used 

---

README.md

Fix badge links in readme.
issue: none

fix(README): fix badge links

---

contracts/core/src/solve/Inbox.sol
contracts/core/src/solve/interfaces/IInbox.sol
contracts/core/test/solve/Outbox_fulfill.t.sol

Fillout inbox interface w/ events and functions. 
issue: none

chore(contracts/core): fillout inbox interface

---

monitor/app/public_rpc.go

Fix the omega public RPC used for tracking the height difference.
issue: #494

fix(monitor/app): fix omega RPC url

---

e2e/app/run.go
e2e/vmcompose/provider.go

Copy `prometheus.yaml` when upgrading VMs.
Also refactor upgrade command a bit.
issue: #2404

ci(e2e): copy prometheus config on upgrade

---

e2e/vmcompose/provider.go

Can't filepath join on url.
issue: none

ci(e2e): fix gcp backup on upgrade

---

e2e/types/testnet.go
relayer/app/bootstrap.go
relayer/app/worker.go

Adds bootstrap offsets as workaround for omega relayer struggling to bootstrap.
Also switch to archive02 for relayer queries.
issue: none

chore(relayer): add omega bootstrap offsets

---

e2e/app/admin/bridgespec.go
e2e/app/admin/testdata/TestNetworkBridgeSpec.golden

Unpause the bridge after a successful Omega upgrade
issue: #2390

chore(e2e/app): unpause bridge

---

docs/content/learn/architecture.md

Update language for Octane
issue: none

chore(docs): update language for Octane

---

.github/actions/goreleaser-snapshot/action.yaml
.github/actions/setup-foundry/action.yaml
.github/workflows/check-sol-artifacts.yaml
.github/workflows/clicommand.yaml
.github/workflows/e2etestadmin.yaml
.github/workflows/pr-e2etest.yaml
.github/workflows/release-snapshot.yaml
.github/workflows/soltest.yaml
.goreleaser-snapshot.yaml
Makefile
e2e/anvilproxy/Dockerfile
lib/anvil/anvil.go
lib/anvil/compose.yaml.tmpl
scripts/foundry_version.go
scripts/foundry_version.txt
scripts/install_foundry.sh

Use single source of truth for foundry version.
Set version in `scripts/foundry-version.txt`.
Read that everywhere we need it
issue: none

chore(*): org foundry version

---

relayer/app/cursors.go

Logic change fix with a commit missed in the https://github.com/omni-network/omni/pull/2429
issue: none

fix(relayer): use latest ref

---

e2e/app/eoa/eoa.go
e2e/app/eoa/static.go
e2e/app/run.go
e2e/manifests/devnetsolve.toml
e2e/solve/deploy.go
e2e/types/manifest.go
lib/contracts/address.go
lib/contracts/address_test.go
lib/contracts/solveinbox/deploy.go
lib/contracts/solveoutbox/deploy.go
lib/contracts/testdata/TestContractAddressReference.golden

Add devnet manifest for deploying solve inbox / outbox contracts.
issue: #2355

feat(e2e): solve devnet

---

halo/attest/keeper/keeper.go
halo/attest/types/helper.go
halo/attest/voter/voter.go

Improve voter logging a bit.
issue: #2286

chore(halo/voter): improve voter logs

---

monitor/xfeemngr/oracle.go

Fix on chain gas price metric.
issue: none

fix(monitor/xfeemngr): fix on chain gas price metric

---

docs/content/operate/faq.md
docs/website/src/css/custom.css

chore(docs): center images

---

lib/contracts/feeoraclev1/feeparams.go
lib/contracts/feeoraclev2/feeparams.go
monitor/xfeemngr/gasprice/buffer.go
monitor/xfeemngr/gasprice/buffer_test.go
monitor/xfeemngr/gasprice/tiers.go
monitor/xfeemngr/xfeemngr.go

Use tiers instead of offset / tolerance.
issue: none

feat(monitor/xfeemngr): tiered buffers

---

e2e/solve/devapp/deposit.go
e2e/solve/devapp/devapp.go
lib/ethclient/ethbackend/backend.go

Add methods for devapp deposit requests and fulfillment checks.
issue: #2065

feat(e2e/solve): support devapp deposits

---

e2e/app/fund.go

Funding Omni EVM was locked
issue: none

chore(e2e/app): unlock funding omni EVM

---

relayer/app/app.go
relayer/app/config.go
relayer/app/cursor/cursors_internal_test.go
relayer/app/cursor/db.go
relayer/app/cursor/store.go
relayer/app/worker.go

Post implementation cleanups and comments
issue: none

chore(relayer/cursor): cleanups and comments

---

.gitmodules
contracts/misc/.gas-snapshot
contracts/misc/.gitignore
contracts/misc/foundry.toml
contracts/misc/package.json
contracts/misc/pnpm-lock.yaml
contracts/misc/src/pledge/Pledge.sol
contracts/misc/test/Pledge.t.sol

Initial V0 pledge app contracts.
issue: #2514

feat(contracts/misc): v0 pledge contract

---

halo/cmd/cmd_internal_test.go

Fix flapping test due to nil feature flags
issue: none

test(halo/cmd): fix flapping test

---

e2e/solve/devapp/deploy.go

Fix devapp token salt.
issue: none

fix(e2e/solve): fix token salt

---

halo/app/prouter.go
halo/app/prouter_internal_test.go

Ensure that proposal contain expected number of txs:
- Height==1, must be empty, 
- Height > 1, no more than 1
issue: #2479

fix(halo/app): ensure proposal tx count

---

octane/evmengine/keeper/keeper_internal_test.go

Fixes flapping test due to fuzzing conflicts.
issue: none

test(octane/evmengine): fix flapping test

---

cli/cmd/register_test.go
e2e/app/anvil.go
e2e/app/eoa/dev.go
e2e/app/eoa/static.go
e2e/app/fund.go
e2e/app/run.go
halo/genutil/evm/evm.go
lib/anvil/accounts.go
lib/anvil/anvil.go
lib/contracts/portal/deploy_test.go
lib/contracts/testdata/TestContractAddressReference.golden
lib/create3/create3_test.go
lib/ethclient/ethbackend/backend.go
lib/ethclient/ethbackend/backends.go

Use new non-anvil dev accounts. (https://github.com/omni-network/omni/pull/2539)
this unlocks devnet forks of public chains.
anvil dev accounts have been used on public chains
resetting state via anvil rpc methods does not fix contract collisions
issue: none

feat(*): new non-anvil dev accounts

---

e2e/anvilproxy/app/anvil.go
e2e/anvilproxy/app/config.go
e2e/anvilproxy/cmd/cmd.go
e2e/app/definition.go
e2e/docker/compose.yaml.tmpl
e2e/docker/testdata/TestComposeTemplate_commit.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network_upgrade.golden
e2e/manifests/devnetsolve.toml
e2e/types/manifest.go
e2e/types/testnet.go
e2e/vmcompose/testdata/TestSetup_127-0-0-3-compose.yaml.golden

Support forking public chains in devnet.
issue: none

feat(e2e): allow forking public chains

---

lib/contracts/feeoraclev1/deploy.go

Fixing bug introduced by logs in #2545 
issue: none

fix(lib/contracts): fix FeeOracleV1 deploy logs

---

e2e/app/admin/common.go

Use new dev keys in devnet admin forge scripts.
issue: none

fix(e2e): fix dev admin priv keys

---

halo/app/prouter.go
halo/attest/keeper/keeper.go
halo/attest/voter/voter.go
lib/chaos/chaos.go
lib/chaos/metrics.go

- Add chaos error metrics
- Remove voter investigation debug logs
- Decrease duplicate vote logs to debug
- Fix prouter comment
issue: none

chore(*): few tiny chores

---

e2e/solve/devapp/deposit.go
lib/ethclient/ethbackend/backend.go

Remove backend clone. 
issue: none

chore(lib/ethclient): remove backend clone

---

halo/evmstaking2/keeper/keeper.go

Integrates validator creation event delivery.
issue: #2525

feat(halo/evmstaking2): integrate validator creation event

---

halo/evmstaking2/keeper/keeper_internal_test.go
lib/ethclient/enginemock.go

Extends the unit test with delivery of validator creation event.
issue: #2525

feat(halo/evmstaking2): unit test for validator creation event

---

monitor/app/app.go
monitor/app/gastip.go
monitor/app/metrics.go

Monitor omni evm gas tip cap.
issue: #2200

chore(monitor): monitor omni EVM gas tip cap

---

docs/content/operate/validator.md

Update funding copy
issue: none

chore(docs): update funding copy

---

e2e/app/run.go

Fund deployers before deploying.
issue: none

fix(e2e): fund before deploy

---

e2e/app/admin/allowoperator.go

Whitelist Rhino and A41 as mainnet operators
issue: none

chore(admin): whitelist Rhino and A41 as mainnet operators

---

monitor/xfeemngr/xfeemngr_internal_test.go

Xfeemngr tests were flapping due to floating point rounding errors. The difference was always <=1, and edge cases regarding max sane values were not being handled. Handle edge cases by adhering to max sane values, and allow variance of +-1 so rounding errors do not occur.
issue: none

fix(monitor/xfeemngr): fix flapping test

---

cli/cmd/staking.go
e2e/app/admin/allowoperator.go
e2e/app/admin/planupgrade.go
lib/netconf/netconf_test.go
lib/netconf/static.go

Adds convenience function to consistetly generate omniscan link per network.
issue: none

chore(lib/netconf): add omniscan tx link

---

e2e/app/admin/allowoperator.go

Allow more mainnet operators.
issue: none

ci(e2e/admin): allow more mainnet operators

---

e2e/app/admin/allowoperator.go

Whitelist more mainnet operators
issue: none

chore(admin): whitelist more mainnet operators

---

e2e/app/admin/allowoperator.go

Whitelist ChorusOne operator
issue: none

chore(admin): whitelist chorusone

---

e2e/app/run.go
e2e/solve/deploy.go
e2e/solve/devapp/deploy.go
e2e/solve/devapp/deposits.go
e2e/solve/devapp/devapp.go
e2e/solve/symbiotic/app.go
e2e/solve/symbiotic/fund.go
solver/app/targets.go

Deploying e2e devapp on staging. 
For now, we're only enabling deposit testing on devnet (because we generate random pks for depositors).
Doing this on staging would require refactoring to use tester or monitor role on staging.
issue: none

feat(e2e/solve): staging devapp

---

docs/content/core/mainnet.md

chore(docs): add mainnet info

---

solver/app/targets.go

Add symbiotic staging target.
issue: none

feat(solver): add staging symbiotic target

---

e2e/app/setup.go

Use real staging solver key.
issue: none

fix(e2e): use staging solver key

---

e2e/netman/manager.go
lib/xchain/provider/provider.go
lib/xchain/provider/streamlogs.go

Refactor a few manual retry usecases to new lib.
issue: none

chore(*): use retry lib

---

e2e/manifests/staging.toml

Enable buffering feature on staging.
issue: #2525

feat(e2e/manisfests): enable buffering feature on staging

---

docs/content/learn/core.md

Update spelling errors
issue: none

chore(docs): update spelling errors

---

solver/app/app.go
solver/app/helpers.go
solver/app/metrics.go
solver/app/procdeps.go
solver/app/processor.go
solver/app/processor_internal_test.go

Add metric tracking latest req offset processed by status. 
issue: none

chore(solver/app): instrument inbox processed offset

---

e2e/vmcompose/provider.go

Copy solver loadgen key on upgrade.
issue: none

chore(e2e): fix upgrading solver

---

e2e/solve/devapp/target.go
e2e/solve/symbiotic/target.go
solver/app/app.go
solver/types/target.go

Log target app metadata on startup.
issue: none

chore(solver/app): log target app metadata

---

e2e/solve/devapp/deposits.go
solver/app/app.go
solver/app/ephemeral.go
solver/app/targets.go

Slight refactor to ensure that correct app and backend is always used. Enable devapp on staging.
issue: none

chore(solver/devapp): refactor for consistency

---

cli/cmd/compose.yaml.tpl
cli/cmd/initnodes.go
halo/app/upgrades.go
scripts/join/join_test.go

Adds feature flags to the join test
issue: #2525

fix(cli/cmd): add feature flags to the joint-test

---

docs/content/core/mainnet.md

Format mainnet URLs
issue: none

chore(docs): format mainnet URLs

---

docs/content/operate/roadmap.md

Just some minor spelling corrections. 
issue: none

Fix minor typo

---

README.md

uses omni brand colors. #consistency
issue: #2712

chore(docs): use brand colors in badges

---

monitor/xfeemngr/gasprice/tiers.go

Add very high gas price tiers to handle sepolia spikes.
issue: none

chore(monitor/xfeemngr): add high end tiers

---

contracts/Makefile
contracts/bindings/ierc20.go
e2e/app/fund.go
lib/contracts/contracts.go
monitor/contract/metrics.go
monitor/contract/monitor.go

Monitor l1 bridge erc20 balance.
issue: none

chore(monitor): monitor l1 bridge balance

---

monitor/app/app.go

Disable AVS monitoring.
issue: https://github.com/omni-network/ops/issues/716

chore(monitor): disable avs monitoring

---

e2e/manifests/omega.toml

Update omega version pins to commit ead6061
issue: none

chore(e2e/manifests): update omega version pins

---

cli/cmd/avs_register_test.go

Join AVS registration & de-reregistration tests.
issue: none

test(cli/cmd): join avs register deregister test

---

e2e/vmcompose/provider.go

Attempt workaround for permission issue on omega by trying to delete the remote file (if present).
issue: none

chore(e2e/vmcompose): workaround permission issue

---

solver/app/v2/app.go
solver/app/v2/bindings.go
solver/app/v2/bindings_internal_test.go
solver/app/v2/procdeps.go
solver/app/v2/types.go

Add solver v2 filler.
Mirrors v1 impl, using v2 types. 
issue: none

feat(solver/app): add v2 filler

---

solver/app/v2/metrics.go
solver/app/v2/processor.go
solver/app/v2/reject.go
solver/app/v2/reject_internal_test.go
solver/app/v2/tokens.go
solver/app/v2/types.go

Cleanup.
Addresses comments in https://github.com/omni-network/omni/pull/2801 (merged before i pushed the commit with fixes)
issue: none

chore(app/solver): v2 cleanpup

---

e2e/vmcompose/provider.go

Add xcaller_privatekey
issue: #2275

chore(e2e): upgrade monitor

---

cli/cmd/devnet.go
cli/cmd/initnodes.go
contracts/allocs/scripts/genallocs.go
e2e/manifests/static.go
lib/netconf/netconf_test.go
scripts/join/join_test.go

Simplify API for getting manifests programatically.
issue: none

chore(e2e/manifests): simplify manifests

---

README.md

chore(readme): add bug bounty program

---

e2e/manifests/omega.toml

Pin omega halo to v0.12.0. 
issue: none

chore(e2e/manifests): update omega halo pin

---

solver/app/v2/app.go
solver/app/v2/helpers.go
solver/app/v2/procdeps.go
solver/app/v2/reject.go
solver/app/v2/reject_internal_test.go
solver/app/v2/types.go

Fix v2 bytes32 <> eth addr conversion. Fix omitted fields in newOrder.
issue: none

fix(solver): fix v2 types and addrs

---

e2e/app/setup.go
monitor/app/app.go
monitor/app/config.go
monitor/app/config.toml.tpl
monitor/app/config_test.go
monitor/app/testdata/default_monitor.toml
monitor/cmd/flags.go

Switch monitor to gRPC (relayer already done).
issue: #2252

chore(monitor): use grpc cprovider

---

e2e/app/admin/allowoperator.go

Add galaxy to operator allow list
issue: none

chore(admin): add galaxy to operator allow list

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Update pins for omega and mainnet.
issue: #2828

chore(e2e/manifests): update mainnet and omega pins

---

docs/content/operate/config.md
docs/content/operate/faq.md
docs/content/operate/run-full-node.md

Improve sync option docs.
issue: none

docs(operate): improve syncing docs

---

docs/content/operate/config.md
docs/content/operate/faq.md

describe how to manually restore Omni provided node snapshots
issue: #2806

docs(config): add manual node snapshot restore

---

e2e/app/admin/planupgrade.go
e2e/app/portalregistry.go
halo/attest/keeper/keeper.go
halo/attest/types/tx.proto
halo/attest/voter/voter.go
halo/config/config.go
halo/evmslashing/evmslashing.go
halo/evmupgrade/evmupgrade.go
halo/portal/keeper/portal.pb.go
halo/portal/keeper/portal.proto
halo/registry/keeper/keeper.go
halo/registry/keeper/logeventproc.go
halo/valsync/keeper/keeper.go
halo/valsync/keeper/query.go
lib/cchain/provider/abci.go
lib/cchain/provider/provider.go
lib/cchain/provider/xblock.go
lib/xchain/connect/connect.go
lib/xchain/provider/fetch.go
octane/evmengine/types/tx.pb.go
octane/evmengine/types/tx.proto

Fixes typos raised during cantina issue 6 and 8.
issue: #2115

chore(*): fix typos found during cantina

---

e2e/docker/compose.yaml.tmpl
e2e/docker/testdata/TestComposeTemplate_commit.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network_upgrade.golden
e2e/test/solve_test.go
solver/app/app.go
solver/app/config.go
solver/app/config.toml.tmpl
solver/app/testdata/default_solver.toml
solver/app/v2/app.go
solver/app/v2/config.go
solver/app/v2/metrics.go
solver/app/v2/server.go
solver/app/v2/testdata/default_solver.toml
solver/cmd/flags.go

Add basic API server skeleton.
issue: none

chore(solver/v2): add api server

---

e2e/manifests/staging.toml

revert validator01 back to full node
issue: none

ci(e2e): revert validator01 to full node

---

e2e/manifests/staging.toml

Enable v2 solver in staging. 
issue: none

chore(e2e): enable v2 solver in staging

---

cli/cmd/initnodes.go
lib/netconf/network.go

- Optimize download and extract of node snapshots for geth and halo by parallelizing the process.
issue:  #2876

feat(cli/cmd): add parallel snapshot download

---

cli/cmd/flags.go
cli/cmd/staking.go

Extends the `omni` cli tool with non-self delegation. Tests will be added in a separate PR.
issue: #2896

feat(cli): create delegation option

---

halo/app/app_config.go
halo/evmstaking2/keeper/helpers.go
halo/evmstaking2/keeper/keeper.go
octane/evmengine/keeper/msg_server.go

Improve evm staking buffer logging.
Also decrease delivery interval of staging since testing done.
issue: none

chore(halo/evmstaking): improve logging

---

lib/xchain/connect/connect.go

Fix typo in xconnector.
issue: none

chore(xchain/connect): fix typo

---

e2e/solve/deploy.go
lib/ethclient/ethbackend/backend.go

Add `chain` to logs to aid debugging.
issue: none

chore(e2e/solve): add chain to logs

---

e2e/app/geth/types.go
e2e/docker/testdata/TestComposeTemplate_commit.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network_upgrade.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-1-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-2-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-4-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-5-compose.yaml.golden
go.mod
go.sum

Bump geth to v1.14.13.
issue: none

chore(deps): bump geth to v1-14-13

---

e2e/solve/test.go

Increase e2e solvernet test timeout.
issue: none

fix(e2e/solve): increase timeouts

---

solver/app/app.go
solver/app/quote.go
solver/app/quote_internal_test.go
solver/app/reject.go
solver/app/server.go

Add v1 quotes api endpoint.
issue: #2921

feat(solver): v1 quote api endpoint

---

e2e/test/cli_test.go
halo/app/start_test.go

Adds a new test ensuring that delegation rewards are distributed.
issue: #2892

test(halo/app): adds delegation rewards test

---

e2e/test/cli_test.go

Increase timeout failing in main ci.
issue: none

chore(e2e/test): increase wait time

---

solver/solana/compose_test.go

Add more test cases to solana compose integration test.
issue: #2955

chore(solver/solana): add more test cases

---

contracts/Makefile
contracts/bindings/solvernetmiddleman.go
e2e/solve/deploy.go
lib/contracts/address.go
lib/contracts/address_test.go
lib/contracts/solvernet/inbox/deploy.go
lib/contracts/solvernet/middleman/deploy.go
lib/contracts/solvernet/outbox/deploy.go
lib/contracts/testdata/TestContractAddressReference.golden
lib/contracts/utils.go
scripts/stagingaddrs/main.go

Add solvernet middleman contract.
Additoinally, refactor contract salt utils to just use contract names, remove
most of the contract specific functions.
issue: none

chore(lib/contracts): add solvernet middleman

---

sdk/package.json
sdk/src/constants/contracts.ts
sdk/src/constants/typehash.ts
sdk/src/index.ts
sdk/src/types/order.ts
sdk/tsconfig.build.json

Initial order SDK logic and setup for build
issue: none

feat(sdk): intial order sdk logic

---

sdk/src/hooks/useGetOpenOrder.ts
sdk/src/hooks/useOpenOrder.ts
sdk/src/hooks/useOrderStatus.ts
sdk/src/index.ts
sdk/src/types/order.ts
sdk/src/types/orderStatus.ts
sdk/src/utils/encodeOrder.ts

feat(sdk): order hooks

---

sdk/src/types/order.ts
sdk/src/utils/encodeOrder.ts

Handle call data encoding internally
issue: none

feat(sdk): encode call data internally

---

e2e/test/solve_test.go
solver/app/app.go
solver/app/quote.go
solver/app/server.go

Serve contract addrs on solver api.
issue: #3005

feat(solver): serve contract addrs

---

solver/app/processor.go
solver/app/processor_internal_test.go

Check should reject again before filling.
issue: none

chore(solve): maybe reject before fill

---

solver/app/bindings.go
solver/app/processor.go
solver/app/reject.go
solver/app/reject_internal_test.go

Reject if dest call reverts.
Tests skipped until proper mocks are added, to unblock staging demos.
issue: none

fix(solve): reject if dest call reverts

---

halo/app/app_config.go

Fixes failing `backwards` e2e manifest by moving the new distribution module "burner" permission behind the `evm-staking-module` feature flag. Adding it changes app hash, so can only be done as part of network upgrade.
issue: none

chore(halo/app): fix backwards e2e test

---

monitor/loadgen/loadgen.go
monitor/loadgen/stake.go

In additional to existing `self-delegations`, also include `normal-delegation`, from valA to valB in monitor loadgen.
issue: none

chore(monitor/loadgen): include normal delegations

---

cli/cmd/staking.go

show delay message on all staking event commands
issue: #2938

chore(cli/cmd): delay message on staking cmds

---

monitor/app/upgrade.go

Include `magellan` in monitor upgrade list.
issue: none

chore(monitor): monitor all upgrades

---

e2e/solve/test.go
e2e/test/solve_test.go
lib/contracts/utils.go
solver/app/app.go
solver/app/approvals.go
solver/app/quote.go
solver/app/reject.go
solver/app/tokens.go

Approve outbox max spend on startup.
issue: none

chore(solver): maintain allowances

---

e2e/test/rewards_test.go
halo/app/upgrades/magellan/upgrade.go
halo/app/upgrades/magellan/upgrade_internal_test.go
scripts/halovisor/build.sh

Remove flaky inflation test
Just check mint module params
also add basic validation of params.
issue: none

ci(e2e/test): simplify mint params test

---

solver/app/app.go
solver/app/internal_testutils.go
solver/app/procdeps.go
solver/app/processor.go
solver/app/processor_internal_test.go
solver/app/reject.go
solver/app/reject_internal_test.go

Cleanup proc deps and did fill check
issue: none

chore(solver): cleanup

---

e2e/docker/docker.go
e2e/docker/docker_test.go
e2e/docker/testdata/TestComposeTemplate_commit.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network_upgrade.golden
e2e/types/manifest.go

Allow pinning solver tag in manifest.
issue: none

chore(e2e): add solver pin to manifest

---

e2e/solve/mocktokens.go
solver/app/testdata/TestTokens.golden

Add mock stEth L2 for solver
issue: none

chore(solver): add mock stEth for solver

---

e2e/app/setup.go
e2e/manifests/omega.toml

chore(e2e): pin omega solver

---

e2e/app/definition.go
e2e/app/setup.go
e2e/cmd/flags.go
monitor/app/app.go
monitor/app/config.go
monitor/app/config.toml.tpl
monitor/app/config_test.go
monitor/app/testdata/default_monitor.toml
monitor/cmd/flags.go
monitor/routerecon/recon.go
monitor/routerecon/recon_internal_test.go
monitor/routerecon/routescan.go
monitor/routerecon/routescan_internal_test.go

increase rate limits of RouteScan API
issue: #3053

chore(monitor): add routescan api key

---

e2e/app/run.go
e2e/vmcompose/provider.go

Increase staging upgrade height delay (due to fireblocks).
Also hopefully fix deploy permissions issues.
issue: none

ci(e2e): fix staging upgrade and permissions

---

e2e/solve/fund.go

Fund solver mock L1 with stEth
issue: none

chore(solver): fund solver with stETH

---

lib/netconf/static.go

Fixing staging token static.
It was incorrect.
issue: none

chore(lib/netconf): fix staging token static

---

solver/app/processor.go

Fix err on "unsupported dest chain", when we should rejct.
issue: none

fix(solver): ignore did fill err

---

cli/cmd/staking.go

call createValidator function from Staking.sol that accepts a signature as a parameter
issue: #3047

chore(cli/cmd): add sig verify to createValidator

---

solver/app/approvals.go
solver/app/procdeps.go
solver/app/reject.go

Do not error if below max allowance. 
issue:  #3111

fix(solver): handle tokens that decrement max allowance

---

e2e/solve/test.go
lib/contracts/solvernet/types.go
solver/app/check.go
solver/app/internal_testutils.go
solver/app/quote.go
solver/app/quote_internal_test.go
solver/types/api.go

Use hex big ints in json api
issue: none

chore(solver): use hex big ints in json api

---

e2e/solve/test.go
e2e/solve/testutil.go
lib/contracts/solvernet/order.go
solver/app/check.go
solver/app/internal_testutils.go
solver/app/reject.go
solver/app/testdata/TestTokens.golden
solver/app/tokens.go
solver/app/tokens_internal_test.go
solver/types/reject.go
solver/types/rejectreason_string.go

Enforce min / max expense sizes.
issue: none

feat(solver): add min and max expense sizes

---

e2e/manifests/omega.toml

Update omega solver pin.
issue: none

chore(e2e): udpdate omega solver pin

---

sdk/src/hooks/useOrder.ts
sdk/src/hooks/useQuote.ts
sdk/src/index.ts
sdk/src/types/order.ts
sdk/src/utils/encodeOrder.ts

Quote hook and api call
issue: none

feat(sdk): useQuote hook and api call

---

go.mod
solver/app/server.go

Enable cors in solver api
issue: none

chore(solver): handle cors

---

sdk/src/hooks/useOrder.ts
sdk/src/hooks/useQuote.ts

- remove slicing as api expects complete call data
- check query key
- disable queries if amounts 0
- deposit and expense amounts should be optional, since only 1 of them should be defined - will add narrowing
issue: none

chore(sdk): hook tweaks

---

sdk/src/hooks/useQuote.ts
sdk/src/internal/api.ts

Validate api responses, handle general errors in fetch.
issue: none

chore(sdk): json fetch util and error types

---

sdk/src/hooks/useGetOrder.ts
sdk/src/hooks/useInboxStatus.ts

Seperate useGetOrder and useInboxStatus hooks.
issue: none

chore(sdk): get order and inbox status hooks

---

e2e/solve/test.go
solver/app/testdata/TestTokens.golden
solver/app/tokens.go
solver/app/tokens_internal_test.go

Reduce solver max spend for eth and wsteth.
issue: none

chore(solver): reduce max spends

---

lib/contracts/solvernet/types_test.go
solver/types/api.go
solver/types/api_test.go

Handle nil on parse.
Add more tests.
issue: none

fix(solver): handle nil values when parsing json

---

lib/xchain/provider/fetch.go

Add block_hash to FilterLogs client err.
issue: none

chore(lib/xchain): add block hash to filter err

---

sdk/src/index.ts

chore(sdk): export provider

---

sdk/src/hooks/useOrder.ts
sdk/src/index.ts
sdk/src/types/order.ts

chore(sdk): export order status

---

scripts/join/join_test.go

- Fix error handling on `shutdownContainers`.
- Remove unnecessary wait logic.
issue: none

fix(join): fix nil error panic in join test

---

e2e/app/anvil.go

Fix funding anvil accounts on staging.
issue: none

ci(e2e): fix anvil funding

---

e2e/manifests/omega.toml

Update omega solver pin.
issue: none

chore(e2e): update omega solver pin

---

solver/app/metrics.go
solver/app/server.go

Add some more solver API metrics and logging.
issue: #3199

chore(solver/app): add more api metrics

---

sdk/src/hooks/useOrder.ts
sdk/src/hooks/useQuote.ts
sdk/src/hooks/useValidateOrder.ts

Enable queries when user enables, make prop required.
issue: none

chore(sdk): enable queries when user enables

---

sdk/src/hooks/useQuote.ts

Flatten quote return type.
issue: none

chore(sdk): flatten quote return type

---

e2e/solve/test.go
e2e/solve/testutil.go

Covers following reject reasons:
- SameChain
- UnsupportedDeposit
- UnsupportedSrcChain
issue: #3177

test(e2e/solve): add more reject reasons test cases

---

.pre-commit/run_sdk_checks.sh

- enable exit on sdk precommit check
issue: none

chore(*): enable exit on sdk precommit check

---

sdk/src/errors/base.ts
sdk/src/hooks/useDidFill.ts
sdk/src/hooks/useOrder.ts
sdk/src/hooks/useParseOpenEvent.ts

- introduce basic error propagation
- these can be improved to narrow reasons etc, but keeping it simple for now
issue: #3217

feat(sdk): introduce basic error propagation

---

sdk/integration-tests/flows.test.ts
sdk/integration-tests/hooks.test.tsx
sdk/integration-tests/test-utils.tsx
sdk/package.json
sdk/pnpm-lock.yaml
sdk/vitest.config.ts

Basic setup for testing the SDK in browser, only works locally at the moment with the devnet running (not setup for CI yet).
issue: none

chore(sdk): setup integration tests

---

sdk/CHANGELOG.md

- install react testing lib
- changelog - can review if we find this a pain to maintain while moving fast, but my thoughts are to only update this when we publish a new version
issue: none

chore(sdk): react testing lib and changelog

---

sdk/package.json
sdk/vitest.config.ts

- decouple unit and int test setups via workspaces
issue: none

chore(sdk): decouple integration and unit test setups

---

solver/app/app.go
solver/app/metrics.go
solver/app/procdeps.go
solver/app/processor.go
solver/app/processor_internal_test.go

Instrument solver order age (as it progress through the status). This will provide the high level "how fast is solvernet" metrics.
issue: #3199

chore(solver/app): instrument order age

---

sdk/src/internal/api.ts
sdk/src/version.ts

- add user agent req header for grafana tracking
issue: none

chore(sdk): set user agent req header

---

lib/pnl/log.go
solver/app/helpers.go
solver/app/pnl.go
solver/app/procdeps.go

Adds basic solver pnl logs.
issue: #3199

chore(solver): add basic pnl

---

sdk/src/errors/base.ts
sdk/src/hooks/useOrder.ts
sdk/src/hooks/useParseOpenEvent.test-d.ts
sdk/src/hooks/useParseOpenEvent.test.ts
sdk/src/hooks/useParseOpenEvent.ts
sdk/test/mocks.ts
sdk/test/unitSetup.ts

- parse open event unit tests
- wrap decode call and propagate / derive error
issue: #3170

chore(sdk): parse event unit test and error propagation

---

e2e/app/admin/common.go

Allow resuming forge script from previous run. 
issue: none

chore(e2e): allow resuming failed forge scripts

---

sdk/src/hooks/useDidFill.ts
sdk/src/hooks/useOrder.ts
sdk/src/hooks/useParseOpenEvent.test.ts
sdk/src/hooks/useParseOpenEvent.ts
sdk/src/types/order.ts

- return complete resolved order
issue: none

feat(sdk): return complete resolved order

---

e2e/anvilproxy/Dockerfile

Install wget in anvil proxy.
issue: none

fix(e2e/anvilproxy): install wget

---

monitor/flowgen/bridging/bridging.go
monitor/flowgen/flowgen.go
solver/app/quote.go

Fixes the deposit amount and adds jobs for omega.
issue: #3006

fix(flowgen): fix deposit amounts and add omega

---

monitor/flowgen/bridging/bridging.go
monitor/flowgen/flowgen.go

Set bridging cadence to half an hour.
issue: none

chore(flowgen): set bridging cadence to 30 minutes

---

solver/app/app.go

Re enable holesky on omega solver.
issue: none

chore(solver): re enabled holesky on omega

---

solver/app/app.go

Txmngr needs block period. Adding full netconf chain in case there are other dependencies.
issue: none

fix(solver): add full holesky netconf chain

---

lib/netconf/provider.go

Wait for expected chains on staging.
issue: none

fix(lib/netconf): fix issue on staging reset

---

solver/app/app.go

Re-enable holesky solver on omega.
issue: none

chore(solver): re enable holesky on omega

---

e2e/app/admin/solvernetspec.go
e2e/app/admin/testdata/TestNetworkSolverNetSpec.golden

Testing various `solvernetspec` configs to ensure the pause mechanism works.
issue: none

chore(e2e): test various solvernetspec configs

---

e2e/app/admin/solvernetspec.go
e2e/app/admin/testdata/TestNetworkSolverNetSpec.golden

Unpausing SolverNet on staging.
issue: none

chore(e2e): unpaused staging solvernet

---

lib/cchain/queryutil/staking.go
monitor/app/staking/staking.go

Limit the amount of query requests.
issue: #3279

feat(monitor): pagination for metrics scraping

---

solver/app/testdata/TestTokens.golden
solver/app/tokens.go

Add sepolia wsteth to supported solver tokens.
issue: none

chore(solver): add sepolia wsteth

---

solver/app/app.go

Remove holesky from solvernet omega.
issue: none

chore(solver): remove omega holesky

---

sdk/package.json

chore(sdk): bump alpha version

---

sdk/package.json
sdk/tsconfig.build.json

Add prepublishOnly step to make sure build runs pre publish.
Bump alpha version.
Fix build
issue: none

chore(sdk): bump version add prepublish step

---

e2e/app/monitor.go
e2e/app/run.go
e2e/docker/docker.go
e2e/types/infra.go
e2e/vmcompose/provider.go

Detect service container panics in e2e tests.
issue: none

ci(e2e): detect service panics

---

monitor/app/public_rpc.go

Tiny logging fix in monitor.
issue: none

chore(monitor): tiny logging fix

---

lib/contracts/address.go
lib/contracts/testdata/TestContractAddressReference.golden

Update oemga solvernet salt versions.
issue: none

chore(lib/contracts): update omega solvernet salt version

---

sdk/src/hooks/useValidateOrder.test-d.ts
sdk/src/hooks/useValidateOrder.test.ts
sdk/test/shared.ts

- useValidateOrder units
issue: #3170

chore(sdk): validate order unit tests

---

sdk/src/hooks/useQuote.test-d.ts
sdk/src/hooks/useQuote.test.ts
sdk/src/hooks/useQuote.ts
sdk/src/hooks/useValidateOrder.test-d.ts
sdk/src/hooks/useValidateOrder.test.ts
sdk/test/shared.ts

- unit test useQuote
issue: #3170

chore(sdk): use quote unit tests

---

lib/cchain/queryutil/staking.go
monitor/staking/staking.go
monitor/supply/supply.go

Fixes bugs:
- exclude jailed validators
- reset timer on errors
- don't exit on success
issue: none

fix(monitor): fix avg staking rewards query

---

e2e/xbridge/deploy.go

Disabling xbridge deploy
issue: none

chore(e2e): disable staging xbridge

---

e2e/manifests/omega.toml

Upgrade omega pin.
issue: none

chore(e2e): upgrade omega pin

---

e2e/manifests/staging.toml
lib/netconf/netconf.go
solver/app/testdata/TestTokens.golden

Re-enable holesky in staging.
issue: none

chore(e2e): enable holesky on staging

---

e2e/solve/test.go
solver/app/app.go
solver/app/rebalance.go

Periodically move L1 OMNI back to native OMNI.
issue: none

feat(solver): rebalance OMNI

---

e2e/test/sdk_test.go
sdk/integration-tests/test-utils.tsx
sdk/package.json
sdk/pnpm-lock.yaml

Use E2E_RPC_ENDPOINTS environment variable if set
issue: none

chore(sdk): use RPC endpoints from environment

---

solver/app/processor.go
solver/app/server.go

Tiny logging and tracing improvements
issue: #3199

chore(solver): small log trace improvements

---

monitor/flowgen/flowgen.go

Enables flowgen on mainnet.
issue: none

chore(monitor): enable flowgen on mainnet

---

solver/app/app.go

Enable mainnet on solver.
issue: none

chore(solver): enable mainnet

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Pin monitor on mainnet to enable flowgen.
issue: none

chore(e2e): pin monitor on mainnet

---

e2e/app/setup.go

Enable solver mainnet key.
issue: none

chore(e2e): enable solver mainnet key

---

e2e/app/anvil.go

Fund all dev accounts on anvil chains.
issue: none

chore(e2e): fund all dev accounts on anvil chains

---

solver/app/targets.go

Whitelisting my address so I can generate SolverNet activity to track in Dune.
issue: none

chore(solver): whitelist zodomo in solver

---

solver/app/quote.go
solver/app/quote_internal_test.go

Test expense and deposit fee calcs
issue: none

test(solver): test expense and deposit fee calcs

---

go.mod
go.sum
halo/cmd/testdata/TestRunCmd_defaults.golden
halo/cmd/testdata/TestRunCmd_flags.golden
halo/cmd/testdata/TestRunCmd_json_files.golden
halo/cmd/testdata/TestRunCmd_toml_files.golden
halo/cmd/testdata/default_config.toml

Bump CometBFT to v0.38.17
issue: none

ci(gomod): update cometbft to v0-38-17

---

contracts/avs/pnpm-lock.yaml
contracts/core/pnpm-lock.yaml
docs/website/package.json
docs/website/pnpm-lock.yaml

- reverts omni-network/omni#3429
issue: none

chore(contracts): revert dependabot PR

---

sdk/pnpm-lock.yaml

- bump wagmi version
issue: none

chore(sdk): bump wagmi

---

docs/website/package.json
docs/website/pnpm-lock.yaml

chore(docs): bump deps

---

solver/app/app.go
solver/app/claimants.go
solver/app/claimants_internal_test.go
solver/app/procdeps.go
solver/app/testdata/TestClaimants.golden
solver/app/testdata/TestTokens.golden
solver/app/tokens.go

Add wsteth claimaints and mainnet tokens.
issue: none

feat(solver): claim wsteth to rebalancer eoa

---

contracts/core/script/manual/genesis-staking/MainnetGenesisStake.s.sol
contracts/core/src/token/MerkleDistributorWithDeadline.sol
contracts/core/test/token/MerkleDistributorWithDeadline.t.sol

Finalizing changes to the distributor contract prior to mainnet deployment.
issue: #3326

chore(contracts/core): finalize distributor changes

---

e2e/solve/test.go

Remove duplicate tests, make it faster.
issue: none

test(e2e/solve): faster solving tests

---

contracts/core/script/manual/genesis-staking/MainnetGenesisStake.s.sol
contracts/core/src/token/MerkleDistributorWithDeadline.sol
contracts/core/test/token/MerkleDistributorWithDeadline.t.sol

Fixed owner assignment in the `MerkleDistributorWithDeadline` contract, as manual assignment is necessary when using create3.
issue: none

fix(contracts/core): add owner assignment to distributor

---

sdk/src/context/omni.tsx
sdk/src/types/config.ts

chore(sdk): enable mainnet

---

e2e/manifests/mainnet.toml

Update omega solver pin
issue: none

chore(e2e): update mainnet solver pin

---

lib/cmd/flags.go
lib/cmd/flags_internal_test.go

Redact flags with urls with secrets in query params.
```
https://api.uniblock.dev/uni/v1/json-rpc?chainId=11155420&apiKey=secret123
https://api.uniblock.dev/uni/v1/json-rpc?chainId=11155420&apiKey=xxxxx
```
issue: none

chore(lib/cmd): redact uniblock urls

---

monitor/flowgen/bridging/bridging.go
monitor/flowgen/bridging/config.go
monitor/flowgen/flowgen.go
monitor/flowgen/symbiotic/config.go
monitor/flowgen/symbiotic/symbiotic.go
monitor/flowgen/types/types.go
monitor/flowgen/util/util.go

Move the open ordering function of a job into a function that can work on network specific configs.
issue: #3006

refactor(monitor/flowgen): dynamic job orders

---

sdk/src/hooks/useOrder.ts

Wait receipt on source chain, not chain user is connected to. 
issue: none

fix(sdk): wait receipt on order src chain

---

solver/app/age.go
solver/app/app.go
solver/app/metrics.go

Track oldest order in ageCache and instrument and log if too old.
issue: none

chore(solver/app): track oldest order

---

sdk/integration-tests/flows.test.tsx
sdk/integration-tests/test-utils.tsx

Works as expected locally so hopefully will fix the issues in CI
issue: none

chore(e2e): mint token in explicit call in integration tests

---

lib/xchain/conflevel_string.go
lib/xchain/provider/fetch.go
lib/xchain/types.go
solver/app/app.go

Stream conf min2 for l1 chains in solver event proc.
issue: none

chore(solver): stream conf min2 for l1 chains

---

monitor/account/monitor.go

Remove infinite for loop
issue: none

fix(monitor): fix infinite for

---

e2e/app/wait.go

Slightly more lenient xmsg offset tests.
issue: none

chore(e2e): more lenient xmsg offset test

---

monitor/flowgen/bridging/bridging.go
monitor/flowgen/bridging/config.go

Introduces dynamic order sizes that will maximize the flow volume automatically.
issue: #3006

feat(monitor/flowgen): dynamic order size for native ETH

---

monitor/flowgen/bridging/bridging.go

Fixes the reverse routing and adds debug logs.
issue: #3006

fix(monitor/flowgen): fix reverse route when bridging

---

monitor/account/monitor.go

Fix incorrect token mapping when fetching token address while monitoring solver token balances.
issue: none

fix(monitor/account): fix solver token balance monitoring

---

solver/app/age.go
solver/app/app.go
solver/app/metrics.go

Reset `oldestOrder` gauge to remove stale data for chains without any orders anymore.
issue: none

chore(solver/app): reset oldest order

---

e2e/manifests/omega.toml

Pin monitor on omega to the version running on staging.
issue: none

chore(e2e): pin monitor on omega

---

monitor/flowgen/flowgen.go

Because jobs are moving the maximum amounts, with low balances jobs are skipped more frequently. In this cases we want to retry earlier.
issue: none

chore(monitor/flowgen): retry earlier on skipped jobs

---

solver/targets/targets.go

Add eigen holesky target.
issue: none

feat(solver): add eigen holesky target

---

solver/tokens/testdata/TestTokens.golden
solver/tokens/tokens.go

Add steth spend bounds. 
issue: none

chore(solver): add steth spend bounds

---

solver/app/handler.go
solver/app/handlers_internal_test.go

Timeout solver API requests after 10s returning 504. This prevents clients hanging due to RPC provider timeouts.
issue: none

chore(solver/app): timeout 504 after 10s

---

sdk/packages/react/README.md

Add notes to SDK readme on supported tokens and min/max. Based on `solver/tokens/tokens.go`
issue: none

chore(sdk): add docs for token support

---

sdk/packages/react/README.md
solver/targets/targets.go
solver/tokens/testdata/TestTokens.golden
solver/tokens/tokens.go

Allow eigen mainnet token (steth) and target (strat manager).
issue: none

chore(solver): eigen mainnet tokens and target

---

sdk/packages/react/package.json

Bump react package ver
issue: none

chore(sdk): bump react package ver

---

monitor/flowgen/bridging/bridging.go
monitor/flowgen/bridging/config.go
monitor/flowgen/flowgen.go
monitor/flowgen/symbiotic/symbiotic.go
monitor/flowgen/types/types.go
sdk/integration-tests/suites/flows.tsx
solver/tokens/testdata/TestTokens.golden
solver/tokens/tokens.go
solver/tokens/tokens_internal_test.go

- Increase maxOrderSize to 3 ETH and decrease the cadence to 25m
- Consolidate solver's spend bounds and flowgen order size
- Improve logging
issue: none

chore(monitor/flowgen): tune volume params

---

solver/app/app.go
solver/app/metrics.go
solver/app/server.go
solver/app/worker.go
solver/job/db.go
solver/job/db_test.go
solver/job/job.pb.go
solver/job/job.proto

Improve solver worker logs and metrics:
- Add `src_chain` to logs, replaces missing `proc` label.
- Add `worker_duration` and `worker_error` metrics.
issue: none

chore(solver/app): improve worker logs and metrics

---

solver/app/targets_internal_test.go
solver/targets/targets.go

Open testnet targets.
issue: none

chore(solver): open testnet targets

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Pin monitor on omega and mainnet to commit running on staging.
issue: none

chore(e2e): ping monitor on omega and mainnet

---

sdk/packages/react/README.md

Improve readme docs
- use contract call example with token expense
- add deposit & expense quote modes 
- improve useOrder return docs
issue: #3498

chore(sdk): improve readme docs

---

scripts/loadsolver/main.go

Adding a script for loadgenning solver a bit.
ETH bridges from Holesky -> Base sepolia every 2 sec
issue: none

chore(scripts): add solver loadgen util script

---

solver/app/targets_internal_test.go
solver/targets/morpho.go
solver/targets/targets.go

Whitelist morpho mainnet vault.
issue: none

chore(solver): whitelist morpho base steakhouse vault

---

solver/targets/morpho.go

fix(solver/targets): fix morpho name

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Update solver and monitor pins.
issue: none

chore(e2e): update solver and monitor pins

---

solver/app/check_internal_test.go
solver/client/client.go

Implements an http client for solver.
issue: none

feat(solver): implement http client

---

.golangci.yaml
e2e/test/solve_test.go
halo/app/start_test.go
lib/errors/go113.go
lib/errors/structured.go
solver/app/app.go
solver/app/handlers_internal_test.go
solver/app/server.go
solver/app/server_internal_test.go

Adds `user-agent` to allows cors headers.
Also add shutdown functions and tests.
issue: none

chore(solver/app): add user-agent cors header

---

e2e/app/geth/types.go
go.mod
go.sum

```
go get github.com/ethereum/go-ethereum
go: downloading github.com/ethereum/go-ethereum v1.15.7
go: upgraded github.com/ethereum/go-ethereum v1.15.6 => v1.15.7
```
issue: none

ci(deps): bump go-ethereum v1-15-7

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bumping solver and monitor pins.
issue: none

chore(e2e): bump solver monitor pins

---

e2e/manifests/omega.toml

Pin omega services to v0.14.0.
issue: #3588

chore(e2e): prepare omega upgrade

---

sdk/packages/react/src/hooks/useGetOrderStatus.test-d.ts
sdk/packages/react/src/hooks/useGetOrderStatus.test.ts

- units for useGetOrderStatus hook
issue: #3170

test(sdk): get order status

---

sdk/packages/react/src/hooks/useOmniContracts.test-d.ts
sdk/packages/react/src/hooks/useOmniContracts.test.ts
sdk/packages/react/src/hooks/useOmniContracts.ts
sdk/packages/react/test/mocks.ts
sdk/packages/react/test/react.ts

- useOmniContracts
- disable retry
issue: #3170

test(sdk): useOmniContracts units

---

sdk/packages/react/package.json

chore(sdk): bump react sdk version

---

lib/contracts/solvernet/order.go

Use `ParseEvent` in `OpenOrder` instead of hard coding last event.
issue: none

chore(lib/solvernet): fix parsing of events in OpenOrder

---

sdk/integration-tests/suites/flows.tsx

Allow more time to check order reaching filled status
issue: none

chore(sdk): increase integration test timeout

---

solver/app/quote_internal_test.go
solver/client/client.go

Support `/api/v1/quote` endpoint in solver client.
Aim is to use this in flowgen for quotes, since we will be adding swaps, so quotes will require complex dependencies.
issue: none

chore(solver/client): support quote endpoint

---

e2e/solve/order_tracker.go
e2e/solve/test.go
e2e/test/sdk_test.go
lib/bi/big.go
lib/bi/unit_test.go
solver/app/app.go
solver/app/check.go
solver/app/check_internal_test.go
solver/app/pricer.go
solver/app/quote.go
solver/app/quote_internal_test.go
solver/app/reject.go
solver/app/reject_internal_test.go
solver/job/db.go

Extract existing like-for-like price logic into a `unaryPrice` function. Next step would be to add support for swaps.
issue: none

refactor(solver/app): extract price function interface

---

e2e/app/test.go
e2e/cmd/flags.go
e2e/solve/order_tracker.go
e2e/solve/test.go
lib/evmchain/evmchain.go
monitor/flowgen/symbiotic/symbiotic.go
sdk/integration-tests/suites/hooks.tsx
solver/app/quote.go
solver/app/quote_internal_test.go
solver/app/reject.go
solver/app/testdata/TestQuote/invalid_deposit_(chain_mismatch)/resp_body.json

Few improvements to CI and solver
issue: none

chore(e2e/test): improve ci

---

lib/ethclient/ethbackend/backend.go

Add mempool limit per priv_key/dest_chain in ethbackend.
issue: none

fix(lib/ethbackend): add mempool limit

---

lib/tokenmeta/tokenmeta.go
lib/tokens/tokens.go

chore(lib/tokens): add WETH

---

.github/workflows/release-official.yaml
.github/workflows/release-snapshot.yaml

Fix the CI so that it builds drake images
issue: none

fix(ci): point docker builds to drake

---

lib/anvil/anvil.go
lib/anvil/compose.yaml.tmpl
lib/uniswap/swap.go
lib/uniswap/swap_test.go

Test and fix SwapToUSDC.
- fork mainnet in integration tests
- allow forks in lib/anvil
- approve router before swapping
- send native value for WETH swap
issue: none

chore(lib/uniswap): test and fix

---

lib/ethclient/ethbackend/backend.go
lib/evmchain/evmchain.go
solver/app/procdeps.go

After submitting fill/claim/reject txs, wait for confirmation, instead of just waiting for mined.
issue: #3657

chore(solver/app): wait for tx confirmation

---

lib/tokenpricer/coingecko/coingecko.go
lib/tokenpricer/coingecko/coingecko_internal_test.go
lib/tokenpricer/coingecko/coingecko_test.go
lib/tokenpricer/mock.go
lib/tokenpricer/tokenpricer.go
lib/tokenpricer/tokenpricer_test.go
monitor/xfeemngr/tokenprice/buffer_test.go

Support arbitrary prices in tokenprice/coingecko by converting via USD prices.
issue: none

chore(lib/coingecko): support arbitrary prices

---

lib/cctp/addrs.go
lib/cctp/genbindings.go
lib/cctp/message-transmitter.json
lib/cctp/message_transmitter_bindings.go
lib/cctp/token-messenger.json
lib/cctp/token_messenger_bindings.go
lib/uniswap/genbindings.go

Init lib/cctp, add contract addrs and bindings.
issue: none

chore(lib/cctp): contract addrs and bindings

---

e2e/cmd/admin.go
e2e/test/bridge_test.go
e2e/test/cli_test.go

Also deploy gasstation for admin tests.
issue: none

ci(e2e): deploy gasstation admin tests

---

e2e/app/eoa/fund.go
e2e/app/eoa/testdata/threshold_reference.json
e2e/solve/mocktokens.go
e2e/solve/test.go
e2e/solve/testutil.go
e2e/test/sdk_test.go
e2e/test/solve_test.go
lib/tokenpricer/mock.go
lib/tokenpricer/mock_internal_test.go
lib/tokens/tokens.json
monitor/flowgen/bridging/bridging.go
monitor/flowgen/bridging/config.go
sdk/integration-tests/suites/flows.tsx
solver/app/app.go
solver/app/internal_testutils.go
solver/app/pricer.go
solver/app/quote.go
solver/app/quote_internal_test.go
solver/app/reject.go
solver/app/testdata/TestTokens.golden

Enables solvernet swaps in devnet and staging.
issue: none

feat(solver/app): enable swaps in ephemeral networks

---

solver/app/helpers.go
solver/app/procdeps.go
solver/app/reject.go
solver/app/reject_internal_test.go
solver/app/types.go

Always handle address conversions.
issue: none

chore(solver/app): address conversion errors

---

e2e/test/cli_test.go
lib/ethclient/enginemock.go
octane/evmengine/keeper/abci.go
octane/evmengine/keeper/db.go
octane/evmengine/keeper/db_internal_test.go
octane/evmengine/keeper/keeper.go
octane/evmengine/keeper/keeper_internal_test.go
octane/evmengine/keeper/msg_server.go

Re-enables the withdrawal functionality.
issue: none

feat(halo): withdrawals

---

sdk/packages/react-next/README.md
sdk/packages/react/README.md

fix some typos in the readme.
issue: none

chore(sdk): fix typos

---

e2e/test/portals_test.go
halo/attest/voter/voter.go
halo/attest/voter/voter_test.go
lib/xchain/provider/provider.go

Add logs to help debug failing CI. 
issue: none

chore(halo/attest): debug devnet stuck attestations

---

lib/cast/cast.go
lib/cctp/addrs.go
lib/cctp/api.go
lib/cctp/bridge.go
lib/cctp/db.go
lib/umath/umath.go

Add SendUSDC
- transfer usdc via cctp token messenger
- store transfer message in db
Receiving will read pending messages from db.
issue: none

feat(lib/cctp): support usdc send

---

monitor/flowgen/bridging/bridging.go

Skip opening flowgen orders if solver returns `InsufficientInventory`.
issue: none

chore(monitor/flowgen): handle insufficient inventory

---

docs/docs/pages/index.md
docs/docs/pages/sdk/getting-started.mdx
docs/vocs.config.mts

Add preview when link is shared
issue: none

chore(docs): add preview

---

docs/docs/pages/sdk/getting-started.mdx
docs/docs/pages/sdk/supported-assets.mdx
docs/pnpm-lock.yaml

And also try out a fun little code-group
issue: none

chore(docs): add supported assets

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Pin mainnet to v0.14.1
issue: #3594

ci(e2e): pin mainnet to hotfix release

---

e2e/solve/test.go
lib/cctp/bindings.go
lib/cctp/bridge.go
lib/cctp/db/db.cosmos_orm.go
lib/cctp/db/db.go
lib/cctp/db/db.pb.go
lib/cctp/db/db.proto
lib/cctp/db/db_test.go
lib/cctp/genbindings.go
lib/cctp/stream.go
lib/xchain/provider.go
lib/xchain/provider/fetch.go
lib/xchain/provider/streamlogs.go
solver/app/app.go

Stream and store CCTP usdc transfer messages.
Save messages by tx hash. Replace incorrect message hash in streamer.
issue: none

feat(lib/cctp): stream and store usdc transfer messages

---

sdk/integration-tests/README.md
sdk/integration-tests/package.json
sdk/package.json
sdk/packages/react/package.json
sdk/pnpm-lock.yaml

- small tweaks to make incoming integration test PR smaller 
issue: none

chore(sdk): various small tweaks

---

monitor/flowgen/bridging/bridging.go
solver/app/app.go
solver/app/check.go
solver/app/handler.go
solver/app/quote.go
solver/app/reject.go
solver/app/server.go
solver/app/testdata/TestTokens/tokens_response.json
solver/app/tokens.go
solver/app/tokens_internal_test.go
solver/types/api.go

Add `/api/v1/tokens` endpoint to solver.
issue: none

chore(solver/app): add tokens endpoint

---

lib/cctp/db/db.go
lib/cctp/db/db_test.go
lib/cctp/stream.go
lib/cctp/stream_internal_test.go
lib/cctp/types/types.go

Add stream event processor tests, plus some fixes.
issue: none

test(lib/cctp): test and fix event proc

---

lib/cctp/api.go
lib/cctp/db/db.go
lib/cctp/db/db_test.go
lib/cctp/mint.go
lib/cctp/stream_internal_test.go

Add cctp.MintForever
- watch db for submitted, not minted messages
- query cctp api for attestations
- if attested, receive message on destination, mark as minted
issue: none

feat(lib/cctp): mint forever

---

lib/cctp/attestations.go
lib/cctp/client.go
lib/cctp/devclient.go

Add dev client that signs and serves attestations
issue: none

feat(lib/cctp): add dev cctp client

---

solver/app/internal_testutils.go
solver/app/testdata/TestTokens.golden
solver/app/tokens.go

Reducing wstETH and stETH max spend bound on testnets.
issue: none

chore(solver): reduce testnet spends

---

docs/docs/pages/guides/basic-deposit.md
docs/docs/pages/guides/contracts-without-onbehalfof.mdx
docs/docs/pages/guides/examples/eigenlayer.mdx
docs/docs/pages/guides/examples/rocketpool.mdx
docs/docs/pages/guides/examples/symbiotic.mdx
docs/docs/pages/sdk/hooks/useOrder.md
docs/docs/pages/sdk/hooks/useQuote.md
docs/docs/pages/sdk/supported-assets.mdx
docs/docs/pages/sdk/utils/withExecAndTransfer.md
docs/vocs.config.mts

chore(docs): various sdk docs tweaks

---

docs/docs/pages/guides/template.mdx
docs/vocs.config.mts

Adds a code snippet template for SDK users.
issue: none

feat(docs): add code snippet template

---

lib/tokens/asset.go
lib/tokens/asset_test.go
lib/tokens/tokens.json
lib/tokens/tokens_test.go
solver/app/testdata/TestTokens.golden
solver/app/testdata/TestTokens/tokens_response.json
solver/app/tokens.go

add usdt support to solver
issue: #3628

feat(solver): add usdt support

---

solver/app/app.go

Enable solver swaps in omega
issue: #3600

chore(solver/app): enable swaps on omega

---

monitor/flowgen/bridging/config.go

Fix incorrect omega flowgen config.
issue: none

chore(monitor/flowgen): fix omega bridging config

---

monitor/flowgen/bridging/config.go

Disable flowgen swaps on mainnet (since it doesn't support it yet)
issue: none

chore(monitor/flowgen): disable mainnet swap gen

---

sdk/integration-tests/suites/flows.tsx
sdk/integration-tests/test-utils.tsx
sdk/packages/test-utils/src/constants.ts

- middleman integration test
issue: none

test(sdk): middleman integration test

---

e2e/gasstation/gaspump.go
e2e/test/bridge_test.go
e2e/test/cli_test.go
e2e/test/solve_test.go
lib/bi/big.go
lib/cctp/audit.go
lib/cctp/mint.go
lib/cctp/types/types.go
lib/ethclient/enginemock.go
lib/tutil/require.go
lib/uniswap/quoter.go
lib/uniswap/swap_test.go
monitor/flowgen/bridging/bridging.go
monitor/xfeemngr/gasprice/buffer_test.go
solver/app/check.go
solver/app/tokens_internal_test.go

Few tiny style cleanups and refactors.
issue: none

chore(lib/cctp): nit clean ups

---

lib/anvil/anvil.go
lib/anvil/compose.yaml.tmpl
lib/uniswap/swap_test.go

Refactor anvil opts to use flags. Add auto impersonate.
issue: none

chore(lib/anvil): flag opts

---

docs/docs/pages/concepts/single-chain-deployment.md
docs/docs/pages/concepts/the-problem.md
docs/docs/pages/concepts/the-solution.md
docs/docs/pages/index.mdx
docs/docs/pages/introduction/omni-overview.md
docs/docs/pages/introduction/what-is-solvernet.md
docs/docs/pages/sdk/getting-started.mdx
docs/vocs.config.tsx

- some quick clean ups I noticed when reading last night
issue: none

chore(docs): another quick docs lick

---

lib/cctp/addrs.go
lib/cctp/devclient.go
lib/cctp/integration_test.go
lib/uniswap/swap_test.go

Scaffold cctp integration tests
- read mainnet urls from env, start auto impersonated anvil forks
- impersonate cctp attest manager, enable our dev attester
- start attesting to cctp messages
issue: none

chore(lib/cctp): scaffold integration test

---

solver/app/handler.go

Debug bad request json bodies.
issue: none

chore(solver): debug bad request bodies

---

e2e/manifests/omega.toml

Update omega pins.
issue: none

chore(e2e): update omega tags

---

e2e/manifests/omega.toml

Update omega pins. 
issue: none

chore(e2e): update omega pins

---

docs/docs/pages/sdk/supported-assets.mdx

add usdt addresses to supported assets
issue: none

chore(docs): add usdt to docs

---

lib/anvil/utils.go
lib/uniswap/swap.go
lib/uniswap/swap_test.go

Add USDT -> USDC route.
issue: none

chore(lib/uniswap): add usdt swap route

---

lib/ethclient/ethbackend/backend.go
lib/txmgr/txmgr.go
relayer/app/sender_internal_test.go

Bump pre-estimated tx gas limit as well.
issue: none

fix(lib/backend): bump pre-estimated tx gas as well

---

lib/anvil/anvil.go
lib/cctp/audit.go
lib/cctp/audit_internal_test.go
lib/cctp/client.go
lib/cctp/contracts.go
lib/cctp/db/db.go
lib/cctp/devclient.go
lib/cctp/domains.go
lib/cctp/integration_test.go
lib/cctp/mint.go
lib/cctp/send.go
lib/ethclient/ethbackend/backends.go
lib/tutil/require.go

Better integration tests plus fixes
issue: none

test(lib/cctp): integration tests and fixes

---

solver/app/testdata/TestTokens.golden
solver/app/testutils_internal_test.go
solver/app/tokens.go

Reduce testnet max wsteth spend.
issue: none

chore(solver): reduce testnet max wsteth spend

---

lib/cctp/integration_test.go
lib/cctp/mint.go

Add IsConfirmed util
A message is confirmed if
- it's been audited (message bytes and message hash finalized)
- it's been received and finalized (nonce key used on finalized dest block height)
issue: none

feat(lib/cctp): add is confirmed util

---

lib/txmgr/txmgr.go

Double gas limits (instead of adding 20%), but cap increase to 500K. 
This aims to fix continued symbiotic tx reverts on omega due to out-of-gas.
issue: none

chore(lib/txmgr): double gas limits but cap

---

sdk/integration-tests/suites/flows.tsx
sdk/packages/core/src/contracts/didFillOutbox.ts
sdk/packages/core/src/contracts/getOrder.ts
sdk/packages/react-next/src/hooks/useQuote.test.ts
sdk/packages/react-next/src/hooks/useValidateOrder.test.ts

- gradually opening PRs from Paul's [branch](https://github.com/omni-network/omni/tree/feat/sdk-core-contracts)
issue: #3486

chore(sdk): tweaks from PLs branch

---

lib/cctp/audit.go
lib/cctp/integration_test.go
lib/cctp/mint.go

Purge confirmed mints from db.
issue: none

feat(lib/cctp): purge confirmed mints

---

monitor/app/app.go
monitor/cctpgen/cctpgen.go

Bridge USDC periodically in monitor.
issue: none

feat(monitor): periodic cctp sends

---

docs/docs/pages/sdk/faq.mdx
docs/vocs.config.tsx

Add an FAQ for common SDK questions
issue: none

chore(docs): add sdk faq

---

solver/app/app.go
solver/targets/symbiotic.go
solver/targets/targets.go
solver/targets/targets_internal_test.go

Paginate to fetch all symbiotic vaults, add token suffix to target name: `Symbiotic:wstETH`
issue: none

chore(solver/targets): add missing symbiotic vaults

---

monitor/flowgen/bridging/bridging.go
monitor/flowgen/bridging/config.go

Delay swaps on staging by 10-30s between quote and openOrder to simulate human behavior.
issue: none

chore(monitor/flowgen): delay swaps on staging

---

monitor/cctpgen/cctpgen.go

Do not return after first sends.
issue: none

fix(monitor/cctpgen): keep sending

---

sdk/packages/react-next/src/hooks/useDidFillOutbox.test.ts
sdk/packages/react-next/src/hooks/useGetOrder.test.ts
sdk/packages/react-next/src/hooks/useGetOrderStatus.test.ts
sdk/packages/react-next/src/hooks/useInboxStatus.test.ts
sdk/packages/react-next/src/hooks/useOmniContracts.test.ts
sdk/packages/react-next/src/hooks/useParseOpenEvent.test.ts
sdk/packages/react-next/src/hooks/useQuote.test.ts
sdk/packages/react-next/src/hooks/useValidateOrder.test.ts
sdk/packages/react-next/test/index.ts
sdk/packages/react-next/test/shared.ts

- some tweaks to react next unit tests
- only useOrder unit remaining, coming in a follow up
issue: #3486

test(sdk): react next unit test tweaks

---

lib/uniswap/addrs.go
lib/uniswap/genbindings.go
lib/uniswap/swap.go
lib/uniswap/swap_test.go
lib/uniswap/weth9.json
lib/uniswap/weth9_bindings.go

Allow swap from usdc. Improve tests.  Unwrap weth manually
issue: none

feat(lib/uniswap): swap from usdc

---

docs/docs/pages/sdk/hooks/useQuote.md
docs/docs/pages/sdk/supported-assets.mdx
docs/docs/pages/sdk/swaps.mdx
docs/vocs.config.tsx

chore(docs): add swaps docs

---

lib/cctp/audit.go
lib/cctp/domains.go
lib/cctp/mint.go
solver/app/app.go
solver/app/rebalance.go
solver/rebalance/rebalance.go

Add rebalance.Start setup. 
issue: none

chore(solver/rebalance): rebalance start boilerplate

---

solver/rebalance/config.go
solver/rebalance/rebalance.go
solver/rebalance/start.go

Scaffold rebalance loops.
issue: none

chore(solver/rebalance): scaffold loops

---

solver/app/app.go
solver/app/pricer.go
solver/app/pricer_internal_test.go

Enable solver swaps on mainnet
issue: none

chore(solver/app): enable swaps on mainnet

---

lib/ethclient/ethbackend/backend.go
solver/app/procdeps.go
solver/app/reject.go
solver/app/trace.go
solver/app/worker.go

Trace order processing.
issue: none

chore(solver/app): trace orders

---

sdk/packages/react/package.json
sdk/packages/react/src/hooks/useQuote.ts
sdk/packages/react/src/hooks/useValidateOrder.ts

- optional queryOpts param for quote and validate
issue: none

chore(sdk): optional queryOpts param

---

sdk/packages/react-next/src/context/index.test.ts
sdk/packages/react-next/src/context/index.ts
sdk/packages/react-next/src/context/omni.tsx
sdk/packages/react-next/src/index.test.ts
sdk/packages/react-next/src/index.ts
sdk/packages/react-next/src/utils/invariant.test.ts
sdk/packages/react-next/src/utils/throwingProxy.test.ts
sdk/packages/react-next/src/utils/throwingProxy.ts

- update exports and barrel file unit test
- various units for coverage
- move throwingProxy to `/utils`
issue: none

chore(sdk): misc react next units and tweaks

---

solver/app/app.go
solver/app/pricer.go
solver/app/procdeps.go
solver/app/processor.go
solver/app/processor_internal_test.go
solver/types/price.go

Log pending order amounts and prices and slippage.
issue: none

chore(solver/app): log pending order prices

---

lib/cctp/devclient.go
lib/cctp/integration_test.go
lib/cctp/testutil/anvil.go
lib/cctp/testutil/testutil.go

Refactor lib integration cctp test utils, so we can use them in solver rebalancing tests.
issue: none

chore(lib/cctp): reorg integration test utils

---

solver/rebalance/deficit.go
solver/rebalance/integration_test.go
solver/rebalance/rebalance.go
solver/rebalance/start.go
solver/rebalance/surplus.go
solver/rebalance/thresholds.go

Rebalance wstETH from Base -> L1.
Includes integration test.
issue: none

feat(solver/rebalance): rebalance wsteth

---

sdk/packages/core/src/contracts/parseInboxStatus.test.ts
sdk/packages/core/src/contracts/parseInboxStatus.ts
sdk/packages/core/src/contracts/parseOpenEvent.test.ts
sdk/packages/core/src/contracts/parseOpenEvent.ts

Brings logic from the react package to core
issue: none

chore(sdk): unit tests for parsing logic in core

---

sdk/packages/core/src/contracts/didFillOutbox.test.ts
sdk/packages/core/src/contracts/getOrder.test.ts
sdk/packages/core/src/contracts/openOrder.test.ts
sdk/packages/core/src/utils/encodeOrderData.test.ts
sdk/packages/test-utils/src/contracts.ts

Unit tests for contract interactions
issue: none

chore(sdk): add unit tests to core package

---

lib/tokens/tokenutil/util.go
monitor/cctpgen/cctpgen.go

Make sure we have enough balance to do all sends before doing any of them
issue: none

chore(monitor/cctpgen): send all together or none

---

.github/workflows/ci-main.yaml
.github/workflows/ci-pr.yaml
.github/workflows/rebalance-test.yaml
lib/cctp/testutil/anvil.go

Run rebalance tests in CI.
issue: none

ci(solver/rebalance): run integration tests in ci

---

lib/cctp/db/db.go
lib/cctp/db/db.pb.go
lib/cctp/db/db.proto
lib/cctp/db/db_test.go

Add CreatedAt field to msg entries.
Do not include it in public types.MsgSendUSDC interface, add separate getter.
issue: none

feat(lib/cctp): add createdAt msg timestamp

---

monitor/app/app.go
monitor/cctpgen/cctpgen.go

Use go level db in cctpgen.
issue: none

chore(monitor/cctpgen): use go level db

---

lib/cctp/metrics.go
lib/cctp/mint.go
lib/cctp/monitor.go
monitor/cctpgen/cctpgen.go
solver/rebalance/start.go

Add oldest_msg metric, refactor monitoring to its own loop.
issue: none

chore(lib/cctp): add oldest msg metric

---

solver/app/testdata/TestTokens.golden
solver/app/testdata/TestTokens/tokens_response.json
solver/app/tokens.go

Reduce OMNI max spend to 450k.
issue: none

chore(solver): reduce OMNI max spend to 450k

---

monitor/flowgen/bridging/config.go

Enable flowgen swaps on mainnet
issue: none

chore(monitor/flowgen): enable mainnet swaps

---

docs/docs/pages/guides/contracts-without-onbehalfof.mdx
docs/docs/pages/guides/multistep-deposit.mdx
docs/docs/pages/guides/template.mdx
docs/docs/pages/guides/transfers.mdx
docs/vocs.config.tsx

Add docs on erc20 and native transfers.
issue: none

chore(docs): add docs on native and erc20 transfers

---

lib/cctp/metrics.go

Fix metric namespace. 
issue: none

chore(lib/cctp): fix metric namespace

---

.pre-commit-config.yaml
.pre-commit/run_sdk_checks.sh

- fix biome precommit hook
issue: #3239

chore(*): fix biome precommit

---

monitor/cctpgen/cctpgen.go

Support CCTP gen on mainnet. 
issue: none

chore(monitor/cctpgen): enable mainnet

---

.github/workflows/sdk-unit-test.yaml
sdk/package.json
sdk/packages/core/src/constants/abis.test.ts
sdk/packages/core/test/assets/SolverNetInbox.json
sdk/packages/core/test/assets/SolverNetMiddleman.json
sdk/packages/core/test/assets/SolverNetOutbox.json
sdk/packages/react-next/src/hooks/useQuote.ts

Get `react-next` package in sync with `react` and ensure the unit tests are run in CI
issue: none

chore(sdk): sync react package

---

monitor/cctpgen/cctpgen.go

Loop per chain, retry failtures. 
issue: none

chore(monitor/cctpgen): loop per chain with retry

---

docs/docs/pages/sdk/faq.mdx
docs/docs/pages/sdk/supported-assets.mdx

Update docs to reflect that swaps is live on mainnet
issue: none

chore(docs): swaps on mainnet

---

solver/rebalance/deficit.go
solver/rebalance/integration_test.go
solver/rebalance/rebalance.go
solver/rebalance/simulate_test.go
solver/rebalance/start.go
solver/rebalance/surplus.go
solver/rebalance/thresholds.go

Add TestSimulate which logs surpluses & deficits.
This is a sanity check on our thresholds / surplus / deficit logic.
issue: none

chore(solver/rebalance): test to log mainnet surplus and deficit

---

solver/rebalance/snapshot_test.go

Rename simulat to snapshot.
issue: none

chore(solver/rebalance): rename simulate to snapshot

---

solver/rebalance/snapshot_test.go

Fix snapshot flag name.
issue: none

chore(solver/rebalance): fix snapshot flag name

---

solver/rebalance/metrics.go
solver/rebalance/monitor.go
solver/rebalance/start.go
solver/rebalance/thresholds.go

Add rebalance metrics and monitoring
Start with monitoring deficits / suprlus / balance, and their corresponding thresholds. 
issue: none

chore(solver/rebalance): metrics and monitoring

---

solver/rebalance/integration_test.go
solver/rebalance/rebalance.go
solver/rebalance/thresholds.go

Cap swaps to max swaps.
Require max swap config to allow swaps. 
issue: none

chore(solver/rebalance): max swap amounts

---

solver/rebalance/rebalance.go

chore(solver/rebalance): cap usdc sends

---

solver/app/reject.go
solver/app/reject_internal_test.go
solver/app/testutils_internal_test.go

Reject on no inventory for native OMNI. 
issue: none

chore(solver): reject on OMNI no inventory

---

docs/vocs.config.tsx

uses an absolute URL
issue: none

chore(docs): show preview on twitter

---

solver/solana/compose.go
solver/solana/compose_test.go
solver/solana/stream.go

Implements streaming of txs to a solana account. 
issue: #2955

chore(solver/solana): implement streaming of txs

---

lib/cctp/util.go
solver/rebalance/deficit.go
solver/rebalance/rebalance.go
solver/rebalance/surplus.go

Add USD deficit / surplus utils.
USD amounts denominated in 6 decimals.
issue: none

feat(solver/rebalance): usd deficit and surplus utils

---

solver/rebalance/integration_test.go

Fix rebalance tests. Make deficit condition more forgiving. 
issue: none

chore(solver/rebalance): fix rebalance integration test

---

sdk/examples/react/.gitignore
sdk/examples/react/README.md
sdk/examples/react/index.html
sdk/examples/react/package.json
sdk/examples/react/src/App.tsx
sdk/examples/react/src/index.css
sdk/examples/react/src/main.tsx
sdk/examples/react/src/providers.tsx
sdk/examples/react/src/vite-env.d.ts
sdk/examples/react/tsconfig.json
sdk/examples/react/tsconfig.node.json
sdk/examples/react/vite.config.ts
sdk/integration-tests/README.md
sdk/pnpm-lock.yaml

- react example runs on testnet right now to avoid the burden of requiring users to setup e2e
- simple react vite app
- will add more usage (useQuote etc)
- will move docs examples to here
issue: none

chore(sdk): add react example to package

---

sdk/packages/core/package.json
sdk/packages/react/package.json

- bump versions to get watchDidFill hook and core api in
issue: none

chore(sdk): bump versions

---

e2e/app/admin/common.go
e2e/app/admin/upgrade.go
e2e/app/chains.go
e2e/app/fund.go

Refactored the upgrade commands for SolverNet contracts such that the upgrade routine includes Hyperlane chains in the network.
issue: #3925

feat(e2e): upgrade contracts on hyperlane chains

---

sdk/examples/react/src/App.tsx

- add `useQuote` to example react app
issue: none

chore(sdk): add useQuote to example app

---

sdk/integration-tests/suites/flows.tsx
sdk/integration-tests/test-utils.tsx
sdk/packages/test-utils/src/clients.ts

Need to use the account rather than address when writing to contracts
issue: none

fix(sdk): minting Omni in integration tests

---

sdk/packages/core/CHANGELOG.md
sdk/packages/react/CHANGELOG.md

- changelog entries
issue: none

chore(sdk): changelog

---

docs/docs/pages/sdk/core/watchDidFill.md
docs/vocs.config.tsx

- docs for watchDidFill
issue: none

chore(docs): watchDidFill docs entry

---

docs/docs/pages/introduction/what-is-solvernet.md
docs/docs/pages/sdk/getting-started/basic-deposit.md
docs/docs/pages/sdk/getting-started/template.mdx
docs/vocs.config.tsx

- guides -> advanced guides
- move basic deposit and template into getting started and specify react specific
issue: none

chore(docs): getting started tweaks

---

solver/rebalance/deficit.go
solver/rebalance/rebalance.go

Send surplus to chains in deficit.
- don't send what's needed on current chain
- prioritize send by chains most in deficit
Most noteable change is change to rebalance loop. Instead of 
doing each loop (sending, swapping, filling) independently, on each chain. 
We're now doing each step sequentially, and each chain sequentially.
Reasoning:
- makes sure we're only sending one send at a time, so no race conditions on chain deficit calcs
- each step still functions indendently, but doing them in order makes logic & logs easier to follow,
and we're not worried about speed
issue: none

feat(solver/rebalance): send by deficits

---

docs/docs/pages/sdk/utils/withExecAndTransfer.mdx

Changes are not live yet
issue: none

fix(docs): keep middleman references

---

solver/app/pricer.go

Reduce solver price cache interval.
issue: none

chore(solver): reduce pricer cache interval

---

solver/rebalance/deficit.go
solver/rebalance/rebalance.go
solver/rebalance/usd.go

Log "USD" for dollar amounts, instead of USDC. 
issue: none

chore(solver/rebalance): log USD for USD amounts

---

solver/rebalance/testdata/thresholds.json
solver/rebalance/threshold_test.go

Threshold reference test. 
issue: none

test(solver/rebalanace): add threshold reference test

---

solver/rebalance/integration_test.go

Increase integration test timeout. 
issue: none

chore(solver/rebalance): increase integration test timeout

---

sdk/examples/react/package.json
sdk/package.json
sdk/packages/core/src/version.ts
sdk/packages/react/package.json
sdk/packages/react/src/version.ts
sdk/pnpm-lock.yaml
sdk/scripts/bumpVersion.ts

- script to bump version.ts to match package.json, can call this as part of the publish step coming up
- script to run react example from root
issue: none

chore(sdk): bump version script

---

solver/rebalance/deficit.go

Do not discount unswappable surpluses from chain deficits.
issue: none

fix(solver/rebalance): fix chain deficit surplus discount

---

lib/anvil/utils.go
lib/uniswap/swap_test.go
solver/rebalance/integration_test.go

Fix USDT funding utils.
Different slots for different chains.
issue: none

fix(lib/anvil): fix usdt funding utils

---

lib/cctp/mint.go

Add MsgTxHash and MsgHash in mint err attributes.
issue: none

chore(lib/cctp): better mint err attrs

---

sdk/examples/core/README.md
sdk/examples/core/package.json
sdk/examples/core/src/run.ts
sdk/examples/core/tsconfig.json
sdk/pnpm-lock.yaml

Similar to the React example
issue: none

feat(sdk): add example script using core

---

docs/docs/pages/introduction/omni-token.md

Update the staking copy
issue: none

chore(docs): update staking copy

---

.github/workflows/changeset.yaml

- set pnpm version
issue: none

chore(*): set pnpm version for changeset workflow

---

solver/rebalance/integration_test.go

Temporarily increase deficit target. 
issue: none

chore(solver/rebalance): increase test deficit target

---

e2e/app/setup.go
lib/contracts/solvernet/config.go
monitor/app/app.go
solver/app/app.go

RPC overrides added to monitor config and selectively applied to account monitoring for now.
issue: #3744

feat(monitor): prep monitor for hyperlane chains

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bump solver pins.
Includes steth deprecation.
issue: none

chore(e2e/manifests): bump solver pin

---

scripts/verifypr/verify.go
scripts/verifypr/verify_internal_test.go

Remove footer requirement from `verifypr`
issue: none

chore(ci): remove footer requirement

---

sdk/.changeset/ripe-crabs-doubt.md

- to test changeset workflow, will delete this file if the workflow opens a PR with version bump and changelog as expected!
issue: ref [https://linear.app/omni-network/issue/OMNI-162](https://linear.app/omni-network/issue/OMNI-162)

chore(sdk): test changset setup

---

sdk/packages/react/README.md

- changeset workflow checks for sdk/** changes
issue: none

chore(sdk): readme tweak to trigger changeset

---

.github/workflows/changeset.yaml

- set working directory for changeset step
issue: none

chore(sdk): set working dir changeset directory

---

monitor/flowgen/flowgen.go

Disable flowgen on mainnet.
issue: none

chore(monitor): disable flowgen on mainnet

---

sdk/packages/react/README.md

- tweak readme again as workflow required a hot fix
issue: none

chore(sdk): tweak readme to trigger changeset

---

.github/workflows/changeset.yaml

- cwd complains about not seeing the sdk dir
issue: none

chore(sdk): resolve cwd changeset issue

---

.github/workflows/changeset.yaml

- logging out cwd info 
issue: none

chore(sdk): debugging changeset cwd issues

---

.github/workflows/changeset.yaml

- use pat instead of github_token as that's restricted at the repo level
- this pat can be used to request PRs via github api
issue: none

chore(sdk): use pat and api commit mode changeset

---

e2e/solve/routing.go

Route filtering had a typo that caused all routes to be applied each time.

fix(e2e): fix route filtering

---

e2e/solve/routing_internal_test.go
lib/contracts/solvernet/chains.go

Reenabling Sepolia on staging.

chore(e2e): enable sepolia routing on staging

---

solver/rebalance/integration_test.go

Bump surplus USD target in integration test setup. 
issue: none

chore(solver/rebalance): bump surplus test target

---

sdk/package.json

chore(sdk): clean cmd

---

sdk/.changeset/fifty-eels-knock.md
sdk/integration-tests/suites/flows.tsx
sdk/packages/core/src/api/getContracts.ts
sdk/packages/core/src/constants/abis.test.ts
sdk/packages/core/src/constants/abis.ts
sdk/packages/core/src/types/contracts.ts
sdk/packages/core/src/utils/withExecAndTransfer.ts
sdk/packages/react/src/hooks/useOmniContracts.test-d.ts
sdk/packages/react/test/shared.ts
sdk/packages/test-utils/src/constants.ts
sdk/packages/test-utils/src/contracts.ts

- rollback middleman changes
- changeset
issue: none

chore(sdk): rollback removing middleman

---

sdk/.changeset/fifty-eels-knock.md
sdk/.changeset/ripe-crabs-doubt.md
sdk/packages/core/CHANGELOG.md
sdk/packages/core/package.json
sdk/packages/core/src/version.ts
sdk/packages/react/CHANGELOG.md
sdk/packages/react/package.json
sdk/packages/react/src/version.ts

- v0.1.3 changeset bump
issue: none

chore(sdk): changeset version bump

---

sdk/.changeset/wide-plums-hang.md
sdk/integration-tests/suites/flows.tsx
sdk/packages/core/src/api/getContracts.ts
sdk/packages/core/src/constants/abis.test.ts
sdk/packages/core/src/constants/abis.ts
sdk/packages/core/src/types/contracts.ts
sdk/packages/core/src/utils/withExecAndTransfer.ts
sdk/packages/react/src/hooks/useOmniContracts.test-d.ts
sdk/packages/react/test/shared.ts
sdk/packages/test-utils/src/constants.ts
sdk/packages/test-utils/src/contracts.ts

- reintroduce executor logic removing middleman stuff
- "minor" version bump changeset file (to bump to 0.2.0)
issue: none

chore(sdk): revert the middleman revert

---

halo/evmstaking/keeper/keeper.go
halo/withdraw/wrapper.go
halo/withdraw/wrapper_internal_test.go
octane/evmengine/keeper/keeper.go

Few fixes as per SigmaPrime audit of `3_drake` release.
ref https://linear.app/omni-network/issue/OMNI-294/fix-nil-pointer-deference

chore(halo): few audit fixes

---

sdk/.changeset/shaky-pugs-care.md

Add changeset entry
issue: none

chore(sdk): add changeset entry to core package

---

sdk/packages/react/src/hooks/useGetOrder.test.ts
sdk/packages/react/src/hooks/useGetOrder.ts

Continuing adding support for queryOpts to hooks
issue: none

feat(sdk): add queryOpts support to useGetOrder

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Upgrade solver pin.
Includes removed check on MaxSpent.Recipient
issue: none

chore(e2e): update solver pin to e00e25c

---

solver/targets/cygnus.go
solver/targets/targets.go

Add cygnus target. 
issue: none

chore(solver): add cygnus target

---

e2e/app/eoa/fund.go
e2e/app/eoa/static_test.go
e2e/app/eoa/testdata/threshold_reference.json

Add support for funding on Mantle.
ref https://linear.app/omni-network/issue/OMNI-301/mantle-evm

feat(e2e): add funding for mantle

---

e2e/app/admin/upgrade.go

Fixing incorrect function name in upgrade logic.

fix(e2e): fix upgrade all calldata

---

contracts/solve/foundry.toml
e2e/app/admin/common.go

Forge needs higher gas limit in upgrade all script dry run.

chore(contracts): increase block gas limit

---

contracts/solve/foundry.toml
e2e/app/admin/common.go

Gas limit was too high, max uint64 couldn't fit.

chore(contracts): fix gas limit

---

e2e/solve/routing_internal_test.go
lib/contracts/solvernet/chains.go

Adding Mantle to the mainnet Hyperlane network.
ref https://linear.app/omni-network/issue/OMNI-301

chore(lib): add mantle to mainnet HL network

---

sdk/.changeset/fluffy-garlics-hunt.md
sdk/.changeset/shaky-pugs-care.md
sdk/.changeset/six-ideas-press.md
sdk/.changeset/slick-mirrors-add.md
sdk/.changeset/wide-plums-hang.md
sdk/packages/core/CHANGELOG.md
sdk/packages/core/package.json
sdk/packages/core/src/version.ts
sdk/packages/react/CHANGELOG.md
sdk/packages/react/package.json
sdk/packages/react/src/version.ts

Update versions and changelog for new version
issue: none

chore(sdk): prepare new version

---

lib/mantle/addrs.go
lib/mantle/bindings.go
lib/mantle/deposit.go
lib/mantle/deposit_test.go
lib/mantle/l1-bridge.json
lib/mantle/l1bridge_bindings.go
lib/tokens/tokens.json
lib/tokens/tokens_test.go
solver/app/testdata/TestTokens.golden

Support USDC deposit from Eth L1 -> Mantle L2.
issue: none

feat(lib/mantle): support usdc deposits

---

e2e/app/admin/planupgrade.go

Set `3_drake` upgrade heights for admin actions.
issue: none

chore(e2e/admin): drake upgrade heights

---

anchor/anchorinbox/helper.go
lib/solutil/compose_test.go
lib/solutil/helpers.go
solver/app/soltypes.go

Helper functions to reject/claim/markfilled solana orders.
issue: none

chore(solver/app): more solana helpers

---

sdk/packages/react/src/hooks/useOrder.test.ts
sdk/packages/react/src/hooks/useOrder.ts

Last hook needing support
issue: none

feat(sdk): add queryOpts support to useOrder

---

docs/docs/pages/sdk/hooks/useOrder.mdx
sdk/packages/react/CHANGELOG.md
sdk/packages/react/package.json
sdk/packages/react/src/version.ts

Changelog and docs for queryOpts support
issue: none

chore(sdk): prepare queryOpts release

---

lib/tokens/tokens.json
lib/tokens/tokens_test.go

Add native MNT token def.
issue: none

chore(lib/tokens): add native mnt

---

solver/fundthresh/testdata/thresholds.json
solver/fundthresh/thresholds.go

Bump mantle USDC target balance.
issue: none

chore(solver): bump mantle usdc target

---

monitor/account/monitor.go
solver/fundthresh/thresholds.go

Bump min solver native MNT threshold on which we alert.
issue: none

chore(solver): min native mnt threshold

---

solver/rebalance/mantle.go

Only deposit USDC to mantle if more than 1k is needed.
issue: none

chore(solver): add min mantle usdc deposit

---

docs/docs/pages/sdk/assets/mainnet.mdx
docs/docs/pages/sdk/assets/testnet.mdx
solver/app/tokens_internal_test.go

Add HL asset docs.
issue: none

chore(solver): extend support asset docs with hl chains

---

solver/app/check_internal_test.go
solver/app/handler.go

Format errors to get err attributes in response.
issue: none

chore(solver): format err attrs in trace

---

e2e/app/eoa/fund.go
e2e/app/eoa/static_test.go
e2e/app/eoa/testdata/threshold_reference.json
e2e/solve/routing_internal_test.go
lib/contracts/solvernet/chains.go

Adding HyperEVM Mainnet.
ref https://linear.app/omni-network/issue/OMNI-320

feat(e2e): add hyperevm mainnet

---

e2e/solve/test.go
sdk/integration-tests/suites/react-hooks.tsx
solver/app/check.go
solver/app/reject.go
solver/app/testutils_internal_test.go
solver/types/reject.go
solver/types/rejectreason_string.go

Support same chain orders in solver.
issue: none

feat(solver): support same chain orders

---

docs/docs/pages/sdk/hooks/useOrder.mdx
docs/docs/pages/sdk/hooks/useQuote.md

chore(docs): more small tweaks

---

solver/targets/gearbox.go
solver/targets/targets.go

Adding some gearbox targets, for logs.
issue: none

chore(solver): add gearbox targets

---

lib/cctp/audit.go

Remove unhelpful sanity check err.
issue: none

chore(lib/cctp): relax sanity check errors

---

e2e/app/eoa/testdata/solver_reference.json
lib/tokens/asset.go
lib/tokens/asset_test.go
lib/tokens/tokens.json
lib/tokens/tokens_test.go
lib/usdt0/bindings.go
lib/usdt0/eids.go
lib/usdt0/ioft.json
lib/usdt0/ioft_bindings.go
lib/usdt0/ofts.go
lib/usdt0/send.go
lib/usdt0/tokens.go

Add a simple Send method for usdt0.
"simple" because we do not track messages and confirm receipt on destinatin. 
Untested.
issue: none

feat(lib/usdt0): simple usdt0 send

---

lib/uni/types.go
solver/app/helpers.go
solver/app/pricer.go
solver/app/procdeps.go
solver/app/reject.go
solver/app/svmproc.go
solver/app/svmtypes.go
solver/app/types.go

Replace `toEthAddr` with `toUniAddr`. Also wire few more svm procdeps.
issue: none

chore(solver/app): more universal solver logic

---

sdk/.changeset/grumpy-tigers-shake.md
sdk/packages/core/src/api/validateOrder.test.ts
sdk/packages/core/src/api/validateOrder.ts
sdk/packages/react/src/hooks/useOrder.test.ts
sdk/packages/react/src/hooks/useOrder.ts
sdk/packages/react/src/hooks/useValidateOrder.test.ts
sdk/packages/react/src/hooks/useValidateOrder.ts

Will add integration tests in another PR
issue: none

feat(sdk): support debug flag in validation endpoint

---

e2e/app/admin/common.go
e2e/app/chains.go
e2e/app/setup.go
lib/contracts/solvernet/chains.go
lib/contracts/solvernet/chains_test.go
lib/contracts/solvernet/config.go
lib/netconf/netconf.go
lib/svmutil/stream.go
monitor/account/monitor.go
monitor/app/app.go
solver/app/app.go
solver/app/tokens_internal_test.go

Add `Trusted` chains to solvernet logic.
issue: none

chore(contracts/solvernet): add trusted chains

---

go.mod
go.sum
lib/hypercore/client.go
lib/hypercore/client_test.go
lib/hypercore/evm_user_modify.go
lib/hypercore/signer.go
lib/hypercore/signing_utils.go
lib/hypercore/signing_utils_internal_test.go
lib/hypercore/types.go

Add hypercore client, implement UsdBigBlocks.
Translates some of hyperliquid's python sdk & tests into golang.
issue: none

feat(lib/hypercore): first action UseBigBlocks

---

lib/hypercore/signer.go

Add fireblocks hypercore signer. 
issue: none

feat(lib/hypercore): add fireblocks signer

---

e2e/app/hyperliquid.go
e2e/cmd/cmd.go

Add e2e command to enable big hyper evm blocks for specified roles
issue: none

feat(e2e): add hl use big blocks command

---

e2e/cmd/cmd.go

Removes required on full def for hyperliquid cmd.
issue: none

chore(e2e): skip full def for hyperliquid cmd

---

Makefile
anchor/Makefile
anchor/localnet/solver_inbox.ts
lib/lib_test.go
lib/svmutil/compose.go
lib/svmutil/compose_test.go
lib/svmutil/localsvm/main.go
lib/svmutil/token.go

Adds `make svm-local` command that spins up SVM docker container with inbox deployed.
issue: none

chore(svmutil/localsvm): local svm

---

anchor/anchorinbox/helper.go
e2e/app/run.go
e2e/app/setup.go
e2e/app/svm.go
lib/svmutil/compose.go
lib/svmutil/compose.yaml.tmpl
lib/svmutil/compose_test.go
lib/svmutil/localsvm/main.go
lib/svmutil/token.go

After starting svm container:
- ensure programs artefacts are ready to be deployed
- Fund eoas with SOL
- Create USDC mint (and fund EOAs)
- Deploy anchor inbox
- Initialise anchor inbox.
issue: none

chore(e2e): init devnet svm

---

solver/app/check.go

Fix trace request json encoding.
issue: none

fix(solver/app): fix trace req args

---

solver/app/check_internal_test.go
solver/app/reject.go
solver/app/testutils_internal_test.go

Fix passing nil err to solvernet.DetectCustomErr
Add test case.
issue: none

fix(solver): fix panic in same chain check error response

---

docs/docs/pages/index.mdx

fix some awkward language
issue: none

chore(docs): fix language on docs landing page

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bump pins to 2144f65.
Includes fix for same chain /check pacis.
issue: none

chore(e2e): bump pins to 2144f65

---

docs/docs/pages/sdk/assets/mainnet.mdx
lib/tokens/tokens.json
lib/tokens/tokens_test.go
solver/app/testdata/TestTokens.golden
solver/app/tokens.go
solver/fundthresh/testdata/thresholds.json
solver/fundthresh/thresholds.go

Support native HYPE in solver.
issue: none

feat(solver): support native hype

---

sdk/examples/react/src/App.tsx
sdk/integration-tests/suites/react-hooks.tsx

- add rejection example
- integration test
issue: none

chore(sdk): add rejection to example app and integration test

---

e2e/cmd/cmd.go
e2e/solve/fund.go
lib/tokens/tokenutil/transfer.go
lib/tokens/tokenutil/transfer_test.go

Fund ops from solver. 
Restrict to surplus on mainnet.
Do not restrict on testnets, to allow testing.
issue: none

feat(e2e/cmd): fund ops from solver

---

contracts/avs/pnpm-lock.yaml
contracts/core/package.json
contracts/core/pnpm-lock.yaml
contracts/solve/pnpm-lock.yaml

Updating dependencies to handle dependabot security alerts.
ref none

chore(contracts): update dependencies

---

lib/usdt0/metrics.go
lib/usdt0/monitor.go
lib/usdt0/send.go
lib/usdt0/send_test.go
solver/rebalance/start.go

Add usdt0 metrics.
issue: none

chore(lib/usdt0): add metrics

---

sdk/.changeset/grumpy-bars-leave.md
sdk/packages/react/src/hooks/useOrder.ts

- shouldn't be conditionally rendering a hook, react throws if srcChainId isn't given
issue: none

fix(sdk): remove bad conditional hook usage

---

e2e/app/setup.go
e2e/docker/compose.yaml.tmpl
e2e/docker/testdata/TestComposeTemplate_commit.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network_upgrade.golden
e2e/vmcompose/provider.go
e2e/vmcompose/testdata/TestSetup_127-0-0-1-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-2-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-4-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-5-compose.yaml.golden
halo/app/proxy.go
halo/app/start.go
halo/cmd/flags.go
halo/cmd/testdata/TestCLIReference_rollback.golden
halo/cmd/testdata/TestCLIReference_run.golden
halo/cmd/testdata/TestRunCmd_defaults.golden
halo/cmd/testdata/TestRunCmd_flags.golden
halo/cmd/testdata/TestRunCmd_json_files.golden
halo/cmd/testdata/TestRunCmd_toml_files.golden
halo/config/config.go
halo/config/config.toml.tmpl
halo/config/config_test.go
halo/config/testdata/default_halo.toml
halo/config/testdata/test_halo.toml

Proxy EVM JSON-RPC requests in geth. This aims to debug some geth resource issues we are seeing.
issue: none

chore(halo/app): proxy evm requests

---

halo/app/proxy.go

Add 10s timeout to proxy requests.
issue: none

chore(halo/app): proxy timeout

---

docs/docs/pages/sdk/faq.mdx

chore(docs): add faq on fees

---

go.mod
go.sum

chore(gomod): tidy

---

docs/docs/public/tokenlist.json

Add OMNI token info for reference by wallets like Metamask.
issue: none

chore(docs): add tokenlist file

---

go.mod
go.sum
lib/tracer/trace.go

chore(gomod): update otel dependency

---

solver/app/cursor.go

Skip hyper evm blocks. 
issue: none

chore(solver): re bootstrap hyper evm cursor

---

monitor/app/app.go

chore(monitor): disable flowgen

---

halo/app/upgrades/earhart/upgrade.go
halo/evmredenom/submit/config.go
halo/evmredenom/submit/submit.go
lib/ethclient/ethclient.go
lib/ethclient/ethclient_gen.go
lib/ethclient/genwrap/genwrap.go
lib/ethclient/mock/mock_interfaces.go
octane/evmengine/keeper/db.go

Implement submission of account batches to redenom contract.
issue: none

chore(hub/evmredenom): implement submission

---

e2e/app/valupdates.go
monitor/loadgen/dos.go
monitor/loadgen/loadgen.go
monitor/loadgen/stake.go

Test DoS of staking event thresholds on staging.
issue: none

chore(monitor/loadgen): staging dos staking events

---

monitor/loadgen/dos.go

Fix panic in dos testsing on staging.
issue: none

chore(monitor): fix dos staging test

---

solver/rebalance/deficit.go

Fix rebalance flap - do not consider NOM in surpluc / deficit. 
issue: none

fix(solver): fix rebalance test flap

---

scripts/stagingaddrs/main.go

Added NOM address to stagingaddrs script.
issue: none

feat(scripts): add nom to stagingaddrs

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bumps monitor to include new redenom role EOA.
issue: none

ci(e2e): bump protected monitor tags

---

e2e/bridge/tokenbridge.go

Upgrading native bridge on staging was failing because the `l1Deposits` value was near the max uint256 due to an underflow caused by subtracting the post-redenominated bridge balance from the OMNI total supply value, which produced a negative number. Added a check for this edge case so that the value is correct.
issue: none

fix(e2e): post redenom bridge balance

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

Bumping monitor and solver pins.
issue: none

feat(e2e): monitor and solver pins

---

e2e/app/admin/bridgespec.go
e2e/app/admin/testdata/TestNetworkBridgeSpec.golden

Prepping action to unpause the omega bridge now that it is paused.
issue: none

chore(e2e): unpause omega bridge

---

e2e/vmcompose/provider.go

Copy redenom key to VM if exists on upgrade.
issue: none

chore(e2e/vmcompose): copy redenom key if exist

---

e2e/manifests/mainnet.toml
e2e/manifests/omega.toml

bump halo for redenom fix
issue: none

chore(e2e/manifests): bump halo for redenom fix

---

e2e/nomina/convert.go

Compared a pointer which caused addresses with no OMNI balance to process conversion TXs. Also implemented an ETH balance check as to not throw on addresses with no ETH (such as `NomMintAuthority`).
issue: none

fix(e2e): fix conversion action

---

e2e/app/erc20faucet.go

Convert faucet to using NOM.
issue: none

feat(e2e): convert faucet to nom

---

e2e/app/eoa/testdata/solver_reference.json
e2e/manifests/staging.toml

remove holesky from staging
issue: none

chore(e2e/manifests): remove holesky from staging
