omni-network/omni

docs/contributing.md

This doc replaces the empty guidelines docs for Go and Solidity with single links with popular guidelines
task: none

chore(docs): edit contributing guidelines

---

.golangci.yml
test/e2e/app/definition.go
test/e2e/cmd/flags.go
test/e2e/docker/docker.go
test/e2e/docker/docker_test.go
test/e2e/docker/testdata/TestComposeTemplate_image_tag_7d1ae53.golden
test/e2e/docker/testdata/TestComposeTemplate_image_tag_main.golden
test/e2e/tests/e2e_test.go
test/e2e/vmcompose/provider.go
test/e2e/vmcompose/provider_test.go
test/e2e/vmcompose/testdata/TestSetup_127_0_0_1_compose.yaml.golden
test/e2e/vmcompose/testdata/TestSetup_127_0_0_2_compose.yaml.golden
test/e2e/vmcompose/testdata/TestSetup_127_0_0_3_compose.yaml.golden

This PR adds `--image-tag` to the e2e runner binary so that the generated docker compose files can pin docker images by tag.
task: https://app.asana.com/0/1206208509925075/1206590491637443/f

feat(e2e): add --image-tag to e2e cmd

---

.gitignore
test/e2e/netman/helpers.go
test/e2e/netman/manager.go

Goerli was rejecting deployments for underpriced replacement transactions. Fixed how we wait for transactions to be mined. Also improved some logging
task: none

fix(netman): improve txn sending and logs

---

test/e2e/cmd/cmd.go
test/e2e/docker/docker.go
test/e2e/types/infra.go
test/e2e/vmcompose/provider.go

Adds support to e2e app to "upgrade" existing `vmcompose` networks. It copies the new docker-compose files and then runs `docker-compose up`
task: none

feat(e2e): support upgrading vmcompose networks

---

.github/workflows/ci-docs.yml
.github/workflows/ci-pr-docs.yml

This PR introduces:
- the `site/` directory in `./docs` (with `.gitkeep`)
- A workflow (`ci-pr-docs.yml`) for deploying preview PRs using the vercel CLI and a github action for commenting the URL of this deployed version
- A workflow (`ci-docs.yml`) for deploying any merges to `main` that have updates to `./docs/site` to the production vercel environment
The required secrets have been added to the repository settings (`VERCEL_TOKEN`, `VERCEL_ORG_ID` and `VERCEL_PROJECT_ID`).
task: https://app.asana.com/0/1206208509925075/1206566996089561

chore(ci): add docs pr and deploy ci

---

.github/workflows/ci-docs.yml

This PR disables the docs `deploy` workflow (now only to be triggered manually)
task: none

fix(ci): disable docs deploy ci

---

.golangci.yml
explorer/graphql/app/app.go
explorer/indexer/app/app.go
halo/app/app.go
halo/attest/metrics.go
halo/comet/metrics.go
halo2/app/start.go
halo2/attest/attester/metrics.go
lib/cchain/provider/metrics.go
lib/gitinfo/gitinfo.go
lib/gitinfo/metrics.go
lib/log/metrics.go
lib/xchain/provider/metrics.go
relayer/app/app.go
relayer/app/metrics.go
relayer/txmgr/metrics.go

Adds `lib_git_commit` and `lib_git_timestamp` "constant gauge metrics" with labels to set to those values. This makes it easy to visualise what commit is running and how old that commit is (since git commits are not directly human parsable).
task: none

chore(lib/gitinfo): add git info metrics to all apps

---

.secrets.baseline
halo/app/config.go
halo/cmd/cmd.go
halo/cmd/cmd_internal_test.go
halo/cmd/testdata/TestCLIReference_halo.golden
halo/cmd/testdata/TestRunCmd_defaults.golden
halo/cmd/testdata/TestRunCmd_flags.golden
halo/cmd/testdata/TestRunCmd_json_files.golden
halo/cmd/testdata/TestRunCmd_toml_files.golden
halo2/app/app.go
halo2/app/app_config.go
halo2/app/logging.go
halo2/app/start.go
halo2/app/start_test.go
halo2/attest/attester/attester.go
halo2/attest/attester/attester_test.go
halo2/attest/keeper/keeper.go
halo2/attest/keeper/msg_server.go
halo2/attest/types/tx.go
halo2/evmengine/keeper/abci.go
halo2/genutil/genutil.go
halo2/genutil/genutil_test.go
lib/cchain/provider/abci2.go
relayer/app/app.go
test/e2e/app/setup.go

Fixes to halo2 to get e2e working:
- Use MemDB by default (something is from with golevelDB, queries always fail)
- Move SDK init, since it is always required.
- Add logging of ABCI methods
- Fix attester issues (race and protos can't be map keys, tests were pointing to old impl)
- Improve visibility of failed txs.
- Implement post InitChain gas meter issue workaround
task: none

fix(halo2): fixes to get halo e2e working

---

halo2/app/logging.go
test/e2e/tests/attestations_test.go

Fixes e2e tests to use halo2 cprovider. Also reduce query debug logs.
task: none

fix(e2e/tests): use halo2 cprovider

---

test/e2e/app/monitor.go

fix(e2e/tests): use halo2 cprovider again

---

lib/cchain/provider/metrics.go
lib/cchain/provider/provider.go

cprovider metrics must be "per chain". Also reduce log label duplication.
task: none

fix(lib/cchain): fix cprovider metrics and logs

---

test/e2e/app/avs.go
test/e2e/netman/avs/xdapp.go

We were using the L1 chain ID in AVS deployment, this updates to use the correct omni chain id.
task: none

fix(e2e): set omnichain id

---

contracts/broadcast/DeployEigenLayer.s.sol/31337/run-latest.json
contracts/script/eigen/deploy-eigenlayer-save-anvil-state.sh
contracts/script/eigen/output/anvil-state.json
test/e2e/docker/compose.yaml.tmpl
test/e2e/docker/testdata/TestComposeTemplate_image_tag_7d1ae53.golden
test/e2e/docker/testdata/TestComposeTemplate_image_tag_main.golden
test/e2e/vmcompose/testdata/TestSetup_127_0_0_3_compose.yaml.golden

The `xprovider` watches a chain's portal from a provided start block. We set our private anvil chains to start at block 0 (via portal `DeployInfo`). When we loaded anvil state for the Eigenlayer deployments, it started from block 12. Then our `xprovider` was watching for block 0, and never processing any `XBlocks`.
The solution is to just set the anvil pre-loaded chain to start at block 0. Another solution could be to set portal `DeployInfo` once the portal is actually deployed, but this is a more difficult – as we don't actually spin up the anvil chains until after setting the `network.json`
task: none

fix(e2e): reset anvil loader to block 0

---

.github/workflows/ci-notify.yml

Since we now have notifications for 2 repos, we need to specify which one CI failed on.
task: none

chore(ci): add repo to notify action

---

lib/log/config.go
lib/log/log.go
lib/log/logger.go
lib/log/testdata/TestSimpleLogs_logfmt.golden
test/e2e/app/static/prometheus.yml.tmpl
test/e2e/docker/compose.yaml.tmpl
test/e2e/docker/docker.go
test/e2e/docker/docker_test.go
test/e2e/docker/testdata/TestComposeTemplate_image_tag_7d1ae53.golden
test/e2e/docker/testdata/TestComposeTemplate_image_tag_main.golden
test/e2e/vmcompose/provider.go
test/e2e/vmcompose/testdata/TestSetup_127_0_0_1_compose.yaml.golden
test/e2e/vmcompose/testdata/TestSetup_127_0_0_2_compose.yaml.golden
test/e2e/vmcompose/testdata/TestSetup_127_0_0_3_compose.yaml.golden

Improves staging metrics and logs:
- Adds support for `logfmt` log format.
- Use that in `vmcompose` deployments
- Add a `container` metric label (to match cadvistor log `container` label)
task: none

chore(e2e): improve staging logs and metrics

---

.golangci.yml
.secrets.baseline
halo/app/start.go
lib/gitinfo/gitinfo.go
lib/gitinfo/metrics.go
lib/log/config.go
lib/log/logger.go
lib/log/metrics.go
test/e2e/app/prometheus.go

Fixes `lib/log` and `lib/gitinfo` metrics. Also enabled cosmosSDK metrics.
task: none

chore(lib/metrics): fix log and git metrics

---

.github/workflows/e2etest.yml
Makefile
halo/attest/keeper/keeper.go
test/e2e/.gitignore
test/e2e/run-multiple.sh

Make debugging CI e2e easier. Currently the github UI is overloaded with container logs.
Uploads failed e2e test container logs as github artefact. Only spew warn|error logs.
task: none

test(e2e): upload failed containers logs

---

.secrets.baseline
halo/app/app.go
halo/app/prouter.go
halo/attest/keeper/cpayload.go
halo/attest/keeper/cpayload_internal_test.go
halo/attest/keeper/keeper.go
halo/attest/keeper/msg_server.go
halo/attest/keeper/proposal_server.go
halo/evmengine/keeper/abci.go
halo/evmengine/keeper/keeper.go
halo/evmengine/keeper/msg_server.go
halo/evmengine/keeper/proposal_server.go
halo/evmengine/module/module.go
lib/expbackoff/expbackoff.go
relayer/app/monitor.go
relayer/app/worker.go
test/e2e/app/contract.go
test/e2e/netman/avs/xdapp.go
test/e2e/netman/pingpong/pingpong.go

Fixes a bug in `aggregateAtts`. We assumed `BlockHashes` are unique across chains, which is probably the case in the wild but definitely not the case for anvil chains in e2e. Use `BlockHeader` for uniqueness instead.
Also use the cosmos sdk `baseapp.ValidateVoteExtensions`. This requires moving the attestation CProvider to attest keeper proper. And makes evmkeeper depend on attest keeper so had to change deps.
Also improve relayer worker reset backoff and logs.
Also improve e2e test logs.
task: none

fix(halo/attest): fix bug in attestation aggregation

---

relayer/app/metrics.go
relayer/app/monitor.go

Adds head (`latest,safe,finalised`) monitoring to relayer.
task: none

chore(relayer): add head monitoring

---

lib/math/sum.go
test/e2e/app/math.go
test/e2e/app/run.go

We shouldn't have a random math function in `run.go`
task: none

chore(e2e): moving sum function to dedicated file

---

.secrets.baseline
lib/errors/errors.go
lib/txmgr/config.go
lib/txmgr/txmgr.go
lib/txmgr/txmgr_internal_test.go
relayer/app/app.go
relayer/app/opsender.go
test/e2e/app/avs.go
test/e2e/app/contract.go
test/e2e/app/definition.go
test/e2e/app/run.go
test/e2e/netman/avs/xdapp.go
test/e2e/netman/helpers.go
test/e2e/netman/manager.go
test/e2e/netman/pingpong/pingpong.go
test/e2e/send/backend.go
test/e2e/send/sender.go

Implement `send.Sender` that implements `bindings.TxOptions` and `bindings.DeployBackend` so that we can keep on using bindings but also txmgr for reliable sending in e2e.
task: none

refactor(e2e): ues txmgr as bindings txopts and backends

---

lib/txmgr/txmgr.go
test/e2e/docker/compose.yaml.tmpl

Fixes root cause of "nonce to low" in e2e tests. When quering txreceipts, geth sometimes returns "transaction indexing in progress". Old txmgr didn't handle this and tried resubmitting while the tx was then confirmed in most cases. Instead it should re-attempt fetching the receipt.
task: none

fix(lib/txmgr): handle wait mine edge case

---

docs/site/docusaurus.config.ts
docs/site/src/css/custom.css

This PR does two things: 
1. Fixes the search bar, now yielding results which should be viewable from running the app locally or in the preview commented in this PR. 
- A new viewing API key was created during debugging 
- `contextualSearch` has been disabled, this was a param that would distinguish search results by language, but because of the default crawling settings in Algolia, the index would not exactly match the query params. This param will be required to be set to `true` again once the docs supports multiple languages and docs versions, and the Algolia crawler logic will need to be adjusted accordingly. 
2. Color fix for light mode search modal
task: none

fix(docs): search

---

.secrets.baseline
relayer/app/worker_test.go
test/e2e/app/avs.go
test/e2e/app/contract.go
test/e2e/app/definition.go
test/e2e/app/run.go
test/e2e/backend/backend.go
test/e2e/backend/backends.go
test/e2e/backend/wait.go
test/e2e/netman/avs/xdapp.go
test/e2e/netman/helpers.go
test/e2e/netman/manager.go
test/e2e/netman/pingpong/pingpong.go

Refactor `send.Sender` to `backend.Backends` to align more with its use as a bindings "Backend". It is used for more things than sendings. It is a general bindings backend.
Also adds a handy struct to wait for multiple transactions to be mined in tests.
task: none

refactor(e2e/send): rename sender to backends

---

.golangci.yml
Makefile
test/e2e/app/rpc.go
test/e2e/app/run.go
test/e2e/app/start.go
test/e2e/manifests/ci.toml

Adds the start of our "ci" manifest that will do a lot of non-happy path tests. v0 just starts one validator late.
task: none

test(e2e): add ci manifest with catchup node

---

halo/app/start_test.go
halo/attest/keeper/keeper.go
halo/attest/keeper/query.go
halo/attest/types/query.pb.go
halo/attest/types/query.proto
lib/cchain/provider.go
lib/cchain/provider/abci.go
lib/cchain/provider/provider.go
lib/cchain/provider/provider_test.go
relayer/app/app.go
relayer/app/metrics.go
relayer/app/monitor.go

Monitor "latest attested height" from relayer. This ensures consistent/synchronised reporting of key cross-chain metrics and avoids prometheus scrap offset issues resulting in negative lag in grafana.
Added a `LatestAttestation` query endpoint to `halo's` `attest` module.
task: none

chore(relayer): monitor attested height from relayer

---

test/e2e/app/run.go
test/e2e/cmd/cmd.go

In order to copy the docker-compose file, it has to be generated by `Setup`.
task: none

fix(e2e): fix upgrade command

---

.secrets.baseline
halo/Dockerfile
halo/attest/keeper/keeper.go
halo/attest/keeper/msg_server.go
halo/attest/keeper/proposal_server.go
halo/cmd/flags.go
halo/cmd/testdata/TestCLIReference_run.golden
halo/cmd/testdata/TestRunCmd_defaults.golden
halo/cmd/testdata/TestRunCmd_flags.golden
halo/cmd/testdata/TestRunCmd_json_files.golden
halo/cmd/testdata/TestRunCmd_toml_files.golden
halo/comet/comet.go
halo/config/config.go
halo/config/config.toml.tmpl
halo/config/testdata/default_halo.toml
halo/evmengine/keeper/keeper.go
test/e2e/app/run.go
test/e2e/app/setup.go
test/e2e/app/setup_internal_test.go
test/e2e/app/start.go
test/e2e/app/testdata/TestUpdateConfigStateSync.golden
test/e2e/backend/backends.go
test/e2e/manifests/ci.toml
test/e2e/netman/manager.go

Adds `state_sync=true` to ci manifest.
This highlighted the following issue in our attest module design:
- Snapshot sync restores the consensus chain at a certain height. Both the application state AND cometBFT state.
- That means that for the first block after a snapshot restore, there is no information about the previous block’s app/cometBFT state. 
- This is a problem for our current attest module logic, since we rely on “previous block validator set”.
- Which is not available immediately after a restore.
Solution:
- Just use current validator set
- Only drawback is that last votes from outgoing validators will be dropped
- This shouldn’t be a problem, unless validators get evicted from the set very regularly.
Considered solutions:
- Track previous validator set
- We manually keep …

fix(halo/attest): use current validator set for approvals

---

halo/attest/keeper/keeper.go

Improve halo attest module's "Voted for rollup blocks" logging to only log the first 5 votes as this can be super noisy.
task: none

chore(halo/attest): improve vote log

---

test/e2e/docker/compose.yaml.tmpl
test/e2e/docker/testdata/TestComposeTemplate_image_tag_7d1ae53.golden
test/e2e/docker/testdata/TestComposeTemplate_image_tag_main.golden

Until now we were running Prometheus with the default settings (command flags). With this PR we set those explicitly and enable 2 new flags:
- Instruct Prometheus to scrape and store metrics exemplars
- Disable the Prometheus UI on our staging env and only run it in agent mode. This way it consumes a lot less resources. The agent mode can be potentially conditional and on localhost we can run the full Prometheus UI.
task: none

chore(e2e/prometheus): update prometheus command

---

docs/site/docs/develop/introduction.md

Clarify xmsg.sender as the msg.sender of the source xcall
task: none

chore(docs): add clarifying comment

---

.secrets.baseline
halo/app/start.go
halo/cmd/flags.go
halo/cmd/testdata/TestCLIReference_run.golden
halo/cmd/testdata/TestRunCmd_defaults.golden
halo/cmd/testdata/TestRunCmd_flags.golden
halo/cmd/testdata/TestRunCmd_json_files.golden
halo/cmd/testdata/TestRunCmd_toml_files.golden
halo/config/config.go
halo/config/config.toml.tmpl
halo/config/testdata/default_halo.toml
test/e2e/app/setup.go

Adds a `--snapshot-keep-recent` flag to halo to configure the number of snapshots to keep on disk.
Disable snapshot pruning in e2e tests to avoid [flapping](https://github.com/omni-network/omni/actions/runs/8073387873/job/22057172343) test if restoring a snapshot is slow (due to network blips).
task: none

feat(halo/config): support snapshot keep recent flag

---

halo/attest/voter/metrics.go
halo/attest/voter/voter.go
lib/cchain/provider/metrics.go
lib/cchain/provider/provider.go
lib/xchain/provider/metrics.go
lib/xchain/provider/streamer.go

Adds `*_fetch_error_total` metrics to xprovider and cprovider. Align implementations so they look the same.
task: none

chore(lib/provider): add fetch error metrics to providers

---

lib/cchain/provider/abci.go
lib/cchain/provider/metrics.go
relayer/app/monitor.go

Improve relayer metrics:
- ensure halo attest height is lower than head (call after head).
- add cprovider query latency and errors.
task: none

chore(lib/relayer): improve relayer metrics

---

relayer/app/monitor.go
test/e2e/app/definition.go
test/e2e/app/test.go
test/e2e/manifests/simple.toml
test/e2e/tests/e2e_test.go
test/e2e/tests/eigen_test.go
test/e2e/types/manifest.go

Improve relayer metrics:
- Query in correct order (from back to front)
- Instrument metrics atomically.
- Instrument `xfinal` head which is the `FinalisationStrategy` height.
Also add `slow_tests` flag to e2e manifest and only run slow AVS tests in `simple` manifest.
task: none

chore(relayer): improve relayer metrics

---

test/e2e/manifests/staging.toml

Include anvil chain in staging, chain_a. It will run on vm3.
task: none

ci(e2e): include anvil chain in staging

---

.github/workflows/ci-pr.yml
.github/workflows/pr-e2etest.yml

Enables running a single devnet1 e2e test in PRs. It also fast-builds the halo and relayer images locally (no pushing to dockerhub). 
This is a test. We can disable it if too slow or resource heavy.
task: none

ci(e2e): run single devnet1 e2e test in PRs

---

lib/ethclient/ethclient.go
lib/netconf/netconf.go
test/e2e/app/definition.go

Anvil chains didn't have a finalisation strategy in staging. Not sure why this wasn't caught in e2e, need to confirm.
task: none

fix(e2e): fix missing anvil finalisation strategy

---

.secrets.baseline
test/e2e/app/agent/prometheus.go
test/e2e/app/agent/prometheus.yml.tmpl
test/e2e/app/agent/prometheus_internal_test.go
test/e2e/app/agent/testdata/TestPromGen_manifest1_gen.golden
test/e2e/app/agent/testdata/TestPromGen_manifest1_update.golden
test/e2e/app/agent/testdata/TestPromGen_manifest2_gen.golden
test/e2e/app/agent/testdata/TestPromGen_manifest2_update.golden
test/e2e/app/run.go
test/e2e/app/setup.go
test/e2e/cmd/cmd.go
test/e2e/cmd/flags.go
test/e2e/vmcompose/provider.go

Fixes `vmcompose` infra provider to deploy correct prometheus config that only tries to scrape services that are deployed on each specific host.
Previously, each prometheus tried to scrape all targets, even though they were not present on all hosts. This resulted in "relayer" down alerts.
Also add a "host" label to prometheus metrics so we can differentiate where the metric are coming from.
task: none

fix(e2e): fix prometheus scrape configs in staging

---

contracts/Makefile

Mark phony make targets as .PHONY
task: none

chore(contracts): mark phony make targets

---

halo/attest/keeper/keeper_internal_test.go

This PR adds type builders for `MsgAddVotes` to avoid duplication in tests.
task: https://app.asana.com/0/0/1206715268196567/f

test(halo/attest): add type builders to avoid duplication

---

.github/workflows/ci-main.yml
.github/workflows/ci-release.yml
.github/workflows/release-official.yml
.github/workflows/release-snapshot.yml
.goreleaser.yaml
.secrets.baseline
scripts/install_omni_cli.sh

Configures goreleaser for official releases on git tags.
task: none

ci(goreleaser): release omni cli as github archive

---

relayer/app/buffer.go
relayer/app/buffer_internal_test.go
relayer/app/cursors.go
relayer/app/cursors_internal_test.go
relayer/app/opsender.go
relayer/app/state.go
relayer/app/types.go
relayer/app/types_internal_test.go
relayer/app/worker.go
relayer/app/worker_internal_test.go

Housekeeping:
- unexports functions that don't need to be exported
- filename changes
task: none

refactor(relayer/app): unexport functions

---

.goreleaser.yaml

Fixes missing `omni` cil artefacts for github triggered release.
task: none

ci(gorelease): fix missing omni release artefacts

---

lib/promutil/resetgauge.go
lib/promutil/resetgauge_test.go
monitor/avs/metrics.go
monitor/avs/monitor.go

Adds a `promutil.ResetGaugeVec` and use in `monitor/avs` to support operator removals from metrics.
task: none

refactor(monitor/avs): add and use reset gauge

---

scripts/install_omni_cli.sh

This PR makes the install script compatible for linux and adds the export of `$HOME/bin` to the PATH in the shell run commands file
task: none

fix(scripts): cli install script for linux

---

.github/workflows/e2etest.yml
.github/workflows/pr-e2etest.yml

Configure e2e GH actions to push logs to Loki on failure. This is configured only for e2e tests which are run as a result of merge to `main` branch.
task: https://app.asana.com/0/1206208509925075/1206729533969884/f

chore(ci): push e2e logs to Loki

---

lib/avs/anvil/anvil.go
lib/ethclient/ethbackend/backend.go
lib/ethclient/ethbackend/backend_internal_test.go

Fix sporadic flapping tests due to leading zeros being stripped in `backendStubSigner`
task: none

fix(lib/ethbackend): fix leading zero bug in stub signer

---

monitor/avs/avs.go
test/e2e/app/definition.go
test/e2e/docker/compose.yaml.tmpl
test/e2e/docker/docker.go
test/e2e/docker/docker_test.go
test/e2e/docker/testdata/TestComposeTemplate_image_tag_7d1ae53.golden
test/e2e/docker/testdata/TestComposeTemplate_image_tag_main.golden
test/e2e/vmcompose/testdata/TestSetup_127_0_0_3_compose.yaml.golden

Decreases anvil blocks times on staging (or any VM deployment) from 1s to 12s to reduce disk usage by 10x. 
task: none

ci(e2e): decrease staging anvil block period

---

.secrets.baseline
halo/config/config.go
halo/config/config.toml.tmpl
lib/buildinfo/buildinfo.go
relayer/app/config.go
relayer/app/config.toml.tmpl

Adds the current buildinfo version to halo and relayer config toml.
task: none

chore(config): add version to config toml

---

.secrets.baseline
test/e2e/app/perturb.go
test/e2e/app/run.go
test/e2e/app/setup.go
test/e2e/app/start.go
test/e2e/manifests/ci.toml

Adds a `fullnode01` node to ci manifest. Add a restart perturbation to it.
task: none

test(e2e): add restarted full node to ci manifest

---

cli/cmd/register.go

add avs contract address to cli so operators don't need to add the flag
task: none

chore(cli): add goerli avs address

---

docs/site/docs/operate/testnet/register.md

Fixes some operator docs
task: none

fix(docs): update reference operator yaml

---

halo/attest/keeper/common_test.go
halo/attest/keeper/keeper.go
halo/attest/testutil/mock_interfaces.go

Drop votes for attestations that were approved by a different validator set.
This ensures that the signatures of an approved attestation always match the validator set that approved it.
task: none

fix(halo/attest): drop votes for previously approved attestations

---

.secrets.baseline
lib/k1util/k1util.go
lib/k1util/k1util_test.go
test/tutil/random.go

Adds a unit test that confirms that cometBFT privval signatures are compatible with ethereum RSV signatures. This confirms we can use web3signer as keystore.
We cannot use tendermint privval/kms since its signing interface is limited to tendermint votes and proposals and we need to sign attest votes as well.
task: none

test(lib/k1util): ensure cometBFT privval compatible with web3signer

---

halo/app/app.go
halo/attest/keeper/cpayload.go
halo/evmengine/keeper/abci.go
halo/evmengine/keeper/abci_internal_test.go
halo/evmengine/keeper/evmmsgs.go
halo/evmengine/keeper/keeper.go
halo/evmengine/keeper/logmsgprovider.go
halo/evmengine/keeper/msg_server.go
halo/evmengine/keeper/msg_server_internal_test.go
halo/evmengine/keeper/proposal_server.go
halo/evmengine/keeper/proposal_server_internal_test.go
halo/evmengine/types/cpayload.go
halo/evmengine/types/tx.go
halo/evmengine/types/tx.pb.go
halo/evmengine/types/tx.proto
lib/ethclient/enginemock.go

Adds evm logs of current EVM head as part of `MsgExecutionPayload` in `PrepareProposal`, verify it in `ProcessProposal`, deliver the logs to `EVMLogProviders` in `FinaliseBlock`.
Added a `pocLogProvider` to test the feature. 
task: none

feat(halo/evmengine): add evm logs to execution payload

---

monitor/avs/avs.go
monitor/avs/monitor.go
test/e2e/manifests/staging.toml
test/e2e/types/chain.go

Goerli stopped finalizing blocks, RIP.
- use arb sepolia and op sepolia for rollups
- we can't use Goerli for the AVS contracts anymore (we could, but wouldn't be able to pass restaking payloads to Omni), so let's just use our anvil chain for now
task: none

chore(e2e): migrate to sepolia

---

docs/site/docusaurus.config.ts

Fixes "Edit this page" links on docs
task: none

chore(docs): fix edit page

---

docs/site/docs/develop/introduction.md

Mention on develop section about xmsg only being relayed once finalized
task: https://app.asana.com/0/1206684215872507/1206806971862696/f

chore(docs): develop notice xmsg only for finalized xmsgs

---

halo/config/testdata/default_halo.toml
lib/buildinfo/buildinfo.go
relayer/app/testdata/default_relayer.toml

Increases version in lib/buildinfo so version is shown when running version command on locally built CLI
task: https://app.asana.com/0/1206684215872507/1206806971862694/f

chore(lib/buildinfo): bump buildinfo minor and patch version

---

.secrets.baseline
test/e2e/app/avs.go
test/e2e/app/run.go
test/e2e/cmd/cmd.go
test/e2e/cmd/flags.go

Add `avs-deploy` subcommand to the e2e runner binary.
task: https://app.asana.com/0/1206208509925075/1206799220447925/f

feat(e2e): add avs-deploy subcommand

---

relayer/app/app.go

AVS monitoring will be enabled this [PR](https://github.com/omni-network/omni/pull/590), currently, we are facing an error because of a public goerli endpoint that got deprecated.
task: none

chore(relayer/app): remove avs monitoring

---

halo/attest/keeper/common_test.go
halo/attest/keeper/keeper.go
halo/attest/keeper/keeper_test.go
halo/attest/types/helpers.go
halo/attest/types/keys.go
test/e2e/app/avs.go

Approve attestations sequentially. 
I.e., so only approve 3, if the previously approved is 2. Do not allow approving 4 if previously approved is 2.
This fixes the following critical bug:
- Given a vote window of 10.
- If the last approved was 2 (so vote window is [0,12]
- If we skip 3 and approved 12 next, and then we approve 14, the vote window is [4,24]
- Which means 3 will never be approved.
- This will cause the cross chain protocol to stall forever.
task: none

fix(halo/attest): only approve sequentially

---

halo/valsync/keeper/keeper.go
halo/valsync/keeper/query.go

Fixes missing "remove validator updates" by storing them in the validator set.
task: none

fix(halo/valsync): store removed updates to db

---

e2e/app/definition.go
e2e/manifests/ci.toml
halo/app/start.go
halo/app/start_test.go
halo/cmd/init.go
halo/evmstaking/evmstaking.go
lib/ethclient/enginemock.go
lib/xchain/provider/mock.go
lib/xchain/provider/mock_internal_test.go

- Adds support for "increased self-delegation" if deposit by existing validator.
- Add cprovider to xprovider mock since it can query the local halo instance
- Add a "wait for cometBFT validator set to change" assertion in smoke test
- Add a "mock deposit" to "engine mock" so we trigger validator updates in smoke test.
task: none

test(halo/app): assert validator update in smoke test

---

.golangci.yml
.secrets.baseline
lib/ethclient/ethbackend/backends.go
lib/fireblocks/client.go
lib/fireblocks/client_test.go
lib/fireblocks/jsonhttp.go
lib/fireblocks/sign.go
lib/fireblocks/types.go
lib/txmgr/config.go
lib/txmgr/txmgr.go
lib/txmgr/txmgr_internal_test.go
relayer/app/sender.go

Adds support for `externalSigners` to txmgr. This is the interface that `fireblocks.Sign` provides.
Also do some general renaming and cleanup.
task: none

refactor(lib/txmgr): add support for fireblocks signer

---

.secrets.baseline
e2e/app/definition.go
e2e/cmd/cmd.go
e2e/cmd/flags.go
e2e/netman/pingpong/pingpong.go
e2e/vmcompose/provider_test.go
lib/contracts/avs/register.go
lib/ethclient/ethbackend/backend.go
lib/ethclient/ethbackend/backends.go
lib/fireblocks/account.go
lib/fireblocks/client.go
lib/fireblocks/client_test.go
lib/fireblocks/config.go
lib/fireblocks/key.go

- Adds a Fireblocks based `ethbackend`.
- Refactor fireblocks.Environment to use netconf.Network.
- Wire fireblocks backend into e2e using flags.
task: none

feat(lib/ethbackend): add fireblocks backend and wire e2e

---

.secrets.baseline
e2e/app/avs.go
e2e/app/create3.go
e2e/app/run.go
e2e/netman/manager.go
e2e/netman/pingpong/pingpong.go
halo/genutil/evm/evm.go
halo/genutil/evm/testdata/TestMakeGenesis.golden
lib/anvil/accounts.go
lib/contracts/avs/avs_test.go
lib/contracts/avs/deploy.go
lib/contracts/create3/deploy.go
lib/contracts/portal/deploy.go
lib/contracts/portal/deploy_test.go
lib/contracts/proxyadmin/deploy.go
lib/contracts/proxyadmin/deploy_test.go
lib/contracts/static.go
lib/ethclient/ethbackend/backend.go
lib/ethclient/ethbackend/backends.go
lib/netconf/static.go

Deploy AVS via Create3. 
Also refactor all lib/contracts deployments, to only expose a single network based Deploy func.
task: https://app.asana.com/0/1206208509925075/1206909416405983

feat(lib/contracts): deploy avs via create3

---

.secrets.baseline
e2e/app/run.go
e2e/app/setup.go
e2e/app/valupdates.go
halo/genutil/evm/evm.go
halo/genutil/evm/testdata/TestMakeGenesis.golden
lib/k1util/k1util.go
monitor/app/app.go
monitor/app/config.go
monitor/app/config_test.go
monitor/app/monitor.toml
monitor/app/testdata/default_monitor.toml
monitor/cmd/cmd.go
monitor/cmd/flags.go
monitor/loadgen/loadgen.go
monitor/loadgen/stake.go

Add a `loadgen` package to `monitor` service that periodically self-delegates validator stake to test validator updates in staging/devnet.
Update monitor config to load those keys and e2e app to wire it.
task: none

ci(monitor/loadgen): add auto validator self-delegation

---

e2e/app/avs.go
lib/contracts/avs/deploy.go

Only deploy an network's AVS if it has not already been deployed.
task: none

feat(lib/contracts): only deploy avs if its not deployed

---

e2e/netman/manager.go
lib/contracts/addrs.go

Fix staging and devnet addrs.
- use different accounts for relayer and operator.
- add staging deployer config
-  add comments to update staging addresses with proper addresses.
task: none

fix(e2e): fix staging and devnet addrs

---

halo/genutil/testdata/TestMakeGenesis.golden
lib/netconf/static.go

We didn't require e2e tests to pass in PRs, so automerge merged it before I could fix it.
task: none

test(ci): fix failing CI after automerge

---

e2e/netman/manager.go

Do not read block height from receipt, as it may be nil.
task: none

fix(e2e/netman): fix nil pointer dereference

---

lib/buildinfo/buildinfo.go
lib/contracts/addrs.go

Use git hash in salt for ephemeral deployments. Use static salt for long term deployments.
task: none

fix(lib/contracts): use git hash for ephemeral salts

---

lib/txmgr/config.go

Increase timeout for fireblocks signing since they are slow 🐢 
task: none

refactor(lib/txmgr): increase default network timeout

---

e2e/app/key/gcp.go
e2e/app/key/key_internal_test.go

GCP uses URL base64 encoding :/
task: none

fix(e2e/key): fix base64 parsing

---

e2e/manifests/staging.toml

Fixes staging manifest. p2p_exection keys must be defined on the EVM node itself, not on the halo node.
task: none

fix(e2e/manifest): fix staging manifest evm key

---

e2e/app/definition.go
e2e/types/manifest.go

Simplifies manifest key type into a map of typed keys.
task: none

ci(e2e): refactor manifest key type

---

.secrets.baseline
e2e/app/definition.go
e2e/app/geth.toml.tmpl
e2e/app/setup.go
e2e/app/setup_internal_test.go
e2e/app/testdata/TestWriteGethConfigTOML.golden
e2e/docker/compose.yaml.tmpl
e2e/docker/docker_test.go
e2e/docker/testdata/TestComposeTemplate_image_tag_7d1ae53.golden
e2e/docker/testdata/TestComposeTemplate_image_tag_main.golden
e2e/manifests/staging.toml
e2e/types/manifest.go
e2e/types/testnet.go
e2e/vmcompose/testdata/TestSetup_127_0_0_1_compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127_0_0_2_compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127_0_0_4_compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127_0_0_5_compose.yaml.golden
lib/ethclient/ethbackend/backends.go

Improves geth config:
- Use internal IPs for nat when using docker
- Enable p2p discovery
- Switch static nodes to trusted nodes
- Use IsArchive instead of GcMode
- Move most flags to config file
- Store nodekey as file instead of "test only" flag
- Copy jwtsecret to halo config instead of sharing mount.
- Add explicit `archive` mode to manifest.
- Clarify what each mode means.
- Always broadcast e2e txs via full or archive node if available (seems like txs stuck in  mempool is now solved?).
task: none

ci(e2e): improve geth config

---

.secrets.baseline
e2e/app/agent/prometheus.go
e2e/app/agent/prometheus_internal_test.go
e2e/app/agent/testdata/TestPromGen_manifest1_gen.golden
e2e/app/agent/testdata/TestPromGen_manifest1_update.golden
e2e/app/agent/testdata/TestPromGen_manifest2_gen.golden
e2e/app/agent/testdata/TestPromGen_manifest2_update.golden
e2e/app/agent/testdata/TestPromGen_manifest3_gen.golden
e2e/app/agent/testdata/TestPromGen_manifest3_update.golden
e2e/app/agent/testdata/TestPromGen_manifest4_gen.golden
e2e/app/agent/testdata/TestPromGen_manifest4_update.golden
e2e/app/geth.toml.tmpl
e2e/app/testdata/TestWriteGethConfigTOML.golden
e2e/docker/compose.yaml.tmpl
e2e/docker/testdata/TestComposeTemplate_image_tag_7d1ae53.golden
e2e/docker/testdata/TestComposeTemplate_image_tag_main.golden
e2e/types/testnet.go
e2e/vmcompose/provider.go
e2e/vmcompose/testdata/TestSetup_127_0_0_1_compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127_0_0_2_compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127_0_0_4_compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127_0_0_5_compose.yaml.golden

Enables geth metrics. Also reverts the broadcast node to validators since "tx stuck in mempool" obviously isn't fixed. This [deploy](https://github.com/omni-network/ops/actions/runs/8509402994/job/23304866875) got stuck with it.
task: none

ci(e2e): enable geth metrics and revert broadcast evm

---

e2e/app/definition.go
e2e/types/manifest.go

Adds all nodes with mode "seed" as p2p seed nodes by default. Also remove them persisted peers list.
task: none

ci(e2e): fix default seed nodes

---

e2e/app/setup.go
e2e/docker/compose.yaml.tmpl
e2e/docker/docker.go
e2e/docker/testdata/TestComposeTemplate_image_tag_7d1ae53.golden
e2e/docker/testdata/TestComposeTemplate_image_tag_main.golden
e2e/vmcompose/provider.go
e2e/vmcompose/testdata/TestSetup_127_0_0_1_compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127_0_0_2_compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127_0_0_3_compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127_0_0_4_compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127_0_0_5_compose.yaml.golden

Solve the problem of monitor service on staging have console logs. This is due to misconfiguration. Solve it by defining log config in one place, not two.
task: none

ci(e2e): improve container log config

---

halo/app/logging.go
halo/app/prouter.go
halo/attest/keeper/keeper.go
halo/evmengine/keeper/msg_server.go

Improve evmengine logging.
> Note that we MUST not use `"msg"` logging attributes, since this replaces the actual logging message.
task: none

chore(halo/evmengine): improve logging

---

e2e/app/geth.toml.tmpl

Geth doesn't seem to support "full sync" when being used as fullnode engineAPI.
task: none

ci(e2e): change geth to fullsync

---

.secrets.baseline
e2e/app/geth.toml.tmpl
e2e/app/setup.go
e2e/app/testdata/TestWriteGethConfigTOML.golden
e2e/docker/compose.yaml.tmpl
e2e/docker/testdata/TestComposeTemplate_image_tag_7d1ae53.golden
e2e/docker/testdata/TestComposeTemplate_image_tag_main.golden
e2e/vmcompose/testdata/TestSetup_127_0_0_1_compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127_0_0_2_compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127_0_0_4_compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127_0_0_5_compose.yaml.golden

Geth nodekey files are hex encoded (not just bytes).
Geth require --metrics flag to actually populate metrics.
task: none

ci(e2e): fix geth nodekey and metrics

---

relayer/app/state.go
relayer/app/state_internal_test.go
relayer/app/worker.go

Reset worker cursors on error. This mitigates the current bug where on-disk cursors are updated even if submissions fail.
task: none

feat(relayer): reset worker cursors on error

---

relayer/app/state_internal_test.go

Slight improve to test to ensure that not all cursors are deleted.
task: none

test(relayer): slight test improvement

---

e2e/vmcompose/provider.go

Upgrading by simply `docker compose up -d` sometimes fails due to race conditions with init container and on-disk locks.
Best do `down` before `up -d`
task: none

ci(e2e): harden upgrade command

---

e2e/app/avs.go
e2e/netman/manager.go
lib/contracts/addrs.go
lib/netconf/network.go
lib/netconf/static.go

Add network versions.
Ephermeral networks have random versions. Persistent networks have explicit verions. Portal deployment salts include network version.
task: none

feat(e2e): add network versions

---

.secrets.baseline
halo/app/privkey.go
halo/app/privval_internal_test.go
halo/app/start.go
halo/cmd/flags.go
halo/cmd/init.go
halo/cmd/testdata/TestCLIReference_run.golden
halo/cmd/testdata/TestRunCmd_defaults.golden
halo/cmd/testdata/TestRunCmd_flags.golden
halo/cmd/testdata/TestRunCmd_json_files.golden
halo/cmd/testdata/TestRunCmd_toml_files.golden
halo/cmd/testinput/input2/config/halo.json
halo/config/config.go
halo/config/config.toml.tmpl
halo/config/testdata/default_halo.toml
lib/k1util/k1util.go

Add support for eigenlayer-generated operator private keys. 
Notes:
- Keys should be stored in: `<home>/config/*.ecdsa.key.json`
- Password must be provided as a flag: `--eigenlayer-key-password`
- cometBFT key must be removed `config/priv_validator_key.json`
task: none

feat(halo/app): add support for eigenlayer generated operator keys

---

e2e/app/run.go
e2e/cmd/cmd.go

Allow upgrades of the explorer DB connection.
task: none

fix(e2e): allow explorer db connection upgrade

---

docs/site/docs/learn/testnet/testnet.md

adds a link to our blog post on how to delegate ETH to secure testnet.
task: none

feat(docs): add holesky delegation blog post

---

halo/app/prouter.go
halo/attest/keeper/cpayload.go
halo/attest/keeper/cpayload_internal_test.go
halo/attest/keeper/keeper.go
halo/attest/voter/voter.go

Only proposed votes in vote window. This solves an issue identified on staging where out-of-window votes were proposed which causes the chain to stall.
Block N:
- vote Window is: [6,10] (latest approved att=8)
- so a validator votes: v1:[6] which is in the vote window
- but when block N is processed, att 9 and 10 is approved.
Block N+1:
- vote Window is: [8,12] (latest approved att=10)
- but the block proposal now includes v1:[6] (vote from previous block)
- which is outside the vote window
- so the proposal gets rejected.
Solution:
- proposer should filter valid votes.
- Previously, it simply includes all votes it has, even though some might now be invalid.
task: none

fix(halo/attest): only propose valid votes

---

halo/attest/keeper/keeper.go
halo/attest/keeper/keeper_internal_test.go

Window compare has a bug resulting in inverted responses.
task: none

fix(halo/attest): flip window compare boolean

---

e2e/types/infra.go

Fix comparing e2e infra instances by only using IPs. Since ports are only defined for the one set, not the other.
task: none

ci(e2e): fix instance equal

---

.secrets.baseline
halo/attest/voter/voter.go

Pause voting if too far ahead (1000 blocks). No point in writing all those votes to disk. Also nice to log this.
task: none

feat(halo/voter): pause voting if too far ahead

---

halo/valsync/keeper/query.go
halo/valsync/keeper/query_internal_test.go

When querying validator set by id, we didn't populate activated height. This fixes it and adds a test.
task: none

fix(halo/valsync): populate activated height in query

---

lib/cchain/provider/abci.go
lib/cchain/provider/provider.go
lib/cchain/provider/provider_test.go
lib/cchain/provider/testdata/TestXBlock.golden
lib/cchain/provider/xblock.go
lib/cchain/provider/xblock_internal_test.go

Use the validator set created height to fetch the block header to use its timestamp.
Use height 1 instead of genesis since we can't fetch its timestamp.
task: none

fix(lib/cchain): fix consensus xblock timestamp

---

halo/app/cmtlog.go
halo/app/sdklog.go
lib/log/log.go

Fixes CosmosSDK and CometBFT logs `source` by skipping the custom wrapper loggers. Also simplify stacktrace logic by just taking inner most stack which fixes issue of cosmosSDK errors missing stack traces. 
task: none

fix(lib/log): fix cosmos log source and stack

---

e2e/app/create3.go
e2e/app/definition.go
e2e/app/proxyadmin.go
e2e/cmd/flags.go
e2e/netman/manager.go
e2e/types/testnet.go
e2e/types/testnet_test.go
lib/ethclient/ethbackend/backends.go

Add support for multiple `--rpc-overrides=chain_a=url1,url2`. This is spread round robin over all users.
task: none

ci(e2e): support multiple public chain rpcs

---

lib/cchain/provider/testdata/TestXBlock.golden
lib/cchain/provider/xblock.go

Removes the timestap field from consensus xblocks. It uses normal consensus cblock timestamp, but those blocks are pruned differently than xblocks data which causes conflicts.
XBlocks need their own timestamps. Until then, they will have zero timestamps.
task: none

fix(lib/cchain): revert timesstamp regression

---

.secrets.baseline
e2e/app/setup.go
e2e/types/testnet.go

Fix flapping e2e test that used validator04 for relayer halo url which is only started at the end of the e2e test.
Instead, use a random halo address only from nodes that are started immediately.
task: none

ci(e2e): use random started halo address

---

lib/contracts/proxyadmin/deploy.go

Use legacy txns for create3 proxy admin deployment. 
task: none

chore(lib/contracts): use legacy tx for create3 proxy admin deployments

---

lib/contracts/proxyadmin/deploy.go

Do not force legacy tx in proxy admin create3 deployments.
Trying locally shows that the deployment works as previously written. 
task: none

chore(lib/contracts): remove force legacy tx in proxy admin deployment

---

lib/netconf/static.go

Add op and arb sepolia portal addresses and deploy heights.
task: none

chore(lib/netconf): add op and arb sepolia portals

---

.secrets.baseline
e2e/app/avs.go
e2e/app/definition.go
e2e/app/eoa/eoa.go
e2e/app/fund.go
e2e/app/key/key.go
e2e/app/key/key_internal_test.go
e2e/app/key/key_test.go
e2e/app/key/upload.go
e2e/app/monitor.go
e2e/app/run.go
e2e/app/setup.go
e2e/app/test.go
e2e/app/valupdates.go
e2e/cmd/cmd.go
e2e/cmd/flags.go
e2e/netman/manager.go
e2e/types/chain.go
e2e/types/testnet.go
halo/app/start_test.go
halo/cmd/init.go
halo/genutil/evm/evm.go
lib/netconf/netconf.go
lib/netconf/static.go
monitor/app/app.go
monitor/app/avssync.go
monitor/app/config.go
monitor/app/config.toml.tpl
monitor/app/testdata/default_monitor.toml
monitor/cmd/flags.go

Introduces GCP based EOA keys:
- Add a eoa key to monitor service
- Use it to call `omniAVM.SyncToOmni` once per day.
- Remove relayer-key flag from e2e app and from netman.
- Move it and monitor key to `eoa` package.
- Use GCP based keys (or anvil key for devnet)
- Add eoa keys to devnet and staging genesis.
- Fund eoa keys for anvil.
- Remove deployInfo froms Deploy results
- Move it to app.Definition, where it uses deterministic netman and avs contract addrs.
task: none

ci(e2e): refactor eoa keys

---

e2e/app/eoa/eoa.go
lib/txmgr/txmgr.go

Testnet EOAs have been manually funded. Use them.
task: none

ci(e2e): use proper testnet relayer key

---

.secrets.baseline
e2e/app/run.go
e2e/cmd/cmd.go
e2e/cmd/flags.go
e2e/docker/docker.go
e2e/types/infra.go
e2e/vmcompose/provider.go

Improve upgrade command:
- Add support for "partial upgrades" where only VMs with matching serviceRexexp is upgraded.
- Upgrade VMs in parallel.
- Also upgrade keys
task: none

ci(e2e): improve upgrade command

---

e2e/app/agent/prometheus.yml.tmpl
e2e/app/run.go
e2e/vmcompose/provider.go
lib/netconf/static.go

Copy files to correct path on remove VM. Only copy applicable services. Wire agent secrets.
task: none

ci(e2e): fix upgrade copied files

---

e2e/types/chain.go

more accurate block times for op-sep and arb-sep
task: none

chore(e2e): update rollup block times

---

e2e/docker/compose.yaml.tmpl
e2e/docker/docker.go
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/manifests/devnet2.toml

With the flag removed we'd create the container but not start it, the check to start it also should be `network.IsEphemeral`
task: none

chore(explorer/db): removing flag for explorer db

---

.secrets.baseline
e2e/app/run.go
e2e/netman/pingpong/pingpong.go
lib/ethclient/ethbackend/backend.go

Increase the number of parallel pingpongs to test multiple xmsgs per block.
task: none

ci(e2e): increase parallel pingpongs

---

.golangci.yml
halo/attest/keeper/keeper.go
halo/attest/keeper/keeper_test.go
halo/attest/keeper/metrics.go
halo/attest/voter/voter.go
lib/cchain/provider/abci.go
lib/ethclient/engineclient.go
lib/ethclient/ethclient.go

Add metrics to attest keeper to debug slow votes:
- votes extended per block (by validators) (per source chain)
- votes proposed per block
- db method latencies
task: none

chore(halo/attest): add vote and latency metrics

---

.secrets.baseline
e2e/app/agent/prometheus.go
e2e/app/agent/prometheus_internal_test.go
e2e/app/agent/testdata/TestPromGen_manifest1_gen.golden
e2e/app/agent/testdata/TestPromGen_manifest1_update.golden
e2e/app/agent/testdata/TestPromGen_manifest2_gen.golden
e2e/app/agent/testdata/TestPromGen_manifest2_update.golden
e2e/app/agent/testdata/TestPromGen_manifest3_gen.golden
e2e/app/agent/testdata/TestPromGen_manifest3_update.golden
e2e/app/agent/testdata/TestPromGen_manifest4_gen.golden
e2e/app/agent/testdata/TestPromGen_manifest4_update.golden
e2e/vmcompose/provider.go
explorer/graphql/app/app.go
explorer/graphql/app/config.go
explorer/graphql/cmd/cmd.go
explorer/indexer/app/app.go
explorer/indexer/app/config.go
explorer/indexer/cmd/cmd.go

Add prometheus metrics API to explorer-indexer/graphql. Also configure them with agent.
task: none

ci(e2e): add explorer metrics

---

halo/attest/voter/voter.go

Increases voter disk buffer from 1k to 10k. 1k isn't much, since we can include up to 256 votes per block, so 10k allows buffering 40 blocks which is better than 4.
task: none

chore(halo/voter): increase disk buffer

---

halo/attest/voter/metrics.go
halo/attest/voter/voter.go

Adds a metric for "number of committed/proposed votes" per block per validator. This will help identify if votes are not actually moved from "available" to "proposed" and "proposed" to "committed".
task: none

chore(halo/voter): add proposed metric per block

---

lib/txmgr/metrics.go
relayer/app/creator.go
relayer/app/creator_internal_test.go
relayer/app/metrics.go
relayer/app/sender.go

Implement a simple model for estimating submission gas. Use it to split streamUpdates into multiple submissions.
task: none

feat(relayer): split submissions by estimating gas model

---

lib/ethclient/ethbackend/wait.go

Fixes [race](https://github.com/omni-network/omni/actions/runs/8661404913/job/23751478704) in ethbackend due to concurrent writes.
task: none

ci(e2e): fix race in ethbackend

---

contracts/script/StrategyParams.sol

Use internal for library functions.
task: none

chore(contracts): use internal for library functions

---

.secrets.baseline
halo/attest/voter/voter.go
halo/attest/voter/voter_internal_test.go
halo/attest/voter/voter_test.go
halo/comet/comet.go

Fixes two issues in vote:
- TrimBehind didn't trim proposed votes. It should since we shouldn't vote for them again.
- TrimBehind interfered with the "ensure sequential votes" logic resulting in false positives. Rather keep explicit "latest vote" in state.
task: none

fix(halo/voter): fix trimming issues

---

.secrets.baseline
halo/app/app.go
halo/attest/testutil/mock_interfaces.go
halo/attest/types/interface.go
halo/attest/voter/voter.go
halo/attest/voter/voter_internal_test.go
halo/attest/voter/voter_test.go
halo/valsync/keeper/common_internal_test.go
halo/valsync/keeper/keeper.go
halo/valsync/keeper/query.go
halo/valsync/keeper/query_internal_test.go
halo/valsync/module/module.go
halo/valsync/testutil/expected_interfaces.go
halo/valsync/testutil/mock_interfaces.go
halo/valsync/types/interfaces.go
lib/k1util/k1util.go

Removes the `windowCompare` and `IsValidator` queries from `voter.Deps` by avoiding queries all-together:
- Use `voter.TrimBehind` to calculate `isInWindow`
- Add a `UpdateValidators` function that is called by `valsync` keeper.
This remove all the queries completely so should increases vote speed significantly.
task: none

chore(halo/voter): remove halo queries

---

e2e/manifests/ci.toml
halo/evmengine/keeper/abci.go
halo/evmengine/keeper/abci_internal_test.go
halo/evmengine/keeper/keeper_internal_test.go
halo/evmengine/keeper/msg_server.go
halo/evmengine/keeper/msg_server_internal_test.go
halo/evmengine/keeper/proposal_server.go
halo/evmengine/keeper/proposal_server_internal_test.go

Handle evm syncing in evmengine.
When verifying proposals (ProcessProposal)
- If payload invalid, reject proposal
- if syncing, wait until not syncing
- Other errors, retry 
When finalizing proposal (FinaliseBlock)
- if payload invalid, error
- if syncing, wait until not syncing
- Other errors, retry
task: none

fix(halo/evmengine): handle evm syncing

---

cli/cmd/devnet.go
e2e/app/valupdates.go
e2e/netman/helpers.go
e2e/netman/pingpong/pingpong.go
lib/ethclient/ethclient.go
lib/ethclient/ethclient_gen.go
lib/ethclient/genwrap/genwrap.go
lib/ethclient/mock/mock_interfaces.go
monitor/account/monitor.go
monitor/loadgen/stake.go
relayer/app/monitor.go

Adds validator balance to logs when funding validators. 
Also extract common `EtherBalanceAt` to reduce duplication.
task: none

ci(e2e): debug validator insufficient balance

---

e2e/app/eoa/eoa.go
e2e/app/wait.go
e2e/netman/pingpong/pingpong.go
halo/cmd/cometconfig.go
halo/cmd/testdata/TestRunCmd_defaults.golden
halo/cmd/testdata/TestRunCmd_flags.golden
halo/cmd/testdata/TestRunCmd_json_files.golden
halo/cmd/testdata/TestRunCmd_toml_files.golden

ci.toml now runs 4 omni_evms instead of 1. This causes general slowdown on github runners causing timeouts so extend it.
Also:
- Small optimisation wrt eoa role verify
- Tune statesync to be more robust
task: none

ci(e2e): extend e2e timeouts

---

cli/cmd/devnet.go

Adds `omni devnet clean` command that clean dirs and files generated by the `start` command
task: none

feat(cli): add devnet clean command

---

explorer/indexer/app/db.go
explorer/indexer/app/db_test.go

Was inserting empty data from the wrong block reference.
task: none

fix(explorer/indexer): msg insert fix

---

halo/app/app_config.go
halo/evmengine/keeper/proposal_server.go
halo/evmengine/keeper/proposal_server_internal_test.go

Decrease attestation trim lag from 14 days to 1 day. This addresses our HUGE DB problem and should decrease the size by 10x.
task: none

chore(halo/attest): decrease genesis trim lag

---

halo/app/app_config.go
halo/app/start.go

Decrease the `default` prune option from 5 days to 1 day. This should also decrease disk usage by 5x. Normal users of halo don't need historical state in general. So 1 day should be fine as default.
task: none

chore(halo): decrease default prune options

---

.secrets.baseline
e2e/app/definition.go
e2e/app/setup.go
e2e/types/testnet.go
halo/app/start.go
halo/app/start_test.go
halo/cmd/cmd.go
halo/cmd/flags.go
halo/cmd/testdata/TestCLIReference_run.golden
halo/cmd/testdata/TestRunCmd_defaults.golden
halo/cmd/testdata/TestRunCmd_flags.golden
halo/cmd/testdata/TestRunCmd_json_files.golden
halo/cmd/testdata/TestRunCmd_toml_files.golden
halo/config/config.go
halo/config/config.toml.tmpl
halo/config/testdata/default_halo.toml
lib/netconf/netconf.go
lib/netconf/testdata/TestSaveLoad.golden

First step in refactor netconf to use onchain registry.
Remove `Chain.AuthRPC` from netconf and move to a flag `--engine-endpoint` on halo.
task: none

refactor(halo): move authrpc field from netconf to halo flag

---

e2e/app/definition.go

Use a proposer `BroadcastEVM` when selecting EVM RPCs for external networks. Otherwise, validator04 is sometimes chosen which is down at the start of E2E and so cannot mine transactions.
task: none

ci(e2e): fix flapping e2e test

---

e2e/app/run.go

Prevent accidental deploying of protected networks:`testnet`, `mainnet`.
task: none

ci(e2e): dont deploy protected networks

---

e2e/vmcompose/data.go

Fix `vmcompose` evm regex to match `mock_l1`. 
task: none

ci(e2e): fix vmcompose evm regex

---

lib/stream/stream.go
relayer/app/worker.go

EVM nodes sometimes lag a few blocks, even under normal circumstances. Retry should retry a little when the block isn't finalised yet as this is expected behaviour.
task: none

chore(relayer): retry fetching xblock if not finalised

---

.secrets.baseline
e2e/app/definition.go
e2e/app/key/key.go
e2e/app/key/key_test.go
e2e/app/valupdates.go
e2e/manifests/staging.toml
e2e/test/app_test.go
e2e/test/attestations_test.go
e2e/test/block_test.go
e2e/test/e2e_test.go
e2e/vmcompose/testdata/TestSetup_127_0_0_3_compose.yaml.golden
halo/app/lazyvoter.go
halo/attest/keeper/keeper.go
halo/attest/voter/voter.go
lib/netconf/provider.go
lib/xchain/provider/provider.go

Fixes a few issues introduced by the netconf refactor:
- omni_consensus chain validator sets start at 1, not 0, so set `DeployHeight=1`
- Add e2e tests for validator updates (had to make devnet validator keys deterministic)
- Replace `mock_l1` on staging with `slow_l1`
- Also remove custom workarounds for slow staging chains since we now have explicit slow chains.
Also fix two bugs in attest keeper:
- Boolean flip while ensuring strict-sequential approvals.
- Don't delete anything after latest approve attestation since this could cause gaps once catching up.
task: none

fix(halo): fixes few post-refactor bugs

---

.secrets.baseline
cli/cmd/devnet.go
e2e/app/cleanup.go
e2e/app/run.go
e2e/app/setup.go
e2e/cmd/cmd.go

Only stop and delete existing network at the last possible moment before re-deploying the new network.
This decreases downtime incase the deploy fails. 
task: none

ci(e2e): clean network as late as possible

---

explorer/indexer/app/app.go
monitor/app/app.go
relayer/app/app.go

Starts serving prometheus metrics immediately on startup. Previously, we only did this after the network was loaded from portal registry which takes a long a time and results in `App Down` alerts.
task: none

fix(monitor): start app monitoring first

---

lib/evmchain/evmchain.go
lib/evmchain/evmchain_internal_test.go

Fixes typo in evmchain config for anvil chains.
task: none

ci(e2e): fix anvil chain id typo

---

e2e/vmcompose/data.go

Less regex to identify anvil service.
task: none

ci(e2e): harden port selector

---

cli/cmd/devnet.go
lib/netconf/provider.go

Deprecate `CheckOnChain` and use noop logger for CLI call
task: none

chore(cli/lib): revert to await on chain function use

---

halo/cmd/flags.go
halo/cmd/init.go
halo/cmd/testdata/TestCLIReference_init.golden

Adds a `--trusted-sync` flag to `halo init` which sets the trusted state-sync fields by querying the omni consensus RPC.
task: none

feat(halo/cmd): support trusted state sync init

---

halo/app/app.go
halo/app/start.go
halo/attest/keeper/common_test.go
halo/attest/keeper/keeper.go
halo/attest/module/module.go
halo/evmengine/keeper/abci_internal_test.go
halo/evmengine/keeper/keeper.go
halo/evmengine/keeper/keeper_internal_test.go
halo/evmengine/keeper/msg_server_internal_test.go
halo/evmengine/keeper/proposal_server_internal_test.go
halo/evmengine/module/module.go

Fixes a nil pointer during halo startup by wiring voter using depject.
task: none

fix(halo/app): fix voter nil pointer

---

explorer/graphql/app/schema.graphql
explorer/graphql/mockresolver/resolver.go

* add a `revertReason` field to receipts
* update mock data to return a non-empty revert reason if `xmsg.status == "failed"`
task: https://app.asana.com/0/1206208509925075/1207157766307979/f

feat(explorer/graphql): add receipt revert reason

---

lib/contracts/feeoraclev1/feeparams.go
monitor/xfeemngr/oracle.go
monitor/xfeemngr/xfeemngr.go
monitor/xfeemngr/xfeemngr_internal_test.go

Keep on chain gas prices above live gas prices.
By introducing an on chain "sheild", set to the same pct as thegas price buffer threshold,
we ensure that on chain gas prices are always at least as high as live gas prices.
With this implementation, on chain gas prices may be up to 20% greater than, but never less than, live gas prices.
As opposed to before, in which on chain gas prices could up to 10% greater than or 10% less than live gas prices.
task: https://app.asana.com/0/1206208509925075/1207250196592177

feat(monitor/xfeemngr): keep on-chain gas prices above live gas prices

---

.secrets.baseline
cli/cmd/cmd.go
cli/cmd/devnet.go
cli/cmd/flags.go
cli/cmd/operator.go
e2e/app/geth/config.go
e2e/app/geth/config_internal_test.go
lib/netconf/netconf_test.go

Adds the first part of the `omni operator init-nodes` command. So far it just inits geth, halo is next.
task: none

chore(cli): add operator init-nodes

---

e2e/app/definition.go
e2e/app/perturb.go
e2e/app/run.go
e2e/manifests/ci.toml
e2e/types/manifest.go
e2e/types/testnet.go
halo/evmengine/keeper/abci.go
halo/evmengine/keeper/abci_internal_test.go
halo/evmengine/keeper/helpers.go
halo/evmengine/keeper/keeper_internal_test.go
halo/evmengine/keeper/msg_server_internal_test.go
halo/evmengine/keeper/proposal_server.go
halo/evmengine/keeper/proposal_server_internal_test.go
lib/ethclient/enginemock.go

Add `retryForever` when calling engine API inside consensus. 
task: none

feat(halo/evmengine): harden engine api

---

monitor/xfeemngr/xfeemngr_internal_test.go

Disable flapping test temporarily. This needs to be properly fixed.
task: none

test(xfeemgr): disable flapping test

---

monitor/xfeemngr/oracle.go
monitor/xfeemngr/xfeemngr_internal_test.go

Fix flapping xfeemnger tests
- decrease epsilion in float comparisons, warn if conv rate is unrepresentable on chain
task: none

fix(monitor/xfeemngr): fix flapping tests

---

explorer/graphql/app/schema.graphql
explorer/graphql/mockresolver/resolver.go

Fix the mock data returned by the GraphQL API to return timestamps in the past. Otherwise the "TimeAgo" logic doesn't work in the Explorer and breaks the UI. 
task: none

fix(explorer/graphql): use mock timestamps in the past

---

e2e/docker/compose.yaml.tmpl
e2e/docker/testdata/TestComposeTemplate_commit_no_explorer.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/docker/testdata/TestComposeTemplate_main_explorer.golden
e2e/vmcompose/testdata/TestSetup_127_0_0_3_compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127_0_0_6_compose.yaml.golden

introduces a temporary fix to the docker compose file for images unavailable for apple chip machines
task: none

fix(e2e): tmp docker compose fix for apple chip machines

---

halo/config/testdata/default_halo.toml
halo/genutil/testdata/TestMakeGenesis.golden
lib/buildinfo/buildinfo.go
monitor/app/testdata/default_monitor.toml
relayer/app/testdata/default_relayer.toml

bump buildinfo version to include docker compose platform fix, mainly for CLI
task: none

chore(lib/buildinfo): bump version

---

explorer/graphql/app/schema.graphql
explorer/graphql/mockresolver/resolver.go

Return entire chain entity instead of just chain ID for each XMsg, XRceipt and XBlock to make it simpler on the front end.
task: none

feat(explorer/graphql): add chain entity instead of chainID

---

halo/app/abci.go
halo/app/app.go
halo/app/rollback.go
halo/app/sdklog.go
halo/app/start.go
halo/evmengine/keeper/abci.go
halo/evmengine/keeper/abci_internal_test.go
halo/evmengine/keeper/keeper.go
halo/evmengine/keeper/keeper_internal_test.go
halo/evmengine/keeper/msg_server.go
halo/evmengine/keeper/msg_server_internal_test.go
halo/evmengine/keeper/proposal_server_internal_test.go
lib/ethclient/enginemock.go
lib/ethclient/ethclient.go
lib/ethclient/ethclient_gen.go
lib/ethclient/genwrap/genwrap.go
lib/ethclient/mock/mock_interfaces.go

Sets cometBFT `AppHash` as the EVM `BeaconBlockRoot` when building EVM blocks.
This required moving optimistic building from `msg_server` to it's own custom hook called after `abci.finaliseblock` so we have access to the final appHash.
Also includes a PoC rollback function, this will be completed and tested in following PR.
task: none

feat(halo/evmengine): set apphash as beaconblockroot

---

e2e/app/avs.go
e2e/manifests/devnet0.toml
e2e/netman/manager.go
lib/evmchain/evmchain.go
lib/log/logger.go
lib/log/testdata/TestSimpleLogs_cli.golden

adds `mock_op` and `mock_arb` to `devnet0` and makes cli logs info-only, as well as adding a log line when a portal is private-deployed
task: none

feat(cli): rollups in devnet

---

e2e/test/geth_test.go

Adds a e2e test case ensuring beacon block root is non-empty.
task: none

test(e2e): add non-empty beacno root check

---

halo/attest/voter/voter_test.go
lib/xchain/provider.go
lib/xchain/provider/fetch.go
lib/xchain/provider/mock.go
relayer/app/cursors_internal_test.go
relayer/app/monitor.go
relayer/app/worker_internal_test.go

Align emit cursor metrics with finalisation strategy so they don't artificially show lag.
task: none

chore(relayer/monitor): align emit cursor with finalisation strat

---

.secrets.baseline
halo/attest/voter/metrics.go
halo/attest/voter/voter.go
relayer/app/metrics.go
relayer/app/monitor.go

Refactor north star lag metrics to use a single stream name instead of src and dst chain names.
This makes grafana queries much easier and allows the table view to work.
task: none

chore(relayer): refactor proper stream metrics

---

halo/attest/voter/voter_test.go
lib/xchain/provider.go
lib/xchain/provider/fetch.go
lib/xchain/provider/mock.go
relayer/app/cursors_internal_test.go
relayer/app/monitor.go
relayer/app/worker_internal_test.go

Fix attested stream offsets by querying emitted xmsg offsets on-chain instead of using xmsgs from the attested block since it doesn't contain xmsgs from all streams.
task: none

chore(relayer): query onchain attested stream offsets

---

lib/contracts/feeoraclev1/feeparams.go

Use default 1Gwei gas price if fetching fails which it will always when deploying public portals since private chains are not running yet.
task: none

ci(e2e): use default gas price if fetching fails

---

explorer/graphql/data/message_provider.go

Fixes an edge cases where the receipt doesn't exist yet and we try to view an XMsg.
task: none

fix(explorer/graphql): allow for null receipt properties

---

halo/app/app.go
halo/app/rollback.go
halo/app/start.go
halo/cmd/cmd.go
halo/cmd/cmd_internal_test.go
halo/cmd/flags.go
halo/cmd/testdata/TestCLIReference_halo.golden
halo/cmd/testdata/TestCLIReference_rollback.golden
halo/valsync/keeper/common_internal_test.go
halo/valsync/keeper/keeper.go
halo/valsync/module/module.go

Remove `--rollback-evm` flag and logic to attempt EVM rollback as this isn't possible without recreating the block which isn't possible without slashing risk.
Also fix a panic `valsync` module by providing voter in constructor.
task: none

refactor(halo): remove evm from rollback

---

.goreleaser.yaml
Makefile
e2e/docker/compose.yaml.tmpl
e2e/docker/testdata/TestComposeTemplate_commit_no_explorer.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/docker/testdata/TestComposeTemplate_main_explorer.golden
e2e/forkproxy/Dockerfile
e2e/forkproxy/app/app.go
e2e/forkproxy/cmd/cmd.go
e2e/forkproxy/main.go
e2e/vmcompose/testdata/TestSetup_127-0-0-3-compose.yaml.golden
scripts/build_docker.sh

Add the forkproxy binary (and docker image already manually upload to dockerhub).
Forkproxy:
- It wraps anvil an internal anvil instance
- Proxying requests to that instance
TODO:
- Add support for forking the anvil instance if configured.
- Proxy requests to forked instance. 
task: none

ci(e2e): implement forkproxy

---

e2e/forkproxy/app/app.go
e2e/forkproxy/cmd/cmd.go

Add support for constant forking of underlying anvil in forkproxy if `--fork=true`.
It waits a bit, then starts a fork of the current anvil a few blocks deep. Rinse-and-repeat.
task: none

ci(e2e): support forking proxy

---

.goreleaser.yaml

use tags instead of version for goreleaser, as version might trim prefix "v" (https://goreleaser.com/customization/templates/)
task: https://app.asana.com/0/1206208509925075/1207372351528377/f

fix(goreleaser): use tags instead of version in ldflags

---

e2e/forkproxy/app/app.go
relayer/app/monitor.go

Fixes incorrect logging in relayer.
Also, fix forkproxy startup issue.
task: none

chore(relayer): logging improvements

---

lib/evmchain/evmchain.go

makes devnet0 anvil node have non sub second block time, which would lead to errors, fixes cli devnet start command
task: none

fix(devnet0): non sub second block times for anvil nodes

---

e2e/app/monitor.go
explorer/indexer/app/app.go
halo/attest/voter/voter.go
halo/attest/voter/voter_test.go
lib/netconf/netconf.go
lib/xchain/provider.go
lib/xchain/provider/fetch.go
lib/xchain/provider/mock.go
lib/xchain/provider/mock_internal_test.go
lib/xchain/provider/provider.go
lib/xchain/provider/provider_internal_test.go
lib/xchain/provider/provider_test.go
lib/xchain/types.go
relayer/app/cursors_internal_test.go
relayer/app/worker.go
relayer/app/worker_internal_test.go

Add support for `ConfLevel` qhen streaming/querying xblocks from xprovider.
task: none

refactor(lib/xchain): support conf level when querying xprovider

---

e2e/forkproxy/app/app.go

Improve error logging to debug "start anvil timeouts".
task: none

chore(e2e/forkproxy): improve logging

---

e2e/app/run.go
halo/evmengine/keeper/helpers.go
lib/cchain/provider/abci.go
lib/xchain/provider/provider.go
relayer/app/sender.go

Harden e2e tests:
- decrease waiting for supported chain (make it faster)
- prevent blocking in evmengine retry forever
- limit cprovider backoffs to 1s (consensus block time) (previous 2min could cause timeouts)
- limit xprovider backoffs to 10s (good average between all evm finalizations)
- Add `block_offset` to relayer logs
task: none

ci(e2e): harden e2e tests

---

lib/netconf/netconf.go
lib/xchain/types.go
relayer/app/cursors.go
relayer/app/cursors_internal_test.go
relayer/app/state.go
relayer/app/state_internal_test.go
relayer/app/worker.go

Refactor relayer to support multiple attestation streams:
- Subscribe to attestations per `ChainVer`, track state per DestChain-ChainVer pair.
- Implement `MsgOffsetFilter` to pick the first MsgOffset from either `Fuzzy` or `Finalized` chains.
task: none

chore(relayer): merge finalized and latest streams

---

.goreleaser.yaml
e2e/anvilproxy/app/proxy.go
e2e/app/monitor.go
halo/app/start.go
halo/app/start_test.go
lib/cchain/provider/abci.go
lib/cchain/provider/provider.go
lib/netconf/provider.go
relayer/app/app.go
relayer/app/sender.go
relayer/app/worker.go
relayer/app/worker_internal_test.go

Do not attempt to submit fuzzy attestations that do not match the fetched XBlock. Just skip since they will be submitted by finalized attestations.
Also improve logging and fix snapshot github action.
task: none

refactor(relayer): skip mismatching fuzzy attestations

---

docs/site/docs/tools/cli/cli.md

related to #1151 CLI devnet will use commit tag when fetching docker images
task: none

docs(cli): use latest tag with src install

---

e2e/anvilproxy/app/app.go
e2e/anvilproxy/app/proxy.go
e2e/anvilproxy/app/xmsg.go
e2e/app/perturb.go
e2e/manifests/fuzzyhead.toml
e2e/types/manifest.go

Support explicit fuzy perturbations instead of coming all fuzzy head types into a single pertubation.
Also add two more fuzzy perturbations.
task: none

ci(e2e): support explicit fuzzy perturbations

---

e2e/types/chain.go
lib/netconf/provider.go
lib/xchain/provider/fetch.go

Fixes broken e2e tests by configuring all evms with both shards: latest and finalized.
Also error is xprovider detects unexpected shardID.
Also fix receipt shardID.
task: none

fix(netconf): support both shards on all evms

---

halo/attest/voter/voter_test.go
lib/xchain/merkle.go
lib/xchain/provider.go
lib/xchain/provider/fetch.go
lib/xchain/provider/mock.go
lib/xchain/types.go
relayer/app/cursors.go
relayer/app/cursors_internal_test.go
relayer/app/worker.go
relayer/app/worker_internal_test.go

Ensure we submit incrementing valSetID per stream. This is enforced by the portal contract, so relayer should not submit fuzzy attestations from pervious validator sets. It should stick with finalized until the new validator set attests to the fuzzy shards.
task: none

chore(relayer): ensure increnting valsetid per shard

---

relayer/app/metrics.go
relayer/app/monitor.go

Continue fetching offsets for all streams even though some failed. This mitigates startup issue on staging with op_sepolia having very slow finalization which prevents metrics from being initialised for latest as well.
task: none

chore(relayer): harden offset metrics

---

e2e/app/run.go
e2e/netman/pingpong/pingpong.go

Most most ping pongs to use finalized conf level, only 1 per edge to use latest.
This ensures we test both latest, while also ensuring ping pongs last as long as possible using minimal gas.
task: none

ci(e2e): move most ping pongs to finalized

---

Makefile

deprecate secrets-baseline in favour of native github secrets scanning. fewer tools ❤️
task: none

chore(*): remove secrets baseline

---

halo/app/app.go
halo/app/start.go
halo/attest/keeper/cpayload.go
halo/attest/keeper/cpayload_internal_test.go
halo/attest/keeper/keeper.go
halo/registry/keeper/cache.go
halo/registry/keeper/keeper.go
halo/registry/keeper/logeventproc.go
halo/registry/types/interface.go
lib/ethclient/enginemock.go
lib/netconf/netconf.go
lib/netconf/static.go

Add `PortalProvider` interface to `attest` module and gate votes to supported portals only.
Implement it as a cache in `registry` module to mitigate DB lookups.
task: none

feat(halo/attest): gate votes by supported portals

---

lib/netconf/network.go
lib/xchain/connect/connect.go

Adds `xconnect.New` function that returns a `xconnect.Connector` that provides easy connection for off-chain local-dev programs and apps that want to query or interact with the omni network and supported chains. 
This is aimed at scripting and debugging and querying an existing omni network.
task: none

ci(tutil): add xconnector

---

e2e/app/definition.go
e2e/types/chain.go
e2e/types/testnet.go
halo/attest/voter/voter.go
lib/netconf/netconf.go
lib/netconf/network.go
lib/netconf/provider.go
lib/netconf/static.go
lib/xchain/connect/connect.go
lib/xchain/provider/fetch.go
lib/xchain/provider/mock.go
lib/xchain/provider/mock_internal_test.go
lib/xchain/provider/provider.go
lib/xchain/provider/provider_test.go
lib/xchain/types.go
relayer/app/worker.go

Introduce the `AttestInterval` portal registry and netconf chain field that defines the constant period for attestations even if blocks are empty.
This ensures the "attest head" of quiet chains do not get too stale which requires historical queries.
task: none

feat(xchain): attest at constant interval even if empty

---

halo/app/app.go
halo/app/rollback.go
halo/app/start.go
octane/evmengine/keeper/abci.go
octane/evmengine/keeper/abci_internal_test.go
octane/evmengine/keeper/keeper.go
octane/evmengine/keeper/keeper_internal_test.go
octane/evmengine/keeper/msg_server_internal_test.go
octane/evmengine/keeper/proposal_server.go
octane/evmengine/keeper/proposal_server_internal_test.go
octane/evmengine/module/module.go
octane/evmengine/types/types.go

Adds support for a custom `FeeRecipientProvider` to Octane. Halo configures it to burn all execution fees. This is enforced by the protocol.
task: none

feat(octane): support custom fee recipient

---

.github/workflows/release-official.yml

fixes parsing error found in https://github.com/omni-network/omni/actions/runs/9501746339/job/26188033774

fix(ci): use ref name in tag releases

---

e2e/app/setup.go
halo/app/cmtlog.go
monitor/loadgen/loadgen.go

Enable cometBFT debug logs in CI. Decrease more very noisy cometBFT debug logs. Generate more validator updates in CI. This is aimed at identifying the root cause of sporadic chain stalls in CI.
task: none

ci(e2e): improve debug logging

---

halo/genutil/testdata/TestMakeGenesis.golden
lib/netconf/static.go

Increase maximum validators per network to 30 as we are implementing a whitelist in the omni staking contract.
task: none

chore(halo): bump max validators to 30

---

lib/ethclient/enginemock.go
octane/evmengine/keeper/abci.go
octane/evmengine/keeper/abci_internal_test.go
octane/evmengine/keeper/keeper.go
octane/evmengine/keeper/msg_server.go
octane/evmengine/keeper/msg_server_internal_test.go
octane/evmengine/keeper/proposal_server.go
octane/evmengine/keeper/proposal_server_internal_test.go

Add additional execution payload validation:
- `ParentHash` must match latest block.
- `Timestamp` must match consensus block or latest execution+1.
- `Withdrawals` must be empty.
- `FeeRecipient` must be expected.
task: none

fix(octane/emvengine): more payload verifications

---

cli/cmd/develop.go

removes depth from git clone command, allowing template repo to be updated without breaking the scaffolding command fixing [broken pipelines](https://github.com/omni-network/omni/actions/runs/9571036989)
also updates the template to the newest commit
task: none

fix(cli): remove depth from git clone cmd

---

.golangci.yml
e2e/app/portalregistry.go
e2e/app/run.go
e2e/app/setup.go
e2e/test/e2e_test.go
halo/registry/keeper/helper.go
halo/registry/keeper/keeper.go
halo/registry/keeper/logeventproc.go
halo/registry/keeper/logeventproc_internal_test.go
lib/fireblocks/client_test.go
lib/tracer/trace_test.go
lib/tutil/random.go
relayer/app/creator_test.go

Add unit tests and more e2e tests to halo registry. 
Fix some issues:
- Ensure emit portal messages are created for all networks
- Error if duplicate portals are added.
- Add basic validation
task: none

fix(halo/registry): add tests and fix issues

---

docs/site/docs/develop/quickstart/quickstart.md

removes using the bash script for deployment and makes following the tutorial simpler by just using foundry commands on shell
task: none

docs(quickstart): simplify command deps

---

docs/site/docs/develop/quickstart/quickstart.md

add missing env vars required for foundry deployment scripts
task: none

docs(quickstart): add deployment env vars

---

lib/netconf/provider.go
relayer/app/app.go
relayer/app/creator.go
relayer/app/sender.go

Fix issue introduces by `adding mock portals` that resulted in `out-of-gas` submission reverted issues of large `setNetwork` consensus chain messages by increasing gas limit for ephemeral chains and using proper gas estimation for protected chains. 
Also prevent ephemeral chains from loading mock portals into netconf. 
task: none

fix(halo/relayer): increase gas limit of consensus chain submissions

---

halo/attest/keeper/common_test.go
halo/attest/keeper/keeper.go
halo/attest/keeper/keeper_test.go

- If we find something in the cache, we should return true.
- don't delete anything if we don't have our first approved attestation
task: none

fix(attest): two fixes to deletion logic

---

e2e/README.md

Fix the example command, out of date since #160
task: none

fix(docs): correct old path in example cmd

---

lib/txmgr/txmgr.go

Use geth [ErrIntrinsicGas](https://github.com/ethereum/go-ethereum/blob/master/core/error.go#L81) instead of defining it again.
task: none

fix(lib/netconf): use geth error

---

lib/contracts/address.go
lib/contracts/avs/deploy.go
lib/netconf/netconf_test.go

Use hard-coded AVS contract addr to prevent CI errors.
task: none

fix(lib/contracts): fix avs deploy error

---

e2e/netman/pingpong/pingpong.go

Only allow the latest shard in the pingping XDapp if it is supported.
task: none

fix(e2e/pp): check if latest shard is enabled for pp

---

e2e/netman/pingpong/pingpong.go
lib/netconf/static.go

* Bump network version
* Remove well-known portal contract address from the previous network version
* Add timeout for StartAllEdges (ping pong test app)
* Improve logging
task: none

fix(lib/netconf): fix-omega-deploy

---

lib/fireblocks/sign.go
lib/netconf/static.go
lib/txmgr/txmgr.go

This will likely get a little noisy, so we'll probably drop it after some debugging. But it's fine to merge for now.
task: none

feat(txmgr): additional logic to debug omega

---

e2e/test/attestations_test.go
halo/attest/keeper/keeper.go
halo/attest/keeper/query.go
halo/attest/types/query.pb.go
halo/attest/types/query.proto
lib/cchain/provider/abci.go
lib/cchain/provider/metrics.go
lib/cchain/provider/provider.go

- adds new `EarliestAttestationInState` method to Attest keeper's query interface
- implements historical walkback for the cchain provider's `fetch` function
- in the event that we don't find the requested attestation offset, we exponentially backoff going back in time
- we stop when we find an earlier attestation, and then perform binary search (if necessary) to find the requested attestation offset
- NOTE: I've confirmed that all our tests pass with this change AND the keeper's [trimLag](https://github.com/omni-network/omni/blob/main/halo/attest/keeper/keeper.go#L51) set to 1
task: https://app.asana.com/0/1206208509925075/1207131279471036

feat(cprovider): query historical state for attestations

---

e2e/app/definition.go
lib/contracts/feeoraclev1/feeparams.go
lib/netconf/provider.go
octane/evmengine/keeper/keeper.go

Avoid division by zero.
This fixes OMP-25 as per sigma prime audit.
task: none

fix(octane/keeper): avoid division by zero

---

lib/merkle/msg_test.go
lib/xchain/merkle.go

Fixes linear search of large merkle trees by populating a reverse lookup table in constructor.
Fixes OMP-24 as per Sigma Prime audit.
task: none

fix(lib/xchain): avoid linear merkle index search

---

halo/attest/voter/voter.go

Verify voter state loaded from disk to avoid panics due to corrupted state.
Fixes OMP-20 as per Sigma Prime audit.
task: none

fix(halo/voter): verify state loaded from disk

---

lib/contracts/avs/register.go
lib/k1util/k1util.go
lib/k1util/k1util_test.go
lib/netconf/netconf_test.go

Adds additional error handling for invalid pubkeys.
Fixes OMP-16 as per Sigma Prime audit.
task: none

fix(lib/k1util): add invalid pubkey error handling

---

lib/merkle/core.go
lib/merkle/core_test.go

Adds validations that ensures that merkle trees have an odd number of nodes.
This protects against panics due to malformed trees and fixes OMP-12 as per Sigma Prime audit.
task: none

fix(lib/merkle): ensure trees have odd number of nodes

---

e2e/app/definition.go
lib/ethclient/ethbackend/backend.go
lib/ethclient/ethbackend/backends.go
lib/txmgr/txmgr.go
lib/txmgr/txmgr_internal_test.go

Ensure RPC nodes are synced when deploying/upgrading any network. This mitigates against nonce-too-low issues caused by out-of-sync RPC nodes.
task: none

ci(e2e): ensure nodes are synced

---

.golangci.yml
lib/txmgr/txmgr.go
lib/txmgr/txmgr_internal_test.go

Treats all network errors while querying receipts as temporary; retrying fetching receipts, don't give up.
This fixes the issue where a network error occurs, but the tx is mined, txmgr gives up querying receipt, and then gets stuck trying to bump fees and resubmit the tx (getting ErrNonceToLow). 
This caused flapping e2e tests when perturbations restart the EVM. 
task: https://app.asana.com/0/1206208509925075/1207634096794277

fix(lib/txmgr): handle network errors while querying receipts

---

lib/cchain/provider/provider_test.go
lib/stream/stream.go

Fix non-deterministic test by synchronising async fetcher with test code.
issue: #1340

test(cchain/provider): fix flapping test

---

lib/txmgr/txmgr.go

Dereference the uint64 pointer so it's useful.
issue: none

fix(txmgr): make log actually useful

---

scripts/verifypr/verify.go
scripts/verifypr/verify_internal_test.go

Allow linking issues to PRs with optional `fixes/close/resolved` prefix.
[e.g.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
```
issue: fix #1234
```
issue: none

chore(verifypr): allow linking issues

---

e2e/app/run.go
e2e/app/start.go
e2e/manifests/staging.toml
e2e/netman/pingpong/pingpong.go
lib/contracts/avs/deploy.go
lib/contracts/create3/deploy.go
lib/contracts/proxyadmin/deploy.go
lib/ethclient/ethbackend/backend.go
lib/ethclient/ethbackend/wait.go
lib/ethclient/helper.go
lib/txmgr/txmgr.go

Enable arb_sepolia on staging.
Also:
- Remove receipt checking not required.
- Wait for EVMs on e2e startup
- Handle `syncProgress` not available error
issue: none

ci(e2e): enable arb_sepolia on staging

---

lib/netconf/static.go

new omega deployment requires a version bump
issue: none

chore(lib/netconf): bumps omega version to support a new deployment

---

monitor/cmd/flags.go

Adds missing `--halo-addr` flag to `monitor` service.
issue: none

ci(e2e): add halu url flag to monitor

---

lib/xchain/provider/provider.go
lib/xchain/provider/provider_internal_test.go

Fixes concurrent fetch workers causing race in offset tracker. 
Instead, wait for "next height" before assigning the offset.
issue: fix #1372

fix(xchain/provider): fix concurrent offset tracker issue

---

halo/app/start.go

Disable optimistic execution since octane doesn't support it at this point. Currently it results in omni_evm reorgs, both "allowed" and "impossible". 
issue: none

fix(halo): disable optimistic exectution

---

e2e/app/eoa/fund.go

Decrease large eoa fund threshold to within sane max so that these accounts can be funded and alerts cleared.
issue: none

chore(e2e/eoa): decrease large threshold within sane max

---

halo/attest/voter/voter_test.go
lib/ethclient/ethbackend/backend.go
lib/txmgr/txmgr.go
lib/xchain/provider.go
lib/xchain/provider/fetch.go
lib/xchain/provider/mock.go
monitor/xmonitor/monitor.go
relayer/app/cursors_internal_test.go

Refactor `monitorOffsets` to use the `emitCursorCache`. 
Had to add a method to xprovider in order to map `ConfLevel` to `Height`:
```
// ChainVersionHeight returns the latest height for the provided chain version.
ChainVersionHeight(ctx context.Context, chainVer ChainVersion) (uint64, error)
```
issue: none

refactor(monitor): use emit cursor cache for offset monitor

---

.github/workflows/clicommand.yml
.github/workflows/pr-e2etest.yml
.github/workflows/release-official.yml
.github/workflows/release-snapshot.yml

Fixes CI builds such as https://github.com/omni-network/omni/actions/runs/9844777751/job/27178902859
issue: none

chore(deps): update to goreleaser v2

---

relayer/app/gas.go
relayer/app/gas_internal_test.go
relayer/app/sender.go

Broadcast xmsgs don't have a destination chain ID set. Gas estimation therefore cannot use the xmsg.DestChainID to infer destination chain. Rather provide destination chain explicitly.
issue: none

fix(relayer): fix gas estimation of broadcast msgs

---

lib/txmgr/txmgr.go
lib/txmgr/txmgr_internal_test.go

Fixes txmgr issue always returning first candidate tx even if different tx mined.
issue: fixes #1391

fix(lib/txmgr): return actual mined tx

---

monitor/xmonitor/emitcursorcache.go
monitor/xmonitor/monitor.go

When populating the emitcursorcache, don't start from DeployHeight or LatestAttestation, since that can esily be more than 128 block old. Our fullnodes only store 128 blocks with of historical state, so just start there.
issue: none

chore(monitor/xchain): start populating emit cache from head-128

---

monitor/xmonitor/monitor.go

Replace incorrect `errors.Wrap` with `errors.New` causing nil pointer.
issue: none

fix(monitor): fix nil pointer in xmonitor

---

halo/attest/keeper/keeper.go

These logs added in #1291 are not human-readable.
Before:
After:
issue: none

fix(attest): make log human-readable

---

halo/app/lazyvoter.go
halo/attest/testutil/mock_interfaces.go
halo/attest/types/interface.go
halo/attest/voter/voter.go
halo/attest/voter/voter_test.go
halo/valsync/keeper/keeper.go
halo/valsync/keeper/query.go
halo/valsync/keeper/query_internal_test.go
halo/valsync/module/module.go
halo/valsync/testutil/expected_interfaces.go
halo/valsync/testutil/mock_interfaces.go
halo/valsync/types/interfaces.go
halo/valsync/types/query.go

Refactor valsync `Subscriber` interface. 
Providing the whole active set (instead of only validator update deltas), simplifies and hardens the logic avoiding unexpected silent out-of-order updates.
This was raised by the Zellic audit.
issue: #1390

refactor(halo/valsync): improve subscriber interface

---

halo/genutil/defaults.go
halo/genutil/genutil_internal_test.go
halo/genutil/testdata/TestMakeGenesis.golden
octane/evmengine/keeper/abci.go
octane/evmengine/keeper/abci_internal_test.go

Explicitly disable cometBFT block max bytes. This effectively increases maximum block size from 21MB (default) to 100MB. 
We MUST include the EVM block, which is limited to `MaxGas` (30M), not bytes. In practice, 30M gas results in +-3MB blocks. 
issue: none

chore(halo/genutil): disable cometBFT max block bytes

---

monitor/xmonitor/emitcursorcache.go

For very new chains (in particular, the omni_evm and omni_consensus chains), the `latest` height is ~0, and we're underflowing.
issue: none

fix(monitor): correctly start fromHeight to start streaming from

---

e2e/fbproxy/app/app.go
e2e/fbproxy/app/config.go
e2e/fbproxy/app/fireblocks.go
e2e/fbproxy/app/middleware.go
e2e/fbproxy/app/middleware_test.go
e2e/fbproxy/app/proxy.go
e2e/fbproxy/app/txargs.go
e2e/fbproxy/cmd/cmd.go
e2e/fbproxy/main.go
lib/fireblocks/key.go

Add a fireblocks rpc proxy that enables raw signing.
The proxy intercepts `eth_sendTransaction` requests, signs them,
and forwards an `eth_sendRawTransaction` request.
Prerequisite for running admin forge scripts (#1393)
issue: #1393

feat(e2e): fireblocks rpc proxy

---

.github/dependabot.yml

removes dependabot labels like `dependencies` and `go`
issue: none

chore(ci): remove dependabot labeling

---

relayer/app/sender.go

This log can display (incorrectly) as 0 ([example](https://omniops.grafana.net/goto/OindVflSg?orgId=1)), since we may be relying on the `txMgr` to estimate gas for us. We should log the actual gas limit from the `tx` itself.
issue: none

fix(relayer): correctly log estimated gas

---

e2e/app/definition.go
e2e/manifests/omega.toml
e2e/types/manifest.go

Pin omage version to `1da6143` so halo is pinned while other services (relayer/monitor/geth) is upgraded to latest (or whatever versions is defined in upgrade action)
issue: none

ci(e2e): pin omega version to 1da6143

---

e2e/manifests/omega.toml
e2e/vmcompose/provider.go

Upgrade omega version by 1 commit to restart the halo instances to fix the stalled chain.
Also, don't upgrade jwtsecret since halo isn't always restarted on upgrade. Which caused the current chain stall.
issue: none

ci(e2e): bump omega halo

---

e2e/manifests/omega.toml

adds the second archive node to the Omega manifest. Will be picked up on the next Omega release.
issue: #1502

feat(e2e/manifests): add second archive node in Omega manifest

---

e2e/docker/compose.yaml.tmpl
e2e/docker/testdata/TestComposeTemplate_commit.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-1-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-2-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-3-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-4-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-5-compose.yaml.golden
monitor/app/app.go
relayer/app/monitor.go

Enables serving `pprof` on the same server/port as prometheus for `relayer` and `monitor`.
Also clarify ports in docker-compose.
issue: none

chore(relayer): enable pprof on prometheus port

---

.pre-commit-config.yaml
.pre-commit/run_golint.sh
e2e/anvilproxy/app/xmsg.go
lib/cchain/provider/abci.go
lib/ethclient/ethbackend/backend.go
lib/txmgr/txmgr.go
lib/umath/umath.go
lib/xchain/provider/mock.go
monitor/xfeemngr/gasprice/buffer_test.go
monitor/xmonitor/emitcache/emitcursorcache.go
octane/evmengine/keeper/msg_server.go
scripts/golint/main.go
scripts/golint/uintsub.go
scripts/golint/uintsub_internal_test.go

Adds a custom `scripts/golint` linter that uses the `golang.org/x/tools/go/analysis` framework.
Implement a simple `uintsubtract` linter that detects uint subtractions. Bypass by using `a-b` inside a uintsub function.
Integrate and run this linter using the `pre-commit` framework.
Also fix all occurrences in the repo.
issue: #1431

ci(scripts): add custom uint subtract go linter

---

e2e/app/definition.go
e2e/app/setup.go
e2e/types/manifest.go
e2e/vmcompose/testdata/TestSetup_127-0-0-1-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-2-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-4-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-5-compose.yaml.golden

Use externalIP as "advertisingIP" for seeds and fullnodes on protected chains. The rest use internal IPs since they don't support external inbound connections.
issue: none

ci(e2e): configure external advertised P2P IP

---

monitor/app/app.go
monitor/xmonitor/emitcache/emitcursorcache.go

Store zero cursors to ditinguish between "not populated" and "nothing there yet". This should reduce errors by a lot.
issue: #1465

fix(monitor/emitcache): store zero cursors

---

e2e/app/tokenbridge.go
lib/contracts/address.go
lib/contracts/l1bridge/deploy.go
lib/contracts/omnitoken/deploy.go
lib/netconf/static.go

Add support for deploying token & l1 bridge during omega deploy.
It also updates bridge deploy flow to support multiple testnet versions, and mainnet.
Though mainnet bridge deployment config is not introduced, and would therefore error.
issue: #1414

feat(e2e): add support for testnet token and bridge

---

e2e/app/geth/config.go
e2e/app/geth/testdata/TestWriteConfigTOML_archive.golden
e2e/app/geth/testdata/TestWriteConfigTOML_full.golden
e2e/docker/compose.yaml.tmpl
e2e/docker/testdata/TestComposeTemplate_commit.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-1-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-2-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-4-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-5-compose.yaml.golden

feat(e2e/docker): adds a mapping for port 8546 so we can use web sockets via our load balancers.
I did go through the code and the "ProxyPort" configuration in the Docker Compose template and tried to make modifications to optionally pass in "WSPort", but this ended up back relating to objects from the CometBFT SDK where there is only a single "Port" field.
Also enabled graphql.
issue: none

feat(e2e/docker): enable graphql and websockets in geth

---

e2e/types/testdata/TestAttestIntervals.golden
e2e/types/testnet_test.go
halo/evmstaking/evmstaking.go
lib/evmchain/evmchain.go

Adds a golden file to make `AttestInterval` for each chain and each network type explicit and easy to lookup or reference.
issue: none

chore(e2e): add attest interval golden file

---

lib/cchain/provider.go
lib/cchain/provider/abci.go
lib/cchain/provider/provider.go

Exposes the cprovider underlying comet rpc client. This is mostly for use in xconnector.
issue: none

chore(lib/cchain): expose cprovider comet rpc client

---

e2e/manifests/omega.toml

unpin the halo version for Omega deployment
issue: none

chore(e2e/manifests): unpin halo version

---

halo/app/app_config.go
halo/attest/keeper/builder_test.go
halo/attest/keeper/keeper_test.go

Reduce the trimLag to 1, keeping only the last epoch's attestations in state.
issue: #1343

feat(attest): only store the most recent attestations in state

---

cli/cmd/develop.go

In the `omni developer new` command, which clones the [hello-world-template](https://github.com/omni-network/hello-world-template), just use `main`. It was referencing an old commit, and forcing ourselves to update that commit manually isn't great because it means we have to remember to update it every time we want to change the template
issue: none

fix(cli): template commit

---

docs/release.md

Update `release.md` after latest discussion about the release process, specifically introduce cutting from release branches and change the semantic versioning standard for releases `release/X`
issue: none

chore(docs): update release docs

---

e2e/app/monitor.go

Using the delayed node for the monitor can cause unexpected failures (eg. [here](https://github.com/omni-network/omni/actions/runs/10010990361/attempts/1)).
issue: none

fix(e2e): avoid using delayed nodes for monitor

---

halo/app/pruning_test.go
halo/app/start.go
halo/app/start_test.go
lib/cchain/provider/abci.go
lib/cchain/provider/provider.go

This allows us to fail earlier and with a useful error type.
issue: none

fix(cchain): sanity check binary search start index

---

.github/workflows/gotest.yml

CI is failing due to docker pull anvil timeouts. So do explicit pull before running tests.
issue: none

ci(lib/anvil): increase anvil pull timeout

---

e2e/app/definition.go
e2e/app/setup.go
halo/cmd/cometconfig.go
halo/cmd/testdata/TestRunCmd_defaults.golden
halo/cmd/testdata/TestRunCmd_flags.golden
halo/cmd/testdata/TestRunCmd_json_files.golden
halo/cmd/testdata/TestRunCmd_toml_files.golden

When attempting to join omega using `omni operator init-nodes` and the local node fetches peer addresses from the bootstrapped peers, debug logs show that private IPs are returned, this causes P2P networking to fail.
This attempt to address the problem by using "advertised" IPs consistently (not only in advertised IP context).
This means that our internal nodes will also connect to seed/fullnodes using their external IPs.
When asked for peers, they would then hopefully return those external IPs and not internal IPs like previously.
issue: none

ci(e2e): populate p2p with advertised addrs

---

.github/workflows/ci-main.yml
.github/workflows/ci-notify.yml
.github/workflows/ci-pr.yml
.github/workflows/pr-label.yml

Adds the `release/v0.X` label to PRs to any release branch.
Also ensures github actions run on release branches.
issue: #1552

ci(github): label release branch PRs

---

scripts/verifypr/verify.go
scripts/verifypr/verify_internal_test.go

Less strict parsing of conventional commit. Allow spaces around footer. Allow more footers.
issue: none

chore(scripts/verifypr): less strict parsing

---

.github/workflows/ci-main.yml
.github/workflows/ci-pr.yml

Fix github action release branch matching.
As per docs:
`*: Matches zero or more characters, but does not match the / character. For example, Octo* matches Octocat.`
issue: none

ci(github): fix release branch matching

---

lib/cchain/provider/abci.go

Actually find the earliest store height, don't just return `startPoint` always.
issue: none

fix(cchain): correctly find earliest store height

---

halo/app/pruning_test.go
halo/app/start_test.go
lib/tutil/random.go

Attempts to fix the flapping tests in CI:
- Pick random bind ports to avoid `bind address already in use`.
- Harden PruneHistoryTest:
- Pick chain without fuzzy dependent attestations.
- First wait for att=0 to be eligible for deletion
- Then wait for it to be deleted 
- Speeds up test from 30s to 12s. 
issue: none

test(halo): harden flapping tests

---

halo/app/app.go
halo/app/rollback.go
halo/app/start.go
halo/attest/keeper/keeper.go
halo/registry/keeper/helper.go
halo/registry/keeper/keeper.go
halo/registry/keeper/logeventproc.go
halo/registry/keeper/logeventproc_internal_test.go
halo/registry/module/module.go
halo/registry/types/interface.go
lib/netconf/netconf.go
lib/netconf/netconf_test.go
lib/netconf/static.go

This ensures that we never create or verify votes for unsupported Conf levels.
issue: #1579

feat(attest): reject votes for unsupported conf levels

---

cli/cmd/compose.yml.tpl
e2e/app/geth/config.go
e2e/app/geth/testdata/TestWriteConfigTOML_archive.golden
e2e/app/geth/testdata/TestWriteConfigTOML_full.golden
e2e/app/setup.go
halo/app/cmtlog.go
halo/app/start.go
halo/attest/voter/voter.go
lib/netconf/static.go
lib/p2putil/pex.go
lib/p2putil/pex_test.go

Staging only has a single fullnode, it is also an archive node, use an externalIP in order to join to it.
Also some general cleanups:
- Improve docker compose comments
- Set geth moniker correctly
- Indent voter json for easier human readability
- Wire missing staging seed embeds
- Add `p2putil.FetchPexPeers` to debug p2p issues.
issue: #1541

ci(e2e): use external IP for staging fullnode1

---

e2e/app/definition.go
e2e/app/setup.go

Improve P2P config:
- Remove all seed node persistent peers. It seems like seed nodes don't add persistent peers to address book. They should only wait for incoming connections. 
- Enable strict routing for public nodes (seeds and fullnodes)
- Set private peer IDs (validators and archive nodes)
issue: #1541

ci(e2e): improve p2p config

---

e2e/app/definition.go
e2e/app/setup.go

Improve seed node p2p again:
- Add normal persisted peers (since staging had a blip where seednode didn't have any nodes)
- Prepopulate addressbook with persisted peers.
issue: #1541

ci(e2e): improve seed node p2p config

---

lib/stream/stream.go

Cancel the context for all workers on shutdown, this avoids leaking goroutines as we observed in #1464. 
issue: #1602

fix(lib): cancel worker context on Stream shutdown

---

e2e/app/setup.go

Disable `seedmode` since it doesn't seem to work well in small networks. This aims to fix joining staging issues.
issue: #1541

ci(e2e): disable seedmode

---

e2e/app/definition.go
lib/p2putil/pex_test.go

Remove seed nodes config, connect all peers simply as persisted peers. This aims to address issue with staging seed node still not having any peers in its address book.
issue: #1541

ci(e2e): dont configure seed nodes

---

e2e/test/attestations_test.go
lib/cchain/provider/abci.go
lib/cchain/provider/metrics.go

Include the chain name, and set better buckets for these metrics.
issue: #1526

feat(cchain): improve lookback metrics

---

cli/cmd/operator.go
halo/app/lazyvoter.go
halo/app/metrics.go
halo/app/monitor.go
halo/app/start.go
halo/cmd/init.go
lib/ethclient/enginemock.go
lib/netconf/static.go

Adds logs and metrics for halo/geth syncing, also geth peers. 
Don't initialise voter until the node is a validator. This avoid issues with partial rpc endpoint config in non-validators.
issue: #1526

chore(halo): monitor comet syncing

---

halo/genutil/evm/evm.go

Add testnet faucet allocs.
Fund 10 accounts, derived from a single faucet mnemonic.
issue: none

chore(halo/genutil): add testnet faucet allocs

---

e2e/app/monitor.go
e2e/app/setup.go
e2e/docker/docker.go
e2e/manifests/ci.toml
e2e/manifests/devnet1.toml
e2e/manifests/fuzzyhead.toml
e2e/test/attestations_test.go
e2e/types/testnet.go
halo/app/app_config.go
halo/app/start.go
halo/cmd/testdata/TestCLIReference_rollback.golden
halo/cmd/testdata/TestCLIReference_run.golden
halo/cmd/testdata/TestRunCmd_defaults.golden
halo/cmd/testdata/TestRunCmd_flags.golden
halo/cmd/testdata/TestRunCmd_json_files.golden
halo/cmd/testdata/TestRunCmd_toml_files.golden
halo/config/config.go
halo/config/testdata/default_halo.toml

Archive nodes: Keep everything.
Anything else: Prune "everything", keep the bare minimum (Cosmos enforces the necessary limits based on snapshots, state needed for Byzantine behaviour detection, etc.).
This PR also adds archive nodes to our e2e test networks, in order to support the monitor.
issue: #1546

feat(e2e): keep minimal state for non-archive nodes

---

e2e/app/setup.go
e2e/docker/docker.go
e2e/manifests/devnet0.toml
e2e/types/testnet.go

The relayer has to use an archive node after #1612, else it might not be able to fetch necessary attestations.
issue: none

fix(e2e): relayer should use an archive node

---

e2e/app/cleanup.go
e2e/app/perturb.go
e2e/cmd/cmd.go
e2e/docker/docker.go
lib/xchain/provider.go
monitor/xmonitor/emitcache/emitcursorcache.go
monitor/xmonitor/emitcache/emitcursorcache_internal_test.go
monitor/xmonitor/emitcache/metrics.go

Workaround cache not populated errors by falling back to querying (archive) nodes. Also add metrics with the aim of debugging and fixing the emitcache issues in the long run.
Also refactor docker to use `docker compose` instead of `docker-compose` which isn't supported on github runners anymore it seems.
issue: #1591

chore(monitor/emitcache): fallback to archive node

---

lib/cchain/provider/abci.go
lib/cchain/provider/provider.go

Capture the source chain (worker name) in cprovider Subscribe logs, along with the number of lookback steps
issue: #1375

chore(cchain): add debug logs capturing lookback

---

docs/site/docs/develop/xapp/example.md

Update xapp example docs.
- rename `GlobalGreeter` section to `GreetingBook`
- update code blocks
- cleanup `isXCall` section
issue: none

chore(docs): xapp example fixes

---

e2e/app/definition.go
e2e/docker/compose.yaml.tmpl
e2e/docker/docker.go
e2e/docker/docker_test.go
e2e/docker/testdata/TestComposeTemplate_commit.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/types/manifest.go
e2e/types/testnet.go
e2e/vmcompose/provider.go

Support pinning of monitor and relayer images.
issue: https://github.com/omni-network/omni/issues/1629

ci(e2e): pin monitor and relayer images

---

halo/app/lazyvoter.go
halo/app/metrics.go
halo/app/monitor.go

Adds the `halo_comet_validator` constant gauge metric that tracks whether the local halo node is a cometBFT validator (1) or not (0). Se should add an alert if any `validator` halo instance is not a validator.
issue: #1526

chore(halo): instrument validator status

---

.github/workflows/e2etest.yml

Remove github action step that pushes e2e logs to loki since it has never worked for a long time.
issue: #1626

chore(github): remove pushing e2e logs to loki

---

halo/app/start_test.go
lib/cchain/provider.go
lib/cchain/provider/provider.go
lib/cchain/provider/provider_test.go
lib/stream/stream.go
lib/xchain/provider/provider.go
monitor/app/app.go
monitor/app/historical.go
monitor/app/metrics.go
monitor/app/sync.go
relayer/app/cursors_internal_test.go
relayer/app/worker.go

Implements a periodic cprovider historical baseline tracking. Results in `monitor_cprovider_historical_baseline_seconds` histogram. 
Also refactor `cprovder` to align with `xprovider` sync vs async API. 
Improve `stream` package log labels.
issue: #1623

chore(monitor): implement historical baseline tracking

---

.github/workflows/clicommand.yml
.github/workflows/pr-e2etest.yml
.github/workflows/release-snapshot.yml
Makefile
e2e/app/definition.go
e2e/docker/compose.yaml.tmpl
e2e/docker/testdata/TestComposeTemplate_commit.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-1-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-2-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-3-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-4-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-5-compose.yaml.golden
scripts/halovisor/Dockerfile
scripts/halovisor/build.sh

Introduce the `halovisor` docker image:
- It is a drop-in replacement for `halo` image.
- It wraps cosmovisor and the all halo versions from genesis to latest.
- The aim is to support default cosmosSDK-cosmovisor-based network upgrades from within docker. 
Inspired by [this](https://tutorials.cosmos.network/hands-on-exercise/4-run-in-prod/5-migration-prod.html) blog
issue: none

ci(e2e): build and use halovisor

---

e2e/app/testdata/TestManifestServiceReference.golden
e2e/manifests/staging.toml

Changes staging manifest to remove Slow L1 and adds Holesky to the public chains
Incorrect link below. Issue is the same number, but in the ops repo.
issue: #348

chore(e2e/manifests): removes slow l1 on staging and introduces holesky

---

cli/cmd/compose.yml.tpl
cli/cmd/operator.go
halo/cmd/init.go

For `locally joined` omni full nodes, allow enabling metrics of geth/halo by binding ports only.
Enable colorized halo logs by default.
issue: none

chore(cli): allow easy metrics

---

e2e/app/eoa/fund.go
e2e/app/fund.go
e2e/app/run.go
monitor/loadgen/loadgen.go

Relayer on staging is running out of 20ETH balance fast: 
- Increase relayer funding from 20 to 50
- Decrease parallel ping pongs from 10 to 3
- Increase self-delegation period from 1H to 6H (allowing more relayer downtime before `old valset` issue is triggered).
issue: #1701

ci(e2e): address relayer funds issue

---

halo/app/app.go
halo/app/app_config.go
halo/evmslashing/depinject.go
halo/evmstaking/depinject.go
halo/evmupgrade/depinject.go
halo/registry/module/module.go
octane/evmengine/keeper/abci_internal_test.go
octane/evmengine/keeper/keeper.go
octane/evmengine/keeper/msg_server_internal_test.go
octane/evmengine/module/module.go
octane/evmengine/types/cpayload.go

Refactor halo app wiring to use `depinject` for `EvmEventProcessors`.
issue: none

refactor(halo): wire evmeventprocs using depinject

---

halo/app/monitor.go
halo/attest/voter/voter.go
lib/cchain/provider/abci.go
lib/cchain/provider/provider.go
lib/fireblocks/jsonhttp.go
monitor/xfeemngr/oracle.go
scripts/golint/logattrs.go
scripts/golint/logattrs_internal_test.go
scripts/golint/main.go

Add a custom `golint` linter to ensure our log attributes are consistently `snake_case`.
issue: none

ci(golant): add log attrs snake case lint

---

e2e/app/admin/common.go
e2e/fbproxy/app/app.go

Reduce timeout risk in admin forge scripts
- Increase fbproxy write timeout to allow for mpc fireblocks signing.
- Run admin scripts in sequence, not parallet
issue: none

fix(e2e): reduce admin script timeout risk

---

halo/config/testdata/default_halo.toml
halo/genutil/testdata/TestMakeGenesis.golden
lib/buildinfo/buildinfo.go
monitor/app/testdata/default_monitor.toml
relayer/app/testdata/default_relayer.toml

Updates the omni version on main to `v0.4-dev` to indicate we are building on top of v0.4.0
issue: none

chore(buildinfo): update omni version

---

.github/workflows/check-sol-artifacts.yml
.github/workflows/ci-verifypr.yml
.github/workflows/clicommand.yml
.github/workflows/e2etest.yml
.github/workflows/golangci-lint.yml
.github/workflows/gotest.yml
.github/workflows/pr-e2etest.yml
.github/workflows/pre-commit.yml

Lock go minor version in ci
Locking goversion to 1.22 in ci until we can upgrade to 1.23. Upgrade to 1.23 
is blocked by https://github.com/ethereum/go-ethereum/issues/30100
issue: none

chore(ci): lock go minor version in ci

---

.github/workflows/release-official.yml
.github/workflows/release-snapshot.yml

Lock go minor version in ci
Locking goversion to 1.22 in ci until we can upgrade to 1.23. Upgrade to 1.23
is blocked by https://github.com/ethereum/go-ethereum/issues/30100
Adds version locks missed in https://github.com/omni-network/omni/pull/1721
issue: none

chore(ci): lock go minor version

---

halo/attest/keeper/cpayload.go
halo/attest/keeper/keeper.go
halo/attest/keeper/keeper_internal_test.go
halo/attest/keeper/proposal_server.go

Fixes attest module `verifyAggVotes` dedup logic to align with `aggregateVotes` logic that uses `attestation root` as dedup key. 
issue: #1731

fix(halo/attest): fix duplicate agg vote logic

---

go.mod
go.sum

Use our fork of `cosmos/iavl` that fixes a race condition during snapshot restore.
issue: #1524

fix(cosmos/iavl): use fork as workaround

---

e2e/types/testdata/TestAttestIntervals.golden
lib/contracts/feeoraclev1/deploy.go
lib/contracts/feeoraclev1/feeparams.go
lib/evmchain/evmchain.go
lib/netconf/netconf.go
lib/netconf/static.go
monitor/app/app.go
monitor/xfeemngr/contract/bound.go
monitor/xfeemngr/contract/contract.go
monitor/xfeemngr/contract/mock.go
monitor/xfeemngr/oracle.go
monitor/xfeemngr/xfeemngr.go
monitor/xfeemngr/xfeemngr_internal_test.go

Support management of onchain fee params for a chain not in the network.
Testnet sepolia chains post tx data to sepolia. Their xcall fees should therefore 
be calculated using sepolia gas prices. Sepolia is not in the omega network, but we
need to manage it's fee params on chain.
Requires https://github.com/omni-network/ops/pull/385
issue: none

feat(monitor/xfeemngr): manage fee params for chain not in network

---

e2e/app/run.go

Allow ephemeral network upgrades.
issue: none

chore(e2e): allow ephemeral network upgrades

---

e2e/app/setup.go
monitor/app/app.go
monitor/app/config.go
monitor/app/config.toml.tpl
monitor/app/testdata/default_monitor.toml
monitor/cmd/cmd.go
monitor/cmd/flags.go
monitor/xfeemngr/xfeemngr.go

Pass all rpc overrides to the xfeemngr.
This allows us to pass in rpcs for chains that are not in-network. 
We pass to xfeemngr explicitly, because other processes assume all
endpoints are in-network.
issue: none

feat(e2e): pass all rpc overrides to xfeemnger

---

lib/netconf/netconf.go
monitor/routerecon/metrics.go
monitor/routerecon/recon.go
monitor/routerecon/recon_internal_test.go
monitor/routerecon/routescan.go
monitor/routerecon/routescan_internal_test.go
monitor/routerecon/types.go

Improve routescan recon:
- Fix issue with receipt.ConfLevel
- Recon each stream explicitly (except arb_sepolia which isn't supported currently).
- Track completed offset to compare against our submitted offset
- Verify crossTX.ID against expected value
- Improve types.
issue: #1714

chore(monitor): improve routescan recon

---

lib/xchain/types.go

Removes `Receipt.ConfLevel` as this was never used and isn't supported by portals.
issue: none

chore(xchain): remove unused conf level from receipt

---

Makefile
e2e/app/definition.go
e2e/app/perturb.go
e2e/docker/compose.yaml.tmpl
e2e/docker/docker.go
e2e/docker/docker_test.go
e2e/docker/testdata/TestComposeTemplate_empheral_network_upgrade.golden
e2e/manifests/backwards.toml
e2e/types/manifest.go
e2e/vmcompose/provider.go

Adds a `backwards.toml` that ensures backwards compatibility of `main` with `v0.4.0` our first omega LTS version. 
issue: #1537

ci(e2e): add backwards compatibility test

---

.github/workflows/release-official.yml

Build halovisor image on official release. Note this still doesn't build multi-arch (darwin) images yet.
issue: #1735

chore(github): build and push halovisor on release

---

halo/attest/keeper/common_test.go
halo/attest/keeper/keeper.go
halo/attest/keeper/keeper_test.go
halo/attest/keeper/metrics.go
halo/attest/testutil/mock_interfaces.go
halo/valsync/types/types.go

Adds three counters that track validator xchain attestation performance:
- `halo_attest_votes_approved_total`: Total number of votes included in approved attestations per validator per stream. Approved votes were present in approved attestations at time of deletion. They count towards rewards
- `halo_attest_votes_discarded_total`: Total number of votes included in discarded attestations per validator per stream. Discarded votes were included on-chain but were either for previously approved attestations (late) or for non-quorum attestations (wrong). They don't count towards rewards".
- `halo_attest_votes_missing_total`: Total number of votes missing from approved attestations per validator per stream. Missing votes were missing from approved attestations at time of deletion. They may be …

chore(halo/attest): instrument validator votes

---

cli/cmd/cmd.go
cli/cmd/compose.yml.tpl
cli/cmd/flags.go
cli/cmd/key.go
cli/cmd/staking.go
e2e/app/portalregistry.go
e2e/app/run.go
halo/app/privkey.go
halo/cmd/cmd.go
halo/cmd/testdata/TestCLIReference_halo.golden
halo/cmd/testdata/TestCLIReference_init.golden
halo/cmd/testdata/TestCLIReference_rollback.golden
halo/cmd/testdata/TestCLIReference_run.golden
halo/genutil/evm/evm.go
lib/netconf/flag.go

Adds the following `omni` cli commands:
- `omni operator create-operator-key`: creates a insecure operator private key
- `omni operator create-validator`: sign and broadcasts `create-validator` transaction.
Adds the following `halo` binary command:
- `halo consensus-pubkey`: Prints the halo consensus pubkey for use in `create-validator` above. 
issue: #1757

feat(cli): add operator commands

---

e2e/docker/compose.yaml.tmpl
e2e/docker/docker.go
e2e/docker/testdata/TestComposeTemplate_commit.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network_upgrade.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-1-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-2-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-4-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-5-compose.yaml.golden

Temporary debug snapsync issues on staging by setting trace level geth logs.
issue: none

ci(e2e): enable geth trace logs on staging

---

cli/cmd/compose.yml.tpl
cli/cmd/flags.go
cli/cmd/operator.go
e2e/app/setup.go
lib/log/config.go

Adds a `--archive` flag to `omni operator init-nodes` to join a network as an archive node.
This is currently blocked on the fact that our archive nodes are not publicly accessible via P2P so the local archive node can't find blocks to download.
issue: none

feat(cli): support archive in init-nodes

---

e2e/docker/docker.go
e2e/vmcompose/provider.go

Move log level to vmcompose since that is what staging uses.
issue: none

ci(e2e): fix verbose geth logs on staging

---

contracts/core/package.json
contracts/core/pnpm-lock.yaml

Lock oz merkle js lib version.
OZ merkle js introduced some breaking typescript changes in 1.0.7
issue: none

fix(contracts): lock oz merkle js lib version

---

lib/xchain/types.go
lib/xchain/types_internal_test.go
monitor/xmonitor/indexer/indexer.go
monitor/xmonitor/indexer/indexer_internal_test.go
monitor/xmonitor/indexer/metrics.go

Adds tracking of the number of fuzzy overrides per stream to monitor indexer.
issue: #1627

chore(monitor/indexer): track number of fuzzy overrides per stream

---

e2e/app/setup.go
monitor/xmonitor/indexer/indexer_internal_test.go

Enables snapshots each block on staging. This aims to debug snapsync issues.
issue: none

ci(e2e): enable constant snapshots in staging

---

e2e/app/gaspump.go
halo/genutil/evm/evm.go

Fund `EOAs` on staging. This ensures that gasstation can be funded by them. Precent gasstation deploy on omega/mainnet at this point.
issue: none

chore(e2e): fix staging gas

---

.goreleaser.yaml
halo/config/testdata/default_halo.toml
halo/genutil/testdata/TestMakeGenesis.golden
lib/buildinfo/buildinfo.go
monitor/app/testdata/default_monitor.toml
relayer/app/testdata/default_relayer.toml

Set `lib/buildinfo.version=main` forever, no need to update this when doing a new release.
This version field will be set by goreleaser.
issue: none

chore(lib/buildinfo): simplify version

---

monitor/app/app.go
monitor/validator/metrics.go
monitor/validator/validator.go
monitor/xmonitor/indexer/metrics.go

Adds basic validator monitoring. Specifically adds a `monitor_validator_power` metric that maps operator eth address to consensus eth address and consensus cometBFT address which is required to map built-in cometBFT validator metrics to our xchain attest validator metrics.
issue: #1811

feat(monitor): track validator power and status

---

e2e/manifests/omega.toml

Adds static P2P keys to omega archive nodes.
issue: none

ci(e2e): add static p2p keys for omega archive nodes

---

e2e/vmcompose/provider.go

Only running `docker compose up -d` doesn't always result in all changes reflecting in services since docker only restarts the container if the docker-compose file itself changed. If only artefacts changed, the container isn't restarted.
This ensures that we always restart the containers.
issue: none

chore(e2e/vmcompose): run docker compose down during upgrade

---

e2e/app/admin/allowoperator.go
e2e/cmd/admin.go

Adds a simple `e2e admin allow-operators` command that ensures all hard-coded operators are allowed as validators. Only omega supported. At this point, the operator addresses are unknown, they should be added later and then the command can be executed.
issue: #1814

chore(e2e): add allow validators command

---

cli/cmd/initnodes.go
halo/cmd/init.go
lib/netconf/netconf_test.go
lib/netconf/omega/consensus-archives.txt
lib/netconf/staging/consensus-archives.txt
lib/netconf/static.go

Add static archive node P2P info. Add those as persisted peers when joining a network as an archive node when running `omni operator init-nodes --archive`
issue: none

chore(cli): init archives as persisted peer

---

monitor/xmonitor/indexer/indexer.go

Adds routescan cross transaction id hash to support linking from grafana to routescan.
issue: none

chore(monitor/indexer): add routescan id hash to logs

---

.golangci.yml
e2e/test/attestations_test.go
halo/app/start_test.go
lib/cchain/provider.go
lib/cchain/provider/abci.go
lib/cchain/provider/provider.go
lib/cchain/provider/provider_test.go
lib/cchain/provider/xblock.go
lib/cchain/provider/xblock_internal_test.go
lib/cchain/types.go
monitor/validator/metrics.go
monitor/validator/validator.go
monitor/validator/validator_internal_test.go

Adds `monitor_validator_uptime` and `monitor_validator_rewrads` and `monitor_validator_tombstoned` metrics.
Also improve cprovider naming.
issue: #1811

chore(monitor/validator): add uptime and rewards

---

cli/cmd/cmd.go
cli/cmd/key.go
halo/cmd/init.go

Adds `omni create-consensus-key` command that generates the following two files:
- `<home>/config/priv_validator_key.json`
- `<home>/data/priv_validator_state.json`
.
issue: none

chore(omni/cli): add create-consensus-key command

---

.goreleaser.yaml

Remove internal binaries from release tarball. Only include external facing `halo` and `omni` binary.
issue: #1844

chore(goreleaser): only include external binaries in release

---

cli/cmd/initnodes.go
cli/cmd/key.go
halo/cmd/init.go

Refactors `omni operator init-nodes` to be "idempotent" such that any existing files are not overwritten. This allows operators to run commands like `omni operator create-consensus-key` first before running `init-nodes`.
Also improve `omni operator create-consensus-key` to generate `voter_state.json`.
issue: #1842

feat(cli/cmd): idempotent init-nodes

---

.github/workflows/release-official.yml

Push (update) `omniops/halovisor:latest` on official release
issue: none

chore(github): push latest halovisor on official release

---

e2e/manifests/omega.toml
monitor/xmonitor/emitcache/emitcursorcache.go
relayer/app/worker.go

Add P2P keys to all omega nodes to ensure that upgrades don't negatively affect P2P peers by rotating keys and needing to timeout and reconnect and refresh.
issue: none

ci(e2e): add p2p keys to all omega nodes

---

halo/attest/keeper/helper.go
halo/attest/keeper/keeper.go
halo/attest/keeper/metrics.go

Improves xchain vote monitoring to allow for easier uptime metrics.
- Adds `halo_attest_votes_expected_total` and init all metrics with correct metrics so calculating uptime is simply `halo_attest_votes_approved_total/halo_attest_votes_expected_total`.
- Rename `stream` label to `chain_version` since it isn't streams but chain vers.
issue: #1811

chore(halo/attest): improve xchain vote metrics

---

.github/workflows/ci-pr-docs.yml

the `docs/content` dir should also trigger preview deployments
issue: none

chore(ci): use full docs dir for vercel trigger

---

halo/registry/keeper/cache.go
octane/evmengine/keeper/abci.go
octane/evmengine/keeper/abci_internal_test.go
octane/evmengine/keeper/keeper.go

Refactor a few caches that store/return pointers to avoid mutation of the cached value before/after getting/setting.
This was pointed out by spearbit audit.
issue: none

chore(*): refactor cached pointers

---

halo/attest/keeper/valaddr.go
halo/attest/types/tx.go

Fixes some spearbit audit issues:
- omni-halo#2: `AttestHeader::Verify()` accepts invalid confirmation level
- omni-halo#3: `Verify()` functions do not check that headers are for the same chain ID
- omni-halo#4: `*valAddrCache.SetAll()` mutex use can be optimized
issue: none

chore(*): some spearbit audit fixes

---

monitor/xmonitor/indexer/indexer.go

Strip 0x from `id_hash` logs since routescan strips it from urls which is what we use this for.
issue: #1811

chore(monitor/indexer): strip 0x for omniscan links

---

halo/attest/keeper/keeper.go
halo/attest/keeper/keeper_test.go
halo/attest/types/tx.go
lib/cchain/provider.go
lib/cchain/provider/abci.go
lib/cchain/provider/provider.go

Fixes `attest.ListAllAttestations` to use `ListRange` instead of `List` which is a perfix query. Also enforce a `maxLimit=100`.
issue: #1895

fix(halo/attest): fix ListAllAttestations

---

contracts/core/src/libraries/Predeploys.sol

Reduce bitshift in isPredeploy check. Namespace of 1024 size allows for this.
issue: #1875

fix(contracts/core): reduce bitshit in ispredeploy check

---

.goreleaser.yaml

Fixes incorrect `main` version of `monitor` service for official releases.
issue: none

ci(goreleaser): fix monitor version

---

lib/contracts/address_test.go
lib/contracts/testdata/TestContractAddressReference.golden

Adding devnet addrs to golden, so they're easy to reference.
They are determinstic (staging is not). 
issue: none

chore(lib/contracts): add devnet addrs to golden

---

monitor/validator/metrics.go
monitor/validator/validator.go

Use potential power since this allows tracking power of unbonded validators
issue: none

chore(monitor/validator): use potential power instead

---

e2e/docker/compose.yaml.tmpl
e2e/docker/testdata/TestComposeTemplate_commit.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network_upgrade.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-1-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-2-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-4-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-5-compose.yaml.golden

We can't bind Cosmos gRPC to port 9090 on our VMs since it clashes with grafana agent.
issue: #1861

ci(e2e): fix port clash

---

e2e/app/geth/config.go
halo/cmd/init.go
halo/config/config.go

Align `omni` cli snapshot period. Also decrease geth snapshot cache back to 1GB.
issue: #1675

ci(e2e): align snapshot period

---

.github/workflows/check-contracts-version.yml
.github/workflows/release-contracts-npm.yml
contracts/core/package.json

Release `@omni-network/contracts` on npm when github release published.
- only on github tags `contracts/v*`
- add check on tag to make sure npm version matches 
issue: #1450

ci(contracts/core): add release worflows for contracts npm

---

cli/cmd/flags.go
cli/cmd/key.go

Suffix the operator address to the private key filename. This mitigates the risk of loosing track of the operator address or of mixing up multiple private keys.
Example
```
omni operator create-operator-key
🎉 Created operator private key                                                            type=insecure file=./operator-private-key-0xe06C945CD25198086C9369CEd1A414Ba028BB177 address=0xe06C945CD25198086C9369CEd1A414Ba028BB177
🚧 Remember to backup this key 🚧
```
issue: none

chore(cli): add operator address to privkey file

---

.github/workflows/release-official.yml
.github/workflows/release-snapshot.yml

Improves CI docker images:
- Skip multi-arch builds during snapshots (normal CI) #speed
- Add multi-arch builds for halovisor during official release
issue: #1735

ci(github): improve CI docker images

---

halo/cmd/cmd.go
halo/cmd/flags.go
halo/cmd/status.go
halo/cmd/testdata/TestCLIReference_halo.golden

Adds the CosmosSDK standard `halo status` command. This is going to be used by cosmovisor during upgrades. 
issue: #1834

feat(halo): add status command

---

halo/app/pruning_test.go
lib/evmchain/evmchain.go
lib/netconf/static.go

Use different chain ids for staging and devnet.
This will allow us to keep both in our metamask (or other wallets) without conflict.
issue: none

chore(lib/evmchain): use sepr chainids for staging and devnet

---

contracts/core/foundry.toml

Avoid 'env var not found' errors in ci.
issue: none

fix(ci): do not require etherscan api keys in ci

---

cli/cmd/compose.yml.tpl
e2e/docker/compose.yaml.tmpl
e2e/docker/testdata/TestComposeTemplate_commit.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network_upgrade.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-1-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-2-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-4-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-5-compose.yaml.golden

Enables geth docker compose udp ports. This should fix discv5 which isn't working on omega.
issue: #1674

ci(e2e): enable geth udp ports

---

e2e/vmcompose/provider.go

Pull images when deploying or upgrading. This resolve issue of using `main` or `latest` images that are not being updated on deploy.
issue: none

ci(e2e): pull latest images on compose up

---

.github/workflows/ci-pr.yml
.github/workflows/pr-label.yml

PRs against `upgrade/**` branches should also run CI.
issue: none

ci(github): run PR ci against upgrade branches

---

halo/valsync/keeper/helper.go
halo/valsync/keeper/keeper.go
halo/valsync/keeper/keeper_internal_test.go

Additional validation before inserting validators into valsync module.
This was raised during the speardit audit.
issue: none

chore(halo/valsync): validate inserted validators

---

lib/cchain/provider/abci.go
lib/cchain/types.go

Fixes 0% uptime metric for validator previously jailed.
issue: none

chore(monitor/validator): fix uptime metric

---

halo/app/app.go
halo/app/app_internal_test.go

Dump upgrade info when binary is too old. This adds support for halovisor to upgrade genesis binary after snapshyncing to block post an upgrade. 
issue: #1834

chore(halo/app): dump upgrade info if binary too old

---

e2e/app/definition.go
e2e/netman/manager.go

Do not initialize private portal addresses.
We set them later post deployment anyways.
issue: none

fix(e2e/netman): do not initialize private portal addrs

---

e2e/cmd/admin.go

Allow `e2e admin test` on staging.
issue: none

chore(e2e): allow admin test on staging

---

e2e/cmd/admin.go

Do not deploy staging when running admin test.
Only deploy devnet. 
issue: none

fix(e2e): do not deploy staging in admin test

---

halo/app/app.go
halo/app/app_internal_test.go

When dupmping upgrade info the disk in the "old binary" use-case, ensure that we set the original upgrade height, not current. This would have caused the new binary to re-run store upgrade loaders.
issue: #1834

fix(halo/app): dump old height

---

cli/cmd/compose.yml.tpl
e2e/docker/compose.yaml.tmpl
e2e/docker/testdata/TestComposeTemplate_commit.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
e2e/docker/testdata/TestComposeTemplate_empheral_network_upgrade.golden
e2e/manifests/backwards.toml
e2e/vmcompose/testdata/TestSetup_127-0-0-1-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-2-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-4-compose.yaml.golden
e2e/vmcompose/testdata/TestSetup_127-0-0-5-compose.yaml.golden
scripts/halovisor/Dockerfile
scripts/halovisor/build.sh

Swap the cosmovisor binary inside halovisor to the omni [fork](https://github.com/omni-network/cosmovisor).
This ensures that the next version, `v0.8.0`. Will be compatible with subsequent e2e app that mounts only a single `/halo` folder to halovisor. This ensures we can use `v0.8.0`as LTS "genesis version" and backwards compatibility target.
issue: none

ci(halovisor): swap to omni cosmovisor fork

---

.github/workflows/release-official.yml

Fix failing release action be removing special namespace runner.
issue: none

ci(github): fix failing release action

---

.github/workflows/release-official.yml

We only support linux/amd64 images at this point.
issue: none

ci(github): fix failing release action again

---

.github/workflows/release-official.yml
.github/workflows/release-snapshot.yml
e2e/app/run.go
e2e/app/setup.go
e2e/manifests/backwards.toml
e2e/manifests/ci.toml
e2e/types/manifest.go
halo/app/app.go
halo/app/start_test.go
halo/app/upgrades.go
halo/app/upgrades/uluwatu/upgrade.go
halo/attest/module/migrations.go
halo/attest/module/module.go
halo/cmd/init.go
halo/genutil/genutil.go
halo/genutil/genutil_test.go
halo/genutil/testdata/TestMakeGenesis.golden
scripts/halovisor/Dockerfile
scripts/halovisor/build.sh

Adds the uluwatu network upgrade to halo.
Also:
- Adds the additional binary to halovisor
- Support genesis network upgrades (to run a post-upgrade network).
- Add a wrapper to halovisor to support explicit binary links via env vars.
- Support network upgrades in e2e.
issue: #1787

chore(halo): add uluwatu network upgrade

---

e2e/app/start.go

Recent contract address changes require omni_evm height=1, this is halo height=3, so wait for initial_height 3.
issue: none

chore(e2e): wait for post-genesis-upgrade

---

monitor/app/app.go

Feemgr contract address failures on omega, this is workaround to get monitor up in anycase.
```
start xfee manager: make oracle: new bound fee oracle: fee oracle addr: no contract code at given address
```
issue: none

chore(monitor): workaround fee manager failure

---

e2e/app/fund.go

Allow funding staging contracts.
Now that staging lib/contract addrs should be accurate, we can fund staging contracts.
issue: none

chore(e2e): allow funding staging contracts

---

halo/app/app.go
halo/app/app_internal_test.go
halo/app/rollback.go
halo/app/start.go
lib/errors/errors.go
monitor/xmonitor/monitor.go

Prevent `panic`s, `[BUG]` logs, and `CONSENSUS FAILURE` logs when upgrade module detects that cosmovisor should switch binaries. This also speeds up cosmovisor switching from 5-10s to 1s.
issue: none

chore(halo/app): smooth cosmovisor upgrades

---

e2e/app/admin/common.go
e2e/fbproxy/app/proxy.go

Forward req headers to remote addr, and response headers back to sender. 
issue: none

fix(e2e/fbproxy): forward req and resp headers

---

halo/app/app.go
halo/app/lazyvoter.go
halo/app/start.go
halo/attest/voter/voter.go
halo/attest/voter/voter_internal_test.go
halo/attest/voter/voter_test.go

If voter fails to persist state to disk, then the in-memory state is inconsistent. This could result in double-signing and possible slashing.
Instead of trying to fix in-memory state via rollbacks or compare-and-swap type logic, just abort the voter (and shutdown halo). This indicates a full disk (or loss of validator state file), so best crash(loop). 
This issue was raised by the spearbit audit.
issue: none

fix(halo/voter): abort app if persistence fails

---

e2e/fbproxy/app/proxy.go

Set proxied request content length.
Additionally, use header.Clone() to clone request header.
issue: none

fix(e2e/fbproxy): set req content length

---

lib/cmd/cmd.go

Minor whitespace issue appearing in terminal as a double space.
issue: none

chore(e2e): whitespace

---

scripts/halovisor/Dockerfile
scripts/halovisor/build.sh

Use multi-arch v0.8.0-rc1 halo image as halovisor genesis. This ensures snappy e2e tests on local macs.
issue: #1984

ci(halovisor): use multiarch v080-rc1 for halovisor genesis

---

.github/workflows/check-sol-artifacts.yml
e2e/app/admin/test.go

Reset to defaults after testing rand bridge spec.
Allows bridge upgrade tests to pass. 
issue: none

test(e2e): reset to default bridge spec

---

halo/app/start.go
halo/cmd/cometconfig.go
halo/cmd/testdata/TestCLIReference_rollback.golden
halo/cmd/testdata/TestCLIReference_run.golden
halo/cmd/testdata/TestRunCmd_defaults.golden
halo/cmd/testdata/TestRunCmd_flags.golden
halo/cmd/testdata/TestRunCmd_json_files.golden
halo/cmd/testdata/TestRunCmd_toml_files.golden
halo/config/config.go
halo/config/testdata/default_halo.toml

Enable all `halo` RPCs inside docker containers. Operators can then control accessibility via bind mounts only. 
Also, serve CosmosRPC BEFORE starting cometbft to improve using them for health checks.
issue: none

ci(halo): enable RPCs for docker

---

halo/app/start.go
halo/cmd/cometconfig.go
halo/cmd/testdata/TestCLIReference_rollback.golden
halo/cmd/testdata/TestCLIReference_run.golden
halo/cmd/testdata/TestRunCmd_defaults.golden
halo/cmd/testdata/TestRunCmd_flags.golden
halo/cmd/testdata/TestRunCmd_json_files.golden
halo/cmd/testdata/TestRunCmd_toml_files.golden
halo/config/config.go
halo/config/testdata/default_halo.toml

This backports the following commits from `main` to `release/v0.8`:
- [ci(halo): enable RPCs for docker (#2036)](https://github.com/omni-network/omni/pull/2036). It is mainly backported in order to start CosmosSDK RPC servers before comet service.
issue: none

chore(halo): start RPCs before comet

---

monitor/app/app.go
monitor/contract/monitor.go

Do not exit on failed connection to staging rpc, made
when getting conrtract addrs.
Additionally, use omni evm staging rpc passed in endpoins to gen staging addresses,
to reduce chance of failed conntection.
issue: none

fix(monitor): do not exit on failed staging connection

---

halo/app/start_test.go
lib/cchain/provider.go
lib/cchain/provider/provider.go
monitor/app/app.go
monitor/app/metrics.go
monitor/app/upgrade.go

Add `monitor_planned_upgrade` metric to track planned upgrades.
issue: none

chore(monitor): instrument planned upgrades

---

.github/workflows/backport.yml

Adds an automatic backport action that only requires a label: `backport-to: release/v0.8`.
issue: none

ci(github): add automatic backport action

---

e2e/app/rpc.go
halo/cmd/cmd_internal_test.go
halo/cmd/testdata/TestCLIReference_halo.golden
lib/cmd/cmd.go

Improve binary errors when subcommands are invalid or not specified, reverting to default cobra behaviour.
issue: none

chore(lib/cmd): improve invalid command errors

---

lib/cchain/provider/abci.go

Make sure the latency function is actually called and metrics are reported.
issue: https://github.com/omni-network/omni/issues/2044

fix(lib): execute latency metric in offset history

---

monitor/xfeemngr/tokenprice/buffer.go

This PR updates the `guageBuffered` func and protects the `b.buffer` price map with the available RW mutex. 
issue: none

fix(monitor): guageBuffered unsafe read access to price map

---

Makefile

Currently, if `make build-docker` is executed on a Linux machine, `arch` returns `x86_64` which is _not_ a valid `$GOARCH` value. Instead, `amd64` should be used.
issue: none

fix(ci): docker build on x86_64 linux

---

e2e/anvilproxy/app/app.go
e2e/anvilproxy/app/proxy.go

Replaces getInstance func with stopInstance.
issue: none

fix(halo): unsafe pointer dereference

---

lib/buildinfo/buildinfo.go

Log binary os.architecture on startup of all binaries. This aids in debugging docker issues.
issue: none

chore(lib/buildinfo): log binary architecture

---

.github/workflows/backport.yml

Backport action is running on all merged PR and failing. Only run on merged PRs with `backport-to` label.
issue: none

chore(github): fix backport action

---

e2e/app/admin/planupgrade.go
e2e/app/run.go
lib/cchain/provider.go
lib/cchain/provider/abci.go
lib/cchain/provider/provider.go
lib/cchain/provider/provider_test.go
monitor/app/metrics.go
monitor/app/upgrade.go

Monitor last applied upgrade in `monitor` service. Add a method to `CProvider` to query this.
Also increase ephemeral chain plan-upgrade delay from 5 to 100 since 5 wasn't sufficient.
issue: none

chore(monitor): instrument last applied upgrade

---

docs/content/operate/3-uluwatu.md
scripts/halovisor/Dockerfile
scripts/halovisor/build.sh

Use latest release LTS v0.8.1 as halovisor genesis binary.
Also bump cosmovisor for improved logging and error handling.
issue: none

ci(halovisor): use halo v0_8_1 as genesis bin

---

docs/content/operate/1-run-full-node.md
docs/content/operate/3-uluwatu.md

Improve docs for v0.9.0 release.
Move `halo Deployment Instruction` to `Run a Full Node` since all nodes, not only validators, need to support network upgrades.
issue: none

docs(operate): improve v0-9-0 docs

---

e2e/cmd/cmd.go
halo/cmd/cmd_internal_test.go
halo/cmd/testdata/TestRunCmd_json_files.golden
lib/cmd/cmd.go

Fixes an issue introduced in #2054:
- Only `run` or root commands logged omni-style app fatal error logs
- All other commands didn't log anything when crashing.
- Now only cobra cli flags or usage issues do cli style logging, everything else is omni style.
This affects v0.9.0, but only halo subcommands like `halo rollback` or `halo init` which will not log fatal errors.
This doesn't affect omni cli thought which has custom logic
Also fixes legacy issue with `e2e` app not supporting viper (e2e vars).
issue: none

fix(lib/cmd): fix missing cli errors

---

e2e/manifests/backwards.toml

Update `backwards.toml` by doing genesis upgrade and testing backwards compatibility with v0.9.0 which is first uluwatu release. 
The `release/v0.8` branch does backwards compatibility with `v0.8.0 -> v0.8.x`
issue: none

ci(backwards): use v0-9-0 as reference

---

.github/dependabot.yml

Add ci for dependabot to open PRs for npm packages. 
issue: #2060

chore(ci): add npm dependabot config

---

contracts/allocs/allocs.go
contracts/allocs/allocs_test.go
contracts/allocs/scripts/genallocs.go
halo/genutil/evm/evm.go

Lock omega allocs to those used at deployment.
issue: none

chore(contracts/allocs): lock omega allocs to omega genesis

---

octane/evmengine/keeper/abci.go
octane/evmengine/keeper/evmmsgs.go
octane/evmengine/keeper/helpers.go
octane/evmengine/keeper/msg_server.go
octane/evmengine/keeper/proposal_server.go

Fixes a possible chain halting issue when a networking error causes fetching evm event logs to fail.
Wrap this like all other network calls inside keeper logic inside a `retryForever`.
issue: none

fix(octane/keeper): retry fecthing evm event logs

---

lib/contracts/address.go

Add mutex to caches.
issue: none

fix(lib/contracts): add mutex to caches

---

Makefile
README.md
docs/content/operate/1-run-full-node.md
docs/content/operate/3-uluwatu.md
docs/content/operate/6-config.md

Improve the raedme and the `Configure a Full Node` doc.
issue: #2114

docs(*): improve readme and operator docs

---

e2e/app/portalregistry.go

Fix wrongly assigned manager to upgrader for portal registry.
issue: none

fix(e2e): fix portal owner

---

e2e/app/admin/planupgrade.go

Sets the omega `uluwatu` network-upgrade height to 3_073_000 which is roughly 9am Mon 14 Oct EST.
issue: https://github.com/omni-network/ops/issues/499

chore(admin): set omega uluwatu upgrade height

---

contracts/core/test/script/AllocPredeploys.t.sol

Num alloc test had correct number but wrong breakdown.
- We have 5 predeploy impls (Staking, Slashing, Upgrades, PortalReg, BridgeNative)
- 15 preinstall contracts
- 1 account we bump nonce off
issue: none

test(contracts/core): fix predeploy num alloc tests

---

e2e/app/create3.go
e2e/app/definition.go
e2e/app/fund.go
e2e/app/gaspump.go
e2e/app/portalregistry.go
e2e/app/run.go
e2e/app/start.go
e2e/app/tokenbridge.go
e2e/netman/manager.go
e2e/types/testnet.go

Merges the two private/public deploy portal flows into one, since split not required anymore.
issue: #1970

refactor(e2e): merge portal deploy flow

---

lib/contracts/address.go

The PR https://github.com/omni-network/omni/pull/2140 introduced a locking around a cache. Some parts of the critical section seem unrelated to the locking and can be done before without changing the read semantics (because this check happened after the cache read before).
issue: none

chore(lib): validate inputs before locking

---

monitor/routerecon/recon.go

Reduce routescan recon loop frequency to mitigate rate limit errors.
issue: none

chore(monitor/routerecon): reduce rate limit issues

---

lib/cmd/flags.go
lib/cmd/flags_internal_test.go

Best effort redaction of tokens in URL paths.
issue: https://github.com/omni-network/ops/issues/170

chore(lib/cmd): redact rpc url tokens

---

lib/xchain/merkle_test.go

Test flapped since it sometimes didn't actually increase the index
issue: none

test(lib/xchain): fix flapping merkle test
