.github/workflows/ci-main.yml, .secrets.baseline
require e2e tests pass before goreleaser
task: none
=> ci(*): update ci-main

.github/workflows/ci-main.yml, .secrets.baseline
=> fix(ci): use needs in ci-main

.pre-commit-config.yaml, go.mod, halo/cmd/genesis.go, halo2/app/app_config.go, halo2/app/helpers.go, halo2/genutil/genutil.go, halo2/genutil/genutil_test.go, halo2/genutil/testdata/TestMakeGenesis.golden
Adds support for generating a cosmos genesis file. 
task: none
=> feat(halo/genutil): create genesis file

lib/netconf/netconf.go, lib/netconf/testdata/TestSaveLoad.golden
=> fix(lib/netconf): format period as string

relayer/app/monitor.go
debug logs for visibility 
task: none
=> chore(relayer/app): debug logs for cursor monitor

halo/app/simnet.go, halo2/app/run_test.go, lib/cchain/provider/abci.go, lib/cchain/provider/abci2.go, lib/cchain/provider/provider.go, relayer/app/app.go, test/e2e/app/monitor.go, test/e2e/tests/attestations_test.go, test/smoke/smoke_test.go
Improve cprovider logs.
task: none
=> chore(lib/cprovider): improve error logs

test/e2e/tests/attestations_test.go
Fixes flapping e2e test if submissions were slow and halo has more than 200 blocks. In which case we only fetch 100 and the test fails. Now we fetch all blocks.
task: none
=> fix(e2e/test): fetch all aggregates even if more than limit

contracts/src/protocol/OmniAVS.sol
Refactor internal delegation getters.
task: none
=> chore(contracts): refactor avs contract

contracts/package.json, contracts/pnpm-lock.yaml
Revert eigen dependencies back to default branch.
task: none
=> chore(contracts): update eigen dep branches

relayer/txmgr/metrics.go, relayer/txmgr/txmgr.go
adds more metrics for txmgr 
task: none
=> feat(relayer/txmgr): additional txmgr metrics

relayer/app/monitor.go
=> fix(relayer/app): use tickers

test/e2e/manifests/simple.toml, test/e2e/manifests/staging.toml
Fix staging and simple manifests.
task: none
=> chore(test/e2e): fix manifests

contracts/script/eigen/deploy-eigenlayer-save-anvil-state.sh
Update anvil eigen script to output the file to `/test/e2e/app/static/el-anvil-state.json`
task: none
=> chore(contracts): update anvil dump script

.github/workflows/ci-pr.yml, .github/workflows/e2etest.yml, .github/workflows/goreleaser.yml, .github/workflows/gotest.yml
testing them on a pr first
task: none
=> test(ci): namespace runners

halo/app/start_test.go, halo/attest/keeper/keeper.go, lib/cchain/provider.go, lib/cchain/provider/metrics.go, lib/cchain/provider/provider.go, lib/cchain/provider/provider_test.go, lib/txmgr/txmgr.go, lib/xchain/provider.go, lib/xchain/provider/provider.go, relayer/app/metrics.go, relayer/app/opsender.go, relayer/app/relayer.go, relayer/app/relayer_test.go, relayer/app/worker.go, scripts/build_docker.sh, test/e2e/app/contract.go
Improve relayer logging and metrics.
task: none
=> chore(relayer): improve logging

test/e2e/netman/avs/xdapp.go
Add empty allowlist to avs initialze params.
task: none
=> fix(test/e2e): add allowlist to avs init

contracts/src/protocol/OmniAVS.sol
Move admin funcs to bottom of avs contract.
task: none
=> chore(contracts): move avs admin funcs down

test/e2e/docker/testdata/TestComposeTemplate_image_tag_7d1ae53.golden, test/e2e/docker/testdata/TestComposeTemplate_image_tag_main.golden, test/e2e/vmcompose/testdata/TestSetup_127_0_0_1_compose.yaml.golden, test/e2e/vmcompose/testdata/TestSetup_127_0_0_2_compose.yaml.golden
Fix failing golden tests due to broken automerge.
task: none
=> fix(e2e): fix failing tests

test/e2e/app/contract.go, test/e2e/app/wait.go
Decrease debug logs waiting for slow txs.
task: none
=> chore(e2e): decrease e2e debug logs

halo/app/start_test.go, halo/attest/keeper/cpayload.go, halo/attest/keeper/cpayload_internal_test.go, halo/attest/types/translate.go, halo/attest/types/tx.go, halo/attest/types/tx.pb.go, halo/attest/types/tx.proto, halo/attest/voter/vote.go, lib/cchain/provider.go, lib/cchain/provider/abci.go, lib/cchain/provider/provider.go, lib/cchain/provider/provider_test.go, lib/xchain/types.go, relayer/app/creator.go, relayer/app/creator_test.go, relayer/app/types.go, relayer/app/types_test.go, relayer/app/worker.go, relayer/app/worker_test.go, test/e2e/app/monitor.go, test/e2e/tests/attestations_test.go
Follow up PR to rename xchain types to align with attest module renaming.
task: none
=> refactor(lib/xchain): rename xtypes to align with attest module

halo/app/app.go, halo/app/start.go, halo/attest/keeper/keeper.go, halo/attest/keeper/metrics.go, halo/attest/module/module.go, halo/attest/types/types.go, halo/attest/voter/metrics.go, lib/netconf/netconf.go
Fix attestation approval to not skip heights when approving. Height X+1 must not be approved until height X is approved.
Also add approved height metric. 
task: none
=> fix(halo/attest): fix approve bug and add metric

test/e2e/app/math.go, test/e2e/app/run.go, test/e2e/netman/pingpong/pingpong.go
Following up on PR #378 and #376 
task: none
=> chore(e2e): e2e test nits

contracts/package.json, contracts/src/pkg/XApp.sol
Add initial XApp contract. XApp is the base contract for user omni applications.
task: none
=> feat(contracts): add XApp utility contract

docs/site/docs/home.md, docs/site/docs/operate/run.md, docs/site/docs/use/overview.md, docs/site/docs/use/protocol.md
- add banner
- fix a couple sections
task: none
=> docs(home): update some initial docs

halo/README.md
Adds a basic halo readme which describes the consensus flow.
task: none
=> chore(halo): describe basic consensus flow

contracts/package.json, contracts/src/examples/PingPong.sol, contracts/src/pkg/XApp.sol, docs/site/docs/develop/xapp.md
Rename xfunc to xrecv
task: none
=> feat(contracts): rename xfunc to xrecv

docs/site/docs/protocol/overview.md
Clarify fees are permanently in ETH
task: https://app.asana.com/0/1206684215872507/1206684219212568/f
=> chore(docs): fee payment information in protocol overview

test/e2e/vmcompose/provider.go
Fixes e2e upgrade command. Copied paths were not correct, and we need to use sudo for everything.
task: none
=> fix(e2e): fix upgrade command

test/e2e/tests/e2e_test.go
Fixed merge issue and test run in main
task: none
=> test(e2e): fix test failure in main

test/e2e/app/test.go, test/e2e/tests/e2e_test.go
Increase e2e test timeout to 60 sec
task: none
=> test(e2e): increase e2e timeout to 60sec

docs/site/docs/develop/contracts.md
Fix outdated code snippet.
task: none
=> fix(docs): update outdated code snippet

README.md
Remove explorer from readme before it's ready.
task: none
=> docs(readme): remove explorer reference

README.md
update devnet instructions for latest makefile commands.
task: none
=> docs(readme): update devnet instructions

contracts/Makefile, contracts/genbindings.go
Add go:generate directive for contract bindings.
task: none
=> chore(contracts): go generate directive for bindings

docs/site/docs/develop/xapp/example.md, docs/site/docs/develop/xapp/fees.md, docs/site/docs/develop/xapp/gas.md
=> chore(docs): revise xapp docs

test/e2e/vmcompose/provider.go
Disable gcloud prompts when running the e2e deploy command.
task: none
=> fix(e2e): disable gcloud prompt

test/e2e/netman/avs/types.go, test/e2e/netman/avs/xdapp.go
Remove MinOperatorStake and MaxOperatorCount from AVS initializer.
task: none
=> fix(test/e2e): fix avs initializer

docs/site/docs/develop/xapp/installation.md
Fix xapp forge import.
task: none
=> chore(docs): fix xapp forge import

docs/site/docs/develop/xapp/fees.md
Revise docs on charging xcall fees to the caller, rather than the contract. 
task: none
=> chore(docs): revise docs on charging fees to caller

halo/evmengine/keeper/msg_server.go
Fix optimistic block timestamp bug
task: none
=> fix(halo/evmengine): fix optimistic block timestamp

.github/CODEOWNERS
=> chore(*): modify codeowners

contracts/Makefile
Enforce abigen version used for bindings.
task: none
=> chore(contracts): enforce abigen version

Makefile, cli/cmd/cmd.go, cli/cmd/devnet.go
`omnicli` -> `omni`
task: none
=> chore(cli): use omni for cli

.secrets.baseline, cli/cmd/devnet.go, cli/cmd/register.go, lib/avs/avs.go, lib/avs/avs_test.go, lib/avs/deployer.go, lib/avs/eigen.go, lib/ethclient/ethbackend/backend.go, lib/ethclient/ethbackend/backend_internal_test.go, lib/ethclient/ethbackend/backends.go, lib/ethclient/ethbackend/wait.go, test/e2e/app/contract.go, test/e2e/app/definition.go, test/e2e/netman/avs/xdapp.go, test/e2e/netman/helpers.go, test/e2e/netman/manager.go, test/e2e/netman/pingpong/pingpong.go
Move backends from `test/e2e/backend` to `lib/ethcient/ethbackend`. 
task: none
=> refactor(lib/ethbackend): move backends out of test

test/e2e/app/run.go
Increase number of ping pongs so staging always has messages.
task: none
=> ci(e2e): more ping pong

.goreleaser.yaml, monitor/Dockerfile, monitor/app/app.go, monitor/app/config.go, monitor/avs/avs.go, monitor/avs/metrics.go, monitor/avs/monitor.go, monitor/cmd/cmd.go, monitor/cmd/flags.go, monitor/main.go
Introduce monitor service, add avs monitoring.
task: https://app.asana.com/0/1206208509925075/1206650262528026
=> feat(monitor): add avs contract monitoring

README.md
Fix the readme's workflow widget
task: none
=> fix(readme): use updated workflow in readme

monitor/app/app.go, monitor/avs/avs.go, monitor/cmd/flags.go, relayer/app/app.go, test/e2e/app/definition.go
Monitor avs contract in relayer.
- hardcode avs addrs
- monitor testnet avs in staging relayer
task: https://app.asana.com/0/1206208509925075/1206648863973026
=> feat(monitor): monitor avs in relayer

README.md
badges don't work with reusable workflows
task: none
=> fix(readme): use ci release in readme badge

.secrets.baseline, lib/avs/avs_test.go, lib/avs/eigen.go
Use big.Int wei amounts in avs tests.
- move DelegateWETH to test package
task: none
=> chore(lib/avs): denominate amounts in wei

.goreleaser.yaml
This PR published releases automatically without using draft releases.
task: none
=> ci(release): auto-publish releases

lib/avs/avs.go
Check receipt status on avs registration / deregistration.
task: none
=> fix(lib/avs): check receipt status on register and deregister

.goreleaser.yaml
Reverts omni-network/omni#521
task: none
=> ci(release): revert auto-publish releases

docs/site/docs/operate/testnet/register.md
removes need for flag decl
task: none
=> chore(docs): update avs operator register

docs/site/docs/operate/testnet/install.md, docs/site/docs/operate/testnet/introduction.md, docs/site/docs/operate/testnet/register.md
some small updates to the operator section
task: none
=> chore(docs): operator updates

test/e2e/vmcompose/provider.go
Save bash commands as bash tmp files to avoid escape hell and inconsistencies between GNU and BSD bash.
task: https://app.asana.com/0/1206208509925075/1206729533969894/f
=> fix(e2e): upgrade command

.golangci.yml, cli/cmd/cmd.go, cli/cmd/errors.go, cli/cmd/omni/main.go, cli/cmd/register.go, lib/avs/avs.go, lib/avs/avs_test.go, lib/cmd/cmd.go, lib/errors/errors.go, lib/log/config.go, lib/log/logger.go, lib/log/testdata/TestSimpleLogs_cli.golden
Improve cli error messages.
- reduce nested wrapped errors
- use noop logger
- print friendly error messages w/ suggestions
task: https://app.asana.com/0/1206208509925075/1206779091198084
=> feat(cli): improve cli error messages

test/e2e/manifests/staging.toml
Remove arb goerli from staging.
task: none
=> chore(ci): remove arb goerli from staging

.golangci.yml, halo/attest/keeper/builder_test.go, halo/attest/keeper/common_test.go, halo/attest/keeper/keeper.go, halo/attest/keeper/keeper_test.go, halo/attest/testutil/mock_interfaces.go
This PR adds unit tests for the attestation keeper's Approve method.
task: https://app.asana.com/0/0/1206715268196568/f
=> test(halo/attest): add attestation keeper approve tests

monitor/avs/avs.go, monitor/avs/metrics.go, monitor/avs/monitor.go
Add more avs metrics.
- owner
- paused
- allowlistEnabled
- strategyParams
task: none
=> feat(monitor/avs): add more metrics

halo/attest/keeper/keeper_test.go
Fixing failing tests in main
task: none
=> test(halo/attest): fix failing tests

monitor/avs/avs.go, monitor/avs/monitor.go
Hardcode staging goerli avs monitor. 
task: none
=> chore(monitor): hardcode goerli staging avs monitor

lib/log/logger.go, lib/log/testdata/TestSimpleLogs_cli.golden
remove the inline prop
task: none
=> fix(lib/log): change the cli log 

cli/cmd/cmd.go
updates help text for wider audience
task: https://app.asana.com/0/1206798996317802/1206817053037169/f
=> chore(cli): help text

.github/workflows/ci-main.yml, .github/workflows/ci-pr.yml, .github/workflows/clitest.yml, .secrets.baseline, scripts/install_omni_cli.sh
- adds wf file to test cli install across operating systems
- updates install script to handle windows, and fix ubuntu installs
task: https://app.asana.com/0/1206208509925075/1206806971862710/f
=> fix(cli): install script and testing

docs/site/docs/home.md, docs/site/docs/learn/introduction/introduction.md
Revises intro section in docs to direct readers to section most relevant to their profile
task: https://app.asana.com/0/1206684215872507/1206684219212568/f
=> chore(docs): revise home section

docs/site/docs/operate/testnet/register.md
Changed file extension from yml to yaml
task: none
=> fix(docs): change file ext to yaml

halo/app/app_config.go, halo/app/logging.go, halo/evmstaking/evmstaking.go, halo/genutil/genutil.go, halo/genutil/testdata/TestMakeGenesis.golden, test/e2e/app/valupdates.go, test/e2e/manifests/ci.toml
Fixes evmstaking event processor
task: none
=> feat(halo/evmstaking): fix evmstaking event processor

lib/xchain/provider/fetch.go
We are seeing errors for get block and we aren't seeing any useful logs 
task: none
=> chore(lib/xchain): add debug to get block

test/e2e/manifests/staging.toml
Remove arb sepolia from staging
task: none
=> chore(test/e2e): remove arb sepolia

cli/cmd/cmd.go, cli/cmd/develop.go, cli/cmd/flags.go
Adds command to scaffold a new omni project using the forge template.
task: https://app.asana.com/0/1206684215872507/1206684219212562/f
=> feat(cli): scaffold forge project

contracts/Makefile, contracts/bindings/create3.go, test/e2e/app/create3.go, test/e2e/cmd/cmd.go, test/e2e/cmd/flags.go
Add Create3 deploy command.
task: https://app.asana.com/0/1206208509925075/1206874791954734
=> feat(test/e2e): add create3-deploy command

docs/release.md
adds a doc outlining the release process
task: https://app.asana.com/0/1206684215872507/1206768819911491/f
=> docs(release): add release doc

e2e/app/definition.go, e2e/app/monitor.go, e2e/app/run.go, e2e/app/valupdates.go, e2e/test/e2e_test.go, explorer/indexer/app/app.go, halo/app/start.go, halo/cmd/init.go, lib/netconf/netconf.go, lib/netconf/testdata/TestSaveLoad.golden, lib/xchain/provider.go, lib/xchain/provider/fetch.go, lib/xchain/provider/provider.go, relayer/app/app.go, relayer/app/creator.go, relayer/app/cursors.go, relayer/app/monitor.go, relayer/app/opsender.go, relayer/app/worker.go
Adds the omni consensus chain to:
- xprovider
- netconf
Also updates relayer to support broadcast.
task: none
=> feat(lib/xchain): add omni consensus chain to xprovider

e2e/types/testnet.go, lib/ethclient/ethbackend/backends.go
fixes choosing val geth
task: none
=> fix(e2e/types): fix choosing val geth

.secrets.baseline, e2e/app/definition.go, e2e/app/run.go, e2e/docker/docker.go, e2e/netman/pingpong/pingpong.go
Refactor monitor-only logic to have less inline branching. Prefer splitting logic: ``if OnlyMonitor, do something else and return"
task: none
=> chore(e2e): improve monitor only logic

docs/site/docs/learn/omni/testnet.md
Add section in learn for users wondering how to stake
task: https://app.asana.com/0/1206684215872507/1206862901604363/f
=> docs(learn): add section for testnet

.secrets.baseline, lib/anvil/accounts.go, lib/contracts/avs/avs_test.go, lib/contracts/avs/deploy.go, lib/contracts/create3/deploy.go, lib/contracts/create3/utils.go, lib/contracts/create3/utils_test.go, lib/contracts/proxyadmin/deploy.go, lib/contracts/proxyadmin/deploy_test.go, lib/contracts/static.go, lib/contracts/utils.go, lib/tutil/tmpdir.go
Deploy ProxyAdmin via Create3 factory
task: none
=> feat(lib/contracts): use create3 for proxy admin deployments

e2e/manifests/staging.toml
Adds seed node and a non-validator node to staging
task: none
=> chore(e2e/manifest): staging seed and non-validator nodes

e2e/vmcompose/provider_internal_test.go, e2e/vmcompose/testdata/TestSetup_127_0_0_3_compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127_0_0_4_compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127_0_0_5_compose.yaml.golden
updating tests to match updated `staging.manifest` file
task: none
=> test(e2e): fixing vm compose for seed and full nodes

lib/contracts/portal/deploy.go, lib/contracts/portal/deploy_test.go, lib/contracts/proxyadmin/deploy_test.go, lib/contracts/static.go
Add Create3 portal deployments
task: https://app.asana.com/0/1206208509925075/1206874791954734
=> feat(lib/contracts): add portal create3 deployments

.secrets.baseline, lib/contracts/portal/deploy.go, lib/contracts/proxyadmin/deploy.go, lib/contracts/static.go, lib/contracts/utils.go, lib/contracts/utils_test.go
Derive static Create3 addresses per each network
task: https://app.asana.com/0/1206208509925075/1206874791954734
=> feat(lib/contracts): derive create3 addresses

docs/site/docs/develop/testnet/resources.md, docs/site/docs/operate/testnet/client.md
Fix broken table in developer resources and emphasize token name in operator client run page
task: none
=> docs(testnet): resources fixes and token name bold

e2e/app/valupdates.go, lib/fireblocks/account.go, lib/fireblocks/client.go, lib/fireblocks/client_test.go, lib/fireblocks/config.go, lib/fireblocks/gettransaction.go, lib/fireblocks/sign.go, lib/fireblocks/supportedassets.go, lib/fireblocks/types.go
Always use prod url. Improve error handling.
task: none
=> fix(lib/fireblocks): fix host url

e2e/app/valupdates.go
Fixes failing e2e test.
task: none
=> test(e2e): fix regression

docs/site/docs/protocol/audits.md
Add page on audtis in protocol section
task: none
=> docs(protocol): audits page

lib/contracts/avs/stategies.go
Add holeksy strategy parameters.
task: https://app.asana.com/0/1206208509925075/1206799371205484
=> feat(lib/contracts): add holesky strategy params

.secrets.baseline, e2e/app/fund.go, e2e/app/run.go, lib/anvil/accounts.go, lib/anvil/utils.go, lib/contracts/avs/deploy.go, lib/contracts/create3/deploy.go, lib/contracts/portal/deploy.go, lib/contracts/proxyadmin/deploy.go
Add staging deployment config for each contract.
task: none
=> fix(e2e): fix staging deployments

.secrets.baseline, e2e/app/definition.go, e2e/cmd/cmd.go, e2e/vmcompose/provider_test.go, lib/fireblocks/account.go, lib/fireblocks/client.go, lib/fireblocks/client_test.go, lib/fireblocks/config.go, lib/fireblocks/sign.go
Adds a `omni e2e <command> <network>` signing not fireblock signing requests. 
Also fix cache population race.
task: none
=> fix(lib/fireblocks): add signing note

lib/contracts/portal/deploy.go
Fix staging expected portal address.
task: none
=> fix(lib/contracts): fix staging expected portal addr

lib/contracts/create3/deploy.go
Check create3 bytecode against deployed bytecode.
task: none
=> feat(lib/contracts): fix create3 bytecode check

halo/genutil/evm/evm.go, halo/genutil/evm/testdata/TestMakeGenesis.golden
Increase dev account funds on staging.
task: none
=> chore(ci/staging): increase staging account funds

contracts/Makefile, e2e/app/avs.go, e2e/app/definition.go, e2e/manifests/testnet.toml, e2e/netman/manager.go, e2e/types/chain.go, e2e/types/testnet.go, lib/chainids/chainids.go, lib/contracts/addrs.go, lib/ethclient/ethbackend/backends.go
Prep avs-deploy script for tesnet holesky deployment.
task: https://app.asana.com/0/1206208509925075/1206799371205484
=> chore(contracts): prep avs-deploy script for testnet

lib/contracts/addrs.go
Update tesnet deployer and admin addresses.
task: https://app.asana.com/0/1206208509925075/1206799371205484
=> chore(lib/contracts): update testnet deploy and admin addrs

cli/cmd/register.go
Add holesky avs address to cli.
task: https://app.asana.com/0/1206208509925075/1206799371205484
=> chore(cli): add holesky avs address

e2e/app/definition.go
Fix network setup during monitor deployment.
task: none
=> fix(monitor): fix monitor setup

lib/contracts/avs/deploy.go, lib/contracts/avs/stategies.go
#makeethereumtestnetseasiertospellandsay
task: none
=> fix(lib): holesky spelling

halo/config/testdata/default_halo.toml, lib/buildinfo/buildinfo.go, monitor/app/testdata/default_monitor.toml, relayer/app/testdata/default_relayer.toml
bump new patch version for CLI
task: none
=> chore(cli): bump patch version

docs/site/docs/learn/testnet/testnet.md, docs/site/docs/operate/testnet/register.md
add avs holesky address and el holesky dashboard to docs
task: https://app.asana.com/0/1206684215872507/1206862901604365/f
=> docs(testnet): add el dashboard and holesky avs address

e2e/netman/manager.go
Add debug logs for insuffient funds in e2e app.
task: none
=> test(e2e): add debug logs for insufficient funds issue

e2e/app/fund.go
Increases funded anvil account balances from 1ETH to 1_000_000 ETH
task: none
=> test(e2e): increase anvil funded amount

e2e/app/fund.go
1M is maybe too much, decreasing to 1k
task: none
=> test(e2e): decrease anvil funded balance

e2e/app/fund.go
=> fix(e2e): decrease anvil funding

e2e/app/fund.go
=> fix(e2e): fix anvil fund type

lib/anvil/anvil.go, lib/anvil/utils.go, lib/anvil/utils_test.go, lib/contracts/avs/avs_test.go, lib/contracts/portal/deploy_test.go, lib/contracts/proxyadmin/deploy_test.go
Fix anvil.FundBalance amount encoding.
task: none
=> fix(e2e): fix fund anvil amt encoding

e2e/types/chain.go, lib/netconf/static.go, monitor/avs/avs.go
Set AVS contract address.
task: none
=> fix(monitor): fix-avs-contract-addr

e2e/netman/manager.go, lib/buildinfo/buildinfo.go, lib/contracts/addrs.go, lib/contracts/portal/deploy.go
Make sure unique portals are deployed each staging run.
task: none
=> fix(e2e): unique portal staging deployments

contracts/test/utils/MockPortal.sol
Passes reverts for mock portal mockxcalls, and removes an unnecessary line of code
task: none
=> fix(contracts): pass revert for mock portal

e2e/app/key/gcp.go, e2e/app/key/key_internal_test.go, e2e/app/key/key_test.go, e2e/app/key/upload.go, e2e/cmd/cmd.go, e2e/docker/compose.yaml.tmpl, e2e/docker/docker.go, e2e/docker/docker_internal_test.go, e2e/docker/testdata/TestComposeTemplate_image_tag_7d1ae53.golden, e2e/docker/testdata/TestComposeTemplate_image_tag_main.golden, e2e/vmcompose/testdata/TestSetup_127_0_0_1_compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127_0_0_2_compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127_0_0_4_compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127_0_0_5_compose.yaml.golden, halo/genutil/evm/evm.go, relayer/app/sender.go
Fix parsing of gcp secret response using explicit json.
Also:
- Add explicit geth tag
- Add debug info to relayer submit revert errors.
task: none
=> fix(e2e/key): fix parsing of secret response

halo/evmengine/keeper/abci.go, halo/evmengine/keeper/abci_internal_test.go, halo/evmengine/keeper/msg_server.go, halo/evmengine/keeper/msg_server_internal_test.go, halo/evmengine/keeper/proposal_server_internal_test.go, halo/genutil/evm/evm.go, halo/genutil/evm/testdata/TestMakeGenesis.golden, lib/ethclient/enginemock.go
Enable cancun hardfork in geth and upgrade EngineAPI to V3.
task: none
=> refactor(lib/ethclient): upgrade engine api to cancun

explorer/Makefile
Fixing make commands to run explorer locally
task: none
=> chore(explorer): fix make commands

e2e/manifests/staging.toml
changing mode to full, isolating the seed mode p2p problem
task: none
=> fix(e2e/manifest): seed to full mode

e2e/vmcompose/provider.go, monitor/loadgen/stake.go
Add missing config files to upgrade command.
Also check balance before self-delegation.
task: none
=> ci(e2e): improve upgrade command

halo/genutil/evm/evm.go, halo/genutil/evm/testdata/TestMakeGenesis.golden, lib/contracts/addrs.go
Use fireblocks staging addrs for staging deployments, rather than fireblocks dev.
task: none
=> chore(lib/contracts): update staging addrs

lib/ethclient/ethbackend/backend.go
Improve ethbackends error logs by including dest chain and from addr.
task: none
=> chore(lib/ethbackend): add dest chain and from addr log attrs

e2e/app/fund.go
Always fund fb dev account on anvil chains.
task: none
=> fix(e2e): always fund fireblocks dev account

.goreleaser.yaml, e2e/docker/compose.yaml.tmpl, e2e/docker/docker.go, e2e/docker/testdata/TestComposeTemplate_main_explorer.golden, e2e/vmcompose/provider.go, e2e/vmcompose/testdata/TestSetup_127_0_0_6_compose.yaml.golden
deploy x chain explorer
task: none
=> chore(ci): deploy x explorer

.goreleaser.yaml, e2e/docker/compose.yaml.tmpl, e2e/docker/testdata/TestComposeTemplate_main_explorer.golden, e2e/vmcompose/testdata/TestSetup_127_0_0_6_compose.yaml.golden
Remove X Explorer UI
task: none
=> fix(ci): remove explorer ui

.secrets.baseline, e2e/manifests/testnet.toml
* Add testnet nodes definition
* Created long-lived keys
task: none
=> chore(testnet): adjust testnet manifest

monitor/account/account.go, monitor/account/metrics.go, monitor/account/monitor.go, monitor/app/app.go
Adds account balance monitoring to monitor service
task: https://app.asana.com/0/1206208509925075/1206990249521844
=> feat(monitor): monitor watches account balances

e2e/netman/manager.go
Add relayer key to testnet.
task: none
=> fix(e2e/netman): add testnet relayer key

lib/chainids/chainids.go, lib/netconf/static.go
Add omni chain ids to lib/chainids.
This allows lib/contracts deployments to deploy to omni testnet.
task: none
=> feat(lib/chainids): add omni chain ids

lib/log/log.go
Fixes two problems with logging library:
- `source` was always the logging library itself. So implement our own `low level log` func to use correct pc.
- `stacktrace` was always the last stace trace in the cause chain. Instead, use the first.
task: none
=> fix(lib/log): fix logging source and stack traces

e2e/types/chain.go
Change to finalized instead of latest
task: none
=> fix(e2e/types): fix holesky finalization strategy

monitor/account/account.go, monitor/account/metrics.go, monitor/account/monitor.go
adds the type of address to the monitor
task: none
=> chore(monitor/account): add type to account monitor

e2e/manifests/testnet.toml
add op, arb sepolia to testnet manifest
task: none
=> chore(e2e/manifest): add op and arb

lib/ethclient/ethbackend/backends.go
increase fireblocks timeout to 5 mins
task: none
=> chore(lib): increase fb timeout

halo/genutil/evm/evm.go
label addresses and put them in the same section
task: none
=> chore(e2e): cleanup testnet addrs

e2e/vmcompose/provider.go
Fixes "concurrent ssh key generation issue" by first doing sequential ssh to each VM to ensure everything is good, then do all upgrade in parallel.
task: none
=> ci(e2e): fix concurrent ssh upgrade issue

.github/workflows/release-snapshot.yml
Use GitHub action template variable and not bash interpolation.
task: none
=> fix(ci): fix indexer-ui docker push

.secrets.baseline, e2e/app/definition.go, e2e/app/run.go, e2e/app/setup.go, e2e/cmd/cmd.go, e2e/cmd/flags.go, e2e/docker/compose.yaml.tmpl, e2e/docker/docker.go, e2e/docker/docker_test.go, e2e/docker/testdata/TestComposeTemplate_empheral_network.golden, e2e/docker/testdata/TestComposeTemplate_main_explorer.golden, e2e/types/manifest.go, e2e/types/testnet.go, e2e/vmcompose/provider.go, e2e/vmcompose/testdata/TestSetup_127_0_0_6_compose.yaml.golden, explorer/graphql/app/config.go, explorer/graphql/app/config.toml.tmpl, explorer/graphql/app/testdata/default_explorer_graphql.toml, explorer/indexer/app/config.go, explorer/indexer/app/config.toml.tmpl, explorer/indexer/app/testdata/default_explorer_indexer.toml
Fixes duplicate explorer DB connection flag in e2e app. Also refactor e2e deploy config a little.
task: none
=> ci(e2e): fix explorer db conn flag

e2e/app/run.go, e2e/netman/pingpong/pingpong.go
=> chore(e2e): fix pong pong args

e2e/docker/compose.yaml.tmpl, e2e/docker/testdata/TestComposeTemplate_empheral_network.golden
IP address conflicts
task: none
=> fix(explorer/db): fix docker db ip address

.github/workflows/release-official.yml
copying explorer ui build and push action from snapshot to release
task: none
=> feat(explorer/ui): adding build and push explorer ui action

explorer/graphql/app/schema.graphql, explorer/graphql/data/message_provider.go, explorer/graphql/resolvers/blocks.go, explorer/graphql/resolvers/messages.go, explorer/graphql/resolvers/messages_test.go, explorer/graphql/resolvers/types.go, explorer/ui/app/graphql/graphql.ts
xmsg(sourceChainID, destChainID, streamOffset)
task: https://app.asana.com/0/1206208509925075/1206970544933854
=> feat(explorer/graphql): xmsg query

e2e/app/monitor.go, e2e/test/attestations_test.go, halo/app/start.go, halo/app/start_test.go, lib/cchain/provider/abci.go, lib/cchain/provider/provider.go, lib/ethclient/ethclient_gen.go, lib/ethclient/genwrap/genwrap.go, lib/ethclient/metrics.go, lib/expbackoff/expbackoff.go, lib/netconf/netconf.go, lib/netconf/netconf_test.go, lib/tracer/rooted.go, lib/tracer/trace.go, lib/tracer/trace_test.go, lib/xchain/provider/fetch.go, lib/xchain/provider/provider.go, relayer/app/app.go
Improve tracing:
- Correlate traces for each protected network+chain+height
- Separate traces for ephemeral networks
- Add tracing to ethclient.
- Add semconv fields.
task: none
=> chore(lib/tracing): improve tracing

cli/cmd/register.go, contracts/script/DeployAVS.sol, lib/netconf/static.go
Add mainnet avs address, and its proxy admin address.
task: none
=> chore(cli): add mainnet avs and proxy admin addrs

halo/config/testdata/default_halo.toml, lib/buildinfo/buildinfo.go, monitor/app/testdata/default_monitor.toml, relayer/app/testdata/default_relayer.toml
Bump buildinfo version to 0.1.3
task: none
=> chore(lib/buildinfo): bump version

lib/xchain/provider/fetch.go, lib/xchain/provider/provider.go
Optimise xprovider `FetchBlock`:
- Previously, we did 4 sequential queries (in most cases):
- HeaderByType
- HeaderByNumber (only avoided for slow single finalising chains)
- FilterXmsgLogs
- FilerXReceiptLogs
- Now we do 3 parallel queries:
- Used cached HeaderByType
- Query HeaderByNumber, FilterXmsgLogs, FilerXReceiptLogs in parallel.
This should reduce fetch block latencies by around 3x-4x, especially for L2s that finalise in batches and for relayer which often lags a bit.
task: none
=> chore(lib/xchain): optimise fetching xblocks

lib/txmgr/metrics.go, relayer/app/metrics.go
Fixed incorrect prometheus functions to calculate histogram buckets.
task: none
=> fix(prometheus): fix histogram buckets

halo/attest/voter/voter.go
Fix `voter.ValidatorUpdates` logic: `isValidator=power>0`.
task: none
=> fix(halo/voter): fix val update logic

lib/netconf/static.go
bump for testnet deploy
task: none
=> chore(netman): bump portal version

lib/netconf/static.go
=> chore(netman): rm old portal address

.secrets.baseline, e2e/app/eoa/eoa.go, e2e/app/setup.go, e2e/app/test.go, e2e/manifests/mainnet.toml, e2e/netman/manager.go, e2e/types/chain.go, halo/cmd/init.go, halo/genutil/evm/evm.go, lib/chainids/chainids.go, lib/netconf/netconf.go, lib/netconf/netconf_test.go, lib/netconf/network.go, lib/netconf/static.go, monitor/account/monitor.go, monitor/app/avssync.go
Add monitor only mainnet manifest.
task: none
=> chore(e2e): add mainnet monitor manifest

e2e/app/geth/types.go, e2e/docker/testdata/TestComposeTemplate_commit_no_explorer.golden, e2e/docker/testdata/TestComposeTemplate_empheral_network.golden, e2e/docker/testdata/TestComposeTemplate_main_explorer.golden, e2e/vmcompose/testdata/TestSetup_127_0_0_1_compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127_0_0_2_compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127_0_0_4_compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127_0_0_5_compose.yaml.golden
Bumps global geth version to latest. 
Unblocks PRs: 
#868 
#867 
task: none
=> chore(e2e): bump geth version

explorer/docker-compose.yml, explorer/indexer/app/app.go, explorer/indexer/app/cursor_test.go, explorer/indexer/app/db.go
fixing cursor height for non-zero chains
task: https://app.asana.com/0/1206208509925075/1207056323965423
=> feat(explorer/indexer): cursor height fix

docs/site/package.json, docs/site/pnpm-lock.yaml
Bumps docusaurus versions
task: none
=> docs(version): bump docusaurus versions

halo/genutil/evm/evm.go
Adds an address to the funded testnet address list
task: none
=> chore(halo/evm): testnet balance user

cli/cmd/register.go, go.mod, go.sum
upgraded github.com/Layr-Labs/eigenlayer-cli v0.7.2 => v0.7.3
task: none
=> chore(gomod): bump eigenlayer-cli version

explorer/graphql/app/schema.graphql, explorer/graphql/data/block_provider.go, explorer/graphql/data/message_provider.go, explorer/graphql/data/provider_helpers.go, explorer/graphql/data/receipt_provider.go, explorer/graphql/resolvers/messages.go, explorer/graphql/resolvers/messages_test.go, explorer/graphql/resolvers/root.go, explorer/graphql/resolvers/types.go, explorer/graphql/utils/hexHelper.go
cursor based message pagination
task: https://app.asana.com/0/1206208509925075/1207080746947777
=> feat(explorer/graphql): message pagination

contracts/Makefile
Infura now supports holesky.
task: none
=> chore(contracts): change holesky rpc to infura

halo/app/cmtlog.go, halo/app/sdklog.go, lib/cmd/flags.go
Remove super noisy cometbft logs. Improve flag redact logic.
task: none
=> chore(*): tiny logging improvements

docs/site/docs/learn/omni/token/token.md, docs/site/docs/protocol/xmessages/fees/native.md, docs/site/src/css/custom.css
Style fixes for dark mode search results modal and better token info discoverability
task: none
=> docs(fix): style and token info discoverability

e2e/app/fund.go
more ctx in the log
task: none
=> chore(e2e/fund): more logs

e2e/app/valupdates.go
Add debug logging in order to figure out why e2e ci.toml sometimes fail while depositing validator updates with "[insufficient balance](https://github.com/omni-network/omni/actions/runs/8756642929/job/24033879825)".
task: none
=> ci(e2e): improve funding validator update logging

halo/genutil/evm/evm.go
Updated an address on the funded testnet address list
task: none
=> chore(halo/evm): testnet address update

halo/app/start.go, halo/cmd/cometconfig.go, halo/cmd/testdata/TestRunCmd_defaults.golden, halo/cmd/testdata/TestRunCmd_flags.golden, halo/cmd/testdata/TestRunCmd_json_files.golden, halo/cmd/testdata/TestRunCmd_toml_files.golden, halo/evmengine/keeper/msg_server.go, halo/genutil/genutil.go, halo/genutil/testdata/TestMakeGenesis.golden, lib/netconf/static.go
Improve halo config:
- comet/config.toml: 
- increased chunk timeout
- nop mempool
- cosmos genesis:
- sashing window: 100 -> 1000 since we are faster than normal 6s blocks.
- custom max validators
task: none
=> chore(halo): improve halo config

e2e/app/valupdates.go
Add debug more logs to figure out why self-delegation sometimes fails. Also add some waits and retries.
task: none
=> ci(e2e): add more debug logging for flapping test

e2e/app/geth/config.go, e2e/app/geth/testdata/TestWriteConfigTOML_archive.golden, e2e/app/geth/testdata/TestWriteConfigTOML_full.golden, e2e/app/geth/types.go, e2e/docker/testdata/TestComposeTemplate_commit_no_explorer.golden, e2e/docker/testdata/TestComposeTemplate_empheral_network.golden, e2e/docker/testdata/TestComposeTemplate_main_explorer.golden, e2e/vmcompose/testdata/TestSetup_127_0_0_1_compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127_0_0_2_compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127_0_0_4_compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127_0_0_5_compose.yaml.golden, go.mod, go.sum, lib/ethclient/ethbackend/backend.go, lib/ethclient/fuzz.go
Upgrade geth to v1.14.0
task: none
=> chore(deps): upgrade geth to v1_14_0

explorer/db/testutil.go, explorer/graphql/app/schema.graphql, explorer/graphql/data/message_provider.go, explorer/graphql/resolvers/messages_test.go, explorer/graphql/resolvers/types.go
adding previous cursor and fixing cursor indices 
task: https://app.asana.com/0/1206208509925075/1207157766307988
=> fix(explorer/graphql): fixing cursors

e2e/test/portals_test.go
Update test case comment.
task: none
=> chore(e2e): update test comment

.github/CODEOWNERS
Adds Dennis as EU timezone code-owner with Corver.
task: none
=> ci(github): update code owners

e2e/app/definition.go, e2e/test/e2e_test.go, explorer/indexer/app/chain_test.go, explorer/indexer/app/cursor_test.go, halo/cmd/init.go, lib/netconf/netconf.go, lib/netconf/static.go, lib/netconf/testdata/TestSaveLoad.golden, monitor/account/account.go, monitor/account/monitor.go, relayer/app/monitor.go
Next step in netconf refactor: remove `IsX` fields.
task: none
=> refactor(lib/netconf): remove bools from netconf

e2e/app/avs.go, e2e/app/contract.go, e2e/app/create3.go, e2e/app/definition.go, e2e/app/fund.go, e2e/app/geth/config.go, e2e/app/monitor.go, e2e/app/proxyadmin.go, e2e/app/run.go, e2e/app/setup.go, e2e/app/test.go, e2e/app/valupdates.go, e2e/app/wait.go, e2e/app/xregistry.go, e2e/docker/compose.yaml.tmpl, e2e/docker/docker_test.go, e2e/netman/manager.go, e2e/netman/pingpong/pingpong.go, e2e/types/chain.go, e2e/types/deployinfo.go, e2e/types/testnet.go, lib/ethclient/ethbackend/backends.go, lib/evmchain/evmchain.go
Cleanup after netconf refactor.
task: none
=> ci(e2e): cleanup after refactor

lib/coingecko/coingecko.go, lib/coingecko/coingecko_test.go, lib/coingecko/options.go
Add simple coingecko public api client with GetPrice method.
task: none
=> feat(lib/coingecko): add simple coingecko client

.github/workflows/ci-docs.yml, .github/workflows/ci-pr-explorer-ui.yml
Add explorer ui preview. Uses same pattern as docs preview.
task: none
=> chore(ci): add explorer ui preview

docs/site/docs/octane/octane.md
add more docs on halo
task: none
=> chore(docs): halo docs

monitor/xfeemngr/gasprice/gasprice.go, monitor/xfeemngr/gasprice/gasprice_test.go, monitor/xfeemngr/gasprice/options.go, monitor/xfeemngr/ticker/mock.go, monitor/xfeemngr/ticker/ticker.go, monitor/xfeemngr/ticker/time.go
Add gas price buffered stream to xfeemngr.
task: https://app.asana.com/0/1206208509925075/1207171569957943
=> feat(monitor/xfeemngr): add gas price buffer

lib/cchain/provider/provider_test.go
Seeks to address flakiness found in: https://github.com/omni-network/omni/actions/runs/8897284166
task: none
=> fix(test): use wait groups for flaky test

explorer/README.md, explorer/graphql/app/app.go, explorer/graphql/app/graphql.go, explorer/graphql/app/index.html, explorer/graphql/app/schema.graphql, explorer/graphql/data/message_provider.go, explorer/graphql/data/receipt_provider.go, explorer/graphql/resolvers/blocks.go, explorer/graphql/resolvers/blocks_test.go, explorer/graphql/resolvers/chain.go, explorer/graphql/resolvers/messages.go, explorer/graphql/resolvers/messages_test.go, explorer/graphql/resolvers/receipts.go, explorer/graphql/resolvers/receipts_test.go, explorer/graphql/resolvers/root.go, explorer/graphql/resolvers/search.go, explorer/graphql/resolvers/search_test.go, explorer/indexer/app/app.go, explorer/indexer/app/db.go
* refactor Explorer
* rename/remove fields
* add doc comments to GraphQL schema
task: none
=> refactor(explorer): explorer refactoring

e2e/netman/pingpong/pingpong.go
Fund OMNI ping pongs with more than ETH pingpongs.
task: none
=> fix(e2e): fund omni pingpongs more

lib/contracts/feeoraclev1/deploy.go, monitor/app/app.go, monitor/xfeemngr/gasprice/buffer.go, monitor/xfeemngr/gasprice/metrics.go, monitor/xfeemngr/metrics.go, monitor/xfeemngr/oracle.go, monitor/xfeemngr/ticker/time.go, monitor/xfeemngr/tokenprice/buffer.go, monitor/xfeemngr/tokenprice/metrics.go, monitor/xfeemngr/xfeemngr.go, monitor/xfeemngr/xfeemngr_internal_test.go
Run xfeemngr in monitor, with metrics.
Additional:
- some refactoring and fixes
task: https://app.asana.com/0/1206208509925075/1207171569957943
=> feat(monitor): run xfeemngr with metrics

LICENSE, docs/site/docs/octane/octane.md
gplv3 plus open interop requirement
task: none
=> chore(docs): update license

halo/config/testdata/default_halo.toml, halo/genutil/testdata/TestMakeGenesis.golden, lib/buildinfo/buildinfo.go, monitor/app/testdata/default_monitor.toml, relayer/app/testdata/default_relayer.toml
=> chore(buildinfo): bumps buildinfo version

explorer/ui/app/components/details/From.tsx, explorer/ui/app/components/details/TabList.tsx, explorer/ui/app/components/details/To.tsx, explorer/ui/app/routes/xmsg.$id/route.tsx
Added xmsg view and page still need to manage the mobile view.
task: https://app.asana.com/0/1206208509925075/1206970544933858
=> feat(explorer/ui): push xmsg page

scripts/install_omni_cli.sh
removes verbosity from curl and tar commands, and some refactoring
task: none
=> chore(cli): remove verbosity from install script

monitor/xfeemngr/metrics.go, monitor/xfeemngr/monitor.go, monitor/xfeemngr/xfeemngr.go
Monitor portal balance - so we can see fees collected
task: none
=> chore(monitor): monitor portal balances

explorer/docker-compose.yml, explorer/graphql/app/schema.graphql, explorer/graphql/mockresolver/resolver.go
This PR simplifies the GraphQL API schema and addresses comments from the previous PR.
task: https://app.asana.com/0/1206208509925075/1207214158765014/f
=> fix(explorer/graphql): simplify schema

e2e/vmcompose/provider.go
Fix upgrade cmd.
task: https://app.asana.com/0/1206208509925075/1207223640934605/f
=> fix(e2e): fix upgrade cmd

e2e/netman/pingpong/pingpong.go, lib/netconf/netconf_test.go
Increase ping pong balance.
task: none
=> chore(e2e): increase ping pong funds

explorer/graphql/app/app.go, explorer/graphql/app/schema.graphql, explorer/graphql/mockresolver/resolver.go
Add mock message filtering.
task: https://app.asana.com/0/1206208509925075/1207244616602365/f
=> feat(explorer/graphql): add mock graphql msg filtering

monitor/xfeemngr/oracle.go, monitor/xfeemngr/xfeemngr.go, monitor/xfeemngr/xfeemngr_internal_test.go
Add max sane gas prices and conversion rates.
task: https://app.asana.com/0/1206208509925075/1207233529904019
=> chore(monitor/xfeemngr): add sane maxes

e2e/app/geth/config_internal_test.go
Test geth version against current import, not latest.
This allows tests to pass when new geth version is released.
task: none
=> test(e2e/app): fix geth version test

explorer/graphql/app/schema.graphql, explorer/graphql/mockresolver/resolver.go
This PR adds some more mock data for the front end dev work. Small changes to the URLs introduced.
task: none
=> chore(explorer/graphql): improve mock data

e2e/app/geth/types.go, e2e/docker/testdata/TestComposeTemplate_commit_no_explorer.golden, e2e/docker/testdata/TestComposeTemplate_empheral_network.golden, e2e/docker/testdata/TestComposeTemplate_main_explorer.golden, e2e/vmcompose/testdata/TestSetup_127_0_0_1_compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127_0_0_2_compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127_0_0_4_compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127_0_0_5_compose.yaml.golden, go.mod, go.sum, halo/evmengine/keeper/abci_internal_test.go, halo/genutil/evm/evm.go, lib/ethclient/enginemock.go, lib/ethclient/fuzz.go
`go: upgraded github.com/ethereum/go-ethereum v1.14.0 => v1.14.2`
Also update geth genesis difficulty to 0 as per [geth PR](https://github.com/ethereum/go-ethereum/pull/29579).
task: none
=> chore(go/mod): bump go-ethereum

explorer/graphql/app/schema.graphql, explorer/graphql/mockresolver/resolver.go
Add mock chain info and implement the supportedChains resolver to unblock FE work.
task: https://app.asana.com/0/1206208509925075/1207265407492995/f
=> feat(explorer/graphql): add mock chain info

explorer/graphql/app/schema.graphql, explorer/graphql/mockresolver/resolver.go
Improve mock data for front-end dev purposes. To be deleted once the backend is ready.
task: https://app.asana.com/0/1206208509925075/1207265405053169/f
=> feat(explorer/graphql): add stats and improve mock data

explorer/ui/app/components/details/From.tsx, explorer/ui/app/components/details/TabList.tsx, explorer/ui/app/components/details/To.tsx, explorer/ui/app/components/svg/arrowIconLong.tsx, explorer/ui/app/components/svg/arrowIconSmall.tsx, explorer/ui/app/lib/formatting.tsx, explorer/ui/app/routes/xmsg.$id/route.tsx
added styling changes to xmsg page and arrows 
task: https://app.asana.com/0/1206208509925075/1207265407492985
=> fix(explorer/ui): styling changes

explorer/ui/app/components/details/From.tsx, explorer/ui/app/components/details/TabList.tsx, explorer/ui/app/components/details/To.tsx, explorer/ui/app/components/home/messageDataTable.tsx, explorer/ui/app/components/queries/messages.tsx, explorer/ui/app/routes/_index.tsx, explorer/ui/app/routes/xmsg.$id/route.tsx
added logo data from BE 
task: https://app.asana.com/0/1206208509925075/1207265407493000
=> fix(explorer/ui): logo display fix

explorer/ui/app/components/details/TabList.tsx, explorer/ui/app/components/details/To.tsx, explorer/ui/app/components/home/messageDataTable.tsx, explorer/ui/app/lib/formatting.tsx, explorer/ui/app/root.tsx
timestamp changes and fixes
task: https://app.asana.com/0/1206208509925075/1207287380065295
=> fix(explorer/ui): timestamp fixes

explorer/ui/app/components/home/messageDataTable.tsx
fixed hover to be inline with design
task: https://app.asana.com/0/1206208509925075/1207298769693370
=> fix(explorer/ui): tool tip hover copy

halo/evmengine/keeper/abci.go, halo/evmengine/keeper/abci_internal_test.go, halo/evmengine/keeper/keeper_internal_test.go, halo/evmengine/keeper/msg_server_internal_test.go, halo/evmengine/keeper/proposal_server_internal_test.go, lib/ethclient/enginemock.go
Adds a unit test for new `evmengine.Finalize` method.
task: none
=> test(halo/evmengine): add finalise test

explorer/ui/app/components/shared/navbar.tsx
updated feedback link
task: https://app.asana.com/0/1206208509925075/1207244616797105
=> fix(explorer/ui): update feedback link

halo/attest/voter/metrics.go, halo/attest/voter/voter.go, relayer/app/metrics.go, relayer/app/monitor.go, relayer/app/worker_internal_test.go
Switches lag metrics from height to stream offset.
task: none
=> chore(relayer): monitor msg offset lag

lib/netconf/static.go
Static devnet portal addresses. 
task: none
=> feat(lib/netconf): static devnet version

e2e/docker/init-omni-evms.sh.tmpl
Fixes evm-init script.
task: none
=> ci(e2e): fix evm init script

relayer/app/monitor.go
Query consensus chain submit cursors.
task: none
=> chore(relayer): fix missing consensus cursors

lib/contracts/feeoraclev1/feeparams.go, relayer/app/monitor.go
Fix panic in relayer using incorrect grafana metric label.
Also make fetching conversion rate during deploy more robust to network errors.
task: none
=> chore(relayer): fix monitor panic

explorer/graphql/data/chains_provider.go
Make returned list deterministic.
task: none
=> fix(explorer): fix a flapping test

.secrets.baseline, e2e/app/setup.go, explorer/graphql/app/config.go, explorer/graphql/app/config_test.go, explorer/graphql/app/testdata/testnet_explorer_graphql.toml, explorer/graphql/data/chains_provider.go, explorer/graphql/data/provider.go, explorer/graphql/resolvers/blocks_test.go, explorer/graphql/resolvers/chain_test.go, explorer/graphql/resolvers/messages_test.go
Fix explorer network config
task: none
=> fix(explorer): fix explorer network config

explorer/graphql/cmd/cmd.go
Fixes reading the network flag/config.
task: none
=> fix(explorer/graphql): fix network flag

explorer/graphql/data/chains_provider.go, explorer/graphql/data/message_provider.go, explorer/graphql/data/types.go, explorer/graphql/resolvers/chain_test.go, explorer/graphql/resolvers/messages_test.go
Link sender/to addresses, blocks and transactions to external chain explorers.
task: none
=> fix(explorer): fix explorer links

halo/config/testdata/default_halo.toml, halo/genutil/testdata/TestMakeGenesis.golden, lib/buildinfo/buildinfo.go, monitor/app/testdata/default_monitor.toml, relayer/app/testdata/default_relayer.toml
bumps patch version number
task: https://app.asana.com/0/1206208509925075/1207372351528377/f
=> chore(buildinfo): bump version number

explorer/graphql/app/schema.graphql, explorer/graphql/data/chains_provider.go, explorer/graphql/data/provider_helpers.go, explorer/graphql/mockresolver/resolver.go, explorer/graphql/resolvers/messages_test.go, explorer/ui/app/components/details/From.tsx, explorer/ui/app/components/details/TabList.tsx, explorer/ui/app/components/details/To.tsx, explorer/ui/app/components/home/messageDataTable.tsx
* fix XMsg detail view ID
* use decimal numbers instead of hex for XMsg view
* fix block ID
* improve unit tests
* fix tx link
task: none
=> fix(explorer): fix ui bugs

.github/workflows/ci-main.yml, .github/workflows/clicommand.yml, .secrets.baseline
introduces command tests in different environments for CLI
task: none
=> chore(cli): include tests for commands

.github/workflows/ci-main.yml, .github/workflows/cliinstall.yml
renames cli ci jobs to match what they do
task: none
=> ci(cli): rename cli workflows

.github/workflows/ci-pr.yml
Include PR CI in cli refactor for workflow files
task: none
=> ci(fix): include pr ci in workflow cli refactor 

explorer/graphql/data/types.go, explorer/graphql/resolvers/messages_test.go, explorer/ui/app/components/details/From.tsx, explorer/ui/app/components/details/TabList.tsx, explorer/ui/app/components/details/To.tsx, explorer/ui/app/routes/xmsg.$id/route.tsx
* properly handle nil receipts when displaying txHash and receipt timestamp
* move block timestamp to source chain and not dest chain to fix confusion
task: none
=> fix(explorer): fix explorer bugs

halo/app/app.go, halo/app/app_config.go, halo/evmslashing/evmslashing.go, halo/evmstaking/evmstaking.go
Add evmslashing module, connected to Slashing predeploy.
task: https://app.asana.com/0/1206208509925075/1207375377017419
=> feat(halo): add evmslashing module

e2e/app/run.go
Increase max supported chain attempts. 
task: none
=> chore(e2e): increase supported chain attempts

halo/evmslashing/evmslashing.go
=> fix(lib): fix a typo in package name

halo/evmstaking/evmstaking.go
Fix evmstaking log filter query.
Query for CreateValidator OR Delegate events.
task: none
=> fix(halo): fix evmstaking event query

.secrets.baseline, e2e/app/agent/prometheus.go, e2e/app/agent/prometheus_internal_test.go, e2e/app/agent/testdata/TestPromGen_manifest1_gen.golden, e2e/app/agent/testdata/TestPromGen_manifest1_update.golden, e2e/app/agent/testdata/TestPromGen_manifest2_gen.golden, e2e/app/agent/testdata/TestPromGen_manifest2_update.golden, e2e/app/agent/testdata/TestPromGen_manifest3_gen.golden, e2e/app/agent/testdata/TestPromGen_manifest3_update.golden, e2e/app/agent/testdata/TestPromGen_manifest4_gen.golden, e2e/app/agent/testdata/TestPromGen_manifest4_update.golden
Scrape XExplorer metrics
task: https://app.asana.com/0/1206208509925075/1207149842829922/f
=> feat(e2e): scrape explorer ui metrics

lib/contracts/create3/deploy.go
Remove the contract code check as it is not relevant anymore
task: none
=> fix(e2e): remove create3 contract code check

e2e/app/monitor.go, e2e/app/run.go, e2e/netman/pingpong/pingpong.go, lib/netconf/provider.go, lib/xchain/provider/fetch.go
Fixes `XReceipt.ShardID` hardcoding source chain conf level.
task: none
=> ci(e2e): fix e2e msg-receipt mapping

explorer/graphql/app/app.go, explorer/graphql/app/metrics.go
Add more API metrics
task: https://app.asana.com/0/1206208509925075/1207110599733918/f
=> feat(explorer/graphql): add http server metrics

contracts/src/xchain/OmniPortal.sol
Store array length in local variable in solidity contracts to save gas.
task: none
=> chore(contracts): store array length in local vars

.secrets.baseline, halo/app/privkey.go, halo/app/privval_internal_test.go, halo/cmd/flags.go, halo/cmd/testdata/TestCLIReference_rollback.golden, halo/cmd/testdata/TestCLIReference_run.golden, halo/cmd/testdata/TestRunCmd_defaults.golden, halo/cmd/testdata/TestRunCmd_flags.golden, halo/cmd/testdata/TestRunCmd_json_files.golden, halo/cmd/testdata/TestRunCmd_toml_files.golden, halo/config/config.go, halo/config/config.toml.tmpl, halo/config/testdata/default_halo.toml
Remove support for using eigen operator key as halo consensus key.
task: none
=> chore(halo): remove eigen operator key  as cons key option

explorer/graphql/data/message_provider.go, explorer/ui/app/components/home/messageDataTable.tsx
Fix pagination bug
task: https://app.asana.com/0/1206208509925075/1207454220241512/f
=> fix(explorer/ui): fix explorer pagination bug

docs/site/docs/develop/testnet/testnet.md, docs/site/docs/develop/xapp/example.md, docs/site/docs/develop/xapp/fees.md
=> docs(develop): fix typos

halo/attest/voter/metrics.go, halo/attest/voter/voter.go, lib/cchain/provider/metrics.go, lib/netconf/netconf.go, lib/netconf/provider.go, lib/xchain/provider/metrics.go, lib/xchain/provider/provider.go, lib/xchain/types.go, relayer/app/cursors.go, relayer/app/monitor.go
Refactor attestation, cprovider, xprovider, and relayer metrics to include confirmation level and shards.
task: none
=> chore(*): refactor shard confirmation metrics

lib/netconf/netconf.go
Reorg stream name to: `op_sepolia|F|omni_evm`
task: none
=> chore(netconf): reorg stream name

halo/app/app.go, halo/app/rollback.go, halo/app/start.go, halo/attest/keeper/common_test.go, halo/attest/keeper/helper.go, halo/attest/keeper/keeper.go, halo/attest/keeper/metrics.go, halo/attest/module/module.go, halo/attest/testutil/expected_interfaces.go, halo/attest/testutil/mock_interfaces.go, halo/attest/types/interface.go, lib/netconf/netconf.go, relayer/app/app.go, relayer/app/monitor.go, relayer/app/sender.go
Refactor more metrics to be chain_version based. Also add zero streams to relayer monitor metrics.
task: none
=> chore(*): improve stream metrics

.secrets.baseline, explorer/docker-compose.yml
Fix explorer local dev docker compose
task: none
=> fix(explorer): fix local dev docker compose

explorer/ui/app/assets/icons/css/omni.css, explorer/ui/app/components/details/From.tsx, explorer/ui/app/components/details/To.tsx, explorer/ui/app/components/home/chainDropdown.tsx, explorer/ui/app/components/home/messageDataTable.tsx, explorer/ui/app/components/home/overview.tsx, explorer/ui/app/components/shared/rollupIcon.tsx
This PR fixes the icons of chains in both light and dark themes.
task: https://app.asana.com/0/1207021947077646/1207403468294182/f
=> fix(explorer/ui): fix explorer icons

docs/site/docs/learn/omni/token/tokenomics.md
fixes sidebar for tokenomics learn portion
task: none
=> docs(sidebar): fix sidebar for token

contracts/bindings/examples/pingpong.go, contracts/src/examples/PingPong.sol, e2e/netman/pingpong/pingpong.go
Allow specification of conf level in pingpong contract.
task: https://app.asana.com/0/1206208509925075/1207495160781332
=> feat(contracts): specify conf level in pingpong

lib/xchain/provider/fetch.go, relayer/app/monitor.go
Improve relayer monitoring logs. 
task: none
=> chore(relayer): improve some relayer logs

.github/workflows/release-official.yml
introduces more os and arch for explorer ui images as per https://docs.docker.com/build/ci/github-actions/multi-platform/
task: none
=> ci(release): explorer os and arch images

.github/workflows/ci-api.yml, .github/workflows/ci-pr-api.yml, api/.gitignore, api/README.md, api/api/token/supply/circulating.test.ts, api/api/token/supply/circulating.ts, api/api/token/supply/total.ts, api/package.json, api/pnpm-lock.yaml, api/tsconfig.json
Adds a token supply api, to be deployed with vercel.
task: https://app.asana.com/0/1206208509925075/1207497924242030
=> feat(api): add token supply routes

e2e/app/geth/types.go, e2e/docker/testdata/TestComposeTemplate_commit_no_explorer.golden, e2e/docker/testdata/TestComposeTemplate_empheral_network.golden, e2e/docker/testdata/TestComposeTemplate_main_explorer.golden, e2e/vmcompose/testdata/TestSetup_127-0-0-1-compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127-0-0-2-compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127-0-0-4-compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127-0-0-5-compose.yaml.golden, go.mod, go.sum
```
go: upgraded github.com/ethereum/go-ethereum v1.14.4 => v1.14.5
```
task: none
=> chore(deps): bump go ethereum

api/api/notfound.ts, api/package.json, api/pnpm-lock.yaml, api/vercel.json
Move api routes to /v1, remove /api prefix.
Reroute all others to not found 404 handlers
task: none
=> chore(api): clean up api routes and deps

.secrets.baseline, e2e/app/definition.go, lib/netconf/provider.go, lib/netconf/static.go, lib/xchain/provider/fetch.go
Formalize consensus chain metadata in netconf static.
task: none
=> refactor(netconf): formalize consensus chain metadata

contracts/package.json
Bump contracts package version.
task: none
=> chore(contracts): bump version

cli/cmd/develop.go, cli/cmd/flags.go
updates scaffolding to use git commands instead of forge init command and specifies commit hash of the template repository for compatibility
=> chore(cli): updates scaffolding to use new template

halo/attest/keeper/keeper.go, halo/attest/voter/voter.go, lib/xchain/provider.go, relayer/app/cursors.go, relayer/app/worker.go
Improve debug logging in relayer and halo.
task: none
=> chore(relayer): improve debug logging

.github/workflows/release-snapshot.yml
publishes explorer ui docker images to DockerHub for more platforms and arch's like already done on `release-official.yml`
=> ci(snapshot): explorer ui images multi platform and arch

halo/config/testdata/default_halo.toml, halo/genutil/testdata/TestMakeGenesis.golden, lib/buildinfo/buildinfo.go, monitor/app/testdata/default_monitor.toml, relayer/app/testdata/default_relayer.toml
=> chore(buildinfo): bump version

.github/workflows/release-official.yml, .github/workflows/release-snapshot.yml, e2e/docker/compose.yaml.tmpl, e2e/docker/testdata/TestComposeTemplate_empheral_network.golden, e2e/docker/testdata/TestComposeTemplate_main_explorer.golden, e2e/vmcompose/testdata/TestSetup_127-0-0-6-compose.yaml.golden
=> chore(ci/e2e): set explorer ui image platform

halo/app/prouter.go, halo/attest/keeper/keeper.go
Slight logging improvements.
task: none
=> chore(halo): improve debug logging

docs/site/docs/develop/introduction.md
notifies developers that using omni as a bridge requires additional implementation
task: https://app.asana.com/0/1206208509925075/1207559459891668/f
=> docs(develop): no bridge dev info

halo/config/testdata/default_halo.toml, halo/genutil/testdata/TestMakeGenesis.golden, lib/buildinfo/buildinfo.go, monitor/app/testdata/default_monitor.toml, relayer/app/testdata/default_relayer.toml
bump buildinfo patch version
task: none
=> chore(buildinfo): bump patch version

e2e/app/run.go
Temporarily allow deploying omega testnet.
task: none
=> ci(e2e): enable deploying omega testnet

contracts/script/DeployAVS.sol, contracts/src/token/OmniBridgeNative.sol, contracts/src/xchain/OmniPortal.sol, contracts/test/avs/OmniAVS_syncWithOmni.t.sol
=> docs(contracts): fix typos

docs/site/docs/learn/testnet/testnet.md, docs/site/docs/protocol/xmessages/components/portals.md
updates code links in protocol portals section and updates learn section docs testnet holesky to sepolia
task: https://app.asana.com/0/1206208509925075/1207559459891672/f
=> docs(learn/protocol): links and testnet name update

halo/genutil/evm/evm.go
Prefund testnet account
task: none
=> chore(halo/genutil): prefund pavels address

.github/CODEOWNERS
Adds aauysh to code owners for halo/relayer/lib.
task: none
=> chore(github): add aayush to code owners

lib/netconf/static.go
Increase Omega network version
task: none
=> chore(lib/netconf): increase network version

cli/README.md
=> chore(cli): update cli readme

lib/netconf/static.go
=> fix(lib/netconf): fix consensus rpc

e2e/types/testnet.go
Avoid using omni_evm with perturbations for broadcasting. Our txmgr currently has a [bug](https://app.asana.com/0/1206208509925075/1207634096794277) that results in failed e2e txs when validator02_evm is restarted.
task: none
=> ci(e2e): avoid broadcasting to evm with perturbations

lib/txmgr/txmgr.go
* Retry with a fee bump on "_Intrinsic gas too low_" error
* Log an error instead of a warn on "_ Unknown error publishing transaction_"
task: none
=> fix(lib/txmgr): fix txmgr intrinsic gas too low err

lib/netconf/static.go
Add Arb Sepolia to netconf static config.
task: none
=> chore(lib/netconf): add arb sepolia to static

e2e/app/definition.go, lib/fireblocks/client.go, lib/fireblocks/config.go, lib/fireblocks/jsonhttp.go, lib/fireblocks/sign.go
* Handle non-json body errors properly
* Increase retry interval from 1s to 5s to avoid getting rate limited
task: none
=> fix(lib/fireblocks): handle errors and increase query interval

lib/netconf/static.go
Add portal address to neconf static.
task: none
=> chore(lib/netconf): add portal address to static

lib/netconf/static.go
=> chore(lib/netconf): bump omega version

e2e/manifests/omega.toml
Test deployment without arb sepolia.
task: none
=> test(e2e): remove arb sepolia

e2e/manifests/omega.toml
Remove base from omega manifest for test purposes.
task: none
=> test(e2e): remove base from omega manifest

e2e/manifests/omega.toml
Add arb sepolia to Omega
task: none
=> chore(e2e): add arb sepolia

e2e/manifests/omega.toml, e2e/manifests/staging.toml, lib/netconf/static.go
* Remove arb_sepolia from omega
* Add arb_sepolia to staging
* Bump network version
task: none
=> feat(lib/netconf): bump network version

lib/contracts/address.go, lib/contracts/avs/deploy.go, lib/contracts/create3/deploy.go, lib/contracts/feeoraclev1/deploy.go, lib/contracts/portal/deploy.go, lib/contracts/proxyadmin/deploy.go, lib/netconf/netconf_test.go
Rename some leftovers of testnet to omega.
task: none
=> chore(contracts): rename testnet to omega

e2e/manifests/staging.toml
Swaps over the arb_sepolia chain config with base_sepolia
task: none
=> feat(e2e): swap over arb_sepolia with base_sepolia

e2e/manifests/staging.toml
Add arb_sepolia to staging network
task: none
=> chore(e2e): add arb_sepolia to staging

e2e/manifests/staging.toml
Remove arb_sepolia from staging
task: none
=> test(e2e): remove arb_sepolia from staging

halo/attest/keeper/keeper.go
@corverroos and I found this lacking when debugging on Friday.
task: none
=> feat(attest): log blockhash when overriding entries

docs/site/pnpm-lock.yaml
Update ws dependency. 
task: none
=> chore(docs): update ws dep

api/package.json, api/pnpm-lock.yaml
Run pnpm update in api.
task: none
=> chore(api): update dependencies

.github/pull-request-template.md, scripts/verifypr/verify.go, scripts/verifypr/verify_internal_test.go
remove the footer requirement for asana links, now that we're moving to GH issues
issue: none
=> chore(ci): enforce github issues in PRs

halo/attest/voter/voter.go
Keep an up-to-date map of offset based on StreamID, and report a reorg if the next block's XMsgs don't apply consecutively on our map's offsets.
issue: #1312
=> feat(attest): detect reorgs based on XMsg StreamOffsets

lib/xchain/provider/fetch.go
This gives us more reorg-resistance, and ensures that the header, XMsgs, and XReceipts returned by the provider's `GetBlock` are all consistent.
issue: #1313
=> feat(xchain): fetch XMsgLogs and XMsgReceipts by blockhash

e2e/manifests/omega.toml
Add base sepolia to omega testnet.
issue: none
=> chore(e2e/manifests): add base_sepolia to omega

e2e/app/avs.go, e2e/netman/manager.go, lib/fireblocks/sign.go, lib/txmgr/txmgr.go, relayer/app/creator.go, relayer/app/creator_internal_test.go, relayer/app/gas.go, relayer/app/gas_internal_test.go, relayer/app/sender.go
Revert to using proper RPC gas estimation for arb_sepolia. This should fix failing submissions and reenable support for arb.
issue: none
=> fix(relayer): fix arb gas estimation

e2e/app/eoa/fund.go, e2e/app/eoa/static_test.go, e2e/app/fund.go, e2e/cmd/cmd.go
Fixes account funding command.
issue: #1360
=> ci(e2e): fixes funding command

e2e/app/eoa/eoa.go, e2e/app/fund.go, monitor/account/account.go, monitor/account/metrics.go, monitor/account/monitor.go, monitor/app/app.go, monitor/avs/avs.go
Use eoa package to monitor accounts including new metrics `monitor_account_balance_low` which indicate that the account funding action should be triggered.
issue: #1360
=> refactor(monitor): use eoa package to monitor accounts

.github/workflows/ci-api.yml, .github/workflows/ci-docs.yml, .github/workflows/ci-pr-api.yml, .github/workflows/ci-pr-docs.yml, .github/workflows/soltest.yml
Bump pnpm-setup-action ver form v2 to v4
issue: none
=> chore(ci): bump pnpm setup action ver

.github/CODEOWNERS
update the codeowners file
issue: none
=> chore(ci): update codeowners

halo/app/abci.go, halo/attest/voter/voter.go
Improve voter reorg detection logs and metrics and logic. 
Also add `height` log attr to abci context.
issue: none
=> chore(halo/voter): improve reorg detection logs and metrics

e2e/netman/pingpong/pingpong.go
We group the edges by the source, and deploy in parallel across each source-group. However, for a specific source-group, we start them in series so as to avoid blitzing Fireblocks. 
issue: none
=> fix(e2e): lower parallelization when starting contracts

contracts/src/libraries/Quorum.sol
Improve readability of quorum logic as per Sigma Prime audit OMP-26.
issue: none
=> chore(contracts/libraries): improve readability

monitor/xmonitor/emitcursorcache.go, monitor/xmonitor/emitcursorcache_internal_test.go, monitor/xmonitor/monitor.go
Two more fixes to `emitcursorcache`:
- Trimming had a bug. It always deleted at least 1 height.
- Monitoring "current stream offset" doesn't necessarily hit attested xblocks, so add `AtOrBefore` to use closest populated cursor instead.
issue: none
=> fix(monitor): fix emit cursor cache

monitor/xmonitor/emitcursorcache.go
Fix emitcursorcache stream conf level. 
issue: none
=> chore(monitor): add missing fixes

lib/netconf/static.go
Add static artifacts for Omega network
issue: none
=> chore(lib/netconf): update static artefacts

halo/attest/keeper/common_test.go, halo/attest/keeper/keeper.go, halo/attest/keeper/keeper_test.go, halo/attest/keeper/query.go, halo/attest/types/query.pb.go, halo/attest/types/query.proto
Lists all attestations of the given status found. Expected to be mostly used for debugging.
issue: #1314
=> feat(attest): add ListAllAttestations query

e2e/app/run.go
Disable deploying `omega`
issue: none
=> chore(e2e/app): disable omega deploy

lib/netconf/netconf_test.go, lib/netconf/omega/consensus-genesis.json, lib/netconf/static.go
Add omega static artefacts.
issue: none
=> chore(lib/netconf): add omega static artefacts

contracts/Makefile, contracts/bindings/unpauseportal.go, contracts/core/script/admin/UnpausePortal.s.sol, e2e/app/admin/unpauseportal.go, e2e/cmd/admin.go
Add unpause portal admin command.
issue: #1393
=> feat(e2e): add unpause-portal command

octane/evmengine/keeper/msg_server.go
Improve readability of the event delivery and panic catching section in EVMEngine.
issue: none
=> chore(octane/evmengine): improve readability event delivery

halo/genutil/evm/evm.go
adds team addresses to testnet genesis for testing and distribution to developers
issue: none
=> chore(halo) add addrs to testnet genesis

e2e/app/rpc.go
Add `last_err` and `last_height` to `timed out waiting for height` errors.
issue: none
=> ci(e2e): more deploy debug logs

contracts/core/.gas-snapshot, contracts/core/test/script/Admin.t.sol, e2e/app/admin/admin_internal_test.go, e2e/app/admin/common.go, e2e/app/admin/config.go, e2e/app/admin/pauseportal.go, e2e/app/admin/unpauseportal.go, e2e/app/admin/upgradeportal.go, e2e/cmd/flags.go, e2e/fbproxy/app/app.go
Add option to run admin action on all chains in a network.
Additional:
- refactor / improve logging
issue: #1393
=> feat(e2e/admin): add option to run admin action on all chains

halo/genutil/evm/evm.go
chore(halo): adds marks address
issue: none
=> chore(halo): add mark address to testnet genesis

halo/genutil/evm/evm.go
=> chore(halo): add aayush to testnet genesis

cli/cmd/register_test.go, e2e/app/tokenbridge.go, e2e/netman/manager.go, e2e/test/bridge_test.go, lib/contracts/address.go, lib/contracts/address_test.go, lib/contracts/create3/deploy.go, lib/contracts/feeoraclev1/deploy.go, lib/contracts/l1bridge/deploy.go, lib/contracts/omnitoken/deploy.go, lib/contracts/portal/deploy.go, lib/contracts/portal/deploy_test.go, lib/contracts/testdata/TestContractAddressReference.golden, lib/netconf/netconf_test.go
Cleanup deployment config code. 
Just use a mapping of network ID to config. 
issue: none
=> chore(lib/contracts): cleanup deployment configs

e2e/app/admin/common.go
Return error if any run on any fails. 
issue: none
=> fix(e2e/admin): return error on any failures

cli/cmd/operator.go, halo/cmd/init.go
While joining a network with `omni operator init-nodes`, populate the cometBFT address book with 5 random public peers of any RPC fullnode. This acts as an effective "bootstrap peers" which aids network discovery and P2P networking in addition to seeds nodes.
This follows the example of [penumbra](https://github.com/penumbra-zone/penumbra/issues/3056#issuecomment-1738271515).
```
Advice within the tendermint/cometbft community boils down to 1) run seed nodes; and 2) write directly to address book, rather than use the "seeds" setting in the config.toml.
```
issue: #1311
=> feat(cli/init): populate address book to bootstrap peers

monitor/xmonitor/emitcache/emitcursorcache.go
Improve emitcache population performance by fetching cursors in parralel. This should reduce staging post-deploy "cache not populated" errors a bit.
issue: #1465
=> chore(monitor/emitcache): fetch cursors in parallel

e2e/app/run.go, lib/contracts/testdata/TestContractAddressReference.golden, lib/netconf/static.go
bumping Omega version for a new deployment, and enable deployment
issue: none
=> feat(lib/netconf): update omega version

e2e/app/run.go, lib/netconf/omega/consensus-genesis.json, lib/netconf/static.go
updates netconf post Omega deployment, as well as contract addresses and protects deployment
issue: none
=> chore(lib/netconf): add omega consensus and execution genesis

lib/netconf/static.go
I think we're ready to set this now, so we might as well.
issue: none
=> chore(lib): set mainnet chain ID to 166

docs/site/docs/develop/quickstart/quickstart.md
Companion PR for [hello-world-template](https://github.com/omni-network/hello-world-template/pull/6) update
issue: none
=> chore(docs): update quickstart docs with new template update

contracts/core/package.json
Bump contracts package version. 
issue: none
=> chore(contracts/core): bump version

.github/ISSUE_TEMPLATE/custom.md
Adds a very simple issue template with "Problem to Solve" and "Proposed Solution". Note: used the Github settings UI to create this and it was pretty strict with formatting.
issue: none
=> chore(ci): update issue templates

.github/workflows/ci-main.yml, .github/workflows/ci-pr.yml, cli/cmd/develop.go
Backport a CLI fix to v0.2 release (#1547)
issue: none
=> fix(cli): omni developer new template 

lib/ethclient/ethclient.go
The result of a call to `eth_getBlockByNumber` can be `nil`, with a `nil` error. This most often happens when calling the `Pending` block, but it can happen in other situations (see [here](https://github.com/ethereum/go-ethereum/blob/ed8fd0ac0919ee954cfa621d16a5d0cfbf30c96d/core/blockchain.go#L929)). geth [checks for the returned block ](https://github.com/ethereum/go-ethereum/blob/2e8e35f2ada60e8e90aff8f6374ea7cd7da16116/ethclient/ethclient.go#L217-L219)being `nil` before returning, throwing an error in this case. We should do the same.
This PR refactors things to use geth's `HeaderByNumber` method, which will perform the check for us.
issue: none
=> fix(lib): endpoint HeaderByNumber might return nil

contracts/Makefile, contracts/README.md, contracts/avs/README.md, contracts/core/README.md
Cleanup contract readmes. 
issue: none
=> docs(contracts): cleanup contract readmes

README.md, contracts/README.md, contracts/core/README.md
=> docs(contracts): cleanup readmes

e2e/app/setup.go, e2e/manifests/staging.toml, e2e/manifests/static.go, halo/cmd/init.go, lib/netconf/netconf_test.go, lib/netconf/staging/consensus-seeds.txt, lib/netconf/staging/execution-seeds.txt
Adds wellknown staging p2p addresses as well as other fixes to "join staging".
issue: #1541
=> ci(e2e): well known staging seeds

docs/site/docs/develop/quickstart/quickstart.md, docs/site/docs/develop/xapp/example.md, docs/site/docs/tools/contracts/contracts.md
the hello-world-template had a makeover ([here](https://github.com/omni-network/hello-world-template/pull/8)) and references to it need to be updated.
issue: #1596
=> chore(docs): update hello-world-template references

e2e/app/run.go, lib/netconf/omega/consensus-genesis.json, lib/netconf/static.go
Update netconf static, prevent redeploy.
issue: none
=> chore(e2e): post omega deployment updates

e2e/app/run.go, lib/netconf/omega/consensus-genesis.json, lib/netconf/static.go
Backport 1618.
Update netconf static, disable redeploy
issue: none
=> chore(e2e): post omega deploy updates

halo/app/metrics.go, halo/app/monitor.go, halo/app/start.go
Monitor database directory size in halo: `halo_db_size_bytes`
issue: #1526
=> chore(halo): monitor db size

docs/site/docs/develop/faq.md, docs/site/sidebars.ts
adds a simple developer FAQ section, we can add more to it over time.
issue: none
=> chore(docs): add developer FAQ section

docs/site/docs/home.md
=> chore(docs): update home copy

halo/genutil/genutil.go, halo/genutil/testdata/TestMakeGenesis.golden
Order genesis validators by address for deterministic genesis files.
issue: #1539
=> chore(halo/genutil): deterministic validator order

docs/site/docs/develop/contracts.md, docs/site/docs/develop/xapp/example.md
fixes some broken links in the docs.
issue: none
=> chore(docs): update github links

docs/site/docs/operate/run/full.md
Add comment on known issue with sporadic panics on sync ie #1524 
issue: none
=> chore(docs): add known validator sync issue

lib/contracts/feeoraclev1/feeparams.go, monitor/xfeemngr/oracle.go
Allows for calculating fees for an xcall callback to the source.
issue: none
=> feat(monitor/xfeemngr): sync a chains fee params with itself

.github/workflows/pr-e2etest.yml, .github/workflows/release-snapshot.yml, e2e/app/perturb.go, lib/netconf/provider.go, scripts/halovisor/build.sh
Fix build:
- Typo in halovisor build script
- Update rollback for command for halovisor
- Few random logging improvements in netconf.
issue: none
=> chore(e2e): fix build

scripts/check_network.sh
Adds a simple script to test network connectivity.
issue: none
=> chore(scripts): add check network script

.github/ISSUE_TEMPLATE/custom.md
Use headers instead of italics. Because it's easier to parse visually
issue: none
=> chore(ci): update custom.md

lib/txmgr/txmgr.go
Support gas prices lower than 1 gwei.
issue: none
=> chore(lib/txmgr): increase gas price granularity

e2e/app/run.go, lib/contracts/testdata/TestContractAddressReference.golden, lib/netconf/static.go
Allow re-deploying omega.
issue: none
=> ci(e2e): prep for omega redeploy

e2e/app/run.go, lib/netconf/omega/consensus-genesis.json, lib/netconf/static.go
Add redeployed omega deploy heights and genesis files.
issue: none
=> ci(e2e): update omega post deploy

e2e/app/erc20faucet.go, e2e/app/tokenbridge.go, e2e/cmd/cmd.go, e2e/cmd/flags.go, lib/contracts/omnitoken/deploy.go
Add erc20 faucet e2e comand.
issue: none
=> feat(e2e): add erc20 faucet cmd

lib/txmgr/txmgr.go, monitor/xfeemngr/contract/bound.go
Txmgr to backoff before bumping gas to avoid hotspinning.
Also avoid caching txopts as per [godoc](https://github.com/omni-network/omni/blob/main/lib/ethclient/ethbackend/backend.go#L175-L177).
issue: fixes #1601
=> chore(lib/txmgr): backoff when bumping fees

.github/workflows/ci-pr.yml
Wire the `pr-label.yml` github action to run in PRs
issue: none
=> chore(github): run pr-label action on PRs

halo/config/testdata/default_halo.toml, halo/genutil/testdata/TestMakeGenesis.golden, lib/buildinfo/buildinfo.go, monitor/app/testdata/default_monitor.toml, relayer/app/testdata/default_relayer.toml
Bump version of `release/v0.5` branch
issue: none
=> chore(buildinfo): bump version v0_5_0

lib/xchain/connect/connect.go, monitor/app/app.go, monitor/routerecon/metrics.go, monitor/routerecon/recon.go, monitor/routerecon/recon_internal_test.go, monitor/routerecon/routescan.go, monitor/routerecon/routescan_internal_test.go
Period recon of latest routescan cross-transaction on omega.
issue: #1714
=> chore(monitor): recon latest routescan cross tx

monitor/xfeemngr/oracle.go
Do not try to correct postsTo when chain postsTo itself.
issue: none
=> fix(monitor/xfeemngr): handle postTo self case

docs/content/build-xdapp/showcase-dapps.md
Move xstake links to omni org.
issue: none
=> chore(docs): fix xstake link

docs/content/build-xdapp/testnet-omega.md
=> chore(docs): link to faucet

monitor/routerecon/recon.go, monitor/routerecon/routescan.go, monitor/routerecon/types.go
Improve error handling and add status check
issue: none
=> chore(monitor/routerecon): improve routerecon

cli/cmd/compose.yml.tpl, cli/cmd/operator.go
Fix halovisor mounts. Make geth log level explicit.
issue: none
=> chore(cli): fix init-nodes command

halo/attest/keeper/keeper.go
Vote instrument logic panics if attestations were overridden since valSetID==0.
issue: none
=> fix(halo/attest): skip vote tracking for overridden attestations

e2e/netman/manager.go, lib/contracts/feeoraclev1/feeparams.go
Add postsTo L1 chains feeParams when initing fee oracle.
issue: none
=> ci(e2e): also init fee oracle posts to chains

e2e/anvilproxy/app/xmsg.go
We switched querying logs from using `From/To` block height to using `BlockHash` a while back. But we never updated `anvilproxy` accordingly. It failed to detect any responses to fuzz, erroring instead. This switches fuzzy msg detection to using block hashes instead. 
issue: none
=> chore(e2e/anvilproxy): fix fuzzy detect logic

docs/content/learn/token.md
=> chore(docs): update token docs

docs/content/build/omega.md
=> chore(docs): update tg link

docs/website/docusaurus.config.ts
=> chore(docs): fix footer links

docs/content/operate/run-full-node.md
Remove broken CLI link
issue: none
=> chore(docs): clean up CLI doc

contracts/Makefile, contracts/bindings/omnigaspump.go, contracts/bindings/omnigasstation.go, lib/contracts/address.go, lib/contracts/address_test.go, lib/contracts/gaspump/deploy.go, lib/contracts/gasstation/deploy.go, lib/contracts/testdata/TestContractAddressReference.golden
Add OmniGasPump and OmniGasStation deploy utils.
issue: #1686
=> chore(lib/contracts): add gaspump and gasstation deploy utils

e2e/cmd/cmd.go
Add deploy-gas-app e2e command.
issue: #1686
=> chore(e2e): add deploy-gas-app e2e command

e2e/app/admin/allowoperator.go
Add marks operator address for testing omega operator validators
issue: none
=> chore(e2e): add marks operator address

lib/cchain/provider/abci.go, monitor/xfeemngr/gasprice/buffer.go, monitor/xfeemngr/tokenprice/buffer.go, relayer/app/sender.go
Decrease noisy logs, decrease log level if retryable . Add block height to relayer submit logs. 
issue: none
=> chore(*): improve few random logs

halo/app/lazyvoter.go, halo/app/monitor.go, halo/app/start.go
=> chore(hlao/app): improve logging

e2e/app/admin/allowoperator.go
Add A41 and BlockDeamon to omega staking validator allow list.
issue: none
=> ci(e2e): add 2 operators to allow list

contracts/avs/pnpm-lock.yaml, contracts/core/package.json, contracts/core/pnpm-lock.yaml
Run pnpm update elliptic in both contract dirs.
issue: none
=> chore(contracts): update elliptic

.github/workflows/release-snapshot.yml, .goreleaser.yaml, cli/cmd/initnodes.go, cli/cmd/omni/Dockerfile
Dockerize `omni` cli for power users preferring docker over raw binaries.
issue: none
=> ci(goreleaser): dockerize omni cli

e2e/app/fund.go, e2e/cmd/cmd.go, lib/contracts/fund.go
Add contracts to funding actions.
Configure OmniGasStation with fund thresholds.
issue: none
=> feat(e2e): add contracts to fund cmd

e2e/anvilproxy/app/proxy.go
Forward anvil headers in proxy.
issue: none
=> fix(e2e/anvilproxy): copy response headers

cli/cmd/compose.yml.tpl, e2e/docker/compose.yaml.tmpl, e2e/docker/testdata/TestComposeTemplate_commit.golden, e2e/docker/testdata/TestComposeTemplate_empheral_network.golden, e2e/docker/testdata/TestComposeTemplate_empheral_network_upgrade.golden, e2e/vmcompose/testdata/TestSetup_127-0-0-1-compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127-0-0-2-compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127-0-0-4-compose.yaml.golden, e2e/vmcompose/testdata/TestSetup_127-0-0-5-compose.yaml.golden, halo/app/app.go, halo/app/start.go, halo/app/start_test.go, halo/cmd/cmd_internal_test.go, halo/cmd/flags.go, halo/cmd/testdata/TestCLIReference_rollback.golden, halo/cmd/testdata/TestCLIReference_run.golden, halo/cmd/testdata/TestRunCmd_defaults.golden, halo/cmd/testdata/TestRunCmd_flags.golden, halo/cmd/testdata/TestRunCmd_json_files.golden, halo/cmd/testdata/TestRunCmd_toml_files.golden, halo/cmd/testinput/input1/config/halo.toml, halo/cmd/testinput/input2/config/halo.json, halo/config/config.go, halo/config/config.toml.tmpl, halo/config/testdata/default_halo.toml, lib/cchain/grpc/client.go
Adds support for cosmos gRPC and REST APIs.
issue: #1861
=> feat(halo): support cosmos grpc and api

e2e/app/admin/allowoperator.go
Adds kingnodes to staking allow list
issue: none
=> chore(e2e/admin): add kingnodes to staking allow list

.github/workflows/release-snapshot.yml
Fixes snapshot build.
issue: none
=> ci(github): fix snapshot build

.github/workflows/release-snapshot.yml
=> ci(github): fix build again

monitor/app/app.go, monitor/contract/metrics.go, monitor/contract/monitor.go
Add contract balance monitoring.
issue: none
=> feat(monitor): add contract balance monitoring

.github/workflows/e2etestadmin.yml
Fix contract admin test workflow. Install forge & contract dependencies. 
issue: none
=> ci(github): fix admin test workflow

.github/workflows/e2etestadmin.yml
Fix admin workflow again.
Specify pnpm version.
issue: none
=> ci(github): fix admin test worflow

e2e/cmd/admin.go
Cleanup infra after admin test.
issue: none
=> chore(e2e): clean up infra after admin test

halo/app/app.go, halo/app/app_config.go, halo/app/app_config_internal_test.go, halo/app/pruning_test.go, halo/attest/keeper/common_test.go, halo/attest/keeper/keeper.go
Wait for attestations to exit vote window before deleting. 
issue: #1787
=> feat(halo/attest): only delete after vote window

e2e/app/admin/pausexsubmit.go, e2e/app/admin/unpausexsubmit.go
=> chore(e2e): fix logs

lib/p2putil/disc_test.go
Adds a simple discv4 debug test. Doesn't run automatically.
issue: none
=> test(lib/p2putil): add naive discv4 debug test

.github/workflows/release-official.yml, .github/workflows/release-snapshot.yml
=> ci(github): fix release

monitor/xfeemngr/contract/bound.go, monitor/xfeemngr/contract/metrics.go, relayer/app/metrics.go, relayer/app/sender.go
Add total spend metrics to relayer and xfeemngr.
issue: #1962
=> feat(metrics): add relayer and monitor spend metrics

monitor/xfeemngr/contract/bound.go, monitor/xfeemngr/oracle.go, monitor/xfeemngr/xfeemngr.go, monitor/xfeemngr/xfeemngr_internal_test.go
Lazy bind fee oracle contract. Makes startup resilient to failed connections.
issue: none
=> fix(monitor/xfeemngr): lazy bind fee oracle contracts

docs/content/operate/validator.md
Update validator doc
issue: none
=> chore(docs): update validator doc

docs/content/README.md
adds some info on docs.
issue: none
=> chore(docs): add short readme for docs content

README.md
There were some broken links in the readme, went to fix them and decided to correct other things, improve language, and simplify.
issue: none
=> chore(docs): fix broken links and simplify readme

e2e/app/admin/allowoperator.go, e2e/app/admin/common.go, e2e/app/admin/config.go, e2e/app/admin/pauseportal.go, e2e/app/admin/pausexcall.go, e2e/app/admin/pausexsubmit.go, e2e/app/admin/portalspec.go, e2e/app/admin/test.go, e2e/app/admin/upgrade.go, e2e/cmd/admin.go, e2e/cmd/flags.go
Add --broadcast flag to admin commands, to
broadcast transactions. Default to no broadcast.
issue: #1920
=> feat(e2e): add --broadcast flag to admin commands

e2e/app/admin/test.go
Fix admin command - broadcast txns in test.
issue: none
=> fix(e2e): broadcast txns in admin test

scripts/halovisor/Dockerfile
Missed this previous [PR](https://github.com/omni-network/omni/pull/2005), we should also update the dockerfile default.
issue: none
=> fix(halovisor): fix genesis

docs/content/operate/1-run-full-node.md
Update platform req to not current platform support, raised by Galaxy.
issue: none
=> chore(docs): fix platform requirements

.goreleaser-official.yaml, .goreleaser-snapshot.yaml, Makefile
fix local docker build using new goreleaser yamls.
issue: #1984
=> ci(goreleaser): fix local docker build

monitor/xmonitor/indexer/metrics.go
Use gwei in fee metrics, add unit to metric name.
issue: #1962
=> chore(monitor): use gwei in fee total metrics

lib/tokens/coingecko/coingecko_test.go
Require non-zero rand mock token price.
issue: none
=> fix(test): require non zero rand price

README.md
Add development environment setup instructions to the contributing section.
issue: none
=> chore(readme): add dev env setup instructions

README.md
Minor improvements of dev env setup instructions.
issue: none
=> chore(readme): improve dev env setup instructions

docs/content/operate/1-run-full-node.md
=> chore(docs): fix typo

e2e/app/admin/allowoperator.go
Add galaxy to validator allow list.
issue: none
=> chore(e2e/admin): add galaxy to validator allow list

halo/app/start_test.go, halo/app/upgrades.go, halo/app/upgrades/uluwatu/upgrade.go
Update slashing params during `uluwatu` network upgrade.
issue: #2018
=> feat(halo/uluwatu): update slashing params

e2e/app/admin/allowoperator.go, e2e/app/admin/planupgrade.go, e2e/cmd/admin.go, e2e/manifests/staging.toml
Add `plan-upgrade` admin action. Disable staging auto-upgrade to test it.
issue: none
=> chore(e2e): add plan upgrade admin action

docs/content/faq.md
Add pre-EIP155 FAQ
issue: none
=> chore(docs): add pre-EIP155 faq

docs/content/operate/4-roadmap.md
Fix token display issue
issue: none
=> chore(docs): fix token display

docs/content/operate/5-faq.md
Add rollback FAQ item to docs
issue: none
=> docs(operator): add rollback faq

README.md, docs/content/build/1-quickstart.md
update readme and fix a spelling error
issue: none
=> chore(docs): update readme

Makefile, README.md
add makefile command for env setup
issue: none
=> chore(*): simplify setup process

Makefile
Removes legacy simnet command from makefile.
issue: none
=> chore(makefile): remove make halo-simnet

scripts/halovisor/Dockerfile
Bump omni cosmovisor fork version for improved logging, see [commit](https://github.com/omni-network/cosmovisor/commit/2f1fa004cfecde866849b5ce8d2d14b69410378a)
issue: none
=> chore(halovisor): bump omni cosmovisor for better logs

.github/workflows/backport.yml
Add debug logs to backport action
issue: none
=> chore(github): debug backport action

.github/workflows/backport.yml
Add more debug logs
issue: none
=> chore(github): debug backport more

.github/workflows/backport.yml
Finally fix backport action.
issue: none
=> chore(github): final backport fix

e2e/netman/pingpong/pingpong.go
Only send on latest conf level if one of the two vertexes is a slow chain (holesky). This slows down ping pong resulting in more time spent ping ponging. Latest conf level spends all the contract funds in a few hours.
issue: none
=> chore(e2e): slow down pingpongs

lib/tokens/coingecko/coingecko.go, lib/tokens/coingecko/coingecko_test.go, lib/tokens/tokens.go
Sanitize coingecko response.
- check all requested tokens are in response
- check requrested currency is in response
- check prices are non zero and non negative
issue: none
=> fix(lib/tokens): sanitize coingecko response

halo/attest/keeper/cpayload.go, halo/attest/keeper/keeper.go, lib/cchain/provider/abci.go, lib/xchain/provider/fetch.go
Fixes for multiple reported issues in Cantina.
issue: none
=> fix(*): multiple fixes from the reports

docs/content/build/4-faq.md, docs/content/learn/5-resources.md, docs/website/sidebars.ts
Move FAQ to the Build section, since it's only relevant for builders (there's an FAQ section for operators too). Also adds a resources section, with links to various resources for those who are curious.
issue: none
=> chore(docs): update learn

README.md
Fix links in README
issue: none
=> chore(docs): fix links in README

monitor/xfeemngr/contract/bound.go
Fix wei -> gwei conversion in monitor info log
issue: none
=> fix(xfeemngr): fix wei to gwei conversion in monitor info log

e2e/manifests/staging.toml
Enables genesis upgrade in staging. Since manual testing is done.
issue: none
=> ci(staging): enable genesis upgrade

docs/website/pnpm-lock.yaml
Upgrade express deps.
Bumps cookie dependency, to silience dependabot alert.
issue: none
=> chore(docs): upgrade express dependencies

docs/content/README.md, docs/content/operate/1-run-full-node.md, docs/content/operate/2-validator.md, docs/content/operate/5-faq.md, docs/content/operate/6-config.md, docs/website/sidebars.ts, e2e/app/geth/config_internal_test.go, e2e/app/geth/testdata/default_config.toml, e2e/app/setup.go, halo/cmd/cmd_internal_test.go, halo/cmd/cometconfig.go, halo/cmd/init.go, halo/cmd/testdata/default_config.toml, halo/config/config_test.go, halo/config/testdata/test_halo.toml, halo/evmslashing/evmslashing.go
Adds `Configure a Full Node` detailed step by step guide. Also improve validator config step.
Add default config golden files for download.
issue: #2114
=> docs(halo): add configure a full node

scripts/verifypr/verify.go, scripts/verifypr/verify_internal_test.go
Add support for other repos while referencing issue
issue: none
=> feat(scripts): support other repo issues

.github/workflows/check-sol-artifacts.yml, .github/workflows/soltest.yml, contracts/Makefile
Fix pnpm version to 8.14.0 so it's consistent locally vs CI.
issue: none
=> chore(ci): fix pnpm version and add make install tools

docs/website/package.json, docs/website/pnpm-lock.yaml
Update docs dependencies.
issue: none
=> chore(docs/website): update dependencies

e2e/app/admin/allowoperator.go
Whitelist chorus one and pops one operators addresses
issue: none
=> ci(e2e/admin): whitelist chorus one and pops one operators

docs/content/operate/3-uluwatu.md
Adds slashing params change to uluwatu docs.
issue: none
=> docs(operate): add slashing params change to uluwatu docs

.github/CODEOWNERS
Update codeowners for auto reviewer assign.
issue: none
=> chore(github): update codeowners

lib/xchain/provider/fetch.go
Combines fetching of xmsgs and xreceipt into a single call reducing xchain RPCs by 25%.
issue: #1899
=> chore(xchain/provider): combine fetching msg and receipt logs

docs/website/package.json, docs/website/pnpm-lock.yaml
Update docusaurus version.
issue: none
=> chore(docs/website): update deps

contracts/core/package.json, contracts/core/pnpm-lock.yaml
Update contract dev dependencies. 
issue: none
=> chore(contracts/core): update dev dependencies

docs/content/operate/3-uluwatu.md
Adds cosmovisor upgrade name and height to public docs.
issue: none
=> docs(operate): improve uluwatu docs

cli/cmd/flags.go, cli/cmd/staking.go
Refactor unjail command to reuse some of the new helper functions as well as combine the new config.
issue: none
=> refactor(cli): unjail cli command

cli/cmd/omni/main.go, halo/cmd/cmd_internal_test.go, halo/cmd/testdata/TestCLIReference_halo.golden, lib/buildinfo/buildinfo.go, lib/cmd/cmd.go, lib/merkle/msg_test.go
Improve cli errors
issue: none
=> chore(cli): improve cli errors

e2e/app/eoa/static.go
Fix staging upgrader and manager.
issue: none
=> fix(e2e/app): fix staging upgrade and manager

docs/content/operate/6-config.md
Fixes a typo and punctuation.
issue: none
=> docs(operate): typo and punctuation

e2e/app/eoa/eoa.go, e2e/app/portalregistry.go
Add comments explaining roles.
issue: none
=> chore(e2e): improve comments and naming

e2e/app/admin/allowoperator.go
White list node operator DAIC.
issue: none
=> chore(e2e/admin): whitelist operator DAIC

Makefile, scripts/stagingaddrs/main.go
Add script to print staging contract addresses. 
issue: none
=> chore(scripts): add script to print staging addrs

monitor/contract/metrics.go
=> fix(monitor/contract): fix name label typo

contracts/Makefile, contracts/avs/pnpm-lock.yaml, contracts/core/pnpm-lock.yaml, scripts/install_pnpm.sh
Update pnpm and upgrade lockfiles as well as other dependencies.
issue: none
=> chore(ci): update pnpm version to latest

lib/pnl/log.go, lib/tokens/pricer.go, lib/tokens/pricer_test.go, relayer/app/app.go, relayer/app/pnl.go, relayer/app/sender.go
Add profit-and-loss logs for xsubmissions.
We can sum on these metrics to in grafana to measure pnl.
issue: #1962
=> feat(relayer): add pnl logs for xsubmissions

contracts/Makefile, contracts/core/package.json, contracts/core/pnpm-lock.yaml, docs/website/package.json, docs/website/pnpm-lock.yaml
Update npm dependencies.
Additional:
- refactor contracts makefile
issue: none
=> chore(*): update npm deps

.github/workflows/ci-join.yml
Fixes invalid github action
issue: #2175
=> ci(github): fix join action

.github/workflows/ci-join.yml, .github/workflows/ci-notify.yml, docs/content/build/1-quickstart.md, docs/content/operate/1-run-full-node.md
Use `bash` instead of `sh` since the script downloaded is a bash script.
Also improve slack notifications.
issue: #2175
=> ci(github): fix join action for linux

.github/workflows/ci-join.yml, .github/workflows/ci-notify.yml
Fixes join action path.
issue: #2175
=> ci(github): fix join action path

.github/workflows/ci-join.yml
Run `join omega nightly` using latest main images.
issue: #2175
=> ci(github): fix join action images

.github/workflows/ci-join.yml, .github/workflows/ci-notify.yml
Fix nightly join omega docker image build using goreleaser.
issue: #2175
=> ci(github): fix join action image build

.github/workflows/ci-join.yml
Fixes homedir which is now repo root.
issue: #2175
=> ci(github): fix join action workdir

e2e/manifests/mainnet.toml
Decrease mainnet validators to 2
issue: #2079
=> ci(e2e): decrease mainnet vals

contracts/allocs/scripts/genallocs.go, contracts/allocs/scripts/genallocs_internal_test.go, e2e/manifests/static.go, halo/genutil/evm/evm.go, halo/genutil/genutil.go
Set mainnet genesis prefund allocations.
issue: none
=> chore(*): add mainnet genesis prefund allocs

e2e/app/setup.go
Enable staging debug logs to debug potential issues better.
issue: none
=> ci(e2e): enable debug logs on staging

halo/app/monitor.go, halo/app/ready.go, halo/app/start.go
Fix missing cometBFT prometheus metrics
issue:  #2207
=> fix(halo): fix missing comet prometheus metrics

relayer/app/creator.go, relayer/app/creator_internal_test.go, relayer/app/creator_test.go, relayer/app/cursors_internal_test.go, relayer/app/types.go, relayer/app/worker.go, relayer/app/worker_internal_test.go
Optimisation for relayer submissions to only submit minimum signatures to reach quorum. This reduces submission gas costs.
issue: none
=> fix(relayer): decrease submitted signatures

docs/content/operate/5-faq.md
Add a new FAQ question on how to check node's readiness.
issue: #2091
=> chore(docs): add a new FAQ question

e2e/types/chain.go, e2e/types/testdata/TestAttestIntervals.golden, lib/evmchain/evmchain.go
Adds mainnet chain IDs
issue: #2221
=> feat(lib): add mainnet chain ids

e2e/app/run.go
Disable pingpong deploy and start on mainnet.
issue: #2208
=> ci(e2e): disable pingpongs on mainnet

e2e/app/eoa/eoa.go, e2e/app/fund.go, e2e/cmd/cmd.go, halo/genutil/evm/evm.go
Rename overlooked safe and funder.
issue: none
=> fix(e2e): fix renaming funder and safe

e2e/netman/manager.go
Add some retries when deploying fee oracle since it sporadically fails on staging.
issue: none
=> ci(e2e): retry deploying feeoracle

e2e/app/fund.go, halo/genutil/evm/evm.go
Add funded cold to staging genesis.
issue: none
=> fix(e2e): add cold to staging genesis

e2e/app/fund.go, e2e/app/run.go, e2e/manifests/mainnet.toml
allow mainnet deploy.
Also add missing public chains to `mainnet.toml`
issue: https://github.com/omni-network/ops/issues/534
=> ci(e2e): allow mainnet deploy

e2e/types/chain.go
=> fix(e2e): add chain names

contracts/allocs/allocs.go
Adding missing mainnet allocs.
issue: none
=> ci(contracts): add mainnet allocs

lib/contracts/address.go, lib/contracts/testdata/TestContractAddressReference.golden
Bump mainnet salt version.
issue: none
=> chore(lib/contracts): bump mainnet salt version

lib/contracts/portal/deploy.go
Add retries to deploy portal proxy.
issue: none
=> ci(e2e): retry deploying portal proxy

e2e/types/chain.go, lib/cmd/flags.go, lib/xchain/connect/connect.go, lib/xchain/flags.go, monitor/routerecon/recon_internal_test.go
Improve xconnector:
- Use public RPC by default
- Support infura API env var
Add tests to e2e/types public chains.
issue: none
=> chore(xchain/connect): improve xconnector rpcs

docs/content/operate/2-validator.md
update nomenclature for xchain rpcs
issue: none
=> chore(docs): update nomenclature

e2e/app/run.go
Disable mainnet deploy
issue: none
=> ci(e2e): disable mainnet deploy

.github/workflows/check-sol-artifacts.yml, .github/workflows/e2etestadmin.yml, .github/workflows/soltest.yml, contracts/Makefile
Lock foundry version. Update pnpm install. 
Additional: rename make install-tools -> make install-pnpm
issue: none
=> fix(ci): lock foundry version in e2e admin tests

.github/workflows/e2etestadmin.yml
Run make pnpm-install in contracts dir.
issue: none
=> fix(ci): fix install-pnpm dir

scripts/join/join_test.go
Ensure context is cancelled when either of the goroutines exit, so that the other goroutine also exists, so that the eg.Wait returns and the test completes. It currently hangs since cancel isn't called in all flows.
issue: none
=> ci(scripts/join): fix hanging test

scripts/join/join_test.go
Improve `join-nightly` logging.
issue: none
=> ci(scripts/join): improve logs
